import { defineRollup } from "@plugins/database/plugins/derived-tables/core";
import { _attemptConvAgg, _attemptPushAgg } from "./rollup-table";
import { _conversations, pushes } from "./tables";

// Trigger-maintained materialized rollups for `attempts_v`'s two per-attempt
// aggregates. They hold the SAME aggregated columns the view's former inline
// CTEs produced; `attempts_v` LEFT JOINs them, turning a full recompute into a
// flat join over two small pre-rolled tables. A missing rollup row reads as
// NULL through the LEFT JOIN, exactly as a missing CTE group did (pending /
// closed / active semantics for an attempt with no conversation / push).
//
// Every piece of SQL — the table, the maintain function and triggers per source,
// the reconcile — is generated by `defineRollup` (derived-tables) from these
// declarations. See plugins/database/plugins/derived-tables/CLAUDE.md.
//
// COMPLETENESS — why one source each suffices: a rollup row is keyed by the
// source's own `attempt_id` (no hop), so every write that can move an attempt's
// aggregate is a write to `conversations` / `pushes` itself — a reparent
// (`attempt_id` changing) included, since `attempt_id` is the carry the UPDATE
// trigger diffs. An attempt DELETE cascades (FK onDelete: cascade) to its
// conversations and pushes, which fires their DELETE triggers. The boot
// reconcile is the safety net regardless.

// ── attempt_conv_agg (the per-attempt conversation aggregate) ────────────────
// A row exists iff the attempt has ≥1 conversation. `has_conv` is a constant
// `true` marker — a missing row reads as NULL = "no conversation".
//
// TWO DISTINCT LIVENESS NOTIONS — do not confuse them (this cost a fleet of
// worktrees once; see the `retained` column in views.ts):
//
//   has_live_conv  ⇔  status NOT IN ('gone','done')   "a process is expected"
//     The PROGRESS notion. `gone` means the runtime process vanished, so nothing
//     is running and nothing will run until someone resumes. Drives the DISPLAY
//     derivations: attempts_v.status (in_progress / pushed) and, through
//     attempts_v.active, tasks_v's in_progress / need_action / blocked branches.
//
//   has_open_conv  ⇔  status <> 'done'                "the user still owns this"
//     The RETENTION notion, and the one any DESTRUCTIVE consumer must read.
//     `done` is the ONLY terminal status — it is written exclusively by an
//     explicit close (`exit_clean` / the UI Exit actions → markConversationClosed).
//     `gone` is NOT terminal: it is precisely the state `resumeConversation`
//     REQUIRES to allow a resume, so a `gone` conversation is a conversation the
//     user can still come back to. Matches `isActiveStatus()`
//     (conversations/server/status.ts) and `conversations_v.active`, which have
//     always used `status <> 'done'`.
//
// Reading the progress notion as if it were the retention notion is what let the
// worktree reaper delete the checkouts of live-but-dormant conversations: a pane
// killed to reclaim resources wrote `gone`, which flipped has_live_conv false,
// which flipped attempts_v.active false, which retired the reaper's "never reap
// an active attempt" guard.
//
//   has_waiting_conv  ⇔  status = 'waiting'           "the user is asked"
//     Feeds the task's `need_action` status (P8 v3 step 19): `tasks_v` and the
//     `tasks` collection read it here instead of grouping `conversations`.
//
// The reads are exactly the columns the aggregate reads, so a write to any
// other conversation column (`waiting_for`, `last_viewed_at`, …) re-aggregates
// nothing.
export const attemptConvAgg = defineRollup({
  table: _attemptConvAgg,
  key: _attemptConvAgg.attemptId,
  select: (scope) => `
    SELECT c.attempt_id,
           true AS has_conv,
           bool_or(c.status NOT IN ('gone', 'done')) AS has_live_conv,
           bool_or(c.status <> 'done') AS has_open_conv,
           max(c.ended_at) AS max_ended_at,
           bool_or(c.status = 'waiting') AS has_waiting_conv
      FROM conversations c
     WHERE ${scope("c.attempt_id")}
     GROUP BY c.attempt_id`,
  sources: [
    {
      table: _conversations,
      carry: _conversations.attemptId,
      reads: [_conversations.status, _conversations.endedAt],
    },
  ],
});

// ── attempt_push_agg (the per-attempt push aggregate) ────────────────────────
// A row exists iff the attempt has ≥1 push. `has_push` is a constant `true`
// marker — a missing row reads as NULL = "no push".
export const attemptPushAgg = defineRollup({
  table: _attemptPushAgg,
  key: _attemptPushAgg.attemptId,
  select: (scope) => `
    SELECT p.attempt_id,
           true AS has_push,
           min(p.created_at) AS min_push_at
      FROM pushes p
     WHERE ${scope("p.attempt_id")}
     GROUP BY p.attempt_id`,
  sources: [
    {
      table: pushes,
      carry: pushes.attemptId,
      reads: [pushes.createdAt],
    },
  ],
});
