import { relative } from "node:path";
import { dataRoot, defineDataDir } from "@plugins/infra/plugins/paths/core";

// Everything the gateway daemon owns under the data root. Four directories, and
// each one is handed to the Go process as an explicit flag (`-log-dir`,
// `-central-routes-file`, `-sockets-dir`) rather than left to a Go-side default
// derived from the inherited `SINGULARITY_DIR` — a second, silently-drifting
// derivation of the same layout is exactly what this registry exists to end.
// The pid file has no flag: the launcher writes it itself.

/**
 * The gateway's log directory: its own rotating slog sink (`gateway.log`), the
 * per-worktree channel logs it writes, and the raw stdout/stderr capture the
 * launcher opens for the daemon (`gateway-stdio.log`).
 *
 * Declared as its own entry rather than left to the bare `logs` kind: the kind
 * is a reclaim class, not an owner, and these files have one.
 */
export const gatewayLogs = defineDataDir({
  kind: "logs",
  name: "gateway",
  owner: "infra/launcher",
  description:
    "Gateway daemon logs: its rotating slog sink, per-worktree channel logs, and the raw stdio capture",
  // Observability output. Losing it costs the record of a past boot, never
  // anything the running system needs.
  reclaim: { kind: "safe" },
});

/**
 * The gateway's routing state: `central-routes.json`, the manifest naming which
 * request paths the gateway forwards to the central runtime instead of a
 * worktree backend.
 */
export const gatewayState = defineDataDir({
  kind: "state",
  name: "gateway",
  owner: "infra/launcher",
  description:
    "Gateway routing state: the central-routes manifest naming the paths forwarded to the central runtime",
  // Regenerated by the central runtime on every boot — but until that boot
  // happens the file is the only record of which paths route centrally, so a
  // sweeper deleting it under a running gateway breaks OAuth mid-flight.
  reclaim: { kind: "restart" },
});

/**
 * The gateway's pid file (`gateway.pid`), written by the launcher after the
 * spawn and read by every "is it already running?" probe.
 *
 * `locks` rather than `state`: the file is not durable app state, it is how one
 * process claims host-singleton ownership of port 9000 for another process to
 * discover — the same reclaim class as the flock slot dirs beside it.
 */
export const gatewayLocks = defineDataDir({
  kind: "locks",
  name: "gateway",
  owner: "infra/launcher",
  description:
    "The gateway daemon's pid file — how a launcher discovers an already-running gateway",
  // A pid conveys nothing once its process is gone; reclaimable the moment
  // nothing on the box is running, never while the gateway is up.
  reclaim: { kind: "restart" },
});

/**
 * The per-worktree Unix domain sockets the gateway dials each backend on
 * (`<namespace>.sock`). Backends do not listen on TCP — this directory IS the
 * transport.
 */
export const socketsDir = defineDataDir({
  kind: "services",
  name: "sockets",
  owner: "infra/launcher",
  description:
    "Per-worktree Unix domain sockets the gateway dials each backend on — the whole backend transport",
  // Live kernel objects with open file descriptors on both ends. Meaningless
  // once nothing is running, unsafe to touch while anything is.
  reclaim: { kind: "restart" },
  // PERMANENT, not a to-do — the same grandfathering the postgres cluster and
  // the zero replica carry, for the same reason. These are live IPC endpoints
  // the running gateway and every backend hold open; relocating them means
  // stopping the gateway and with it every backend on the host, so the entry
  // stays where those processes already have it.
  legacyLocation: {
    path: "sockets",
    reason:
      "live IPC endpoints held open by the running gateway and every backend; moving them means stopping the whole fleet, so they are grandfathered in place",
  },
});

/** The central routing manifest, inside {@link gatewayState}. */
export const CENTRAL_ROUTES_FILENAME = "central-routes.json";

const GATEWAY_PID_FILENAME = "gateway.pid";

/**
 * Where the pid file sits *relative to a data root* — `"locks/gateway/gateway.pid"`.
 *
 * For the one caller that must name this file under a root that is NOT this
 * process's own: teardown finds a release preview's gateway under its
 * `/tmp/sgp-XXXXXX` data dir, not under `SINGULARITY_DIR`. It cannot use
 * `gatewayLocks.file(...)`, but it also must not spell the location a second
 * time — a hand-written copy would go on naming the old spot after the layout
 * migration moved the real one, leaving every preview's gateway un-killable.
 *
 * Derived from the declaration rather than written out, so the two cannot drift.
 * Same shape (and same reason) as `assetMirrorRelativeToRoot()`.
 */
export function gatewayPidFileRelativeToRoot(): string {
  return relative(dataRoot(), gatewayLocks.file(GATEWAY_PID_FILENAME));
}

export default [gatewayLogs, gatewayState, gatewayLocks, socketsDir];
