// DO NOT EDIT — autogenerated by `./singularity build`
// (see plugins/framework/plugins/tooling/plugins/codegen/core/plugin-registry-gen.ts).
//
// Adding/removing a plugin: create or delete the plugin's `<runtime>/index.ts`
// and rebuild — this file regenerates from the filesystem. The
// `plugins-registry-in-sync` check fails on drift.

export interface CollectedEntry {
  pluginPath: string;
  id: string;
  loader: () => Promise<{ default: unknown }>;
  dependsOn: string[];
}

export const exhibitsEntries: CollectedEntry[] = [
  { pluginPath: "config_v2/plugins/settings", id: "config_v2.settings", loader: () => import("@plugins/config_v2/plugins/settings/exhibits"), dependsOn: ["primitives/plugins/css/plugins/control-panel"] },
  { pluginPath: "infra/plugins/claude-cli", id: "infra.claude-cli", loader: () => import("@plugins/infra/plugins/claude-cli/exhibits"), dependsOn: [] },
  { pluginPath: "primitives/plugins/adaptive-bar", id: "primitives.adaptive-bar", loader: () => import("@plugins/primitives/plugins/adaptive-bar/exhibits"), dependsOn: ["primitives/plugins/css/plugins/text"] },
  { pluginPath: "primitives/plugins/css/plugins/color-picker", id: "primitives.css.color-picker", loader: () => import("@plugins/primitives/plugins/css/plugins/color-picker/exhibits"), dependsOn: [] },
  { pluginPath: "primitives/plugins/css/plugins/control-panel", id: "primitives.css.control-panel", loader: () => import("@plugins/primitives/plugins/css/plugins/control-panel/exhibits"), dependsOn: ["primitives/plugins/css/plugins/ui-kit"] },
  { pluginPath: "primitives/plugins/css/plugins/coords", id: "primitives.css.coords", loader: () => import("@plugins/primitives/plugins/css/plugins/coords/exhibits"), dependsOn: [] },
  { pluginPath: "primitives/plugins/css/plugins/text", id: "primitives.css.text", loader: () => import("@plugins/primitives/plugins/css/plugins/text/exhibits"), dependsOn: ["primitives/plugins/css/plugins/ui-kit"] },
  { pluginPath: "primitives/plugins/css/plugins/ui-kit", id: "primitives.css.ui-kit", loader: () => import("@plugins/primitives/plugins/css/plugins/ui-kit/exhibits"), dependsOn: ["primitives/plugins/css/plugins/control-panel", "primitives/plugins/css/plugins/text"] },
  { pluginPath: "primitives/plugins/css/plugins/yield", id: "primitives.css.yield", loader: () => import("@plugins/primitives/plugins/css/plugins/yield/exhibits"), dependsOn: ["primitives/plugins/css/plugins/text"] },
  { pluginPath: "primitives/plugins/metrics/plugins/chart-kit", id: "primitives.metrics.chart-kit", loader: () => import("@plugins/primitives/plugins/metrics/plugins/chart-kit/exhibits"), dependsOn: ["primitives/plugins/css/plugins/text", "primitives/plugins/css/plugins/ui-kit"] },
  { pluginPath: "primitives/plugins/section-card", id: "primitives.section-card", loader: () => import("@plugins/primitives/plugins/section-card/exhibits"), dependsOn: [] },
  { pluginPath: "tasks/plugins/task-draft-form", id: "tasks.task-draft-form", loader: () => import("@plugins/tasks/plugins/task-draft-form/exhibits"), dependsOn: [] },
];
