import noAdhocLayout from "./no-adhoc-layout";

/**
 * Lint barrel for the `no-adhoc-layout` rule. The root `eslint.config.ts`
 * auto-discovers this default export and registers `no-adhoc-layout` repo-wide
 * as `error`.
 *
 * Layout composition routes through the layout primitives — `<Frame>` (named
 * slots, owns the shrink hierarchy), `<Grid>`/`<Cluster>`/`<Center>`/`<Overlay>`
 * (@plugins/primitives/plugins/css/plugins/*), `<Stack>`/`<Inset>`
 * (@plugins/primitives/plugins/css/plugins/spacing/web), and `<TruncatingText>` (the only
 * home for `min-w-0`) — never raw `flex`/`grid`/`items-*`/`absolute`/`overflow-*`.
 *
 * The `ignores` array below has two tiers:
 *
 *   1. PERMANENT — the layout primitives THEMSELVES. They own the raw mechanics
 *      the rule redirects to; they will never migrate (they ARE the
 *      implementation). These globs stay forever.
 *
 *   2. BURNDOWN — every file that pre-dated the rule, grandfathered so the gate
 *      lands as `error` for NEW code without a repo-wide rewrite. This list
 *      drains to empty over time (the `no-adhoc-spacing` playbook: 389 → 0). Do
 *      NOT add entries back. A genuinely-fixed one-off escapes per-site,
 *      travelling with the code:
 *
 *        // eslint-disable-next-line layout/no-adhoc-layout -- <reason>
 */
export default {
  name: "layout",
  rules: {
    "no-adhoc-layout": noAdhocLayout,
  },
  ignores: {
    "no-adhoc-layout": [
      // ── PERMANENT: the layout primitives themselves ──────────────────────
      "plugins/primitives/plugins/css/plugins/**/*.{ts,tsx}", // Frame/Grid/Cluster/Center/Overlay + presentational css/ sub-plugins (surface, card, truncating-text, spacing, badge, row, ...)
      "plugins/primitives/plugins/floating-action/web/internal/floating-action.tsx", // owns the morph/positioning mechanics (absolute panel, the rigid `trigger` collapsed-footprint wrapper) — a layout primitive, never drains
      // ── BURNDOWN: grandfathered pre-rule offenders (drains to 0) ──────────
      // <BURNDOWN-START> (generated — see lint/index.ts header)
      "plugins/active-data/plugins/plugin-link/web/components/plugin-link-chip.tsx",
      "plugins/active-data/plugins/plugin-link/web/panes.tsx",
      "plugins/active-data/plugins/task/web/components/task-card.tsx",
      "plugins/active-data/web/internal/active-data-inline-node.tsx",
      "plugins/apps/plugins/agent-manager/plugins/shell/web/components/agent-manager-layout.tsx",
      "plugins/apps/plugins/agent-manager/plugins/welcome/web/components/welcome-view.tsx",
      "plugins/apps/plugins/agent-manager/plugins/worktree-switcher/web/components/worktree-dropdown.tsx",
      "plugins/apps/plugins/app-rail-framing/plugins/hidden/web/components/hidden-framing.tsx",
      "plugins/apps/plugins/app-rail-framing/plugins/rail/web/components/rail-framing.tsx",
      "plugins/apps/plugins/deploy/plugins/servers/web/components/add-server-form.tsx",
      "plugins/apps/plugins/deploy/plugins/servers/web/components/server-detail.tsx",
      "plugins/apps/plugins/deploy/plugins/servers/web/components/server-status-badge.tsx",
      "plugins/apps/plugins/deploy/plugins/servers/web/panes.tsx",
      "plugins/apps/plugins/home/plugins/shell/web/components/home-layout.tsx",
      "plugins/apps/plugins/pages/plugins/history/web/components/page-version-preview.tsx",
      "plugins/apps/plugins/pages/plugins/page-tree/web/components/delete-page-action.tsx",
      "plugins/apps/plugins/pages/plugins/page-tree/web/components/page-breadcrumb.tsx",
      "plugins/apps/plugins/pages/plugins/page-tree/web/components/page-cover.tsx",
      "plugins/apps/plugins/pages/plugins/page-tree/web/components/page-icon-button.tsx",
      "plugins/apps/plugins/pages/plugins/page-tree/web/panes.tsx",
      "plugins/apps/plugins/pages/plugins/starred/web/components/star-button.tsx",
      "plugins/apps/plugins/pages/plugins/welcome/plugins/quick-create/web/components/quick-create-section.tsx",
      "plugins/apps/plugins/pages/plugins/welcome/plugins/recent-pages/web/components/recent-pages-section.tsx",
      "plugins/apps/plugins/pages/plugins/welcome/web/panes.tsx",
      "plugins/apps/plugins/story/plugins/pages-integration/web/components/story-section.tsx",
      "plugins/apps/plugins/story/plugins/pages-integration/web/components/upgrade-action.tsx",
      "plugins/apps/plugins/story/plugins/render/web/components/no-renderer.tsx",
      "plugins/apps/plugins/story/plugins/renderers/plugins/slides/web/components/slides-renderer.tsx",
      "plugins/apps/plugins/story/plugins/shell/web/components/story-gallery.tsx",
      "plugins/apps/plugins/story/plugins/shell/web/components/story-header.tsx",
      "plugins/apps/plugins/story/plugins/shell/web/components/story-view-switcher.tsx",
      "plugins/apps/plugins/surface/plugins/floating/web/components/desktop-wallpaper.tsx",
      "plugins/apps/plugins/surface/plugins/floating/web/components/window-chrome.tsx",
      "plugins/apps/plugins/surface/plugins/floating/web/components/window-resize-handles.tsx",
      "plugins/apps/plugins/surface/plugins/solo/web/solo-placement.tsx",
      "plugins/apps/plugins/surface/web/components/surface-body.tsx",
      "plugins/apps/web/components/app-rail.tsx",
      "plugins/apps/web/components/app-tab-bar.tsx",
      "plugins/apps/web/components/apps-layout.tsx",
      "plugins/backup/web/components/backup-panel.tsx",
      "plugins/build/plugins/build-info/web/components/build-info.tsx",
      "plugins/build/plugins/build-logs/web/components/build-log-section.tsx",
      "plugins/build/plugins/build-profiling/web/components/build-profiling-section.tsx",
      "plugins/build/web/components/build-button.tsx",
      "plugins/build/web/components/build-popover-content.tsx",
      "plugins/code-explorer/plugins/file-resolve/web/internal/file-disambiguation.tsx",
      "plugins/code-explorer/web/components/conv-file-tree-body.tsx",
      "plugins/code-explorer/web/components/file-tree-view.tsx",
      "plugins/code-explorer/web/components/file-tree.tsx",
      "plugins/code-explorer/web/components/global-file-tree-body.tsx",
      "plugins/conversations/plugins/agents/web/components/agent-detail.tsx",
      "plugins/conversations/plugins/agents/web/components/agent-launches.tsx",
      "plugins/conversations/plugins/agents/web/components/agent-status.tsx",
      "plugins/conversations/plugins/agents/web/components/agents-list.tsx",
      "plugins/conversations/plugins/agents/web/components/delete-agent-action.tsx",
      "plugins/conversations/plugins/agents/web/components/system-agent-detail.tsx",
      "plugins/conversations/plugins/agents/web/components/system-folder.tsx",
      "plugins/conversations/plugins/agents/web/panes.tsx",
      "plugins/conversations/plugins/conversation-category/web/components/category-chip-row.tsx",
      "plugins/conversations/plugins/conversation-category/web/components/category-chip-toolbar.tsx",
      "plugins/conversations/plugins/conversation-preprompt/web/components/preprompt-chip.tsx",
      "plugins/conversations/plugins/conversation-preprompt/web/components/preprompt-list-icon.tsx",
      "plugins/conversations/plugins/conversation-progress/web/components/progress-bar-toolbar.tsx",
      "plugins/conversations/plugins/conversation-ui/plugins/item/web/components/conversation-item.tsx",
      "plugins/conversations/plugins/conversations-view/plugins/grouped/web/components/auto-group-box.tsx",
      "plugins/conversations/plugins/conversations-view/plugins/grouped/web/components/group-box.tsx",
      "plugins/conversations/plugins/conversations-view/plugins/grouped/web/components/group-container.tsx",
      "plugins/conversations/plugins/conversations-view/plugins/grouped/web/components/group-gap-zone.tsx",
      "plugins/conversations/plugins/conversations-view/plugins/grouped/web/components/group-rename.tsx",
      "plugins/conversations/plugins/conversations-view/plugins/grouped/web/components/grouped-conversation-list.tsx",
      "plugins/conversations/plugins/conversations-view/plugins/grouped/web/components/grouped-view.tsx",
      "plugins/conversations/plugins/conversations-view/plugins/queue/web/components/queue-view.tsx",
      "plugins/conversations/plugins/preprompts/web/components/preprompt-glyph.tsx",
      "plugins/conversations/plugins/preprompts/web/components/preprompt-select.tsx",
      "plugins/conversations/plugins/recover/web/components/recovery-view.tsx",
      "plugins/conversations/plugins/summary/web/components/summary-pane.tsx",
      "plugins/debug/plugins/broadcasts/web/components/broadcasts-panel.tsx",
      "plugins/debug/plugins/claude-cli-calls/web/components/call-row.tsx",
      "plugins/debug/plugins/claude-cli-calls/web/components/calls-view.tsx",
      "plugins/debug/plugins/live-state-health/web/components/live-state-health.tsx",
      "plugins/debug/plugins/logs/web/components/log-viewer.tsx",
      "plugins/debug/plugins/memory/web/components/memory-panel.tsx",
      "plugins/debug/plugins/profiling/plugins/build/web/components/build-detail.tsx",
      "plugins/debug/plugins/profiling/plugins/push/plugins/push-gantt/web/components/push-gantt.tsx",
      "plugins/debug/plugins/profiling/plugins/push/web/components/push-detail.tsx",
      "plugins/debug/plugins/profiling/plugins/runtime/web/components/runtime-section.tsx",
      "plugins/debug/plugins/profiling/web/components/drag-selection.tsx",
      "plugins/debug/plugins/profiling/web/components/gantt-container.tsx",
      "plugins/debug/plugins/profiling/web/components/gantt-view.tsx",
      "plugins/debug/plugins/profiling/web/components/shared.tsx",
      "plugins/debug/plugins/queue/web/components/queue-view.tsx",
      "plugins/debug/plugins/reports/web/components/reports-view.tsx",
      "plugins/debug/plugins/slow-ops/plugins/cluster/web/components/cluster-view.tsx",
      "plugins/debug/plugins/slow-ops/plugins/pane/web/components/slow-ops-view.tsx",
      "plugins/debug/plugins/worktree-cleanup/web/components/worktree-cleanup-panel.tsx",
      "plugins/framework/plugins/web-core/web/components/plugin-load-errors.tsx",
      "plugins/history/plugins/dialog/web/components/version-history-dialog.tsx",
      "plugins/improve/plugins/element-picker/web/components/picker-overlay.tsx",
      "plugins/improve/plugins/element-picker/web/components/ui-context-chip.tsx",
      "plugins/infra/plugins/events-test/web/components/events-test-view.tsx",
      "plugins/infra/plugins/health/web/components/health-dot.tsx",
      "plugins/layouts/plugins/miller/web/components/collapsed-bar.tsx",
      "plugins/layouts/plugins/miller/web/components/column.tsx",
      "plugins/layouts/plugins/miller/web/components/miller-columns.tsx",
      "plugins/layouts/plugins/miller/web/components/pane-overlay-host.tsx",
      "plugins/layouts/plugins/miller/web/components/resize-handle.tsx",
      "plugins/plugin-meta/plugins/facets/plugins/commands/plugins/render-detail/web/components/commands-detail-section.tsx",
      "plugins/plugin-meta/plugins/facets/plugins/contributions/plugins/render-detail/web/components/contributions-detail-section.tsx",
      "plugins/plugin-meta/plugins/facets/plugins/cross-refs/plugins/render-detail/web/components/cross-refs-detail-section.tsx",
      "plugins/plugin-meta/plugins/facets/plugins/db-schema/plugins/render-detail/web/components/db-schema-detail-section.tsx",
      "plugins/plugin-meta/plugins/facets/plugins/exports/plugins/render-contributions/web/exports-facet-table.tsx",
      "plugins/plugin-meta/plugins/facets/plugins/exports/plugins/render-detail/web/components/exports-detail-section.tsx",
      "plugins/plugin-meta/plugins/facets/plugins/registrations/plugins/render-detail/web/components/registrations-detail-section.tsx",
      "plugins/plugin-meta/plugins/facets/plugins/resources/plugins/render-detail/web/components/resources-detail-section.tsx",
      "plugins/plugin-meta/plugins/facets/plugins/routes/plugins/render-contributions/web/routes-facet-table.tsx",
      "plugins/plugin-meta/plugins/facets/plugins/routes/plugins/render-detail/web/components/routes-detail-section.tsx",
      "plugins/plugin-meta/plugins/facets/plugins/slots/plugins/render-contributions/web/slots-facet-table.tsx",
      "plugins/plugin-meta/plugins/facets/plugins/slots/plugins/render-detail/web/components/slots-detail-section.tsx",
      "plugins/plugin-meta/plugins/plugin-health/web/components/health-section.tsx",
      "plugins/plugin-meta/plugins/plugin-view/plugins/file-tree/web/components/file-tree-section.tsx",
      "plugins/plugin-meta/plugins/plugin-view/plugins/inclusion/web/components/inclusion-section.tsx",
      "plugins/plugin-meta/plugins/plugin-view/plugins/sub-plugins/web/components/sub-plugins-section.tsx",
      "plugins/plugin-meta/plugins/plugin-view/web/components/consumer-list.tsx",
      "plugins/plugin-meta/plugins/plugin-view/web/components/plugin-detail.tsx",
      "plugins/plugin-meta/plugins/plugin-view/web/components/section.tsx",
      "plugins/plugin-meta/plugins/plugin-view/web/panes.tsx",
      "plugins/primitives/plugins/app-shell/web/components/app-shell-layout.tsx",
      "plugins/primitives/plugins/app-shell/web/components/sidebar-pane-section.tsx",
      "plugins/primitives/plugins/avatar/web/components/avatar-picker.tsx",
      "plugins/primitives/plugins/avatar/web/components/avatar.tsx",
      "plugins/primitives/plugins/bar/web/internal/bar.tsx",
      "plugins/primitives/plugins/breadcrumb/web/internal/breadcrumb.tsx",
      "plugins/primitives/plugins/collapsible-wrap/web/internal/collapsible-wrap.tsx",
      "plugins/primitives/plugins/collapsible/web/internal/collapsible.tsx",
      "plugins/primitives/plugins/collapsible/web/internal/expand-all-button.tsx",
      "plugins/primitives/plugins/css/plugins/color-picker/web/internal/alpha-slider.tsx",
      "plugins/primitives/plugins/css/plugins/color-picker/web/internal/color-area.tsx",
      "plugins/primitives/plugins/css/plugins/color-picker/web/internal/color-input.tsx",
      "plugins/primitives/plugins/css/plugins/color-picker/web/internal/color-picker.tsx",
      "plugins/primitives/plugins/css/plugins/color-picker/web/internal/hue-slider.tsx",
      "plugins/primitives/plugins/css/plugins/color-picker/web/internal/swatch-grid.tsx",
      "plugins/primitives/plugins/command-palette/web/internal/command-palette-dialog.tsx",
      "plugins/primitives/plugins/commit-list/web/internal/commit-rail.tsx",
      "plugins/primitives/plugins/commit-list/web/internal/commit-row-item.tsx",
      "plugins/primitives/plugins/data-table/web/internal/data-table.tsx",
      "plugins/primitives/plugins/data-view/plugins/gallery/web/components/data-card.tsx",
      "plugins/primitives/plugins/data-view/plugins/gallery/web/components/gallery-view.tsx",
      "plugins/primitives/plugins/data-view/plugins/list/web/components/list-view.tsx",
      "plugins/primitives/plugins/data-view/plugins/tree/web/components/editable-tree-label.tsx",
      "plugins/primitives/plugins/data-view/plugins/tree/web/components/tree-view.tsx",
      "plugins/primitives/plugins/data-view/web/components/editable-cell.tsx",
      "plugins/primitives/plugins/data-view/web/components/filter/add-filter-affordance.tsx",
      "plugins/primitives/plugins/data-view/web/components/filter/conjunction-cell.tsx",
      "plugins/primitives/plugins/data-view/web/components/filter/field-search-list.tsx",
      "plugins/primitives/plugins/data-view/web/components/filter/filter-builder-popover.tsx",
      "plugins/primitives/plugins/data-view/web/components/filter/filter-group-editor.tsx",
      "plugins/primitives/plugins/data-view/web/components/filter/filter-rule-row.tsx",
      "plugins/primitives/plugins/detail-sections/web/internal/define-detail-sections.tsx",
      "plugins/primitives/plugins/error-boundary/web/components/plugin-error-boundary.tsx",
      "plugins/primitives/plugins/filepath-breadcrumb/web/internal/filepath-breadcrumb.tsx",
      "plugins/primitives/plugins/filter-chips/web/internal/filter-chips.tsx",
      "plugins/primitives/plugins/folder-picker/web/internal/folder-picker-popover.tsx",
      "plugins/primitives/plugins/folder-picker/web/internal/folder-picker.tsx",
      "plugins/primitives/plugins/graph-canvas/web/components/canvas-edge.tsx",
      "plugins/primitives/plugins/graph-canvas/web/components/canvas-node.tsx",
      "plugins/primitives/plugins/graph-canvas/web/components/group-background.tsx",
      "plugins/primitives/plugins/icon-picker/web/components/icon-picker.tsx",
      "plugins/primitives/plugins/launch/web/components/launch-control.tsx",
      "plugins/primitives/plugins/loading/web/internal/loading.tsx",
      "plugins/primitives/plugins/multi-select/web/internal/selection-bar.tsx",
      "plugins/primitives/plugins/multi-select/web/internal/selection-checkbox.tsx",
      "plugins/primitives/plugins/pane-toolbar/web/internal/define-pane-toolbar.tsx",
      "plugins/primitives/plugins/pane/web/components/pane-resolve-guard.tsx",
      "plugins/primitives/plugins/prompt-editor/web/components/prompt-editor.tsx",
      "plugins/primitives/plugins/responsive-overflow/web/internal/responsive-overflow.tsx",
      "plugins/primitives/plugins/search/web/internal/search-input.tsx",
      "plugins/primitives/plugins/css/plugins/selection-indicator/web/internal/selection-indicator.tsx",
      "plugins/primitives/plugins/slot-render/web/internal/render-slot.tsx",
      "plugins/primitives/plugins/css/plugins/status-dot/web/internal/status-dot.tsx",
      "plugins/primitives/plugins/syntax-highlight/web/internal/highlighted-code.tsx",
      "plugins/primitives/plugins/text-editor/plugins/paste-images/web/components/attachment-thumbnail.tsx",
      "plugins/primitives/plugins/text-editor/plugins/paste-images/web/components/lightbox.tsx",
      "plugins/primitives/plugins/text-editor/web/components/text-editor.tsx",
      "plugins/primitives/plugins/css/plugins/toggle-chip/web/internal/toggle-chip.tsx",
      "plugins/primitives/plugins/tooltip/web/components/kbd.tsx",
      "plugins/primitives/plugins/tree/web/internal/rename-input.tsx",
      "plugins/primitives/plugins/tree/web/internal/row-chrome.tsx",
      "plugins/primitives/plugins/tree/web/internal/tree-list.tsx",
      "plugins/primitives/plugins/tree/web/internal/tree-row-chrome.tsx",
      "plugins/reorder/plugins/edit-mode/web/internal/exit-commit-popover.tsx",
      "plugins/reorder/plugins/edit-mode/web/internal/pen-button.tsx",
      "plugins/reorder/plugins/editor/web/internal/items.tsx",
      "plugins/reorder/plugins/editor/web/internal/reorder-editor.tsx",
      "plugins/reorder/plugins/node-types/plugins/header/web/components/header-box.tsx",
      "plugins/reorder/web/components/reorder-diff-renderer.tsx",
      "plugins/reorder/web/internal/dnd-list-middleware.tsx",
      "plugins/reports/plugins/launch-fix/web/components/launch-fix-button.tsx",
      "plugins/review/plugins/code-review/web/components/code-review-section.tsx",
      "plugins/review/plugins/code-review/web/components/code-review-summary.tsx",
      "plugins/review/plugins/code-review/web/components/review-file-row.tsx",
      "plugins/review/plugins/config-defaults/web/components/config-defaults-section.tsx",
      "plugins/review/plugins/plugin-changes/plugins/api-changes/web/components/api-changes-section.tsx",
      "plugins/review/plugins/plugin-changes/plugins/api-changes/web/components/api-changes-summary.tsx",
      "plugins/review/plugins/plugin-changes/plugins/file-changes/web/components/file-changes-section.tsx",
      "plugins/review/plugins/plugin-changes/plugins/file-changes/web/components/file-changes-summary.tsx",
      "plugins/review/plugins/plugin-changes/web/components/plugin-change-card.tsx",
      "plugins/review/plugins/plugin-changes/web/components/plugin-changes-section.tsx",
      "plugins/review/plugins/plugin-changes/web/components/plugin-changes-summary.tsx",
      "plugins/review/web/panes.tsx",
      "plugins/review/web/source.tsx",
      "plugins/screenshot/plugins/draw-canvas/web/draw-canvas.tsx",
      "plugins/screenshot/plugins/draw-on-app/web/components/live-draw-overlay.tsx",
      "plugins/screenshot/web/components/crop-overlay.tsx",
      "plugins/screenshot/web/components/prompt-form.tsx",
      "plugins/screenshot/web/components/screenshot-view.tsx",
      "plugins/screenshot/web/components/tools-pane.tsx",
      "plugins/search/plugins/quick-find/web/components/quick-find-dialog.tsx",
      "plugins/shell/plugins/global-action-bar/web/components/global-action-bar.tsx",
      "plugins/shell/plugins/notifications/web/components/bell-button.tsx",
      "plugins/stats/plugins/commits/web/components/commits-section.tsx",
      "plugins/stats/plugins/commits/web/components/excluded-path-toggles.tsx",
      "plugins/stats/plugins/commits/web/components/lines-charts.tsx",
      "plugins/stats/plugins/cost/web/components/cost-kpis.tsx",
      "plugins/stats/plugins/cost/web/components/cost-section.tsx",
      "plugins/stats/plugins/cost/web/components/top-conversations-table.tsx",
      "plugins/tasks/plugins/attempt-view/web/components/attempt-pane.tsx",
      "plugins/tasks/plugins/auto-start/web/components/queued-chip-action.tsx",
      "plugins/tasks/plugins/task-attachments/web/components/task-attachments.tsx",
      "plugins/tasks/plugins/task-dependencies/web/components/task-dependencies.tsx",
      "plugins/tasks/plugins/task-dependencies/web/components/task-dependents.tsx",
      "plugins/tasks/plugins/task-description/web/components/description-view.tsx",
      "plugins/tasks/plugins/task-description/web/components/task-description.tsx",
      "plugins/tasks/plugins/task-detail/web/components/task-tree-detail.tsx",
      "plugins/tasks/plugins/task-draft-form/web/components/chain-connector.tsx",
      "plugins/tasks/plugins/task-draft-form/web/components/insert-before-children.tsx",
      "plugins/tasks/plugins/task-draft-form/web/components/model-chip.tsx",
      "plugins/tasks/plugins/task-draft-form/web/components/relate-mode-chip.tsx",
      "plugins/tasks/plugins/task-draft-form/web/components/task-draft-card.tsx",
      "plugins/tasks/plugins/task-draft-form/web/components/task-draft-form.tsx",
      "plugins/tasks/plugins/task-events/web/components/task-events.tsx",
      "plugins/tasks/plugins/task-graph/web/components/edge-actions.tsx",
      "plugins/tasks/plugins/task-graph/web/components/task-graph.tsx",
      "plugins/tasks/plugins/task-header/web/components/task-header.tsx",
      "plugins/tasks/plugins/task-list/plugins/recent/web/internal/tasks-recent-view.tsx",
      "plugins/tasks/plugins/task-list/web/components/child-count-action.tsx",
      "plugins/tasks/plugins/task-list/web/components/delete-task-action.tsx",
      "plugins/tasks/plugins/task-preprompt/web/components/task-preprompt-section.tsx",
      "plugins/tasks/plugins/task-status/web/components/task-status.tsx",
      "plugins/ui/plugins/segmented-progress-bar/plugins/dots/web/components/dots-renderer.tsx",
      "plugins/ui/plugins/segmented-progress-bar/plugins/segmented/web/components/segmented-renderer.tsx",
      "plugins/ui/plugins/sidebar-framing/plugins/floating/web/components/floating-framing.tsx",
      "plugins/ui/plugins/sidebar-framing/plugins/flush/web/components/flush-framing.tsx",
      "plugins/ui/plugins/sidebar-framing/plugins/inset/web/components/inset-framing.tsx",
      "plugins/ui/plugins/theme-engine/plugins/theme-customizer/web/components/theme-customizer.tsx",
      "plugins/ui/plugins/theme-engine/plugins/theme-customizer/web/components/token-row.tsx",
      "plugins/ui/plugins/tokens/plugins/categorical/web/components/categorical-picker.tsx",
      "plugins/ui/plugins/tokens/plugins/categorical/web/components/categorical-section.tsx",
      "plugins/ui/plugins/tokens/plugins/chart/web/components/chart-picker.tsx",
      "plugins/ui/plugins/tokens/plugins/chart/web/components/chart-section.tsx",
      "plugins/ui/plugins/tokens/plugins/color-adjust/web/components/color-adjust-picker.tsx",
      "plugins/ui/plugins/tokens/plugins/color-palette/web/components/color-palette-header-dots.tsx",
      "plugins/ui/plugins/tokens/plugins/color-palette/web/components/color-palette-picker.tsx",
      "plugins/ui/plugins/tokens/plugins/color-palette/web/components/color-palette-section.tsx",
      "plugins/ui/plugins/tokens/plugins/density/web/components/density-picker.tsx",
      "plugins/ui/plugins/tokens/plugins/density/web/components/density-section.tsx",
      "plugins/ui/plugins/tokens/plugins/font-family/web/components/font-family-picker.tsx",
      "plugins/ui/plugins/tokens/plugins/font-family/web/components/font-family-section.tsx",
      "plugins/ui/plugins/tokens/plugins/shadow/web/components/shadow-picker.tsx",
      "plugins/ui/plugins/tokens/plugins/shadow/web/components/shadow-section.tsx",
      "plugins/ui/plugins/tokens/plugins/shape/web/components/shape-picker.tsx",
      "plugins/ui/plugins/tokens/plugins/shape/web/components/shape-section.tsx",
      "plugins/ui/plugins/tokens/plugins/sidebar-palette/web/components/sidebar-palette-header-dots.tsx",
      "plugins/ui/plugins/tokens/plugins/sidebar-palette/web/components/sidebar-palette-picker.tsx",
      "plugins/ui/plugins/tokens/plugins/sidebar-palette/web/components/sidebar-palette-section.tsx",
      "plugins/ui/plugins/tokens/plugins/type-scale/web/components/type-scale-picker.tsx",
      "plugins/ui/plugins/tokens/plugins/type-scale/web/components/type-scale-section.tsx",
      "plugins/ui/plugins/tweakcn/plugins/community-browser/web/components/community-browser-section.tsx",
      "plugins/ui/plugins/tweakcn/plugins/community-browser/web/components/community-theme-card.tsx",
      "plugins/ui/plugins/tweakcn/plugins/community-browser/web/components/import-by-url.tsx",
      // <BURNDOWN-END>
    ],
  },
};
