import { useMemo } from "react";
import { useSonata } from "./context";
import { useChordMode } from "./chord-mode-store";

/**
 * Availability gates over the open score, shared by the `Sonata.Section` panels
 * that only mean something for a chord-bearing song. They live here — next to
 * `useSonata()`, the context they read — rather than being re-derived in each
 * section, so "is this a chord song?" has one definition.
 *
 * Sections pass these straight to the slot's `useAvailable`.
 */

/** At least one chord annotation, whatever produced it (authored or analyzed). */
export function useHasChords(): boolean {
  const { score } = useSonata();
  return useMemo(
    () => score.annotations.some((a) => a.type === "chord"),
    [score.annotations],
  );
}

/**
 * At least one AUTHORED chord annotation — i.e. a symbol source (chord grid,
 * Ultimate Guitar) is loaded, so the chord notes are generated by the shell's
 * re-voicing step. A MIDI-only song fails this gate even when a chord *analyzer*
 * found chords.
 */
function useHasAuthoredChord(): boolean {
  const { score } = useSonata();
  return useMemo(
    () =>
      score.annotations.some(
        (a) => a.type === "chord" && a.source === "authored",
      ),
    [score.annotations],
  );
}

/**
 * At least one analyzer-DERIVED chord annotation — the song has note-only
 * regions a chord analyzer could label (a MIDI song, or the MIDI half of a mixed
 * song). This is what the chord-mode toggle has to work with: those are the
 * chords its second voicing pass turns into notes.
 */
export function useHasDerivedChord(): boolean {
  const { score } = useSonata();
  return useMemo(
    () =>
      score.annotations.some(
        (a) => a.type === "chord" && a.source === "derived",
      ),
    [score.annotations],
  );
}

/**
 * The shell's re-voicing step is generating chord notes for this song — so the
 * voicing / rhythm controls have something to act on. True for a symbol source
 * (authored chords), and for any chord-bearing song whose per-song chord mode is
 * on (the detected chords are then voiced too). The Voicing and Rhythm cards gate
 * on this, so flipping chord mode on a MIDI song brings them in unchanged.
 */
export function useHasVoicedChords(): boolean {
  const authored = useHasAuthoredChord();
  const anyChord = useHasChords();
  const chordMode = useChordMode();
  return authored || (chordMode && anyChord);
}
