import { useMemo } from "react";
import { useSonata } from "./context";

/**
 * Availability gates over the open score, shared by the `Sonata.Section` panels
 * that only mean something for a chord-bearing song. They live here — next to
 * `useSonata()`, the context they read — rather than being re-derived in each
 * section, so "is this a chord song?" has one definition.
 *
 * Sections pass these straight to the slot's `useAvailable`.
 */

/** At least one chord annotation, whatever produced it (authored or analyzed). */
export function useHasChords(): boolean {
  const { score } = useSonata();
  return useMemo(
    () => score.annotations.some((a) => a.type === "chord"),
    [score.annotations],
  );
}

/**
 * At least one AUTHORED chord annotation — i.e. a symbol source (chord grid,
 * Ultimate Guitar) is loaded, so the chord notes are generated by the shell's
 * re-voicing step and the voicing / rhythm controls have something to act on.
 * A MIDI-only song fails this gate even when a chord *analyzer* found chords.
 */
export function useHasAuthoredChord(): boolean {
  const { score } = useSonata();
  return useMemo(
    () =>
      score.annotations.some(
        (a) => a.type === "chord" && a.source === "authored",
      ),
    [score.annotations],
  );
}
