/**
 * The activate script: what runs on the host once a bundle has landed.
 *
 * Beside `converge-script.ts` for the same reason that one exists — a shell
 * template whose only execution path is a remote host is a template whose typos
 * are discovered in production — and it shares that file's `sq`, so the two
 * scripts quote their interpolations exactly one way.
 */
import {
  REMOTE_SCRIPT_SHEBANG,
  listenAddress,
  releaseAppPath,
  releaseDir,
  type InstallLayout,
} from "@plugins/apps/plugins/deploy/plugins/deployments/core";
import { sq } from "./converge-script";
import { READY_ATTEMPTS, READY_INTERVAL_SEC } from "./target";

// ── D4: bundle discovery + the activate script ────────────────────────────────
//
// Bundle discovery itself lives in `@plugins/release/plugins/bundles` — the one
// authority on "which bundle would ship, and why not", shared with the (future)
// HTTP surface that has to answer the same question without exiting a process.
// Ship's only job here is to turn its refusal into this command's exit.

/**
 * Activate an uploaded bundle: entrypoint symlink → flip `current` → restart →
 * health gate, reverting on failure.
 *
 * This is ONE script on the host rather than a sequence of `sshRun`s for one
 * reason: the revert must run even if the CLI dies or the connection drops
 * mid-gate. A deploy command whose failure mode is "the site is now broken and
 * stays broken" is not shippable.
 */
export function activateScript(opts: {
  install: InstallLayout;
  runId: string;
  binaryName: string;
  loopbackPort: number;
}): string {
  const { install, runId, binaryName, loopbackPort } = opts;
  const dir = releaseDir(install.compositionId, runId);
  const base = `http://${listenAddress(loopbackPort)}`;

  return `${REMOTE_SCRIPT_SHEBANG}
# GENERATED by \`./singularity deploy ship\` — do NOT edit on the host.
set -euo pipefail

# Progress to stderr, for the same reason as the converge script: a FAILED
# \`sshRun\` returns stderr only, and the failing ship is the one whose log
# matters. See \`runScript\` in \`./target.ts\`.
exec 1>&2

UNIT=${sq(install.unit)}
RUN_USER=${sq(install.runUser)}
RELEASE_DIR=${sq(dir)}
BINARY=${sq(binaryName)}
APP=${sq(releaseAppPath(install.compositionId, runId))}
CURRENT=${sq(install.currentLink)}
CACHE=${sq(`${install.runtimeDir}/equin-release`)}
STALE=${sq(`${install.runtimeDir}/.stale-`)}$$
READY_URL=${sq(`${base}/api/health/ready`)}
HEALTH_URL=${sq(`${base}/api/health`)}
RUN_ID=${sq(runId)}

if [ ! -s "$RELEASE_DIR/$BINARY" ]; then
  echo "activate: $RELEASE_DIR/$BINARY is missing or empty — the upload did not land" >&2
  exit 1
fi
chmod 755 "$RELEASE_DIR/$BINARY"

# The fixed-name entrypoint, created BEFORE the flip so \`current\` never points
# at a dir the unit cannot exec. Relative, so the release dir stays relocatable.
ln -sfn "$BINARY" "$APP.new"
mv -fT "$APP.new" "$APP"
chown -R "$RUN_USER:$RUN_USER" "$RELEASE_DIR"

# What was serving, captured before the flip — this is what a failure restores.
# Empty on a first ship, which is a state of its own below.
PREV="$(readlink "$CURRENT" 2>/dev/null || true)"

MOVED=0
FLIPPED=0
GATE_OK=0

# EVERY failure after this point undoes itself, not just a failed gate: a unit
# that will not restart (an un-converged host) or an ssh deadline mid-gate would
# otherwise leave \`current\` pointing at a build that is not serving. The trap is
# what makes "production is never left down by a bad ship" true for the whole
# rest of the script rather than for the one branch that thought of it.
undo() {
  set +e   # best-effort recovery; the script's own non-zero status still stands
  if [ "$MOVED" -eq 1 ]; then
    mkdir -p "$CACHE"
    mv -- "$STALE"/* "$CACHE"/
    rmdir "$STALE"
    echo "reverted: restored the previous extraction cache" >&2
  fi
  if [ "$FLIPPED" -eq 1 ]; then
    if [ -n "$PREV" ]; then
      ln -sfn "$PREV" "$CURRENT.new"
      mv -fT "$CURRENT.new" "$CURRENT"
      # Say which of the two happened: "reverted and restarted" and "reverted but
      # the host is still down" are very different things to be told.
      if systemctl restart "$UNIT"; then
        echo "reverted: current -> $PREV, $UNIT restarted" >&2
      else
        echo "reverted: current -> $PREV, but restarting $UNIT ALSO failed — the host is DOWN" >&2
      fi
    else
      systemctl stop "$UNIT"
      rm -f "$CURRENT"
      echo "reverted: nothing served before this ship — $UNIT stopped, current removed" >&2
    fi
  fi
  echo "--- journalctl -u $UNIT -n 200 ---" >&2
  journalctl -u "$UNIT" -n 200 --no-pager >&2
}
on_exit() {
  status=$?
  if [ "$status" -ne 0 ] && [ "$GATE_OK" -eq 0 ]; then undo; fi
  exit "$status"
}
trap on_exit EXIT

# Move the extraction cache aside rather than deleting it. The self-extractor
# keys its extract dir on the tarball hash, so every ship would otherwise leave
# a full extracted bundle behind forever — but a revert needs the PREVIOUS
# bundle's cache, so it is only destroyed once the gate has passed.
if [ -d "$CACHE" ] && [ -n "$(ls -A "$CACHE" 2>/dev/null || true)" ]; then
  mkdir -p "$STALE"
  mv -- "$CACHE"/* "$STALE"/
  MOVED=1
fi

# The flip IS the deploy. rename(2) over the existing symlink, so no window
# exists in which \`current\` is absent.
ln -sfn "$RELEASE_DIR" "$CURRENT.new"
mv -fT "$CURRENT.new" "$CURRENT"
FLIPPED=1
echo "[+] current -> $RELEASE_DIR (was: \${PREV:-<none>})"

systemctl restart "$UNIT"

# ── The health gate. Three outcomes, deliberately distinguished:
#     ok=1  ready AND serving the runId we shipped   → success
#     ok=0  never became ready within the window     → "not up"
#     ok=2  ready, but /api/health names another build → the flip did not take
ok=0
body=""
for _ in $(seq 1 ${READY_ATTEMPTS}); do
  if curl -fsS -m 5 "$READY_URL" >/dev/null 2>&1; then ok=1; break; fi
  sleep ${READY_INTERVAL_SEC}
done
if [ "$ok" -eq 1 ]; then
  body="$(curl -fsS -m 5 "$HEALTH_URL" || true)"
  # Liveness alone would let a failed flip pass as success: the PREVIOUS build
  # answers /api/health/ready perfectly happily. The runId is what makes "the
  # build I shipped is the build now answering" checkable.
  printf '%s' "$body" | grep -Eq '"runId"[[:space:]]*:[[:space:]]*"'"$RUN_ID"'"' || ok=2
fi

if [ "$ok" -ne 1 ]; then
  if [ "$ok" -eq 0 ]; then
    echo "gate: $UNIT never became ready at $READY_URL within ${
      READY_ATTEMPTS * READY_INTERVAL_SEC
    }s" >&2
  else
    echo "gate: ready, but /api/health does not report the shipped runId $RUN_ID:" >&2
    printf '%s\\n' "$body" >&2
  fi
  # The trap does the revert and prints the journal — one recovery path for
  # every failure mode, not one per branch that remembered.
  exit 1
fi
GATE_OK=1

# Gate passed: the previous extraction cache has no rollback value now, and on a
# box nobody SSHes into, disk-fill is the failure that takes the site down
# silently. Exactly one extracted bundle is left behind.
if [ "$MOVED" -eq 1 ]; then
  rm -rf -- "$STALE"
  echo "[=] pruned the previous extraction cache under $CACHE"
fi

echo "[ok] $UNIT is serving runId $RUN_ID"
printf '%s\\n' "$body"
`;
}
