#!/bin/sh
# Merge driver for plugins/**/CLAUDE.md.
# Files mix hand-written prose with an <!-- AUTOGENERATED:BEGIN --> block.
# args: %O %A %B %P
#
# Strategy: do a 3-way merge of the file (handles prose). Accept the result
# even if conflicts remain — the post-rebase normalize step rewrites the
# autogen block (erasing benign autogen-only conflict markers) and then
# scans for any residual markers in the prose section. If found there, it
# fails loudly so the agent resolves the real prose conflict manually.
git merge-file -p "$2" "$1" "$3" > "$2.tmp" 2>/dev/null || true
mv "$2.tmp" "$2"
GITDIR=$(git rev-parse --git-dir)
mkdir -p "$GITDIR/singularity-merge-markers"
touch "$GITDIR/singularity-merge-markers/generated"
exit 0
