#!/bin/sh
# Merge driver for plugins/**/CLAUDE.md.
# Files mix hand-written prose with an <!-- AUTOGENERATED:BEGIN --> block.
# args: %O %A %B %P
#
# Strategy: do a 3-way merge of the file (handles prose). Accept the result
# even if conflicts remain — the normalize pass rewrites the autogen block
# (erasing benign autogen-only conflict markers) and then scans for any residual
# markers in the prose section. If found there, it fails loudly so the agent
# resolves the real prose conflict manually; the
# `generated-artifacts-normalized` check re-asserts it on every later run.
git merge-file -p "$2" "$1" "$3" > "$2.tmp" 2>/dev/null || true
mv "$2.tmp" "$2"
# Resolve the marker dir exactly as regen-generated.sh does — read its comment
# there for why the ambient GIT_* pointers are unset first and why an
# unresolvable git dir is fatal instead of a skipped marker.
GITDIR=$(unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_OBJECT_DIRECTORY; git rev-parse --absolute-git-dir 2>/dev/null) ||
  GITDIR=$(git rev-parse --absolute-git-dir 2>/dev/null) || GITDIR=""
if [ -z "$GITDIR" ]; then
  echo "regen-claudemd merge driver: cannot resolve this checkout's git dir; refusing to merge without recording the normalize marker." >&2
  exit 1
fi
mkdir -p "$GITDIR/singularity-merge-markers"
touch "$GITDIR/singularity-merge-markers/generated"
exit 0
