import { existsSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { buildEnrichedTree } from "./docgen";
import {
  findMarkerCalls,
  maskSource,
  readIfExists,
  walkFiles,
} from "@plugins/plugin-meta/plugins/parse-utils/core";

/**
 * Generates the data-views manifest consumed by the data-view primitive: the
 * complete set of `defineDataView("<id>")` ids scraped from every plugin's
 * `web/**` source.
 *
 * Like reorder's reorderable-slots manifest, this is a pure-data bridge from
 * build-time (which can see web-only marker calls) to both runtimes: the
 * data-view barrels read `dataViews` and register one config_v2 descriptor per
 * id under the `primitives.data-view` plugin. Unlike reorder, only the SET of
 * ids is needed (no pluginId — every descriptor registers under data-view), so
 * the manifest is a flat sorted id list.
 *
 * The `data-views-in-sync` check fails on drift.
 */

// The output mirrors the placeholder committed at
// plugins/primitives/plugins/data-view/shared/data-views.generated.ts.
const MANIFEST_REL_PATH =
  "plugins/primitives/plugins/data-view/shared/data-views.generated.ts";

const MANIFEST_HEADER = [
  "// DO NOT EDIT — autogenerated by `./singularity build`",
  "// (see plugins/framework/plugins/tooling/plugins/codegen/core/data-views-gen.ts).",
  "//",
  "// Every `defineDataView(\"<id>\")` marker call found in any plugin's web/**",
  "// source. The data-view primitive registers one config_v2 descriptor per id",
  "// (under `config/primitives/data-view/<id>.jsonc`) on both runtimes from this",
  "// manifest.",
  "//",
  "// The `data-views-in-sync` check fails on drift.",
].join("\n");

/** Extract the first string-literal argument from a marker call's args text. */
function firstStringArg(argsText: string): string | undefined {
  const m = /^\s*"([^"]+)"|^\s*'([^']+)'|^\s*`([^`]+)`/.exec(argsText);
  return m ? (m[1] ?? m[2] ?? m[3]) : undefined;
}

/**
 * Walk the enriched plugin tree (reusing docgen's cached build) and collect
 * every `defineDataView("<id>")` id. Scans each node's `web/**` source via the
 * blessed `findMarkerCalls` scanner (over a comment/regex-masked copy, strings
 * kept so the string-literal id survives), dedupes, and sorts.
 */
export async function collectDataViews(root: string): Promise<string[]> {
  const tree = await buildEnrichedTree(root);
  const ids = new Set<string>();

  for (const node of tree.byDir.values()) {
    const webDir = join(node.dir, "web");
    if (!existsSync(webDir)) continue;
    const files: string[] = [];
    walkFiles(webDir, files);
    for (const file of files) {
      const src = readIfExists(file);
      if (!src || !src.includes("defineDataView")) continue;
      // `{ strings: false }`: the id we extract LIVES IN a string literal, so we
      // must not blank string interiors (only comments / regex literals).
      const calls = findMarkerCalls(
        maskSource(src, { strings: false }),
        "defineDataView",
      );
      for (const call of calls) {
        const id = firstStringArg(call.argsText);
        // Skip ids built from template/identifier expressions (not statically
        // resolvable) — same fail-soft as parseSlotCalls.
        if (id) ids.add(id);
      }
    }
  }

  return [...ids].sort((a, b) => a.localeCompare(b));
}

function renderManifest(ids: string[]): string {
  const lines: string[] = [];
  lines.push(MANIFEST_HEADER);
  lines.push("");
  lines.push("export interface DataViewEntry {");
  lines.push("  id: string;");
  lines.push("}");
  lines.push("");
  if (ids.length === 0) {
    lines.push("export const dataViews: DataViewEntry[] = [];");
  } else {
    lines.push("export const dataViews: DataViewEntry[] = [");
    for (const id of ids) {
      lines.push(`  { id: ${JSON.stringify(id)} },`);
    }
    lines.push("];");
  }
  lines.push("");
  return lines.join("\n");
}

/** Path to the committed manifest file. */
export function dataViewsManifestPath(root: string): string {
  return join(root, MANIFEST_REL_PATH);
}

/** Render the manifest file contents in-memory (used by the in-sync check). */
export async function renderDataViewsManifest(root: string): Promise<string> {
  const ids = await collectDataViews(root);
  return renderManifest(ids);
}

/** Regenerate `data-views.generated.ts` if it drifted. */
export async function generateDataViews(opts: { root: string }): Promise<void> {
  const next = await renderDataViewsManifest(opts.root);
  const file = dataViewsManifestPath(opts.root);
  const existing = existsSync(file) ? readFileSync(file, "utf8") : "";
  if (next !== existing) writeFileSync(file, next);
}
