import { existsSync } from "fs";
import { join, relative } from "path";
import { writeGenerated } from "./write-generated";
import {
  lineAt,
  markerCallSpans,
  maskSource,
  parseStaticCallId,
  unresolvableCallIdMessage,
  walkFiles,
  readIfExists,
} from "@plugins/plugin-meta/plugins/parse-utils/core";
import { buildBarrelFreeTree } from "./barrel-free-tree";
import { computeDisabledIds } from "./disabled-ids";

/**
 * Generates the data-views manifest consumed by the data-view primitive: the
 * complete set of `defineDataView("<id>")` ids scraped from every plugin's
 * `web/**` source.
 *
 * Like reorder's reorderable-slots manifest, this is a pure-data bridge from
 * build-time (which can see web-only marker calls) to both runtimes: the
 * data-view barrels read `dataViews` and register one config_v2 descriptor per
 * id. Each entry carries the *defining* plugin's id (the node whose `web/**`
 * contains the `defineDataView("<id>")` marker), so the descriptor registers
 * under `config/<pluginId>/<id>.jsonc` — the consuming plugin's tree, exactly as
 * reorder plants each slot's directive under its defining plugin.
 *
 * The `data-views-in-sync` check fails on drift.
 */

// The output mirrors the placeholder committed at
// plugins/primitives/plugins/data-view/shared/data-views.generated.ts.
const MANIFEST_REL_PATH =
  "plugins/primitives/plugins/data-view/shared/data-views.generated.ts";

const MANIFEST_HEADER = [
  "// DO NOT EDIT — autogenerated by `./singularity build`",
  "// (see plugins/framework/plugins/tooling/plugins/codegen/core/data-views-gen.ts).",
  "//",
  '// Every `defineDataView("<id>")` marker call found in any plugin\'s web/**',
  "// source. The data-view primitive registers one config_v2 descriptor per id",
  "// on both runtimes from this manifest. Each entry's `pluginId` is the",
  "// *defining* plugin's id (its tree path), so the descriptor registers under",
  "// `config/<pluginId>/<id>.jsonc` — the consuming plugin's tree.",
  "//",
  "// The `data-views-in-sync` check fails on drift.",
].join("\n");

const DATA_VIEW_MARKER = "defineDataView";

/**
 * Every `defineDataView("<id>")` id in one source file, in source order.
 *
 * The file is FULL-masked (so a marker written inside a comment, string or
 * template literal is never matched) and each id is read back from the ORIGINAL
 * by offset. THROWS — naming `displayPath`, the line, and the offending
 * expression — on a call whose id is not a static string literal. Unlike the slot
 * scanner there is no legitimate unresolvable shape here: `defineDataView` is
 * only ever called, never declared in a plugin's `web/**`, and no factory
 * produces data views. So there is nothing to exempt and no escape hatch.
 */
export function scanDataViewIds(src: string, displayPath: string): string[] {
  const out: string[] = [];
  for (const span of markerCallSpans(maskSource(src), DATA_VIEW_MARKER)) {
    const id = parseStaticCallId(src, span);
    if (id.kind !== "value") {
      throw new Error(
        unresolvableCallIdMessage({
          marker: DATA_VIEW_MARKER,
          file: displayPath,
          line: lineAt(src, span.identifier),
          expr: id.kind === "dynamic" ? id.expr : "",
          hint:
            "The data-views manifest is built from source text, so every id must be a " +
            "literal at the call site — a data view whose id this scanner cannot read " +
            "would silently register no config descriptor and lose its saved views. " +
            "Inline the literal instead of hoisting or interpolating it.",
        }),
      );
    }
    out.push(id.value);
  }
  return out;
}

export interface DataViewEntry {
  id: string;
  /** Hierarchy id of the plugin whose web/** owns the `defineDataView` marker. */
  pluginId: string;
}

/**
 * Walk the plugin tree (barrel-free static scan) and collect every
 * `defineDataView("<id>")` id keyed to its DEFINING plugin (the node whose
 * `web/**` owns the marker). Each file is FULL-masked once (so a
 * `defineDataView("x")` written inside a comment, string or template literal is
 * never mistaken for a real marker) and every id is read back from the ORIGINAL
 * by offset. Deduped by id (FIRST definer wins, stable since `tree.byDir`
 * iteration is deterministic) and sorted by id.
 *
 * THROWS on a `defineDataView` call whose id is not statically resolvable. The
 * manifest is the only thing that registers a data view's config descriptor, so
 * an id this scanner cannot read is lost capability, not a tolerable gap —
 * dropping it silently would leave a data view with no persisted view state and
 * nothing anywhere saying why.
 *
 * Uses `{ skipBarrelImport: true }`: this collector only reads `node.dir` /
 * `node.id` and text-scans web source — it never touches facets/barrel data, so
 * a barrel-free tree is correct. Critically, it MUST stay barrel-free: the
 * manifest it feeds is imported by plugin barrels at module-load, so it has to
 * be regenerated BEFORE the first barrel import freezes the ESM cache.
 */
export async function collectDataViews(root: string): Promise<DataViewEntry[]> {
  const tree = await buildBarrelFreeTree(root);
  // A disabled plugin's data-view descriptor never registers at runtime (its
  // barrel is omitted from the registry), so emitting its `config/<pluginId>/`
  // origin would orphan user overrides under `pruneOrphanedConfigFiles`. Skip
  // the disabled closure — the data-view descriptor is a config_v2 origin keyed
  // by the DEFINING plugin, exactly the orphan-prune hazard.
  const disabled = computeDisabledIds(tree);
  const definingPath = new Map<string, string>();

  for (const node of tree.byDir.values()) {
    if (disabled.has(node.id)) continue;
    const webDir = join(node.dir, "web");
    if (!existsSync(webDir)) continue;
    const files: string[] = [];
    walkFiles(webDir, files);
    for (const file of files) {
      const src = readIfExists(file);
      if (!src || !src.includes(DATA_VIEW_MARKER)) continue;
      for (const id of scanDataViewIds(src, relative(root, file))) {
        if (!definingPath.has(id)) definingPath.set(id, node.id);
      }
    }
  }

  return [...definingPath.entries()]
    .map(([id, pluginId]) => ({ id, pluginId }))
    .sort((a, b) => a.id.localeCompare(b.id));
}

function renderManifest(entries: DataViewEntry[]): string {
  const lines: string[] = [];
  lines.push(MANIFEST_HEADER);
  lines.push("");
  lines.push("export interface DataViewEntry {");
  lines.push("  id: string;");
  lines.push("  pluginId: string;");
  lines.push("}");
  lines.push("");
  if (entries.length === 0) {
    lines.push("export const dataViews: DataViewEntry[] = [];");
  } else {
    lines.push("export const dataViews: DataViewEntry[] = [");
    for (const e of entries) {
      lines.push(
        `  { id: ${JSON.stringify(e.id)}, pluginId: ${JSON.stringify(e.pluginId)} },`,
      );
    }
    lines.push("];");
  }
  lines.push("");
  return lines.join("\n");
}

/** Path to the committed manifest file. */
export function dataViewsManifestPath(root: string): string {
  return join(root, MANIFEST_REL_PATH);
}

/** Render the manifest file contents in-memory (used by the in-sync check). */
export async function renderDataViewsManifest(root: string): Promise<string> {
  const entries = await collectDataViews(root);
  return renderManifest(entries);
}

/** Regenerate `data-views.generated.ts` if it drifted. */
export async function generateDataViews(opts: { root: string }): Promise<void> {
  await writeGenerated({
    file: dataViewsManifestPath(opts.root),
    content: await renderDataViewsManifest(opts.root),
  });
}
