import { existsSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";
import {
  findMarkerCalls,
  readIfExists,
  walkFiles,
} from "@plugins/plugin-meta/plugins/parse-utils/core";
import { buildBarrelFreeTree } from "./docgen";
import { computeDisabledIds } from "./disabled-ids";

/**
 * Generates the data-views manifest consumed by the data-view primitive: the
 * complete set of `defineDataView("<id>")` ids scraped from every plugin's
 * `web/**` source.
 *
 * Like reorder's reorderable-slots manifest, this is a pure-data bridge from
 * build-time (which can see web-only marker calls) to both runtimes: the
 * data-view barrels read `dataViews` and register one config_v2 descriptor per
 * id. Each entry carries the *defining* plugin's id (the node whose `web/**`
 * contains the `defineDataView("<id>")` marker), so the descriptor registers
 * under `config/<pluginId>/<id>.jsonc` — the consuming plugin's tree, exactly as
 * reorder plants each slot's directive under its defining plugin.
 *
 * The `data-views-in-sync` check fails on drift.
 */

// The output mirrors the placeholder committed at
// plugins/primitives/plugins/data-view/shared/data-views.generated.ts.
const MANIFEST_REL_PATH =
  "plugins/primitives/plugins/data-view/shared/data-views.generated.ts";

const MANIFEST_HEADER = [
  "// DO NOT EDIT — autogenerated by `./singularity build`",
  "// (see plugins/framework/plugins/tooling/plugins/codegen/core/data-views-gen.ts).",
  "//",
  "// Every `defineDataView(\"<id>\")` marker call found in any plugin's web/**",
  "// source. The data-view primitive registers one config_v2 descriptor per id",
  "// on both runtimes from this manifest. Each entry's `pluginId` is the",
  "// *defining* plugin's id (its tree path), so the descriptor registers under",
  "// `config/<pluginId>/<id>.jsonc` — the consuming plugin's tree.",
  "//",
  "// The `data-views-in-sync` check fails on drift.",
].join("\n");

/** Extract the first string-literal argument from a marker call's args text. */
function firstStringArg(argsText: string): string | undefined {
  const m = /^\s*"([^"]+)"|^\s*'([^']+)'|^\s*`([^`]+)`/.exec(argsText);
  return m ? (m[1] ?? m[2] ?? m[3]) : undefined;
}

export interface DataViewEntry {
  id: string;
  /** Hierarchy id of the plugin whose web/** owns the `defineDataView` marker. */
  pluginId: string;
}

/**
 * Walk the plugin tree (barrel-free static scan) and collect every
 * `defineDataView("<id>")` id keyed to its DEFINING plugin (the node whose
 * `web/**` owns the marker). Scans each node's `web/**` source via the blessed
 * `findMarkerCalls` scanner (which full-masks internally and reads each id back
 * from the ORIGINAL by offset, so a `defineDataView("x")` written inside a
 * string/template literal is never mistaken for a real marker). Deduped by id
 * (FIRST definer wins, stable
 * since `tree.byDir` iteration is deterministic) and sorted by id.
 *
 * Uses `{ skipBarrelImport: true }`: this collector only reads `node.dir` /
 * `node.id` and text-scans web source — it never touches facets/barrel data, so
 * a barrel-free tree is correct. Critically, it MUST stay barrel-free: the
 * manifest it feeds is imported by plugin barrels at module-load, so it has to
 * be regenerated BEFORE the first barrel import freezes the ESM cache.
 */
export async function collectDataViews(root: string): Promise<DataViewEntry[]> {
  const tree = await buildBarrelFreeTree(root);
  // A disabled plugin's data-view descriptor never registers at runtime (its
  // barrel is omitted from the registry), so emitting its `config/<pluginId>/`
  // origin would orphan user overrides under `pruneOrphanedConfigFiles`. Skip
  // the disabled closure — the data-view descriptor is a config_v2 origin keyed
  // by the DEFINING plugin, exactly the orphan-prune hazard.
  const disabled = computeDisabledIds(tree);
  const definingPath = new Map<string, string>();

  for (const node of tree.byDir.values()) {
    if (disabled.has(node.id)) continue;
    const webDir = join(node.dir, "web");
    if (!existsSync(webDir)) continue;
    const files: string[] = [];
    walkFiles(webDir, files);
    for (const file of files) {
      const src = readIfExists(file);
      if (!src || !src.includes("defineDataView")) continue;
      // `findMarkerCalls` full-masks internally (a `defineDataView("x")` written
      // inside a string/template literal vanishes and is never matched) and
      // slices `argsText` from the ORIGINAL, so the string-literal id survives
      // for `firstStringArg` to read.
      const calls = findMarkerCalls(src, "defineDataView");
      for (const call of calls) {
        const id = firstStringArg(call.argsText);
        // Skip ids built from template/identifier expressions (not statically
        // resolvable) — same fail-soft as parseSlotCalls.
        if (id && !definingPath.has(id)) definingPath.set(id, node.id);
      }
    }
  }

  return [...definingPath.entries()]
    .map(([id, pluginId]) => ({ id, pluginId }))
    .sort((a, b) => a.id.localeCompare(b.id));
}

function renderManifest(entries: DataViewEntry[]): string {
  const lines: string[] = [];
  lines.push(MANIFEST_HEADER);
  lines.push("");
  lines.push("export interface DataViewEntry {");
  lines.push("  id: string;");
  lines.push("  pluginId: string;");
  lines.push("}");
  lines.push("");
  if (entries.length === 0) {
    lines.push("export const dataViews: DataViewEntry[] = [];");
  } else {
    lines.push("export const dataViews: DataViewEntry[] = [");
    for (const e of entries) {
      lines.push(
        `  { id: ${JSON.stringify(e.id)}, pluginId: ${JSON.stringify(e.pluginId)} },`,
      );
    }
    lines.push("];");
  }
  lines.push("");
  return lines.join("\n");
}

/** Path to the committed manifest file. */
export function dataViewsManifestPath(root: string): string {
  return join(root, MANIFEST_REL_PATH);
}

/** Render the manifest file contents in-memory (used by the in-sync check). */
export async function renderDataViewsManifest(root: string): Promise<string> {
  const entries = await collectDataViews(root);
  return renderManifest(entries);
}

/** Regenerate `data-views.generated.ts` if it drifted. */
export async function generateDataViews(opts: { root: string }): Promise<void> {
  const next = await renderDataViewsManifest(opts.root);
  const file = dataViewsManifestPath(opts.root);
  const existing = existsSync(file) ? readFileSync(file, "utf8") : "";
  if (next !== existing) writeFileSync(file, next);
}
