import { existsSync, readFileSync, unlinkSync, writeFileSync } from "fs";
import { join, resolve } from "path";
import {
  buildPluginTree,
  type PluginNode,
  type PluginTree,
} from "@plugins/plugin-meta/plugins/plugin-tree/core";
import { getFacet, type Facet, type DocFact } from "@plugins/plugin-meta/plugins/facets/core";

const BEGIN = "<!-- AUTOGENERATED:BEGIN — do not edit; regenerated by `./singularity build` -->";
const END = "<!-- AUTOGENERATED:END -->";

function readIfExists(path: string): string | null {
  return existsSync(path) ? readFileSync(path, "utf8") : null;
}

function pluginDescription(p: PluginNode): string | undefined {
  const parts = [p.descriptions.web, p.descriptions.server, p.descriptions.central].filter(Boolean);
  return parts.length > 0 ? parts.join(" ") : p.description;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function renderDocFacts(facts: DocFact[], bodyIndent: string): string[] {
  const subIndent = `${bodyIndent}  `;
  const lines: string[] = [];
  const folders = new Map<string, DocFact[]>();
  for (const f of facts) {
    let group = folders.get(f.folder);
    if (!group) { group = []; folders.set(f.folder, group); }
    group.push(f);
  }
  for (const [folder, group] of folders) {
    const content: string[] = [];
    for (const fact of group) {
      if (fact.values.length === 0) continue;
      content.push(`${subIndent}- ${fact.key}: ${fact.values.join(", ")}`);
    }
    if (content.length > 0) {
      lines.push(`${bodyIndent}- ${capitalize(folder)}:`);
      lines.push(...content);
    }
  }
  return lines;
}

function renderPluginFacts(
  p: PluginNode,
  facets: Facet[],
  bodyIndent: string,
  root: string,
  lines: string[],
): void {
  const allFacts: DocFact[] = [];
  for (const facet of facets) {
    const data = getFacet(p, facet.def);
    if (data !== undefined) {
      allFacts.push(...facet.renderDoc(data, { root }));
    }
  }
  lines.push(...renderDocFacts(allFacts, bodyIndent));
}

type RenderMode = "detail" | "compact";

function countDescendants(p: PluginNode): number {
  let n = 0;
  for (const c of p.children) n += 1 + countDescendants(c);
  return n;
}

function renderPluginTreeMd(
  p: PluginNode,
  depth: number,
  root: string,
  mode: RenderMode,
  facets: Facet[],
): string[] {
  const headerIndent = "  ".repeat(depth);
  const bodyIndent = `${headerIndent}  `;
  const lines: string[] = [];
  const desc = pluginDescription(p);
  const descStr = desc ? ` — ${desc}` : "";
  const lbMarker = mode === "compact" && p.loadBearing ? " [load-bearing]" : "";

  if (mode === "compact" && p.collapsed && p.children.length > 0) {
    const total = countDescendants(p);
    const subLabel = total === 1 ? "1 sub-plugin" : `${total} sub-plugins`;
    lines.push(`${headerIndent}- **\`${p.name}\`**${lbMarker} [${subLabel}]${descStr}`);
    return lines;
  }

  lines.push(`${headerIndent}- **\`${p.name}\`**${lbMarker}${descStr}`);

  const includeBody = mode === "detail";
  if (includeBody) renderPluginFacts(p, facets, bodyIndent, root, lines);

  if (p.children.length > 0) {
    lines.push(`${bodyIndent}- Plugins:`);
    for (const c of p.children) lines.push(...renderPluginTreeMd(c, depth + 2, root, mode, facets));
  }

  return lines;
}

export interface GenerateDocsOptions {
  root: string;
}

export async function collectAllPlugins(root: string): Promise<PluginNode[]> {
  const tree = await buildPluginTree(resolve(root, "plugins"), { skipBarrelImport: true });
  return Array.from(tree.byDir.values());
}

function renderTreeBody(roots: PluginNode[], root: string, mode: RenderMode, facets: Facet[]): string {
  const lines: string[] = [];
  for (let i = 0; i < roots.length; i++) {
    if (i > 0) lines.push("");
    lines.push(...renderPluginTreeMd(roots[i]!, 0, root, mode, facets));
  }
  return lines.join("\n") + "\n";
}

const COMPACT_HEADER =
  "# Plugins (compact)\n\n" +
  "Slim, always-loaded index of every plugin. Shows only `name — description`; load-bearing infrastructure plugins are marked `[load-bearing]`; collapsed plugins show `[N sub-plugins]` — open the plugin's own `CLAUDE.md` for its full sub-tree. Read [`plugins-details.md`](./plugins-details.md) for the full reference, or open the per-plugin `CLAUDE.md` when working inside a specific plugin.\n\n";

const DETAILS_HEADER =
  "# Plugins (details)\n\n" +
  "Full reference for every plugin. Read this on demand (e.g. before writing a helper, to check whether one already exists). The slim always-loaded index is [`plugins-compact.md`](./plugins-compact.md).\n\n";

const enrichedTreeCache = new Map<string, Promise<PluginTree>>();

export function buildEnrichedTree(root: string): Promise<PluginTree> {
  let cached = enrichedTreeCache.get(root);
  if (!cached) {
    cached = buildPluginTree(resolve(root, "plugins"));
    enrichedTreeCache.set(root, cached);
  }
  return cached;
}

export async function renderCompactDoc({ root }: GenerateDocsOptions): Promise<string> {
  return renderCompactDocFromTree(await buildEnrichedTree(root), root);
}

export async function renderDetailsDoc({ root }: GenerateDocsOptions): Promise<string> {
  return renderDetailsDocFromTree(await buildEnrichedTree(root), root);
}

function renderPluginClaudeAutogen(p: PluginNode, root: string, facets: Facet[]): string {
  const lines: string[] = [];
  lines.push("## Plugin reference");
  lines.push("");
  const desc = pluginDescription(p);
  if (desc) lines.push(`- Description: ${desc}`);
  if (p.loadBearing) lines.push("- Load-bearing: yes");
  renderPluginFacts(p, facets, "", root, lines);
  if (p.children.length > 0) {
    if (p.collapsed) {
      lines.push("- Sub-plugins:");
      for (const c of p.children) {
        lines.push(...renderPluginTreeMd(c, 1, root, "compact", facets));
      }
    } else {
      lines.push("- Sub-plugins:");
      for (const c of p.children) {
        const cdesc = pluginDescription(c);
        const cdescStr = cdesc ? ` — ${cdesc}` : "";
        lines.push(`  - **\`${c.name}\`**${cdescStr}`);
      }
    }
  }
  return lines.join("\n") + "\n";
}

function renderPluginClaudeMd(p: PluginNode, existing: string | null, root: string, facets: Facet[]): string {
  const autogen = renderPluginClaudeAutogen(p, root, facets);
  const block = `${BEGIN}\n\n${autogen}\n${END}\n`;

  if (existing === null) {
    return `# ${p.name}\n\n${block}`;
  }
  const beginIdx = existing.indexOf(BEGIN);
  if (beginIdx < 0) {
    const sep = existing.endsWith("\n") ? "\n" : "\n\n";
    return `${existing}${sep}${block}`;
  }
  const endIdx = existing.indexOf(END, beginIdx);
  if (endIdx < 0) {
    return `${existing.slice(0, beginIdx)}${block}`;
  }
  const after = existing.slice(endIdx + END.length);
  const trimmedAfter = after.startsWith("\n") ? after.slice(1) : after;
  return `${existing.slice(0, beginIdx)}${block}${trimmedAfter}`;
}

export function pluginCompactDocPath(root: string): string {
  return join(root, "docs", "plugins-compact.md");
}

export function pluginDetailsDocPath(root: string): string {
  return join(root, "docs", "plugins-details.md");
}

export function pluginClaudeMdPath(p: PluginNode): string {
  return join(p.dir, "CLAUDE.md");
}

function legacyPluginDocsPath(root: string): string {
  return join(root, "docs", "plugins.md");
}

export async function generatePluginDocs({ root }: GenerateDocsOptions): Promise<void> {
  const tree = await buildEnrichedTree(root);

  const writeIfChanged = (file: string, next: string) => {
    const existing = readIfExists(file) ?? "";
    if (next !== existing) writeFileSync(file, next);
  };

  writeIfChanged(pluginCompactDocPath(root), renderCompactDocFromTree(tree, root));
  writeIfChanged(pluginDetailsDocPath(root), renderDetailsDocFromTree(tree, root));

  for (const info of tree.byDir.values()) {
    const file = pluginClaudeMdPath(info);
    const existing = readIfExists(file);
    const next = renderPluginClaudeMd(info, existing, root, tree.facets);
    if (next !== existing) writeFileSync(file, next);
  }

  const legacy = legacyPluginDocsPath(root);
  if (existsSync(legacy)) {
    try {
      unlinkSync(legacy);
    // eslint-disable-next-line promise-safety/no-bare-catch
    } catch {
      // Best-effort
    }
  }
}

function renderCompactDocFromTree(tree: PluginTree, root: string): string {
  const body = renderTreeBody(tree.roots, root, "compact", tree.facets);
  return `${COMPACT_HEADER}${BEGIN}\n\n${body}\n${END}\n`;
}

function renderDetailsDocFromTree(tree: PluginTree, root: string): string {
  const body = renderTreeBody(tree.roots, root, "detail", tree.facets);
  return `${DETAILS_HEADER}${BEGIN}\n\n${body}\n${END}\n`;
}

export { renderPluginClaudeMd };
