import { existsSync, readFileSync, unlinkSync } from "fs";
import { join } from "path";
import {
  type PluginNode,
  type PluginTree,
} from "@plugins/plugin-meta/plugins/plugin-tree/core";
import {
  getFacet,
  type Facet,
  type DocFact,
} from "@plugins/plugin-meta/plugins/facets/core";
import {
  UNDOCUMENTED_RUNTIME_FOLDERS,
  type PluginId,
} from "@plugins/framework/plugins/plugin-id/core";
import { computeDisabledIds } from "./disabled-ids";
import { writeGenerated } from "./write-generated";
import { buildBarrelFreeTree } from "./barrel-free-tree";
import { buildEnrichedTree } from "./enriched-tree";

/**
 * Marker appended to a plugin's `name — description` line when it (or its
 * dependent closure) is disabled. Disabled plugins STAY in the docs (the code
 * still exists) but are annotated. Deterministic — never names the causing seed
 * (multiple seeds would make it ambiguous and churn the in-sync check):
 *  - seed (`node.disabled === true`): ` (disabled)`
 *  - cascade (in closure, not a seed): ` (disabled — cascade)`
 */
function disabledMarker(p: PluginNode, disabled: Set<PluginId>): string {
  if (p.disabled) return " (disabled)";
  if (disabled.has(p.id)) return " (disabled — cascade)";
  return "";
}

const BEGIN =
  "<!-- AUTOGENERATED:BEGIN — do not edit; regenerated by `./singularity build` -->";
const END = "<!-- AUTOGENERATED:END -->";

function readIfExists(path: string): string | null {
  return existsSync(path) ? readFileSync(path, "utf8") : null;
}

function pluginDescription(p: PluginNode): string | undefined {
  const parts = [
    p.descriptions.web,
    p.descriptions.server,
    p.descriptions.central,
  ].filter(Boolean);
  return parts.length > 0 ? parts.join(" ") : p.description;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

/**
 * A fact's values are rendered one-per-line as a nested list — a comma-joined
 * blob of 40 importers is unreadable and rewrites the whole line in a diff when
 * a single entry is added. A lone value stays inline (it is already on its own
 * line; nesting it would only add noise).
 *
 * Facts whose folder a runtime declares undocumented are dropped here — the one
 * place every generated doc funnels through, so no facet has to know (or repeat)
 * the policy, and this renderer never names a folder.
 */
function renderDocFacts(facts: DocFact[], bodyIndent: string): string[] {
  const subIndent = `${bodyIndent}  `;
  const valueIndent = `${subIndent}  `;
  const lines: string[] = [];
  const folders = new Map<string, DocFact[]>();
  for (const f of facts) {
    if (UNDOCUMENTED_RUNTIME_FOLDERS.has(f.folder)) continue;
    let group = folders.get(f.folder);
    if (!group) {
      group = [];
      folders.set(f.folder, group);
    }
    group.push(f);
  }
  for (const [folder, group] of folders) {
    const content: string[] = [];
    for (const fact of group) {
      if (fact.values.length === 0) continue;
      if (fact.values.length === 1) {
        content.push(`${subIndent}- ${fact.key}: ${fact.values[0]}`);
        continue;
      }
      content.push(`${subIndent}- ${fact.key}:`);
      for (const value of fact.values) content.push(`${valueIndent}- ${value}`);
    }
    if (content.length > 0) {
      lines.push(`${bodyIndent}- ${capitalize(folder)}:`);
      lines.push(...content);
    }
  }
  return lines;
}

function renderPluginFacts(
  p: PluginNode,
  facets: Facet[],
  bodyIndent: string,
  root: string,
  lines: string[],
): void {
  const allFacts: DocFact[] = [];
  for (const facet of facets) {
    const data = getFacet(p, facet.def);
    if (data !== undefined) {
      allFacts.push(...facet.renderDoc(data, { root }));
    }
  }
  lines.push(...renderDocFacts(allFacts, bodyIndent));
}

type RenderMode = "detail" | "compact";

function countDescendants(p: PluginNode): number {
  let n = 0;
  for (const c of p.children) n += 1 + countDescendants(c);
  return n;
}

function renderPluginTreeMd(
  p: PluginNode,
  depth: number,
  root: string,
  mode: RenderMode,
  facets: Facet[],
  disabled: Set<PluginId>,
): string[] {
  const headerIndent = "  ".repeat(depth);
  const bodyIndent = `${headerIndent}  `;
  const lines: string[] = [];
  const desc = pluginDescription(p);
  const descStr = desc ? ` — ${desc}` : "";
  const lbMarker = mode === "compact" && p.loadBearing ? " [load-bearing]" : "";
  const disMarker = disabledMarker(p, disabled);

  if (mode === "compact" && p.collapsed && p.children.length > 0) {
    const total = countDescendants(p);
    const subLabel = total === 1 ? "1 sub-plugin" : `${total} sub-plugins`;
    lines.push(
      `${headerIndent}- **\`${p.name}\`**${lbMarker} [${subLabel}]${disMarker}${descStr}`,
    );
    return lines;
  }

  lines.push(
    `${headerIndent}- **\`${p.name}\`**${lbMarker}${disMarker}${descStr}`,
  );

  const includeBody = mode === "detail";
  if (includeBody) renderPluginFacts(p, facets, bodyIndent, root, lines);

  if (p.children.length > 0) {
    lines.push(`${bodyIndent}- Plugins:`);
    for (const c of p.children)
      lines.push(
        ...renderPluginTreeMd(c, depth + 2, root, mode, facets, disabled),
      );
  }

  return lines;
}

export interface GenerateDocsOptions {
  root: string;
}

export async function collectAllPlugins(root: string): Promise<PluginNode[]> {
  const tree = await buildBarrelFreeTree(root);
  return Array.from(tree.byDir.values());
}

function renderTreeBody(
  roots: PluginNode[],
  root: string,
  mode: RenderMode,
  facets: Facet[],
  disabled: Set<PluginId>,
): string {
  const lines: string[] = [];
  for (let i = 0; i < roots.length; i++) {
    if (i > 0) lines.push("");
    lines.push(
      ...renderPluginTreeMd(roots[i]!, 0, root, mode, facets, disabled),
    );
  }
  return lines.join("\n") + "\n";
}

const COMPACT_HEADER =
  "# Plugins (compact)\n\n" +
  "Slim, always-loaded index of every plugin. Shows only `name — description`; load-bearing infrastructure plugins are marked `[load-bearing]`; collapsed plugins show `[N sub-plugins]` — open the plugin's own `CLAUDE.md` for its full sub-tree. Read [`plugins-details.md`](./plugins-details.md) for the full reference, or open the per-plugin `CLAUDE.md` when working inside a specific plugin.\n\n";

const DETAILS_HEADER =
  "# Plugins (details)\n\n" +
  "Full reference for every plugin. Read this on demand (e.g. before writing a helper, to check whether one already exists). The slim always-loaded index is [`plugins-compact.md`](./plugins-compact.md).\n\n";

export async function renderCompactDoc({
  root,
}: GenerateDocsOptions): Promise<string> {
  return renderCompactDocFromTree(await buildEnrichedTree(root), root);
}

export async function renderDetailsDoc({
  root,
}: GenerateDocsOptions): Promise<string> {
  return renderDetailsDocFromTree(await buildEnrichedTree(root), root);
}

function renderPluginClaudeAutogen(
  p: PluginNode,
  root: string,
  facets: Facet[],
  disabled: Set<PluginId>,
): string {
  const lines: string[] = [];
  lines.push("## Plugin reference");
  lines.push("");
  const desc = pluginDescription(p);
  if (desc) lines.push(`- Description: ${desc}`);
  if (p.loadBearing) lines.push("- Load-bearing: yes");
  // Annotate disabled plugins (the code still exists, but it's omitted from the
  // registries/bundle). Seed vs derived-cascade, deterministic — never names the
  // causing seed (see `disabledMarker`).
  if (p.disabled) lines.push("- Disabled: yes");
  else if (disabled.has(p.id)) lines.push("- Disabled: cascade");
  renderPluginFacts(p, facets, "", root, lines);
  if (p.children.length > 0) {
    if (p.collapsed) {
      lines.push("- Sub-plugins:");
      for (const c of p.children) {
        lines.push(
          ...renderPluginTreeMd(c, 1, root, "compact", facets, disabled),
        );
      }
    } else {
      lines.push("- Sub-plugins:");
      for (const c of p.children) {
        const cdesc = pluginDescription(c);
        const cdescStr = cdesc ? ` — ${cdesc}` : "";
        const cDisMarker = disabledMarker(c, disabled);
        lines.push(`  - **\`${c.name}\`**${cDisMarker}${cdescStr}`);
      }
    }
  }
  return lines.join("\n") + "\n";
}

function renderPluginClaudeMd(
  p: PluginNode,
  existing: string | null,
  root: string,
  facets: Facet[],
  disabled: Set<PluginId>,
): string {
  const autogen = renderPluginClaudeAutogen(p, root, facets, disabled);
  const block = `${BEGIN}\n\n${autogen}\n${END}\n`;

  if (existing === null) {
    return `# ${p.name}\n\n${block}`;
  }
  const beginIdx = existing.indexOf(BEGIN);
  if (beginIdx < 0) {
    const sep = existing.endsWith("\n") ? "\n" : "\n\n";
    return `${existing}${sep}${block}`;
  }
  const endIdx = existing.indexOf(END, beginIdx);
  if (endIdx < 0) {
    return `${existing.slice(0, beginIdx)}${block}`;
  }
  const after = existing.slice(endIdx + END.length);
  const trimmedAfter = after.startsWith("\n") ? after.slice(1) : after;
  return `${existing.slice(0, beginIdx)}${block}${trimmedAfter}`;
}

export function pluginCompactDocPath(root: string): string {
  return join(root, "docs", "plugins-compact.md");
}

export function pluginDetailsDocPath(root: string): string {
  return join(root, "docs", "plugins-details.md");
}

export function pluginClaudeMdPath(p: PluginNode): string {
  return join(p.dir, "CLAUDE.md");
}

function legacyPluginDocsPath(root: string): string {
  return join(root, "docs", "plugins.md");
}

export async function generatePluginDocs({
  root,
}: GenerateDocsOptions): Promise<void> {
  const tree = await buildEnrichedTree(root);
  const disabled = computeDisabledIds(tree);

  // Markdown is not in the format allowlist, so the funnel hands these bytes
  // back untouched — they route through it anyway so there is exactly one write
  // idiom for generated artifacts, with no per-extension opt-in to forget.
  await writeGenerated({
    file: pluginCompactDocPath(root),
    content: renderCompactDocFromTree(tree, root),
  });
  await writeGenerated({
    file: pluginDetailsDocPath(root),
    content: renderDetailsDocFromTree(tree, root),
  });

  for (const info of tree.byDir.values()) {
    const file = pluginClaudeMdPath(info);
    // The renderer needs the CURRENT file (it rewrites only the AUTOGEN block
    // and preserves the hand-written prose around it), so the read stays here.
    const existing = readIfExists(file);
    await writeGenerated({
      file,
      content: renderPluginClaudeMd(
        info,
        existing,
        root,
        tree.facets,
        disabled,
      ),
    });
  }

  const legacy = legacyPluginDocsPath(root);
  if (existsSync(legacy)) {
    try {
      unlinkSync(legacy);
      // eslint-disable-next-line promise-safety/no-bare-catch
    } catch {
      // Best-effort
    }
  }
}

function renderCompactDocFromTree(tree: PluginTree, root: string): string {
  const body = renderTreeBody(
    tree.roots,
    root,
    "compact",
    tree.facets,
    computeDisabledIds(tree),
  );
  return `${COMPACT_HEADER}${BEGIN}\n\n${body}\n${END}\n`;
}

function renderDetailsDocFromTree(tree: PluginTree, root: string): string {
  const body = renderTreeBody(
    tree.roots,
    root,
    "detail",
    tree.facets,
    computeDisabledIds(tree),
  );
  return `${DETAILS_HEADER}${BEGIN}\n\n${body}\n${END}\n`;
}

export { renderPluginClaudeMd };
