import { join } from "path";
import {
  isTestCodePath,
  TESTS_DIR,
  TESTING_FOLDER,
} from "@plugins/framework/plugins/plugin-id/core";
import type { RepoFiles } from "@plugins/framework/plugins/tooling/core";
import { createSemaphore } from "@plugins/packages/plugins/semaphore/core";
import { writeGenerated } from "./write-generated";
import {
  findImports,
  findMarkerCalls,
  lineAt,
  markerCallSpans,
  maskSource,
  parseBoolField,
  parseStaticCallId,
  unresolvableCallIdMessage,
} from "@plugins/plugin-meta/plugins/parse-utils/core";
import { resourceDescriptorFactories } from "@plugins/framework/plugins/tooling/plugins/resource-vocabulary/core";
import {
  buildRegistryGenContext,
  collectEntriesWithDeps,
  type RegistryGenContext,
} from "./plugin-registry-gen";
import { readListed, timeSlicer } from "./scan-pacing";

/**
 * Generates the web load-tier manifest: the DEFERRED plugin-path set that
 * `load-tiers.ts` consumes to split the web registry into the eager substrate
 * (loaded before first paint) and deferred app content (loaded after).
 *
 * Why this exists. The eager set was two hand-maintained allowlists
 * (`DEFERRABLE_APPS` / `EAGER_EXCEPTIONS`) that broke twice — a boot-critical
 * descriptor whose owning plugin was deferred (release, fixed by 146da4a80), and
 * a config web-registration read by an eager shell (sonata/voicing). Both are
 * DECLARED facts, so this derives the eager set from them at codegen time and
 * makes every app deferrable by default.
 *
 * A web plugin is EAGER iff one of four declared/derived facts holds:
 *   1. Structural — it is not app content (`apps/plugins/<app>/plugins/<child>`
 *      with `<child> !== "shell"`): framework, primitives, shared domains, and
 *      every app's `shell` subtree.
 *   2. Watched boot slot — its `web`/`core`/`shared` files call a slot factory
 *      whose contributions always-eager global chrome reads at boot
 *      (`Core.Root`, `Core.Boot`, `Apps.App`, `ActionBar.Item`).
 *   3. Boot-critical resource descriptor — its `core`/`shared`/`web` files
 *      declare a live-state descriptor with `bootCritical: true`. Also enforces
 *      reachability: generation throws if the owning plugin has no web entry.
 *   4. Transitive `dependsOn` closure — anything an eager plugin (transitively)
 *      imports is eager (the `web.generated.ts` dependency graph).
 *
 * The artifact is the DEFERRED set (fail-safe direction: an unknown path → eager,
 * so a modeling gap only over-eagers, never wrongly defers). Deterministic and
 * byte-stable (no Date/randomness); the `eager-tier-in-sync` check fails on drift.
 */

const MANIFEST_REL_PATH =
  "plugins/framework/plugins/web-sdk/core/web-tiers.generated.ts";

const MANIFEST_HEADER = [
  "// DO NOT EDIT — autogenerated by `./singularity build`",
  "// (see plugins/framework/plugins/tooling/plugins/codegen/core/eager-tier-gen.ts).",
  "//",
  "// The DEFERRED web plugin-path set consumed by load-tiers.ts. A plugin is EAGER",
  "// (absent from this set, loaded before first paint) iff it is non-app-content /",
  "// a shell subtree (structural), calls a watched boot slot (Core.Root / Core.Boot",
  "// / Apps.App / ActionBar.Item), owns a bootCritical resource descriptor, or is",
  "// pulled in by the transitive dependsOn closure of any of those. Everything else",
  "// — app content that no eager surface needs at boot — defers.",
  "//",
  "// Fail-safe direction: an unknown path is treated as EAGER, so a modeling gap",
  "// only makes a plugin needlessly eager (slower boot), never wrongly deferred.",
  "//",
  "// The `eager-tier-in-sync` check fails on drift.",
].join("\n");

// ── Structural predicate ───────────────────────────────────────────

// `apps/plugins/<app>/plugins/<rest>` — app *content* iff the first `<rest>`
// segment is not `shell`. Anything shallower (a non-`apps/` plugin, an app
// umbrella, an app's `shell` subtree) is NOT app content and stays eager.
const APP_CONTENT_RE = /^apps\/plugins\/[^/]+\/plugins\/(.+)$/;

/**
 * True IFF `pluginPath` is deferrable-by-default app content:
 * `apps/plugins/<app>/plugins/<child>/…` with `<child> !== "shell"`. Everything
 * else (framework, primitives, shared domains, app umbrellas, and each app's
 * own `shell` subtree) is structurally eager. Pure — exported for tests.
 */
export function isAppContent(pluginPath: string): boolean {
  const m = APP_CONTENT_RE.exec(pluginPath);
  if (!m) return false;
  const firstChild = m[1]!.split("/")[0]!;
  return firstChild !== "shell";
}

// ── Pure core (seed computation + closure) ─────────────────────────

/** A plugin declaring one or more `bootCritical: true` descriptors. */
export interface BootCriticalOwner {
  /** Plugin path (may or may not have a web entry — reachability is enforced). */
  path: string;
  /** Descriptor keys found (for the reachability error + debug annotations). */
  keys: string[];
}

/** An app-content plugin whose files call a watched boot slot factory. */
export interface WatchedSlotHit {
  path: string;
  /** The watched slot marker matched (e.g. `Core.Root`), used as the pin reason. */
  slot: string;
}

export interface EagerTierResult {
  /** Sorted deferred plugin paths. */
  deferred: string[];
  /** App-content plugins pinned eager, with why (sorted) — for the comment block. */
  appContentPins: { path: string; reason: string }[];
}

const CLOSURE_REASON = "dependency closure (imported by an eager plugin)";

/**
 * Compute the deferred set from injected, already-scanned inputs. Pure and
 * synchronous so it is unit-testable with synthetic data.
 *
 * Throws the reachability error if a `bootCritical` descriptor's owning plugin
 * has no web entry — the exact 146da4a80 bug class, made unrepresentable.
 */
export function computeEagerTier(input: {
  webEntryPaths: string[];
  /** Forward edges: `pluginPath` → the web-entry pluginPaths it imports. */
  deps: Map<string, string[]>;
  bootCriticalOwners: BootCriticalOwner[];
  watchedSlotHits: WatchedSlotHit[];
}): EagerTierResult {
  const webSet = new Set(input.webEntryPaths);

  // Reachability guard: a bootCritical descriptor is registered client-side only
  // as a side effect of its owning plugin's web barrel being loaded. If that
  // plugin has no web entry (or is deferred), boot-snapshot can never hydrate the
  // descriptor. Fail generation loudly with the fix.
  for (const owner of input.bootCriticalOwners) {
    if (!webSet.has(owner.path)) {
      throw new Error(
        `Boot-critical resource descriptor(s) [${owner.keys.join(", ")}] declared in ` +
          `plugins/${owner.path} have no web entry, so nothing pulls them into the web ` +
          `import graph and boot-snapshot cannot hydrate them before first paint.\n` +
          `Fix: add a registration-only web barrel (plugins/${owner.path}/web/index.ts) ` +
          `that side-effect-imports the descriptor module, mirroring ` +
          `plugins/release/web/index.ts (commit 146da4a80).`,
      );
    }
  }

  // Seeds, first reason wins (a seed is a set; the reason is for annotation only).
  const seedReason = new Map<string, string>();
  const addSeed = (path: string, reason: string) => {
    if (!seedReason.has(path)) seedReason.set(path, reason);
  };

  // (1) Structural: every non-app-content web entry (incl. shell subtrees).
  for (const p of input.webEntryPaths) {
    if (!isAppContent(p))
      addSeed(p, "structural (non-app-content / shell subtree)");
  }
  // (2) Watched boot slots.
  for (const hit of input.watchedSlotHits) {
    if (webSet.has(hit.path))
      addSeed(hit.path, `watched boot slot ${hit.slot}`);
  }
  // (3) Boot-critical descriptors (all reachable after the guard above).
  for (const owner of input.bootCriticalOwners) {
    addSeed(owner.path, `boot-critical descriptor (${owner.keys.join(", ")})`);
  }

  // (4) Forward transitive closure over `deps`, restricted to web entries.
  const eager = new Set<string>();
  const stack = [...seedReason.keys()];
  while (stack.length > 0) {
    const p = stack.pop()!;
    if (eager.has(p)) continue;
    eager.add(p);
    for (const d of input.deps.get(p) ?? []) {
      if (webSet.has(d) && !eager.has(d)) stack.push(d);
    }
  }

  const deferred = input.webEntryPaths.filter((p) => !eager.has(p)).sort();

  // Annotate every APP-CONTENT plugin that ended up eager (structural eagers are
  // uninteresting — they are the whole substrate). Its reason is its seed reason
  // if it was seeded, else it was pulled in by the closure.
  const appContentPins: { path: string; reason: string }[] = [];
  for (const p of input.webEntryPaths) {
    if (!isAppContent(p) || !eager.has(p)) continue;
    appContentPins.push({
      path: p,
      reason: seedReason.get(p) ?? CLOSURE_REASON,
    });
  }
  appContentPins.sort((a, b) => a.path.localeCompare(b.path));

  return { deferred, appContentPins };
}

// ── Scanners over the file set ─────────────────────────────────────

// The slot factories whose contributions always-eager global chrome reads at
// boot. Each is guarded on the file also importing `head` from an `@plugins/`
// specifier, so a bare textual mention of the member cannot false-positive.
const WATCHED_SLOTS: { marker: string; head: string }[] = [
  { marker: "Core.Root", head: "Core" },
  { marker: "Core.Boot", head: "Core" },
  { marker: "Apps.App", head: "Apps" },
  { marker: "ActionBar.Item", head: "ActionBar" },
];

// The descriptor factories that can carry `bootCritical: true` in a trailing
// options object come from the shared vocabulary
// (`tooling/resource-vocabulary/core`), whose key set `tsc` derives from the
// live-state and query-resource barrels themselves.
//
// This file used to keep its own four-name list, and the docs facet kept a
// different three-name one. Neither knew the five bounded-membership factories,
// so a `windowQueryResourceDescriptor(…, { bootCritical: true })` under
// `apps/plugins/**` was invisible here: the plugin stayed deferred, its
// descriptor was not registered before the boot snapshot hydrated, and the
// surface painted the pending state it was designed never to show. Every miss
// looked exactly like a plugin declaring nothing.
//
// Each name must still be a DISTINCT identifier for the textual scan
// (`\bresourceDescriptor` does not match inside `queryResourceDescriptor`),
// which is what `findMarkerCalls` guarantees.
const DESCRIPTOR_FACTORIES = Object.entries(resourceDescriptorFactories);

/** Every identifier imported from any `@plugins/` specifier in `src`. */
function pluginImportedIdents(src: string): Set<string> {
  const idents = new Set<string>();
  // `findImports` masks comments/regex/strings and reads specifiers by offset,
  // so an import written inside a string/comment never contributes idents.
  for (const imp of findImports(src)) {
    if (imp.keyword !== "import" || imp.sideEffect) continue;
    if (!imp.specifier.startsWith("@plugins/")) continue;
    // `clause` excludes `from`/quotes/`;`, so this is the same token set the old
    // bindings-capture word-scan collected.
    for (const w of imp.clause.match(/[A-Za-z_$][\w$]*/g) ?? []) idents.add(w);
  }
  return idents;
}

// How many plugins' files the scan holds in flight at once. The file set's own
// reader bounds the opens; this bounds how much text is resident.
const PLUGIN_SCAN_WIDTH = 16;

// parse-utils' `walkFiles` predicate, over the file set instead of a directory
// walk: `.ts`/`.tsx` that is not test code (via `isTestCodePath`), skipping
// `node_modules`, nested `plugins/` (sub-plugins are their own nodes) and
// test-code directories.
const SOURCE_FILE_RE = /\.tsx?$/;
const SKIPPED_DIRS = new Set([
  "node_modules",
  "plugins",
  TESTS_DIR,
  TESTING_FOLDER,
]);

/** A plugin's source files under each of `subs`, in `subs` order. */
function sourceFilesUnder(
  repo: RepoFiles,
  pluginPath: string,
  subs: readonly string[],
): string[] {
  const out: string[] = [];
  for (const sub of subs) {
    const base = `plugins/${pluginPath}/${sub}`;
    for (const rel of repo.under(base)) {
      const segments = rel.slice(base.length + 1).split("/");
      const name = segments.pop()!;
      if (!SOURCE_FILE_RE.test(name) || isTestCodePath([name])) continue;
      if (segments.some((s) => SKIPPED_DIRS.has(s))) continue;
      out.push(rel);
    }
  }
  return out;
}

interface Source {
  rel: string;
  text: string;
}

/** The first watched boot slot one of `sources` genuinely calls (with its head imported), or null. */
async function watchedSlotIn(
  sources: readonly Source[],
  tick: () => Promise<void>,
): Promise<string | null> {
  for (const { text } of sources) {
    const idents = pluginImportedIdents(text);
    await tick();
    for (const { marker, head } of WATCHED_SLOTS) {
      if (!idents.has(head)) continue;
      if (!text.includes(marker)) continue; // cheap fast-path
      if (findMarkerCalls(text, marker).length > 0) return marker;
    }
  }
  return null;
}

/**
 * Every `bootCritical: true` descriptor key in ONE source file, in source order.
 *
 * The file is FULL-masked (so a factory written inside a comment, string or
 * template literal is never matched) and each key is read back from the ORIGINAL
 * by offset. THROWS — naming `displayPath`, the line and the offending
 * expression — on a boot-critical declaration whose key is not a static string
 * literal. The key used to fall back to `"(unknown)"`, which pins the plugin
 * eager (right) but names it in the manifest as a key that matches nothing
 * (wrong, and silent). A boot-critical resource is one whose absence before
 * first paint is a visible loading flash, so the one thing this scan must not do
 * is guess.
 *
 * The plugins that OWN the factories need no exemption here (unlike the docs
 * facet's index, which reads EVERY declaration): a wrapper forwards its caller's
 * opts rather than writing a `bootCritical: true` literal, so no call inside
 * `live-state` / `query-resource` reaches the key read at all.
 */
export function bootCriticalKeysIn(src: string, displayPath: string): string[] {
  const keys: string[] = [];
  let masked: string | null = null;
  for (const [factory, entry] of DESCRIPTOR_FACTORIES) {
    if (!src.includes(factory)) continue; // cheap fast-path
    masked ??= maskSource(src);
    for (const span of markerCallSpans(masked, factory)) {
      const argsText = src.slice(span.open + 1, span.close);
      if (!parseBoolField(argsText, "bootCritical")) continue;
      const id = parseStaticCallId(src, span);
      if (id.kind !== "value") {
        throw new Error(
          unresolvableCallIdMessage({
            marker: factory,
            file: displayPath,
            line: lineAt(src, span.identifier),
            expr: id.kind === "dynamic" ? id.expr : "",
            hint:
              "A `bootCritical: true` descriptor pins its plugin into the eager " +
              "load tier, and this manifest is built from source text — so the key " +
              "must be a literal at the declaration site. Inline the literal " +
              "instead of hoisting or interpolating it.",
          }),
        );
      }
      // A collection factory mints several resources from one literal key;
      // every one of them is boot-critical.
      for (const m of entry.mints) keys.push(id.value + m.suffix);
    }
  }
  return keys;
}

// ── Render + public API ────────────────────────────────────────────

function renderManifest(result: EagerTierResult): string {
  const lines: string[] = [MANIFEST_HEADER, ""];
  lines.push(
    "// App-content plugins pinned EAGER (would otherwise defer), and why:",
  );
  if (result.appContentPins.length === 0) {
    lines.push("//   (none)");
  } else {
    for (const pin of result.appContentPins) {
      lines.push(`//   - ${pin.path}: ${pin.reason}`);
    }
  }
  lines.push("");
  lines.push(
    "export const DEFERRED_PLUGIN_PATHS: ReadonlySet<string> = new Set([",
  );
  for (const p of result.deferred) lines.push(`  ${JSON.stringify(p)},`);
  lines.push("]);");
  lines.push("");
  return lines.join("\n");
}

/**
 * Scan the tree and build the pure-core inputs. `ctx` carries the barrel-free
 * tree, its edge graph, the app's own bundle and the file set, so it can be
 * shared with the registry generator.
 */
async function scanEagerTierInputs(
  ctx: RegistryGenContext,
): Promise<Parameters<typeof computeEagerTier>[0]> {
  // The eager tier describes the registry the app SHIPS, so it reads exactly the
  // entry set `generatePluginRegistry` emitted — the same bundle, not a second
  // opinion about who is in it.
  const { entries, deps } = await collectEntriesWithDeps(
    ctx,
    "web",
    ctx.mainBundle,
  );
  const webEntryPaths = entries.map((e) => e.pluginPath);
  const webSet = new Set(webEntryPaths);
  const repo = await ctx.repo();

  const watchedSlotHits: WatchedSlotHit[] = [];
  const bootCriticalOwners: BootCriticalOwner[] = [];
  const tick = timeSlicer();
  const gate = createSemaphore(PLUGIN_SCAN_WIDTH);
  await Promise.all(
    [...ctx.tree.byDir.values()].map((node) =>
      gate.run(async () => {
        // One read of the plugin's web/core/shared files serves both scans. The
        // order is the watched-slot scan's (its first hit names the pin).
        const files = sourceFilesUnder(repo, node.path, [
          "web",
          "core",
          "shared",
        ]);
        const sources = await Promise.all(
          files.map(async (rel) => ({
            rel,
            text: await readListed(repo, rel),
          })),
        );

        // Watched-slot scan: only app-content web entries can flip from
        // deferred to eager via a slot (non-app-content is already
        // structurally eager).
        if (webSet.has(node.path) && isAppContent(node.path)) {
          const slot = await watchedSlotIn(sources, tick);
          if (slot) watchedSlotHits.push({ path: node.path, slot });
        }

        // bootCritical scan: EVERY plugin node (reachability is checked
        // against web entries in the pure core, so a descriptor in a
        // web-entryless plugin throws).
        const keys: string[] = [];
        for (const { rel, text } of sources) {
          keys.push(...bootCriticalKeysIn(text, join(ctx.root, rel)));
          await tick();
        }
        if (keys.length > 0)
          bootCriticalOwners.push({ path: node.path, keys: keys.sort() });
      }),
    ),
  );
  // The scan finishes plugins in whatever order their reads land; the pure core
  // gets them sorted, as the sequential scan used to hand them over.
  watchedSlotHits.sort((a, b) => a.path.localeCompare(b.path));
  bootCriticalOwners.sort((a, b) => a.path.localeCompare(b.path));

  // Restrict deps to web entries defensively (collectEntriesWithDeps already prunes).
  const prunedDeps = new Map<string, string[]>();
  for (const [path, ds] of deps) {
    const kept = ds.filter((d) => webSet.has(d));
    if (kept.length > 0) prunedDeps.set(path, kept);
  }

  return {
    webEntryPaths,
    deps: prunedDeps,
    bootCriticalOwners,
    watchedSlotHits,
  };
}

/** Path to the committed manifest file. */
export function eagerTierManifestPath(root: string): string {
  return join(root, MANIFEST_REL_PATH);
}

/**
 * Render the manifest file contents in-memory (used by the in-sync check). May
 * THROW the reachability error. Builds its own context when none is supplied.
 */
export async function renderEagerTierManifest(
  root: string,
  ctx?: RegistryGenContext,
): Promise<string> {
  const resolvedCtx = ctx ?? (await buildRegistryGenContext(root));
  const result = computeEagerTier(await scanEagerTierInputs(resolvedCtx));
  return renderManifest(result);
}

/** Regenerate `web-tiers.generated.ts` if it drifted. */
export async function generateEagerTier(opts: {
  root: string;
  ctx?: RegistryGenContext;
}): Promise<void> {
  await writeGenerated({
    file: eagerTierManifestPath(opts.root),
    content: await renderEagerTierManifest(opts.root, opts.ctx),
  });
}
