import { resolve } from "path";
import {
  buildPluginTree,
  type PluginTree,
} from "@plugins/plugin-meta/plugins/plugin-tree/core";
import { declareSlotsFromBarrels } from "./slot-declaration-guard";

const enrichedTreeCache = new Map<string, Promise<PluginTree>>();

/**
 * The ENRICHED plugin tree: every node's barrels imported, every facet extracted.
 * The only construction site of a barrel-imported facet tree in the repo — every
 * other `buildPluginTree` caller passes `skipBarrelImport` — so everything that
 * reads a plugin's `contributions` (both docs, every per-plugin `CLAUDE.md`, the
 * config-origin and reorderable-slots generators, the page-editor checks) comes
 * through here.
 *
 * WHY THE DECLARATION PASS RUNS HERE. A plugin's `contributions` array is not
 * always a literal: `reorder` starts with an EMPTY array that a
 * `subscribeSlotsDeclared` callback fills, so it holds 0 entries until a
 * slot-declaration pass has run in this process and ~240 after. Importing the
 * barrel is therefore not enough to read contributions — the pass is a genuine
 * precondition, and a caller that skips it gets a smaller, plausible-looking
 * answer rather than an error.
 *
 * That precondition used to live only in the regen pipeline's step ordering (the
 * guard step runs before docgen), which meant it held inside `./singularity build`
 * and nowhere else: `plugins-doc-in-sync` called the renderer directly, read
 * reorder as contributing nothing, and reported the committed doc out of sync.
 * Same source, two outputs, decided by process history. Owning the precondition
 * here makes the tree — and so every generated artifact downstream of it — a pure
 * function of the checkout, whatever process asks for it.
 *
 * `declareSlotsFromBarrels` is memoized per root, so inside a build (where the
 * guard step already ran) this awaits a settled promise and costs nothing; the
 * generated bytes are unchanged. In a lone check it pays for the pass once.
 *
 * The pass deliberately keeps its own barrel-import loop rather than folding into
 * `buildPluginTree`: it models the plugin REGISTRY and skips disabled plugins,
 * while this tree imports every node's barrel. See the note on
 * `declareSlotsFromBarrels` for why declaring over the full set would break
 * `config-v2:registrations-paired`.
 */
export function buildEnrichedTree(root: string): Promise<PluginTree> {
  let cached = enrichedTreeCache.get(root);
  if (!cached) {
    cached = (async () => {
      await declareSlotsFromBarrels(root);
      return buildPluginTree(resolve(root, "plugins"), { facets: true });
    })();
    enrichedTreeCache.set(root, cached);
  }
  return cached;
}
