import { join } from "path";
import { loadLintContributions } from "@plugins/framework/plugins/tooling/plugins/lint/core";
import type * as ChecksCore from "@plugins/framework/plugins/tooling/plugins/checks/core";
import { writeGenerated } from "./write-generated";

/**
 * Generates `ExemptableRuleId` — the union an `exempt/index.ts` types its
 * `rule` with, so a misspelled or closed rule id is a tsc error in the
 * manifest itself.
 *
 * The set is read off the LIVE contributions, never a list: every contributed
 * lint rule (`<ns>/<rule>`) its barrel does not declare `closed`, plus every id
 * a check declares `exemptable`. Adding a rule or an exemptable id is the only
 * edit; the `exempt:rule-ids-in-sync` check fails on drift.
 */

export const EXEMPT_RULE_IDS_REL_PATH =
  "plugins/framework/plugins/tooling/plugins/exempt/core/rule-ids.generated.ts";

const HEADER = [
  "// DO NOT EDIT — autogenerated by `./singularity build`",
  "// (see plugins/framework/plugins/tooling/plugins/codegen/core/exempt-rule-ids-gen.ts).",
  "//",
  "// Every rule id an `exempt/index.ts` may name: each contributed lint rule",
  "// (`<ns>/<rule>`) not declared `closed`, and each id a check declares",
  "// `exemptable`. The `exempt:rule-ids-in-sync` check fails on drift.",
].join("\n");

// The check fleet is loaded through a COMPUTED specifier. `listAllChecks`
// imports every check module, and those reach server barrels and their
// generated manifests; a literal import here would put the whole fleet in the
// static closure of everything that imports the codegen barrel — a CLI command
// that regenerates would then load a manifest before writing it
// (`cli:codegen-manifests-not-frozen`). Deferred, the fleet loads only when
// this step runs: the last step of the manifest pipeline, after every write.
const CHECKS_CORE = "@plugins/framework/plugins/tooling/plugins/checks/core";

/** The exemptable ids, sorted: open lint rules plus declared check ids. */
export async function collectExemptableRuleIds(
  root: string,
): Promise<string[]> {
  const { listAllChecks } = (await import(CHECKS_CORE)) as typeof ChecksCore;
  const [contributions, checks] = await Promise.all([
    loadLintContributions(root),
    listAllChecks(),
  ]);
  const ids = new Set<string>();
  for (const c of contributions) {
    const closed = new Set(c.closed);
    for (const rule of Object.keys(c.rules)) {
      if (!closed.has(rule)) ids.add(`${c.name}/${rule}`);
    }
  }
  for (const check of checks) {
    for (const id of Object.keys(check.exemptable ?? {})) ids.add(id);
  }
  return [...ids].sort();
}

export async function renderExemptRuleIds(root: string): Promise<string> {
  const ids = await collectExemptableRuleIds(root);
  const union =
    ids.length === 0
      ? "never"
      : `\n${ids.map((id) => `  | ${JSON.stringify(id)}`).join("\n")}`;
  return `${HEADER}\n\nexport type ExemptableRuleId = ${union};\n`;
}

export function exemptRuleIdsPath(root: string): string {
  return join(root, EXEMPT_RULE_IDS_REL_PATH);
}

export async function generateExemptRuleIds({
  root,
}: {
  root: string;
}): Promise<void> {
  await writeGenerated({
    file: exemptRuleIdsPath(root),
    content: await renderExemptRuleIds(root),
  });
}
