import { existsSync, readFileSync, writeFileSync } from "fs";
import { join, resolve } from "path";
import { buildPluginTree } from "@plugins/plugin-meta/plugins/plugin-tree/core";
import { maskSource } from "@plugins/plugin-meta/plugins/parse-utils/core";

/**
 * Generates the fields eager-capability manifest: side-effect imports of every
 * `fields/plugins/<type>/plugins/{storage,filter-sql}/server` barrel.
 *
 * Why this exists. `defineEntity` resolves a field type's Drizzle column builder
 * (`resolveFieldStorage`) SYNCHRONOUSLY at module-eval — before the boot-time
 * `collectContributions` pass populates the live registry — so the
 * `fields/server-capabilities` library keeps an eager index that each
 * `Fields.Storage(...)` / `Fields.FilterSql(...)` call self-registers into. For
 * that index to be populated, every capability barrel must have been evaluated.
 * The barrels were previously force-loaded via a runtime `readdirSync` of the
 * source tree, which (a) is invisible to the composition-closure analyzer, so a
 * filtered release bundle EXCLUDED all of them, and (b) resolves to a non-existent
 * `/plugins` inside a `bun --compile` binary (`import.meta.url` = `/$bunfs/root/…`),
 * crash-looping the release backend.
 *
 * This manifest replaces that scan with real static `import`s: the closure
 * analyzer now sees the edges (barrels land in every bundle), and ESM evaluates
 * them — self-registering each builder — before any `defineEntity` body runs. It
 * lives in the `fields/server-capabilities-loader` plugin (NOT the token-owning
 * `server-capabilities` library, which stays a graph sink): its closure is
 * `loader → barrels → server-capabilities`, a clean DAG. Every eval-time consumer
 * imports the loader barrel for side-effect.
 *
 * The renderer is barrel-FREE (a static `skipBarrelImport` tree scan), so it is
 * sound to regenerate in the pre-barrel phase before the first barrel import
 * freezes the ESM cache. The `fields-eager-in-sync` check fails on drift.
 */

const MANIFEST_REL_PATH =
  "plugins/fields/plugins/server-capabilities-loader/server/internal/eager.generated.ts";

const MANIFEST_HEADER = [
  "// DO NOT EDIT — autogenerated by `./singularity build`",
  "// (see plugins/framework/plugins/tooling/plugins/codegen/core/fields-eager-gen.ts).",
  "//",
  "// Side-effect imports of every fields storage / filter-sql *server* capability",
  "// barrel. This `server-capabilities-loader` barrel imports it so each barrel's",
  "// `Fields.Storage(...)` / `Fields.FilterSql(...)` self-registers into the",
  "// `server-capabilities` eager index at module-eval (before any `defineEntity`",
  "// runs), and so the composition closure statically includes these barrels — no",
  "// runtime filesystem scan. Eval-time consumers import this loader for side-effect.",
  "//",
  "// The `fields-eager-in-sync` check fails on drift.",
].join("\n");

// A fields capability sub-plugin whose `server` barrel must be eagerly loaded:
// `fields/plugins/<type>/plugins/{storage,filter-sql}`.
const CAPABILITY_RE = /^fields\/plugins\/[^/]+\/plugins\/(?:storage|filter-sql)$/;

function hasDefaultExport(file: string): boolean {
  // Mask comments/regex/strings so a commented-out or string-embedded `export
  // default` can't make an entryless barrel look like an entry. This is a pure
  // code-construct detector — the string interior is never read back.
  const src = maskSource(readFileSync(file, "utf8"));
  return (
    /(^|\n)\s*export\s+default\b/.test(src) ||
    /(^|\n)\s*export\s*\{[^}]*\bdefault\b[^}]*\}/.test(src)
  );
}

/**
 * Walk the plugin tree (barrel-free static scan) and collect the `@plugins/…`
 * specifier of every fields storage/filter-sql `server` barrel with a default
 * export. Sorted for deterministic output.
 */
export async function collectFieldEagerBarrels(root: string): Promise<string[]> {
  const tree = await buildPluginTree(resolve(root, "plugins"), {
    skipBarrelImport: true,
  });
  const specifiers: string[] = [];
  for (const node of tree.byDir.values()) {
    if (!CAPABILITY_RE.test(node.path)) continue;
    const barrel = join(node.dir, "server", "index.ts");
    if (!existsSync(barrel) || !hasDefaultExport(barrel)) continue;
    specifiers.push(`@plugins/${node.path}/server`);
  }
  return specifiers.sort();
}

function renderManifest(specifiers: string[]): string {
  const lines: string[] = [MANIFEST_HEADER, ""];
  for (const s of specifiers) lines.push(`import ${JSON.stringify(s)};`);
  lines.push("");
  return lines.join("\n");
}

/** Path to the committed manifest file. */
export function fieldsEagerManifestPath(root: string): string {
  return join(root, MANIFEST_REL_PATH);
}

/** Render the manifest file contents in-memory (used by the in-sync check). */
export async function renderFieldsEagerManifest(root: string): Promise<string> {
  return renderManifest(await collectFieldEagerBarrels(root));
}

/** Regenerate `eager.generated.ts` if it drifted. */
export async function generateFieldsEager(opts: { root: string }): Promise<void> {
  const next = await renderFieldsEagerManifest(opts.root);
  const file = fieldsEagerManifestPath(opts.root);
  const existing = existsSync(file) ? readFileSync(file, "utf8") : "";
  if (next !== existing) writeFileSync(file, next);
}
