import { readFile } from "fs/promises";
import { join, relative } from "path";
import {
  lineAt,
  markerCallSpans,
  maskSource,
  parseStaticCallId,
  unresolvableCallIdMessage,
  walkFilesAsync,
} from "@plugins/plugin-meta/plugins/parse-utils/core";
import { createTimeSlicer } from "@plugins/packages/plugins/macrotask-yield/core";
import { buildBarrelFreeTree } from "./barrel-free-tree";

/**
 * Generates the icon manifest — every icon name the code draws, collected from
 * its `symbol("…")` / `brand("…")` / `seti("…")` literals — into
 * `plugins/ui/plugins/icons/plugins/sprites/server/internal/icon-manifest.generated.ts`,
 * next to the sprite builder, its only reader. (Not in the icons `core/`:
 * the CLI loads that barrel — through the icons checks — in the same process
 * that regenerates this file, which would freeze the stale copy.)
 *
 * The sprite server ships exactly these names, so an icon costs bytes only once
 * some code names it. The `icons/literal-icon-name` lint keeps every argument a
 * string literal (and bans aliasing or passing the functions around), which is
 * what makes a text scan complete; a non-literal that slips through anyway
 * throws here rather than silently drawing an empty box.
 *
 * Only files importing the icons core barrel are read, so an unrelated
 * `symbol(…)` elsewhere is never collected. Barrel-free (a plain file walk), so
 * it is registered as a pre-barrel manifest: the sprites server barrel reaches
 * the file at module-load. The `icons:manifest-in-sync` check fails on drift.
 */

const MANIFEST_REL_PATH =
  "plugins/ui/plugins/icons/plugins/sprites/server/internal/icon-manifest.generated.ts";

/** The barrel `symbol` / `brand` / `seti` are imported from. */
const ICONS_CORE_SPECIFIER = "@plugins/ui/plugins/icons/core";

const MARKERS = { symbol: "symbols", brand: "brands", seti: "seti" } as const;

const MANIFEST_HEADER = [
  "// DO NOT EDIT — autogenerated by `./singularity build`",
  "// (see plugins/framework/plugins/tooling/plugins/codegen/core/icon-manifest-gen.ts).",
  "//",
  '// Every `symbol("…")` / `brand("…")` / `seti("…")` literal in a file importing the icons',
  "// core barrel. The sprite server draws exactly these names.",
  "//",
  "// The `icons:manifest-in-sync` check fails on drift.",
].join("\n");

export interface IconManifest {
  symbols: string[];
  brands: string[];
  seti: string[];
}

/** Is the call at `index` a member call (`x.symbol(…)`) or a declaration (`function symbol(…)`)? */
function isNotABareCall(masked: string, index: number): boolean {
  const before = masked.slice(Math.max(0, index - 16), index);
  return /\.\s*$/.test(before) || /\bfunction\s+$/.test(before);
}

/** The icon names one file's source draws. Throws on a non-literal argument. */
export function scanIconNames(src: string, displayPath: string): IconManifest {
  const out: IconManifest = { symbols: [], brands: [], seti: [] };
  if (!src.includes(ICONS_CORE_SPECIFIER)) return out;
  const masked = maskSource(src);
  for (const [marker, list] of Object.entries(MARKERS) as [
    keyof typeof MARKERS,
    keyof IconManifest,
  ][]) {
    for (const span of markerCallSpans(masked, marker)) {
      if (isNotABareCall(masked, span.identifier)) continue;
      const id = parseStaticCallId(src, span);
      if (id.kind !== "value") {
        throw new Error(
          unresolvableCallIdMessage({
            marker,
            file: displayPath,
            line: lineAt(src, span.identifier),
            expr: id.kind === "dynamic" ? id.expr : "",
            hint:
              "The icon manifest is built from source text, so an icon name must be a " +
              "literal at the call site — a name this scanner cannot read would ship no " +
              "sprite symbol and draw an empty box.",
          }),
        );
      }
      out[list].push(id.value);
    }
  }
  return out;
}

/** Every icon name the repo draws, scanned from source now (not read from the generated file). */
export async function collectIconManifest(root: string): Promise<IconManifest> {
  const symbols = new Set<string>();
  const brands = new Set<string>();
  const seti = new Set<string>();
  // A check pass runs this on the thread its checks share: read without
  // blocking, and pause every ~10 ms of scanning.
  const slice = createTimeSlicer();
  // Every plugin's own files (a walk stops at `plugins/`, where each child is
  // its own node). Not filtered by composition: a name drawn by any plugin in
  // the repo ships, which costs a symbol, never a missing glyph.
  const tree = await buildBarrelFreeTree(root);
  for (const node of tree.byDir.values()) {
    for (const file of await walkFilesAsync(node.dir)) {
      if (file.endsWith(".generated.ts")) continue;
      const src = await readFile(file, "utf8");
      if (!src.includes(ICONS_CORE_SPECIFIER)) continue;
      await slice();
      const found = scanIconNames(src, relative(root, file));
      for (const n of found.symbols) symbols.add(n);
      for (const n of found.brands) brands.add(n);
      for (const n of found.seti) seti.add(n);
    }
  }
  return {
    symbols: [...symbols].sort(),
    brands: [...brands].sort(),
    seti: [...seti].sort(),
  };
}

function renderList(name: string, values: readonly string[]): string {
  if (values.length === 0) return `  ${name}: [],`;
  return [
    `  ${name}: [`,
    ...values.map((v) => `    ${JSON.stringify(v)},`),
    "  ],",
  ].join("\n");
}

function renderIconManifestContent(manifest: IconManifest): string {
  return [
    MANIFEST_HEADER,
    "",
    "export const ICON_MANIFEST: {",
    "  readonly symbols: readonly string[];",
    "  readonly brands: readonly string[];",
    "  readonly seti: readonly string[];",
    "} = {",
    renderList("symbols", manifest.symbols),
    renderList("brands", manifest.brands),
    renderList("seti", manifest.seti),
    "};",
    "",
  ].join("\n");
}

export function iconManifestPath(root: string): string {
  return join(root, MANIFEST_REL_PATH);
}

export async function renderIconManifest(root: string): Promise<string> {
  return renderIconManifestContent(await collectIconManifest(root));
}
