import { existsSync, readdirSync, readFileSync } from "fs";
import { dirname, join, resolve } from "path";
import { type PluginTree } from "@plugins/plugin-meta/plugins/plugin-tree/core";
import {
  findImports,
  findMarkerCalls,
  maskSource,
} from "@plugins/plugin-meta/plugins/parse-utils/core";
import { buildBarrelFreeTree } from "./barrel-free-tree";
import type { CollectedDirDef } from "@plugins/framework/plugins/tooling/plugins/collected-dir/core";
import { asPluginId } from "@plugins/framework/plugins/plugin-id/core";
import { assertCompositionName } from "@plugins/plugin-meta/plugins/composition/core";
import { computeDisabledIds } from "./disabled-ids";
import { writeGenerated } from "./write-generated";

export interface DiscoveredCollectedDir extends CollectedDirDef {
  ownerDir: string;
}

const HEADER = [
  "// DO NOT EDIT — autogenerated by `./singularity build`",
  "// (see plugins/framework/plugins/tooling/plugins/codegen/core/plugin-registry-gen.ts).",
  "//",
  "// Adding/removing a plugin: create or delete the plugin's `<runtime>/index.ts`",
  "// and rebuild — this file regenerates from the filesystem. The",
  "// `plugins-registry-in-sync` check fails on drift.",
].join("\n");

// ── Core barrel discovery ──────────────────────────────────────────

function findCoreBarrels(pluginsRoot: string): string[] {
  const out: string[] = [];
  function walk(dir: string, depth: number): void {
    if (depth > 10) return;
    const barrel = join(dir, "core", "index.ts");
    if (existsSync(barrel)) out.push(barrel);
    let entries;
    try {
      entries = readdirSync(dir, { withFileTypes: true });
    } catch (err) {
      const code = (err as NodeJS.ErrnoException).code;
      if (code !== "ENOENT" && code !== "EACCES" && code !== "ENOTDIR")
        throw err;
      return;
    }
    for (const e of entries) {
      if (!e.isDirectory()) continue;
      if (dir === pluginsRoot) {
        walk(join(dir, e.name), depth + 1);
      } else if (e.name === "plugins") {
        let children;
        try {
          children = readdirSync(join(dir, e.name), { withFileTypes: true });
        } catch (err) {
          const code = (err as NodeJS.ErrnoException).code;
          if (code !== "ENOENT" && code !== "EACCES" && code !== "ENOTDIR")
            throw err;
          continue;
        }
        for (const c of children) {
          if (c.isDirectory()) walk(join(dir, e.name, c.name), depth + 1);
        }
      }
    }
  }
  walk(pluginsRoot, 0);
  return out;
}

// First positional string argument of a `defineCollectedDir("<dir>")` call.
const FIRST_STRING_ARG_RE = /^\s*["']([^"']+)["']/;

// Synchronous: this does only blocking `readdirSync`/`readFileSync`/`existsSync`
// I/O. Keeping it sync (rather than async-by-signature) lets callers — notably
// the structure facet's `extract`, which the facet pipeline invokes without
// `await` — consume it without a top-level await. A top-level await here would
// suspend the facet module mid-evaluation inside the facets ⇄ codegen import
// cycle, surfacing as a TDZ crash ("Cannot access 'default' before initialization").
export function discoverCollectedDirs(root: string): DiscoveredCollectedDir[] {
  const pluginsRoot = resolve(root, "plugins");
  const coreBarrels = findCoreBarrels(pluginsRoot);
  const out: DiscoveredCollectedDir[] = [];
  for (const barrelPath of coreBarrels) {
    const coreDir = dirname(barrelPath);
    let coreFiles;
    try {
      coreFiles = readdirSync(coreDir, { withFileTypes: true });
    } catch (err) {
      const code = (err as NodeJS.ErrnoException).code;
      if (code !== "ENOENT" && code !== "EACCES" && code !== "ENOTDIR")
        throw err;
      continue;
    }
    for (const entry of coreFiles) {
      if (!entry.isFile() || !entry.name.endsWith(".ts")) continue;
      const filePath = join(coreDir, entry.name);
      const src = readFileSync(filePath, "utf8");
      // Fast-path: skip files that can't contain the marker. Correctness still
      // comes from `findMarkerCalls`, which ignores comment/string/regex matches.
      if (!src.includes("defineCollectedDir")) continue;
      for (const call of findMarkerCalls(src, "defineCollectedDir")) {
        const arg = FIRST_STRING_ARG_RE.exec(call.argsText);
        if (!arg) continue;
        out.push({
          dir: arg[1]!,
          _brand: "CollectedDirDef",
          ownerDir: dirname(coreDir),
        });
      }
    }
  }
  return out;
}

// ── Standard plugin folders ────────────────────────────────────────

// The set of directory names considered "standard" inside a plugin. Two parts:
//   1. The collected-dir / runtime names (web, server, central, facet, check,
//      lint, …) discovered generically via `defineCollectedDir`. This part
//      AUTO-GROWS — registering a new runtime or collected-dir type adds its
//      folder name here with zero edits, which is the friction being removed.
//   2. A fixed set of stable structural conventions (core, shared, plugins, bin,
//      scripts, e2e) that are not runtime/collected-dir types and never grow when
//      a new such type is added — so listing them here is not the friction.
//      `e2e` holds a plugin's Playwright scripts; it is deliberately NOT a
//      collected dir (there is nothing to register — a collected dir would
//      generate an empty registry and pull in collected-dir-tsconfig-coverage).
export function standardPluginDirs(root: string): Set<string> {
  const collected = discoverCollectedDirs(root).map((d) => d.dir);
  return new Set([
    ...collected,
    "core",
    "shared",
    "plugins",
    "bin",
    "scripts",
    "e2e",
  ]);
}

// ── Entry collection ───────────────────────────────────────────────

export interface CollectedRawEntry {
  pluginPath: string;
  importPath: string;
  id: string;
}

function hasDefaultExport(file: string): boolean {
  // Mask comments/regex/strings so a commented-out or string-embedded `export
  // default` can't make an entryless barrel look like an entry. These are pure
  // code-construct detectors — the string interior is never read back.
  const src = maskSource(readFileSync(file, "utf8"));
  return (
    /(^|\n)\s*export\s+default\b/.test(src) ||
    /(^|\n)\s*export\s*\{[^}]*\bdefault\b[^}]*\}/.test(src)
  );
}

// ── Registry-generation context ────────────────────────────────────
//
// The plugin tree and the disabled-id closure are pure functions of the
// filesystem — IDENTICAL for every collected dir. Build them ONCE per generation
// pass and thread the context through `renderCollectedDirRegistry`. This is what
// keeps registry codegen O(tree) instead of O(tree × collectedDirs): there are
// ~10 collected dirs (web, server, central, check, lint, facet, …), so a per-def
// rebuild meant ~10 full 840-plugin tree walks (~12s, the dominant codegen cost).
// Taking a prebuilt context — rather than a `root` the renderer rebuilds from —
// makes that redundant build structurally impossible: the renderer literally
// cannot trigger a tree walk.
export interface RegistryGenContext {
  root: string;
  tree: PluginTree;
  // Closed disabled-id set computed from the SAME barrel-free tree the entries
  // come from. Applied unconditionally by the renderer so the
  // `plugins-registry-in-sync` check (which never passes `bundle`) re-derives
  // the identical filtered output from the committed `package.json` flags.
  disabled: Set<string>;
  // Per-`<dir>` filesystem scan (the collected entry list plus the raw
  // import-derived dependency graph), memoized for this context's lifetime.
  //
  // Why it is safe to cache HERE rather than anywhere else: a `RegistryGenContext`
  // is a SNAPSHOT of the tree — `tree` and `disabled` are already source-derived
  // facts frozen at `buildRegistryGenContext` time, and a caller that needs a
  // post-write view of the filesystem must build a fresh ctx to see it. A
  // `<dir>` scan is a pure function of exactly the same inputs (`ctx.tree`,
  // `ctx.root`, `dir`) and of nothing else — in particular NOT of the optional
  // `bundle`, which only filters an already-scanned entry list — so hanging it
  // off the ctx gives it precisely the lifetime it is valid for. Putting it in a
  // module-level cache would instead outlive the snapshot and start answering
  // with a stale filesystem.
  //
  // What it buys: the scan reads every `.ts`/`.tsx` file under every plugin's
  // `<dir>/` tree, which is the expensive half of registry codegen, and the
  // callers that already share ONE ctx re-render the same `<dir>` more than
  // once. `regen-pipeline.ts` shares a ctx between the registry and eager-tier
  // generators (the eager tier re-scanned `web` a second time); `compose-serve.ts`
  // shares a ctx across every activated composition (N compositions × 3 runtime
  // dirs collapse to 3 scans); and the composition-equivalence check renders each
  // collected dir twice, once unfiltered and once bundle-filtered. Behaviour is
  // unchanged — the cache holds the raw pre-filter scan, so the disabled filter,
  // the bundle filter and the dep pruning still run per call.
  dirScans: Map<string, DirEntryScan>;
}

/** The bundle-independent half of `collectEntriesWithDeps`: what one `<dir>`
 *  scan of the tree found, before any disabled/bundle filtering. */
interface DirEntryScan {
  allEntries: CollectedRawEntry[];
  rawDeps: Map<string, string[]>;
}

export async function buildRegistryGenContext(
  root: string,
): Promise<RegistryGenContext> {
  const tree = await buildBarrelFreeTree(root);
  return {
    root,
    tree,
    disabled: computeDisabledIds(tree),
    dirScans: new Map(),
  };
}

/**
 * The `<dir>` scan for this context, computed on first ask and reused after.
 * See `RegistryGenContext.dirScans` for why a ctx is the right lifetime.
 */
function scanDir(ctx: RegistryGenContext, dir: string): DirEntryScan {
  const cached = ctx.dirScans.get(dir);
  if (cached !== undefined) return cached;
  const allEntries = collectEntries(ctx.tree, dir);
  const scan: DirEntryScan = {
    allEntries,
    rawDeps: buildDepsForDir(ctx.root, allEntries, dir),
  };
  ctx.dirScans.set(dir, scan);
  return scan;
}

/**
 * A collected-dir folder name as a JavaScript identifier: `data-dirs` →
 * `dataDirs`, so the emitted registry const is `dataDirsEntries`.
 *
 * Interpolating the folder name raw was fine only because every collected dir
 * happened to be one lowercase word (`check`, `facet`, `fixtures`). The first
 * hyphenated one emitted `export const data-dirsEntries`, which is not a legal
 * identifier — so the generated file failed to PARSE, and the failure surfaced
 * far from here, as a facet-extraction `AggregateError` during doc generation.
 * Deriving the identifier is what makes a hyphenated collected dir
 * representable at all, rather than a trap the next one falls into too.
 */
function identifierForDir(dir: string): string {
  return dir.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

function collectEntries(tree: PluginTree, dir: string): CollectedRawEntry[] {
  const entries: CollectedRawEntry[] = [];
  for (const node of tree.byDir.values()) {
    const indexFile = join(node.dir, dir, "index.ts");
    if (!existsSync(indexFile)) continue;
    if (!hasDefaultExport(indexFile)) continue;
    entries.push({
      pluginPath: node.path,
      importPath: `@plugins/${node.path}/${dir}`,
      id: node.id,
    });
  }
  entries.sort((a, b) => a.importPath.localeCompare(b.importPath));
  return entries;
}

// ── Dependency graph ───────────────────────────────────────────────

function walkTsFiles(dir: string, out: string[]): void {
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch (err) {
    const code = (err as NodeJS.ErrnoException).code;
    if (code !== "ENOENT" && code !== "EACCES" && code !== "ENOTDIR") throw err;
    return;
  }
  for (const e of entries) {
    const p = join(dir, e.name);
    if (e.isDirectory()) {
      if (e.name === "node_modules" || e.name === "plugins") continue;
      walkTsFiles(p, out);
    } else if (e.isFile() && /\.tsx?$/.test(e.name)) {
      out.push(p);
    }
  }
}

// Every import specifier found in a plugin's `<dir>/` tree. `findImports` masks
// comments/regex/strings and reads each specifier back by offset, so an import
// written inside a string/comment can't register a phantom dependency edge.
// Covers both `import … from` and `export … from`.
function collectImportSpecifiers(pluginDir: string, dir: string): Set<string> {
  const subDir = join(pluginDir, dir);
  const files: string[] = [];
  walkTsFiles(subDir, files);
  const specifiers = new Set<string>();
  for (const f of files) {
    for (const imp of findImports(readFileSync(f, "utf8"))) {
      specifiers.add(imp.specifier);
    }
  }
  return specifiers;
}

function collectImportPrefixes(
  pluginDir: string,
  dir: string,
  entryPrefixes: Set<string>,
): Set<string> {
  const prefixes = new Set<string>();
  for (const mod of collectImportSpecifiers(pluginDir, dir)) {
    if (!mod.startsWith("@plugins/")) continue;
    const lastSlash = mod.lastIndexOf("/");
    if (lastSlash > 0) {
      const prefix = mod.slice(0, lastSlash);
      if (entryPrefixes.has(prefix)) prefixes.add(prefix);
    }
  }
  return prefixes;
}

/** True for npm-style bare specifiers (neither relative/absolute nor `@plugins/*`). */
function isBareNpmSpecifier(mod: string): boolean {
  return (
    !mod.startsWith(".") &&
    !mod.startsWith("/") &&
    !mod.startsWith("@plugins/") &&
    !mod.startsWith("@composition-web-registry")
  );
}

/**
 * Bare npm specifiers (per subpath: `react-dom/client` ≠ `react-dom`) imported
 * by each collected plugin's `<dir>/` tree — the source-level vendor-set input
 * for the web-artifacts engine (and its Phase-2 `map-in-sync` cross-check).
 * Node builtins (`node:*`) are included verbatim; consumers filter. Does NOT
 * change the emitted registry shape.
 */
export function collectBareSpecifiers(
  ctx: RegistryGenContext,
  dir: string,
): Map<string, string[]> {
  const out = new Map<string, string[]>();
  for (const e of collectEntries(ctx.tree, dir)) {
    const pluginDir = join(resolve(ctx.root, "plugins"), e.pluginPath);
    const bare = [...collectImportSpecifiers(pluginDir, dir)]
      .filter(isBareNpmSpecifier)
      .sort();
    if (bare.length > 0) out.set(e.pluginPath, bare);
  }
  return out;
}

function buildDepsForDir(
  root: string,
  entries: CollectedRawEntry[],
  dir: string,
): Map<string, string[]> {
  const prefixToPluginPath = new Map<string, string>();
  const entryPrefixes = new Set<string>();
  for (const e of entries) {
    const prefix = e.importPath.slice(0, e.importPath.lastIndexOf("/"));
    prefixToPluginPath.set(prefix, e.pluginPath);
    entryPrefixes.add(prefix);
  }

  const pluginsRoot = resolve(root, "plugins");
  const result = new Map<string, string[]>();

  for (const e of entries) {
    const pluginDir = join(pluginsRoot, e.pluginPath);
    const depPrefixes = collectImportPrefixes(pluginDir, dir, entryPrefixes);
    const deps: string[] = [];
    for (const prefix of depPrefixes) {
      const depPath = prefixToPluginPath.get(prefix);
      if (depPath && depPath !== e.pluginPath) deps.push(depPath);
    }
    if (deps.length > 0) {
      deps.sort();
      result.set(e.pluginPath, deps);
    }
  }
  return result;
}

// ── Filtered entries + pruned deps ─────────────────────────────────
//
// The disabled-closure filter is UNCONDITIONAL (driven by the committed
// `singularity.disabled` seeds), never the optional `bundle` — so the
// `plugins-registry-in-sync` check, which re-renders without `bundle`, sees the
// identical filtered output. Each surviving entry's `dependsOn` is pruned to the
// surviving `pluginPath`s: the disabled filter can drop a dependency
// unconditionally (not only under `bundle`), and a dangling dep on a non-emitted
// plugin would break the loader's topo-sort. Shared by `renderCollectedDirRegistry`
// (so its output is byte-identical) AND the eager-tier generator, which needs the
// exact same filtered web entry set + pruned `dependsOn` graph.
export function collectEntriesWithDeps(
  ctx: RegistryGenContext,
  dir: string,
  // See `renderCollectedDirRegistry`: restrict to a composition's bundle when set.
  bundle?: Set<string>,
): { entries: CollectedRawEntry[]; deps: Map<string, string[]> } {
  const { disabled } = ctx;
  const { allEntries, rawDeps } = scanDir(ctx, dir);
  const entries = (
    bundle ? allEntries.filter((e) => bundle.has(e.id)) : allEntries
  ).filter((e) => !disabled.has(asPluginId(e.id)));
  const survivingPaths = new Set(entries.map((e) => e.pluginPath));
  const deps = new Map<string, string[]>();
  for (const e of entries) {
    const entryDeps = (rawDeps.get(e.pluginPath) ?? []).filter((d) =>
      survivingPaths.has(d),
    );
    if (entryDeps.length > 0) deps.set(e.pluginPath, entryDeps);
  }
  return { entries, deps };
}

// ── Renderer ───────────────────────────────────────────────────────

export function renderCollectedDirRegistry(opts: {
  ctx: RegistryGenContext;
  def: DiscoveredCollectedDir;
  // When provided, restrict the registry to the plugins in this bundle (the
  // dot-form PluginId set of a composition's hard closure). Each surviving
  // entry's `dependsOn` is also pruned to surviving `pluginPath`s — defensive,
  // since a hard closure's deps already survive. When undefined, the output is
  // byte-identical to the unfiltered registry, so the `plugins-registry-in-sync`
  // check (which never passes a bundle) is unaffected.
  bundle?: Set<string>;
}): string {
  const { ctx, def, bundle } = opts;
  const { entries, deps } = collectEntriesWithDeps(ctx, def.dir, bundle);
  const exportName = `${identifierForDir(def.dir)}Entries`;

  const lines: string[] = [];
  lines.push(HEADER);
  lines.push("");
  lines.push("export interface CollectedEntry {");
  lines.push("  pluginPath: string;");
  lines.push("  id: string;");
  lines.push("  loader: () => Promise<{ default: unknown }>;");
  lines.push("  dependsOn: string[];");
  lines.push("}");
  lines.push("");
  lines.push(`export const ${exportName}: CollectedEntry[] = [`);
  for (const e of entries) {
    const entryDeps = deps.get(e.pluginPath) ?? [];
    const depsLiteral =
      entryDeps.length > 0
        ? `[${entryDeps.map((d) => JSON.stringify(d)).join(", ")}]`
        : "[]";
    lines.push(
      `  { pluginPath: ${JSON.stringify(e.pluginPath)}, id: ${JSON.stringify(e.id)}, loader: () => import(${JSON.stringify(e.importPath)}), dependsOn: ${depsLiteral} },`,
    );
  }
  lines.push("];");
  lines.push("");
  return lines.join("\n");
}

// ── Public API ─────────────────────────────────────────────────────

export function collectedDirRegistryPath(def: DiscoveredCollectedDir): string {
  return join(def.ownerDir, "core", `${def.dir}.generated.ts`);
}

export async function generatePluginRegistry(opts: {
  root: string;
  // Optional prebuilt context so the pipeline can share ONE tree walk between the
  // registry and eager-tier generators (both are pure functions of the same
  // barrel-free tree). Built here when absent so standalone callers still work.
  ctx?: RegistryGenContext;
}): Promise<void> {
  const ctx = opts.ctx ?? (await buildRegistryGenContext(opts.root));
  const defs = discoverCollectedDirs(opts.root);
  for (const def of defs) {
    await writeGenerated({
      file: collectedDirRegistryPath(def),
      content: renderCollectedDirRegistry({ ctx, def }),
    });
  }
}

// ── Composition (filtered) registries ──────────────────────────────
//
// A composition build emits gitignored siblings of the committed full
// registries — same export name, restricted to the composition's bundle. The
// committed `<dir>.generated.ts` files are never touched, so the build stays
// byte-identical and `plugins-registry-in-sync` + `git status` stay clean.
//
// There is exactly ONE spelling: PER-NAME `<dir>.composition.<name>.generated.ts`.
// Every producer (auto-serve AND release) keys its registries by composition id,
// so no checkout-global "this checkout is currently composition X" state exists
// and a release can never reconfigure another namespace's backend. The pre-S1
// singleton `<dir>.composition.generated.ts` spelling is gone entirely (S5): no
// path writes it, selects it, or reaps it, so a stray file of that name is inert.

// The registries that need a composition-filtered (closure-restricted) sibling.
// `web`/`server` are the runtime registries the app actually loads at the import
// seam. `prewarm` is release-build-time-only — consumed by the asset-mirror
// release runner to bake each closure mirror's files into the bundle, never
// loaded by the served app — but it needs the same closure filtering so a
// release only pre-warms mirrors in the composition's closure. Central is
// dropped per the F1 requirements; check/lint are build-time-only and never
// loaded into a served app.
//
// `prewarm` is in this ONE set (rather than a released-only sibling set)
// because release is its only consumer and release is now per-name too — which
// also means `listNamedCompositionRegistries` lists prewarm files, so
// compose-serve's deactivation sweep reclaims them like any other.
const COMPOSITION_RUNTIME_DIRS = new Set(["web", "server", "prewarm"]);

export function collectedDirNamedCompositionRegistryPath(
  def: DiscoveredCollectedDir,
  name: string,
): string {
  assertCompositionName(name);
  return join(
    def.ownerDir,
    "core",
    `${def.dir}.composition.${name}.generated.ts`,
  );
}

export async function generateCompositionRegistry(opts: {
  root: string;
  bundle: Set<string>;
  /**
   * The composition id these registries belong to. REQUIRED: every filtered
   * registry is keyed by name, so no producer can write a checkout-global one.
   */
  name: string;
  // Optional prebuilt context so one build shares ONE tree walk across several
  // compositions' registries. Built here when absent so standalone callers work.
  ctx?: RegistryGenContext;
}): Promise<void> {
  assertCompositionName(opts.name);
  const ctx = opts.ctx ?? (await buildRegistryGenContext(opts.root));
  const defs = discoverCollectedDirs(opts.root);
  for (const def of defs) {
    if (!COMPOSITION_RUNTIME_DIRS.has(def.dir)) continue;
    await writeGenerated({
      file: collectedDirNamedCompositionRegistryPath(def, opts.name),
      content: renderCollectedDirRegistry({ ctx, def, bundle: opts.bundle }),
    });
  }
}

/** Parse `<dir>.composition.<name>.generated.ts` into its parts, else null. */
export function parseNamedCompositionRegistryFileName(
  fileName: string,
): { dir: string; name: string } | null {
  const m =
    /^([a-z]+)\.composition\.([a-z0-9][a-z0-9-]{0,62})\.generated\.ts$/.exec(
      fileName,
    );
  if (m === null) return null;
  return { dir: m[1]!, name: m[2]! };
}

/**
 * Every per-name composition registry currently on disk — the auto-serve
 * stage's sweep input (delete the entries whose name is no longer activated).
 */
export function listNamedCompositionRegistries(
  root: string,
): Array<{ dir: string; name: string; file: string }> {
  const out: Array<{ dir: string; name: string; file: string }> = [];
  for (const def of discoverCollectedDirs(root)) {
    if (!COMPOSITION_RUNTIME_DIRS.has(def.dir)) continue;
    const coreDir = join(def.ownerDir, "core");
    let entries;
    try {
      entries = readdirSync(coreDir, { withFileTypes: true });
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
      continue;
    }
    for (const entry of entries) {
      if (!entry.isFile()) continue;
      const parsed = parseNamedCompositionRegistryFileName(entry.name);
      if (parsed === null || parsed.dir !== def.dir) continue;
      out.push({ ...parsed, file: join(coreDir, entry.name) });
    }
  }
  return out;
}
