import { readdirSync, readFileSync } from "fs";
import { join, resolve } from "path";
import { type PluginTree } from "@plugins/plugin-meta/plugins/plugin-tree/core";
import {
  findImports,
  findMarkerCalls,
  maskSource,
  type FsSnapshot,
} from "@plugins/plugin-meta/plugins/parse-utils/core";
import {
  loadRepoFiles,
  type RepoFiles,
} from "@plugins/framework/plugins/tooling/core";
import { createSemaphore } from "@plugins/packages/plugins/semaphore/core";
import { buildBarrelFreeTree } from "./barrel-free-tree";
import type { CollectedDirDef } from "@plugins/framework/plugins/tooling/plugins/collected-dir/core";
import {
  PLUGIN_FOLDERS,
  type PluginFolder,
  type PluginId,
} from "@plugins/framework/plugins/plugin-id/core";
import { assertCompositionName } from "@plugins/plugin-meta/plugins/composition/core";
import { MAIN_COMPOSITION_ID } from "@plugins/infra/plugins/namespace/core";
import {
  classifyEdges,
  type EdgeGraph,
} from "@plugins/plugin-meta/plugins/closure/core";
import { resolveMainComposition } from "./main-bundle";
import { readListed, timeSlicer } from "./scan-pacing";
import { writeGenerated } from "./write-generated";

export interface DiscoveredCollectedDir extends CollectedDirDef {
  ownerDir: string;
}

const HEADER = [
  "// DO NOT EDIT — autogenerated by `./singularity build`",
  "// (see plugins/framework/plugins/tooling/plugins/codegen/core/plugin-registry-gen.ts).",
  "//",
  "// Adding/removing a plugin: create or delete the plugin's `<runtime>/index.ts`",
  "// and rebuild — this file regenerates from the filesystem. The",
  "// `plugins-registry-in-sync` check fails on drift.",
].join("\n");

// How many plugins' files a scan holds in flight at once. The file set's own
// reader bounds the opens; this bounds how much text is resident.
const PLUGIN_SCAN_WIDTH = 16;

// ── Collected-dir discovery ────────────────────────────────────────
//
// A collected dir is declared by a `defineCollectedDir("<dir>")` call in a file
// directly under a plugin's `core/` — a `core/` that has a barrel. The
// candidates come from the repo's FILE SET (git's tracked + untracked-not-
// ignored, the universe the check cache key covers), never from a directory
// walk. The walk this replaced made ~2,600 blocking readdir/exists calls per
// call, four checks called it in one pass, and under a check pass's background
// priority that held the shared check thread for 16–40 s. It also saw
// gitignored directories, which no verdict may depend on.
//
// One pure core, three fronts that differ only in where the file list and the
// text come from:
//   - `discoverCollectedDirsIn(repo)` — async, for checks and for codegen that
//     already holds a file set (a `RegistryGenContext`).
//   - `discoverCollectedDirs(root)` — sync, for callers that cannot await: one
//     `git ls-files`, then reads of the candidates.
//   - `standardPluginDirsFromSnapshot(root, fs)` — the structure facet, over the
//     in-memory snapshot its own tree build already read. No disk at all.

// A file directly under a plugin's `core/`, at a plugin position: a top-level
// plugin directory, or a sub-plugin nested under `plugins/`, at most ten names
// deep (where the plugin-tree walk stops). Group 1 is the plugin's path under
// `plugins/`.
const CORE_FILE_RE =
  /^plugins\/([^/]+(?:\/plugins\/[^/]+){0,9})\/core\/[^/]+\.ts$/;

// A test file never declares a collected dir. Without this, a unit test that
// calls `defineCollectedDir("x")` for real would register a phantom runtime
// folder — a registry, a tsconfig-coverage demand, a "standard" folder name.
// (It also keeps every front agreeing: the facet's snapshot holds no tests.)
const TEST_FILE_RE = /\.test\.ts$/;

interface CollectedDirCandidate {
  /** Repo-relative path of the `core/*.ts` file. */
  rel: string;
  /** The owning plugin's path under `plugins/`. */
  pluginPath: string;
}

/** The `core/*.ts` files among `files` that can declare a collected dir. */
function collectedDirCandidates(
  files: Iterable<string>,
  has: (rel: string) => boolean,
): CollectedDirCandidate[] {
  const out: CollectedDirCandidate[] = [];
  for (const rel of files) {
    const m = CORE_FILE_RE.exec(rel);
    if (!m || TEST_FILE_RE.test(rel)) continue;
    const pluginPath = m[1]!;
    if (has(`plugins/${pluginPath}/core/index.ts`))
      out.push({ rel, pluginPath });
  }
  return out;
}

// First positional string argument of a `defineCollectedDir("<dir>")` call.
const FIRST_STRING_ARG_RE = /^\s*["']([^"']+)["']/;

const PLUGIN_FOLDER_SET: ReadonlySet<string> = new Set(PLUGIN_FOLDERS);
const isPluginFolder = (name: string): name is PluginFolder =>
  PLUGIN_FOLDER_SET.has(name);

/**
 * The collected dirs the candidates' `text` declares. Pure. A declared name
 * that is not a `PluginFolder` throws naming the file: a collected dir is a
 * plugin folder, and a plugin folder needs its row in the boundary table. The
 * typed marker already makes that a tsc error; this covers the untyped copy.
 */
function collectedDirsFrom(
  root: string,
  sources: Iterable<CollectedDirCandidate & { text: string }>,
): DiscoveredCollectedDir[] {
  const pluginsRoot = resolve(root, "plugins");
  const out: DiscoveredCollectedDir[] = [];
  for (const { rel, pluginPath, text } of sources) {
    // Fast-path: skip files that can't contain the marker. Correctness still
    // comes from `findMarkerCalls`, which ignores comment/string/regex matches.
    if (!text.includes("defineCollectedDir")) continue;
    for (const call of findMarkerCalls(text, "defineCollectedDir")) {
      const arg = FIRST_STRING_ARG_RE.exec(call.argsText);
      if (!arg) continue;
      const dir = arg[1]!;
      if (!isPluginFolder(dir)) {
        throw new Error(
          `${rel} declares collected dir "${dir}", which is not a plugin folder. ` +
            `Declare it in LEAF_FOLDERS (plugin-id/core) and give it a row in the ` +
            `boundary table (boundaries/core/boundary-config.ts). Known folders: ` +
            `${PLUGIN_FOLDERS.join(", ")}.`,
        );
      }
      out.push({
        dir,
        _brand: "CollectedDirDef",
        ownerDir: join(pluginsRoot, pluginPath),
      });
    }
  }
  return out;
}

/**
 * Every collected dir the tree declares, from the run's file set: no directory
 * walk, and every read asynchronous (the set's reader bounds the opens).
 */
export async function discoverCollectedDirsIn(
  repo: RepoFiles,
): Promise<DiscoveredCollectedDir[]> {
  const candidates = collectedDirCandidates(repo.under("plugins"), (rel) =>
    repo.has(rel),
  );
  const sources = await Promise.all(
    candidates.map(async (c) => ({
      ...c,
      text: await readListed(repo, c.rel),
    })),
  );
  return collectedDirsFrom(repo.root, sources);
}

// Wedge-breaker for a metadata-only git read, not a latency budget — the bound
// `listRepoFiles` uses, for the same reason.
const GIT_TIMEOUT_MS = 60_000;

function lsFilesSync(root: string, args: string[]): string[] {
  const result = Bun.spawnSync(["git", "ls-files", "-z", ...args], {
    cwd: root,
    stdout: "pipe",
    stderr: "pipe",
    timeout: GIT_TIMEOUT_MS,
  });
  if (result.exitCode !== 0) {
    // Loud, never `[]`: an empty listing would read as "no collected dirs".
    throw new Error(
      `git ls-files ${args.join(" ")} failed in ${root} (exit ${result.exitCode}): ${result.stderr.toString().trim()}`,
    );
  }
  return result.stdout
    .toString()
    .split("\0")
    .filter((p) => p.length > 0);
}

/**
 * The files under `plugins/`, repo-relative and sorted — `listRepoFiles`'
 * universe (tracked + untracked-not-ignored, minus index entries whose file is
 * gone), listed synchronously for the callers that cannot await.
 */
function listPluginFilesSync(root: string): string[] {
  const present = lsFilesSync(root, [
    "--cached",
    "--others",
    "--exclude-standard",
    "--",
    "plugins",
  ]);
  const gone = new Set(lsFilesSync(root, ["--deleted", "--", "plugins"]));
  return [...new Set(present.filter((p) => !gone.has(p)))].sort();
}

/**
 * `discoverCollectedDirsIn`, for callers that cannot await
 * (`listNamedCompositionRegistries`, whose callers include a synchronous
 * program-key read). Same file set, listed with ONE blocking `git ls-files`
 * instead of a directory walk, then a read of each candidate. Nothing on a
 * check pass's shared thread should call it: checks hold a file set already.
 */
export function discoverCollectedDirs(root: string): DiscoveredCollectedDir[] {
  const files = listPluginFilesSync(root);
  const listed = new Set(files);
  const candidates = collectedDirCandidates(files, (rel) => listed.has(rel));
  return collectedDirsFrom(
    root,
    candidates.map((c) => ({
      ...c,
      text: readFileSync(join(root, c.rel), "utf8"),
    })),
  );
}

// ── Standard plugin folders ────────────────────────────────────────

// The set of directory names considered "standard" inside a plugin: the
// plugin-folder vocabulary (`PLUGIN_FOLDERS`, owned by plugin-id/core) plus
// `plugins/`, which holds child plugins rather than code. Discovered collected
// dirs do not widen it — discovery throws on a name outside the vocabulary —
// so the fronts below still run discovery: an undeclared collected dir fails
// every reader of this set, not only codegen.
const STANDARD_DIRS: ReadonlySet<string> = new Set([
  ...PLUGIN_FOLDERS,
  "plugins",
]);

/** The standard plugin folder names, from the run's file set. */
export async function standardPluginDirsIn(
  repo: RepoFiles,
): Promise<Set<string>> {
  await discoverCollectedDirsIn(repo); // throws on an undeclared name
  return new Set(STANDARD_DIRS);
}

/** The standard plugin folder names, for callers that cannot await. */
export function standardPluginDirs(root: string): Set<string> {
  discoverCollectedDirs(root); // throws on an undeclared name
  return new Set(STANDARD_DIRS);
}

// One answer per snapshot: a snapshot is one tree build's frozen read of the
// source, so the answer lives exactly as long as the snapshot does.
const snapshotStandardDirs = new WeakMap<FsSnapshot, Set<string>>();

/**
 * The standard plugin folder names, answered from a plugin-tree build's
 * in-memory FS snapshot — for the structure facet, whose `extract` is
 * synchronous and runs inside that build. The snapshot already holds every
 * plugin's non-test `core/*.ts`, so this touches no disk. `root` is the repo
 * root whose `plugins/` the snapshot covers.
 */
export function standardPluginDirsFromSnapshot(
  root: string,
  fs: FsSnapshot,
): Set<string> {
  const cached = snapshotStandardDirs.get(fs);
  if (cached !== undefined) return cached;
  const prefix = `${resolve(root)}/`;
  const texts = new Map<string, string>();
  for (const [abs, text] of fs.files) {
    if (abs.startsWith(prefix)) texts.set(abs.slice(prefix.length), text);
  }
  const candidates = collectedDirCandidates(texts.keys(), (rel) =>
    texts.has(rel),
  );
  // Throws on an undeclared name.
  collectedDirsFrom(
    root,
    candidates.map((c) => ({ ...c, text: texts.get(c.rel)! })),
  );
  const std = new Set(STANDARD_DIRS);
  snapshotStandardDirs.set(fs, std);
  return std;
}

// ── Entry collection ───────────────────────────────────────────────

export interface CollectedRawEntry {
  pluginPath: string;
  importPath: string;
  id: string;
}

function hasDefaultExport(text: string): boolean {
  // Mask comments/regex/strings so a commented-out or string-embedded `export
  // default` can't make an entryless barrel look like an entry. These are pure
  // code-construct detectors — the string interior is never read back.
  const src = maskSource(text);
  return (
    /(^|\n)\s*export\s+default\b/.test(src) ||
    /(^|\n)\s*export\s*\{[^}]*\bdefault\b[^}]*\}/.test(src)
  );
}

// ── Registry-generation context ────────────────────────────────────
//
// The plugin tree, its edge graph and the app's own composition are pure
// functions of committed source — IDENTICAL for every collected dir. Build them
// ONCE per generation pass and thread the context through
// `renderCollectedDirRegistry`. This is what keeps registry codegen O(tree)
// instead of O(tree × collectedDirs): there are ~10 collected dirs (web, server,
// central, check, lint, facet, …), so a per-def rebuild meant ~10 full
// 840-plugin tree walks (~12s, the dominant codegen cost). Taking a prebuilt
// context — rather than a `root` the renderer rebuilds from — makes that
// redundant build structurally impossible: the renderer literally cannot trigger
// a tree walk.
export interface RegistryGenContext {
  root: string;
  tree: PluginTree;
  // The cross-plugin edge graph of exactly this `tree`, classified once. Held
  // here so the composition resolution below, and the checks that take a ctx,
  // never re-run `classifyEdges` over the same tree.
  graph: EdgeGraph;
  // What the app ships: the `singularity` composition's resolved closure. There
  // is no unfiltered registry — every render says which composition it is for,
  // and this is the answer for the committed `<dir>.generated.ts` files.
  mainBundle: Set<PluginId>;
  // The repo's file set every scan below enumerates and reads — a check's own
  // run set when a check built this ctx, else listed from git on first use.
  // Lazy because half the callers (composition-closure, config_v2's
  // registrations-paired) read only the tree and never scan; memoized so one
  // ctx lists at most once.
  repo(): Promise<RepoFiles>;
  // Per-`<dir>` scan (the collected entry list plus the raw import-derived
  // dependency graph), memoized for this context's lifetime.
  //
  // Why it is safe to cache HERE rather than anywhere else: a `RegistryGenContext`
  // is a SNAPSHOT of the tree — `tree`, `graph` and `mainBundle` are already
  // source-derived facts frozen at `buildRegistryGenContext` time, and a caller
  // that needs a post-write view of the filesystem must build a fresh ctx to see
  // it. A
  // `<dir>` scan is a pure function of exactly the same inputs (`ctx.tree`,
  // `ctx.repo()`, `dir`) and of nothing else — in particular NOT of the `bundle`,
  // which only filters an already-scanned entry list — so hanging it off the ctx
  // gives it precisely the lifetime it is valid for. Putting it in a
  // module-level cache would instead outlive the snapshot and start answering
  // with a stale filesystem.
  //
  // What it buys: the scan reads every `.ts`/`.tsx` file under every plugin's
  // `<dir>/` tree, which is the expensive half of registry codegen, and the
  // callers that already share ONE ctx re-render the same `<dir>` more than
  // once. `regen-pipeline.ts` shares a ctx between the registry and eager-tier
  // generators (the eager tier re-scanned `web` a second time); the build's
  // stage 1 shares a ctx across every composition one invocation names
  // (N compositions × 3 runtime dirs collapse to 3 scans). Behaviour is
  // unchanged — the cache holds the raw pre-filter scan, so the bundle filter
  // and the dep pruning still run per call. It holds the PROMISE, so two
  // concurrent renders of one `<dir>` share one scan.
  dirScans: Map<string, Promise<DirEntryScan>>;
}

/** The bundle-independent half of `collectEntriesWithDeps`: what one `<dir>`
 *  scan of the tree found, before any bundle filtering. */
interface DirEntryScan {
  allEntries: CollectedRawEntry[];
  rawDeps: Map<string, string[]>;
}

/**
 * The shared registry-generation context for `root`. A check passes its run's
 * file set as `repo` (so the scans read through it); codegen omits it and the
 * ctx lists the repo from git the first time a scan needs it.
 */
export async function buildRegistryGenContext(
  root: string,
  repo?: RepoFiles,
): Promise<RegistryGenContext> {
  if (repo !== undefined && repo.root !== root) {
    throw new Error(
      `buildRegistryGenContext(${root}) was handed the file set of ${repo.root}.`,
    );
  }
  const tree = await buildBarrelFreeTree(root);
  const graph = classifyEdges(tree);
  let listing = repo === undefined ? undefined : Promise.resolve(repo);
  return {
    root,
    tree,
    graph,
    // Throws rather than degrading when main's row is missing or its declared
    // exclusions did not take effect — see `resolveMainComposition`. A registry
    // that contradicts the manifest is worth failing the build for.
    mainBundle: resolveMainComposition(graph, root).bundle,
    repo: () => (listing ??= loadRepoFiles(root)),
    dirScans: new Map(),
  };
}

/**
 * The `<dir>` scan for this context, computed on first ask and reused after.
 * See `RegistryGenContext.dirScans` for why a ctx is the right lifetime.
 */
function scanDir(ctx: RegistryGenContext, dir: string): Promise<DirEntryScan> {
  let scan = ctx.dirScans.get(dir);
  if (scan === undefined) {
    scan = computeDirScan(ctx, dir);
    ctx.dirScans.set(dir, scan);
  }
  return scan;
}

async function computeDirScan(
  ctx: RegistryGenContext,
  dir: string,
): Promise<DirEntryScan> {
  const repo = await ctx.repo();
  const allEntries = await collectEntries(ctx.tree, repo, dir);
  return {
    allEntries,
    rawDeps: await buildDepsForDir(repo, allEntries, dir),
  };
}

/**
 * A collected-dir folder name as a JavaScript identifier: `data-dirs` →
 * `dataDirs`, so the emitted registry const is `dataDirsEntries`.
 *
 * Interpolating the folder name raw was fine only because every collected dir
 * happened to be one lowercase word (`check`, `facet`, `fixtures`). The first
 * hyphenated one emitted `export const data-dirsEntries`, which is not a legal
 * identifier — so the generated file failed to PARSE, and the failure surfaced
 * far from here, as a facet-extraction `AggregateError` during doc generation.
 * Deriving the identifier is what makes a hyphenated collected dir
 * representable at all, rather than a trap the next one falls into too.
 */
function identifierForDir(dir: string): string {
  return dir.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

async function collectEntries(
  tree: PluginTree,
  repo: RepoFiles,
  dir: string,
): Promise<CollectedRawEntry[]> {
  const barrels = [...tree.byDir.values()]
    .map((node) => ({ node, rel: `plugins/${node.path}/${dir}/index.ts` }))
    .filter((b) => repo.has(b.rel));
  const texts = await Promise.all(barrels.map((b) => readListed(repo, b.rel)));
  const tick = timeSlicer();
  const entries: CollectedRawEntry[] = [];
  for (const [i, { node }] of barrels.entries()) {
    const isEntry = hasDefaultExport(texts[i]!);
    await tick();
    if (!isEntry) continue;
    entries.push({
      pluginPath: node.path,
      importPath: `@plugins/${node.path}/${dir}`,
      id: node.id,
    });
  }
  entries.sort((a, b) => a.importPath.localeCompare(b.importPath));
  return entries;
}

// ── Dependency graph ───────────────────────────────────────────────

const TS_FILE_RE = /\.tsx?$/;

// Every `.ts`/`.tsx` under a plugin's `<dir>/` tree, skipping `node_modules` and
// nested `plugins/` (each sub-plugin is scanned as its own entry).
function tsFilesUnder(repo: RepoFiles, base: string): string[] {
  return repo.under(base).filter((rel) => {
    const segments = rel.slice(base.length + 1).split("/");
    const name = segments.pop()!;
    return (
      TS_FILE_RE.test(name) &&
      !segments.some((s) => s === "node_modules" || s === "plugins")
    );
  });
}

// Every import specifier found in a plugin's `<dir>/` tree. `findImports` masks
// comments/regex/strings and reads each specifier back by offset, so an import
// written inside a string/comment can't register a phantom dependency edge.
// Covers both `import … from` and `export … from`.
async function collectImportSpecifiers(
  repo: RepoFiles,
  pluginPath: string,
  dir: string,
  tick: () => Promise<void>,
): Promise<Set<string>> {
  const files = tsFilesUnder(repo, `plugins/${pluginPath}/${dir}`);
  const texts = await Promise.all(files.map((rel) => readListed(repo, rel)));
  const specifiers = new Set<string>();
  for (const text of texts) {
    for (const imp of findImports(text)) specifiers.add(imp.specifier);
    await tick();
  }
  return specifiers;
}

/** True for npm-style bare specifiers (neither relative/absolute nor `@plugins/*`). */
function isBareNpmSpecifier(mod: string): boolean {
  return (
    !mod.startsWith(".") &&
    !mod.startsWith("/") &&
    !mod.startsWith("@plugins/") &&
    !mod.startsWith("@composition-web-registry")
  );
}

/**
 * Bare npm specifiers (per subpath: `react-dom/client` ≠ `react-dom`) imported
 * by each collected plugin's `<dir>/` tree — the source-level vendor-set input
 * for the web-artifacts engine (and its Phase-2 `map-in-sync` cross-check).
 * Node builtins (`node:*`) are included verbatim; consumers filter. Does NOT
 * change the emitted registry shape.
 */
export async function collectBareSpecifiers(
  ctx: RegistryGenContext,
  dir: string,
): Promise<Map<string, string[]>> {
  const repo = await ctx.repo();
  const { allEntries } = await scanDir(ctx, dir);
  const tick = timeSlicer();
  const out = new Map<string, string[]>();
  for (const e of allEntries) {
    const specifiers = await collectImportSpecifiers(
      repo,
      e.pluginPath,
      dir,
      tick,
    );
    const bare = [...specifiers].filter(isBareNpmSpecifier).sort();
    if (bare.length > 0) out.set(e.pluginPath, bare);
  }
  return out;
}

async function buildDepsForDir(
  repo: RepoFiles,
  entries: CollectedRawEntry[],
  dir: string,
): Promise<Map<string, string[]>> {
  const prefixToPluginPath = new Map<string, string>();
  for (const e of entries) {
    const prefix = e.importPath.slice(0, e.importPath.lastIndexOf("/"));
    prefixToPluginPath.set(prefix, e.pluginPath);
  }

  const tick = timeSlicer();
  const gate = createSemaphore(PLUGIN_SCAN_WIDTH);
  const result = new Map<string, string[]>();
  await Promise.all(
    entries.map((e) =>
      gate.run(async () => {
        const deps = new Set<string>();
        for (const mod of await collectImportSpecifiers(
          repo,
          e.pluginPath,
          dir,
          tick,
        )) {
          if (!mod.startsWith("@plugins/")) continue;
          const lastSlash = mod.lastIndexOf("/");
          if (lastSlash <= 0) continue;
          const depPath = prefixToPluginPath.get(mod.slice(0, lastSlash));
          if (depPath && depPath !== e.pluginPath) deps.add(depPath);
        }
        if (deps.size > 0) result.set(e.pluginPath, [...deps].sort());
      }),
    ),
  );
  return result;
}

// ── Filtered entries + pruned deps ─────────────────────────────────
//
// There is exactly ONE filter, and it is REQUIRED: a registry is the registry of
// some composition, so "render this registry without saying which composition it
// is for" has no spelling. `generatePluginRegistry` passes `ctx.mainBundle` at
// the call site where that question is asked; a composition build passes its own.
// Each surviving entry's `dependsOn` is pruned to the surviving `pluginPath`s: a
// dangling dep on a non-emitted plugin would break the loader's topo-sort (a hard
// closure's deps already survive, so this is defensive). Shared by
// `renderCollectedDirRegistry` (so its output is byte-identical) AND the
// eager-tier generator, which needs the exact same filtered web entry set +
// pruned `dependsOn` graph.
export async function collectEntriesWithDeps(
  ctx: RegistryGenContext,
  dir: string,
  // The composition's bundle: the dot-form PluginId set of its hard closure.
  bundle: Set<string>,
): Promise<{ entries: CollectedRawEntry[]; deps: Map<string, string[]> }> {
  const { allEntries, rawDeps } = await scanDir(ctx, dir);
  const entries = allEntries.filter((e) => bundle.has(e.id));
  const survivingPaths = new Set(entries.map((e) => e.pluginPath));
  const deps = new Map<string, string[]>();
  for (const e of entries) {
    const entryDeps = (rawDeps.get(e.pluginPath) ?? []).filter((d) =>
      survivingPaths.has(d),
    );
    if (entryDeps.length > 0) deps.set(e.pluginPath, entryDeps);
  }
  return { entries, deps };
}

// ── Renderer ───────────────────────────────────────────────────────

export async function renderCollectedDirRegistry(opts: {
  ctx: RegistryGenContext;
  def: DiscoveredCollectedDir;
  // REQUIRED: which composition this registry is for — the dot-form PluginId set
  // of its hard closure. Pass `ctx.mainBundle` for the committed
  // `<dir>.generated.ts` files. Required rather than optional because an
  // unfiltered render would be a registry belonging to no composition, which is
  // how the app's membership and the manifest's used to drift apart silently.
  bundle: Set<string>;
}): Promise<string> {
  const { ctx, def, bundle } = opts;
  const { entries, deps } = await collectEntriesWithDeps(ctx, def.dir, bundle);
  const exportName = `${identifierForDir(def.dir)}Entries`;

  const lines: string[] = [];
  lines.push(HEADER);
  lines.push("");
  lines.push("export interface CollectedEntry {");
  lines.push("  pluginPath: string;");
  lines.push("  id: string;");
  lines.push("  loader: () => Promise<{ default: unknown }>;");
  lines.push("  dependsOn: string[];");
  lines.push("}");
  lines.push("");
  lines.push(`export const ${exportName}: CollectedEntry[] = [`);
  for (const e of entries) {
    const entryDeps = deps.get(e.pluginPath) ?? [];
    const depsLiteral =
      entryDeps.length > 0
        ? `[${entryDeps.map((d) => JSON.stringify(d)).join(", ")}]`
        : "[]";
    lines.push(
      `  { pluginPath: ${JSON.stringify(e.pluginPath)}, id: ${JSON.stringify(e.id)}, loader: () => import(${JSON.stringify(e.importPath)}), dependsOn: ${depsLiteral} },`,
    );
  }
  lines.push("];");
  lines.push("");
  return lines.join("\n");
}

// ── Public API ─────────────────────────────────────────────────────

export function collectedDirRegistryPath(def: DiscoveredCollectedDir): string {
  return join(def.ownerDir, "core", `${def.dir}.generated.ts`);
}

export async function generatePluginRegistry(opts: {
  root: string;
  // Optional prebuilt context so the pipeline can share ONE tree walk between the
  // registry and eager-tier generators (both are pure functions of the same
  // barrel-free tree). Built here when absent so standalone callers still work.
  ctx?: RegistryGenContext;
}): Promise<void> {
  const ctx = opts.ctx ?? (await buildRegistryGenContext(opts.root));
  const defs = await discoverCollectedDirsIn(await ctx.repo());
  for (const def of defs) {
    await writeGenerated({
      file: collectedDirRegistryPath(def),
      // The committed registries ARE the `singularity` composition's registries
      // — `compositionRegistryFileName` says so, and this is where that is made
      // true rather than merely asserted afterwards.
      content: await renderCollectedDirRegistry({
        ctx,
        def,
        bundle: ctx.mainBundle,
      }),
    });
  }
}

// ── Composition (filtered) registries ──────────────────────────────
//
// A composition build emits gitignored siblings of the committed full
// registries — same export name, restricted to the composition's bundle. The
// committed `<dir>.generated.ts` files are never touched, so the build stays
// byte-identical and `plugins-registry-in-sync` + `git status` stay clean.
//
// There is exactly ONE spelling: PER-NAME `<dir>.composition.<name>.generated.ts`.
// Every producer (auto-serve AND release) keys its registries by composition id,
// so no checkout-global "this checkout is currently composition X" state exists
// and a release can never reconfigure another namespace's backend. The pre-S1
// singleton `<dir>.composition.generated.ts` spelling is gone entirely (S5): no
// path writes it, selects it, or reaps it, so a stray file of that name is inert.

// The registries that need a composition-filtered (closure-restricted) sibling.
// `web`/`server` are the runtime registries the app actually loads at the import
// seam. `prewarm` is release-build-time-only — consumed by the asset-mirror
// release runner to bake each closure mirror's files into the bundle, never
// loaded by the served app — but it needs the same closure filtering so a
// release only pre-warms mirrors in the composition's closure. Central is
// dropped per the F1 requirements; check/lint are build-time-only and never
// loaded into a served app.
//
// `prewarm` is in this ONE set (rather than a released-only sibling set)
// because release is its only consumer and release is now per-name too — which
// also means `listNamedCompositionRegistries` lists prewarm files, so
// a future reclaim sweep would list prewarm files like any other. (Nothing
// sweeps today — the compose-serve deactivation stage that used to was deleted
// with the serve fan-out; Phase 5 owns the replacement.)
const COMPOSITION_RUNTIME_DIRS = new Set(["web", "server", "prewarm"]);

export function collectedDirNamedCompositionRegistryPath(
  def: DiscoveredCollectedDir,
  name: string,
): string {
  assertCompositionName(name);
  return join(def.ownerDir, "core", compositionRegistryFileName(def.dir, name));
}

/**
 * The registry FILE NAME for one `<dir>` and one composition — the single fact
 * that `singularity`'s registry is the committed `<dir>.generated.ts` and every
 * other composition's is the gitignored `<dir>.composition.<id>.generated.ts`.
 *
 * That equality is not a carve-out for main. It is exactly what Phase 1's
 * `plugins-registry-in-sync` check proves: the committed registry IS the
 * `singularity` composition's registry, re-derived from the filesystem on every
 * build and asserted byte-identical. So `singularity` is an ordinary composition
 * here, and `build` and `build --composition singularity` are identical by
 * construction rather than by two code paths that agree.
 *
 * Every consumer asks THIS — the codegen writer, the backend's boot-time
 * selector, the web fleet planner, `release`'s compile-time alias — so no caller
 * can arrive at "the composition's registry" by spelling a filename and get main
 * wrong. Filename-shaped (rather than path-shaped) because `release` names the
 * file relative to the repo root and holds no `DiscoveredCollectedDir`;
 * `compositionRegistryPath` is the def-shaped wrapper for everyone else.
 */
export function compositionRegistryFileName(
  dir: string,
  composition: string,
): string {
  assertCompositionName(composition);
  return composition === MAIN_COMPOSITION_ID
    ? `${dir}.generated.ts`
    : `${dir}.composition.${composition}.generated.ts`;
}

/** Where composition `composition`'s `<dir>` registry lives — see
 *  `compositionRegistryFileName` for why main resolves to the committed file. */
export function compositionRegistryPath(
  def: DiscoveredCollectedDir,
  composition: string,
): string {
  return composition === MAIN_COMPOSITION_ID
    ? collectedDirRegistryPath(def)
    : collectedDirNamedCompositionRegistryPath(def, composition);
}

export async function generateCompositionRegistry(opts: {
  root: string;
  bundle: Set<string>;
  /**
   * The composition id these registries belong to. REQUIRED: every filtered
   * registry is keyed by name, so no producer can write a checkout-global one.
   */
  name: string;
  // Optional prebuilt context so one build shares ONE tree walk across several
  // compositions' registries. Built here when absent so standalone callers work.
  ctx?: RegistryGenContext;
}): Promise<void> {
  assertCompositionName(opts.name);
  // The main composition's registry is the COMMITTED `<dir>.generated.ts`
  // (`compositionRegistryFileName`), which `generatePluginRegistry` already
  // wrote this build. Writing a `<dir>.composition.singularity.generated.ts`
  // beside it would mint a second, gitignored spelling of the same registry —
  // the file that used to reconfigure main's backend on its next spawn purely by
  // being present, and the reason `--hermetic --composition singularity` was
  // refused. Nothing may produce it, so the skip is here, at the one writer,
  // rather than as a guard at each caller.
  if (opts.name === MAIN_COMPOSITION_ID) return;
  const ctx = opts.ctx ?? (await buildRegistryGenContext(opts.root));
  const defs = await discoverCollectedDirsIn(await ctx.repo());
  for (const def of defs) {
    if (!COMPOSITION_RUNTIME_DIRS.has(def.dir)) continue;
    await writeGenerated({
      file: collectedDirNamedCompositionRegistryPath(def, opts.name),
      content: await renderCollectedDirRegistry({
        ctx,
        def,
        bundle: opts.bundle,
      }),
    });
  }
}

/** Parse `<dir>.composition.<name>.generated.ts` into its parts, else null. */
export function parseNamedCompositionRegistryFileName(
  fileName: string,
): { dir: string; name: string } | null {
  const m =
    /^([a-z]+)\.composition\.([a-z0-9][a-z0-9-]{0,62})\.generated\.ts$/.exec(
      fileName,
    );
  if (m === null) return null;
  return { dir: m[1]!, name: m[2]! };
}

/**
 * Every per-name composition registry currently on disk — the auto-serve
 * stage's sweep input (delete the entries whose name is no longer activated).
 *
 * Synchronous (callers include a synchronous program-key read), so it takes the
 * git-listed sync discovery front. The per-name registries themselves are
 * GITIGNORED, so no file set holds them: reading the (at most three) owning
 * `core/` directories is the only way to see them.
 */
export function listNamedCompositionRegistries(
  root: string,
): Array<{ dir: string; name: string; file: string }> {
  const out: Array<{ dir: string; name: string; file: string }> = [];
  for (const def of discoverCollectedDirs(root)) {
    if (!COMPOSITION_RUNTIME_DIRS.has(def.dir)) continue;
    const coreDir = join(def.ownerDir, "core");
    let entries;
    try {
      entries = readdirSync(coreDir, { withFileTypes: true });
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
      continue;
    }
    for (const entry of entries) {
      if (!entry.isFile()) continue;
      const parsed = parseNamedCompositionRegistryFileName(entry.name);
      if (parsed === null || parsed.dir !== def.dir) continue;
      out.push({ ...parsed, file: join(coreDir, entry.name) });
    }
  }
  return out;
}
