import { existsSync, readdirSync, readFileSync, rmSync, writeFileSync } from "fs";
import { dirname, join, resolve } from "path";
import { buildPluginTree, type PluginTree } from "@plugins/plugin-meta/plugins/plugin-tree/core";
import { findMarkerCalls, maskSource } from "@plugins/plugin-meta/plugins/parse-utils/core";
import type { CollectedDirDef } from "@plugins/framework/plugins/tooling/plugins/collected-dir/core";
import { asPluginId } from "@plugins/framework/plugins/plugin-id/core";
import { computeDisabledIds } from "./disabled-ids";

export interface DiscoveredCollectedDir extends CollectedDirDef {
  ownerDir: string;
}

const HEADER = [
  "// DO NOT EDIT — autogenerated by `./singularity build`",
  "// (see plugins/framework/plugins/tooling/plugins/codegen/core/plugin-registry-gen.ts).",
  "//",
  "// Adding/removing a plugin: create or delete the plugin's `<runtime>/index.ts`",
  "// and rebuild — this file regenerates from the filesystem. The",
  "// `plugins-registry-in-sync` check fails on drift.",
].join("\n");

// ── Core barrel discovery ──────────────────────────────────────────

function findCoreBarrels(pluginsRoot: string): string[] {
  const out: string[] = [];
  function walk(dir: string, depth: number): void {
    if (depth > 10) return;
    const barrel = join(dir, "core", "index.ts");
    if (existsSync(barrel)) out.push(barrel);
    let entries;
    try {
      entries = readdirSync(dir, { withFileTypes: true });
    } catch (err) {
      const code = (err as NodeJS.ErrnoException).code;
      if (code !== "ENOENT" && code !== "EACCES" && code !== "ENOTDIR") throw err;
      return;
    }
    for (const e of entries) {
      if (!e.isDirectory()) continue;
      if (dir === pluginsRoot) {
        walk(join(dir, e.name), depth + 1);
      } else if (e.name === "plugins") {
        let children;
        try {
          children = readdirSync(join(dir, e.name), { withFileTypes: true });
        } catch (err) {
          const code = (err as NodeJS.ErrnoException).code;
          if (code !== "ENOENT" && code !== "EACCES" && code !== "ENOTDIR") throw err;
          continue;
        }
        for (const c of children) {
          if (c.isDirectory()) walk(join(dir, e.name, c.name), depth + 1);
        }
      }
    }
  }
  walk(pluginsRoot, 0);
  return out;
}

// First positional string argument of a `defineCollectedDir("<dir>")` call.
const FIRST_STRING_ARG_RE = /^\s*["']([^"']+)["']/;

// Synchronous: this does only blocking `readdirSync`/`readFileSync`/`existsSync`
// I/O. Keeping it sync (rather than async-by-signature) lets callers — notably
// the structure facet's `extract`, which the facet pipeline invokes without
// `await` — consume it without a top-level await. A top-level await here would
// suspend the facet module mid-evaluation inside the facets ⇄ codegen import
// cycle, surfacing as a TDZ crash ("Cannot access 'default' before initialization").
export function discoverCollectedDirs(
  root: string,
): DiscoveredCollectedDir[] {
  const pluginsRoot = resolve(root, "plugins");
  const coreBarrels = findCoreBarrels(pluginsRoot);
  const out: DiscoveredCollectedDir[] = [];
  for (const barrelPath of coreBarrels) {
    const coreDir = dirname(barrelPath);
    let coreFiles;
    try {
      coreFiles = readdirSync(coreDir, { withFileTypes: true });
    } catch (err) {
      const code = (err as NodeJS.ErrnoException).code;
      if (code !== "ENOENT" && code !== "EACCES" && code !== "ENOTDIR") throw err;
      continue;
    }
    for (const entry of coreFiles) {
      if (!entry.isFile() || !entry.name.endsWith(".ts")) continue;
      const filePath = join(coreDir, entry.name);
      const src = readFileSync(filePath, "utf8");
      // Fast-path: skip files that can't contain the marker. Correctness still
      // comes from `findMarkerCalls`, which ignores comment/string/regex matches.
      if (!src.includes("defineCollectedDir")) continue;
      for (const call of findMarkerCalls(src, "defineCollectedDir")) {
        const arg = FIRST_STRING_ARG_RE.exec(call.argsText);
        if (!arg) continue;
        out.push({
          dir: arg[1]!,
          _brand: "CollectedDirDef",
          ownerDir: dirname(coreDir),
        });
      }
    }
  }
  return out;
}

// ── Standard plugin folders ────────────────────────────────────────

// The set of directory names considered "standard" inside a plugin. Two parts:
//   1. The collected-dir / runtime names (web, server, central, facet, check,
//      lint, …) discovered generically via `defineCollectedDir`. This part
//      AUTO-GROWS — registering a new runtime or collected-dir type adds its
//      folder name here with zero edits, which is the friction being removed.
//   2. A fixed set of stable structural conventions (core, shared, plugins, bin,
//      scripts) that are not runtime/collected-dir types and never grow when a
//      new such type is added — so listing them here is not the friction.
export function standardPluginDirs(root: string): Set<string> {
  const collected = discoverCollectedDirs(root).map((d) => d.dir);
  return new Set([...collected, "core", "shared", "plugins", "bin", "scripts"]);
}

// ── Entry collection ───────────────────────────────────────────────

interface CollectedRawEntry {
  pluginPath: string;
  importPath: string;
  id: string;
}

function hasDefaultExport(file: string): boolean {
  // Mask comments/regex (keep string interiors) so a commented-out `export
  // default` can't make an entryless barrel look like an entry.
  const src = maskSource(readFileSync(file, "utf8"), { strings: false });
  return (
    /(^|\n)\s*export\s+default\b/.test(src) ||
    /(^|\n)\s*export\s*\{[^}]*\bdefault\b[^}]*\}/.test(src)
  );
}

// ── Registry-generation context ────────────────────────────────────
//
// The plugin tree and the disabled-id closure are pure functions of the
// filesystem — IDENTICAL for every collected dir. Build them ONCE per generation
// pass and thread the context through `renderCollectedDirRegistry`. This is what
// keeps registry codegen O(tree) instead of O(tree × collectedDirs): there are
// ~10 collected dirs (web, server, central, check, lint, facet, …), so a per-def
// rebuild meant ~10 full 840-plugin tree walks (~12s, the dominant codegen cost).
// Taking a prebuilt context — rather than a `root` the renderer rebuilds from —
// makes that redundant build structurally impossible: the renderer literally
// cannot trigger a tree walk.
export interface RegistryGenContext {
  root: string;
  tree: PluginTree;
  // Closed disabled-id set computed from the SAME barrel-free tree the entries
  // come from. Applied unconditionally by the renderer so the
  // `plugins-registry-in-sync` check (which never passes `bundle`) re-derives
  // the identical filtered output from the committed `package.json` flags.
  disabled: Set<string>;
}

export async function buildRegistryGenContext(
  root: string,
): Promise<RegistryGenContext> {
  const pluginsRoot = resolve(root, "plugins");
  const tree = await buildPluginTree(pluginsRoot, { skipBarrelImport: true });
  return { root, tree, disabled: computeDisabledIds(tree) };
}

function collectEntries(tree: PluginTree, dir: string): CollectedRawEntry[] {
  const entries: CollectedRawEntry[] = [];
  for (const node of tree.byDir.values()) {
    const indexFile = join(node.dir, dir, "index.ts");
    if (!existsSync(indexFile)) continue;
    if (!hasDefaultExport(indexFile)) continue;
    entries.push({
      pluginPath: node.path,
      importPath: `@plugins/${node.path}/${dir}`,
      id: node.id,
    });
  }
  entries.sort((a, b) => a.importPath.localeCompare(b.importPath));
  return entries;
}

// ── Dependency graph ───────────────────────────────────────────────

function walkTsFiles(dir: string, out: string[]): void {
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch (err) {
    const code = (err as NodeJS.ErrnoException).code;
    if (code !== "ENOENT" && code !== "EACCES" && code !== "ENOTDIR") throw err;
    return;
  }
  for (const e of entries) {
    const p = join(dir, e.name);
    if (e.isDirectory()) {
      if (e.name === "node_modules" || e.name === "plugins") continue;
      walkTsFiles(p, out);
    } else if (e.isFile() && /\.tsx?$/.test(e.name)) {
      out.push(p);
    }
  }
}

const IMPORT_FROM_RE = /from\s*["']([^"']+)["']/g;

function collectImportPrefixes(pluginDir: string, dir: string, entryPrefixes: Set<string>): Set<string> {
  const subDir = join(pluginDir, dir);
  const files: string[] = [];
  walkTsFiles(subDir, files);
  const prefixes = new Set<string>();
  for (const f of files) {
    // Mask comments/regex (keep import path strings) so a commented-out import
    // can't register a phantom dependency edge.
    const src = maskSource(readFileSync(f, "utf8"), { strings: false });
    let m: RegExpExecArray | null;
    IMPORT_FROM_RE.lastIndex = 0;
    while ((m = IMPORT_FROM_RE.exec(src))) {
      const mod = m[1]!;
      if (!mod.startsWith("@plugins/")) continue;
      const lastSlash = mod.lastIndexOf("/");
      if (lastSlash > 0) {
        const prefix = mod.slice(0, lastSlash);
        if (entryPrefixes.has(prefix)) prefixes.add(prefix);
      }
    }
  }
  return prefixes;
}

function buildDepsForDir(
  root: string,
  entries: CollectedRawEntry[],
  dir: string,
): Map<string, string[]> {
  const prefixToPluginPath = new Map<string, string>();
  const entryPrefixes = new Set<string>();
  for (const e of entries) {
    const prefix = e.importPath.slice(0, e.importPath.lastIndexOf("/"));
    prefixToPluginPath.set(prefix, e.pluginPath);
    entryPrefixes.add(prefix);
  }

  const pluginsRoot = resolve(root, "plugins");
  const result = new Map<string, string[]>();

  for (const e of entries) {
    const pluginDir = join(pluginsRoot, e.pluginPath);
    const depPrefixes = collectImportPrefixes(pluginDir, dir, entryPrefixes);
    const deps: string[] = [];
    for (const prefix of depPrefixes) {
      const depPath = prefixToPluginPath.get(prefix);
      if (depPath && depPath !== e.pluginPath) deps.push(depPath);
    }
    if (deps.length > 0) {
      deps.sort();
      result.set(e.pluginPath, deps);
    }
  }
  return result;
}

// ── Renderer ───────────────────────────────────────────────────────

export function renderCollectedDirRegistry(opts: {
  ctx: RegistryGenContext;
  def: DiscoveredCollectedDir;
  // When provided, restrict the registry to the plugins in this bundle (the
  // dot-form PluginId set of a composition's hard closure). Each surviving
  // entry's `dependsOn` is also pruned to surviving `pluginPath`s — defensive,
  // since a hard closure's deps already survive. When undefined, the output is
  // byte-identical to the unfiltered registry, so the `plugins-registry-in-sync`
  // check (which never passes a bundle) is unaffected.
  bundle?: Set<string>;
}): string {
  const { ctx, def, bundle } = opts;
  const { disabled } = ctx;
  const allEntries = collectEntries(ctx.tree, def.dir);
  const deps = buildDepsForDir(ctx.root, allEntries, def.dir);
  const exportName = `${def.dir}Entries`;

  // The disabled-closure filter is UNCONDITIONAL (driven by the committed
  // `singularity.disabled` seeds), never the optional `bundle` — so the
  // `plugins-registry-in-sync` check, which re-renders without `bundle`, sees
  // the identical filtered output. `survivingPaths` is derived from the
  // post-filter `entries`, so `dependsOn` is pruned to survivors.
  const entries = (bundle ? allEntries.filter((e) => bundle.has(e.id)) : allEntries)
    .filter((e) => !disabled.has(asPluginId(e.id)));
  const survivingPaths = new Set(entries.map((e) => e.pluginPath));

  const lines: string[] = [];
  lines.push(HEADER);
  lines.push("");
  lines.push("export interface CollectedEntry {");
  lines.push("  pluginPath: string;");
  lines.push("  id: string;");
  lines.push("  loader: () => Promise<{ default: unknown }>;");
  lines.push("  dependsOn: string[];");
  lines.push("}");
  lines.push("");
  lines.push(`export const ${exportName}: CollectedEntry[] = [`);
  for (const e of entries) {
    // Always prune `dependsOn` to surviving paths: the disabled filter can drop
    // a dependency unconditionally (not only under `bundle`), and a dangling
    // dep on a non-emitted plugin would break the loader's topo-sort.
    const entryDeps = (deps.get(e.pluginPath) ?? []).filter((d) => survivingPaths.has(d));
    const depsLiteral = entryDeps.length > 0
      ? `[${entryDeps.map((d) => JSON.stringify(d)).join(", ")}]`
      : "[]";
    lines.push(
      `  { pluginPath: ${JSON.stringify(e.pluginPath)}, id: ${JSON.stringify(e.id)}, loader: () => import(${JSON.stringify(e.importPath)}), dependsOn: ${depsLiteral} },`,
    );
  }
  lines.push("];");
  lines.push("");
  return lines.join("\n");
}

// ── Public API ─────────────────────────────────────────────────────

export function collectedDirRegistryPath(
  def: DiscoveredCollectedDir,
): string {
  return join(def.ownerDir, "core", `${def.dir}.generated.ts`);
}

export async function generatePluginRegistry(opts: {
  root: string;
}): Promise<void> {
  const ctx = await buildRegistryGenContext(opts.root);
  const defs = discoverCollectedDirs(opts.root);
  for (const def of defs) {
    const file = collectedDirRegistryPath(def);
    const next = renderCollectedDirRegistry({ ctx, def });
    const existing = existsSync(file) ? readFileSync(file, "utf8") : "";
    if (next !== existing) writeFileSync(file, next);
  }
}

// ── Composition (filtered) registries ──────────────────────────────
//
// A composition build emits gitignored siblings of the committed full
// registries — same export name, restricted to the composition's bundle. The
// committed `<dir>.generated.ts` files are never touched, so the build stays
// byte-identical and `plugins-registry-in-sync` + `git status` stay clean.

// The registries that need a composition-filtered (closure-restricted) sibling.
// `web`/`server` are the runtime registries the app actually loads at the import
// seam. `prewarm` is release-build-time-only — consumed by the asset-mirror
// release runner to bake each closure mirror's files into the bundle, never
// loaded by the served app — but it needs the same closure filtering so a
// release only pre-warms mirrors in the composition's closure. Central is
// dropped per the F1 requirements; check/lint are build-time-only and never
// loaded into a served app.
const COMPOSITION_RUNTIME_DIRS = new Set(["web", "server", "prewarm"]);

export function collectedDirCompositionRegistryPath(
  def: DiscoveredCollectedDir,
): string {
  return join(def.ownerDir, "core", `${def.dir}.composition.generated.ts`);
}

export async function generateCompositionRegistry(opts: {
  root: string;
  bundle: Set<string>;
}): Promise<void> {
  const ctx = await buildRegistryGenContext(opts.root);
  const defs = discoverCollectedDirs(opts.root);
  for (const def of defs) {
    if (!COMPOSITION_RUNTIME_DIRS.has(def.dir)) continue;
    const file = collectedDirCompositionRegistryPath(def);
    const next = renderCollectedDirRegistry({ ctx, def, bundle: opts.bundle });
    const existing = existsSync(file) ? readFileSync(file, "utf8") : "";
    if (next !== existing) writeFileSync(file, next);
  }
}

// Remove any stale filtered registries so a plain (non-composition) build
// reverts the runtimes to the full committed registries. No-throw if absent.
export async function clearCompositionRegistries(opts: {
  root: string;
}): Promise<void> {
  const defs = discoverCollectedDirs(opts.root);
  for (const def of defs) {
    if (!COMPOSITION_RUNTIME_DIRS.has(def.dir)) continue;
    const file = collectedDirCompositionRegistryPath(def);
    if (existsSync(file)) rmSync(file);
  }
}
