import { existsSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { buildEnrichedTree } from "./docgen";
import {
  setDefaultOriginAnnotationsPreparer,
  type OriginAnnotationsProvider,
} from "./config-origin-gen";
import { getFacet } from "@plugins/plugin-meta/plugins/facets/core";
import { slotsFacetDef } from "@plugins/plugin-meta/plugins/facets/plugins/slots/core";
import { contributionsFacetDef } from "@plugins/plugin-meta/plugins/facets/plugins/contributions/core";
import type { ConfigDescriptor } from "@plugins/config_v2/core";

/**
 * Generates the reorderable-slots manifest consumed by the reorder plugin and
 * the per-slot contribution catalog injected into generated config origins.
 *
 * The manifest is a pure-data bridge: the live server can't see web-slot
 * contributions, but this build-time codegen (via the facets pipeline docgen
 * already uses) can. reorder reads `reorderableSlots` from
 * `plugins/reorder/shared/reorderable-slots.generated.ts` on both runtimes and
 * registers one config_v2 directive per slot.
 */

// The output mirrors the placeholder committed at
// plugins/reorder/shared/reorderable-slots.generated.ts.
const MANIFEST_REL_PATH =
  "plugins/reorder/shared/reorderable-slots.generated.ts";

const MANIFEST_HEADER = [
  "// DO NOT EDIT — autogenerated by `./singularity build`",
  "// (see plugins/framework/plugins/tooling/plugins/codegen/core/reorderable-slots-gen.ts).",
  "//",
  "// The list of reorderable render slots (those whose `.Render` applies the",
  "// reorder middleware, i.e. `defineRenderSlot` without `reorder: false`). Each",
  "// entry's `pluginId` is the *defining* plugin's id (its tree path), so reorder",
  "// registers the slot's config_v2 directive under `config/<pluginId>/`.",
  "//",
  "// The `reorderable-slots-in-sync` check fails on drift.",
].join("\n");

export interface ReorderableSlotEntry {
  slotId: string;
  pluginId: string;
}

interface CatalogItem {
  entryKey: string;
  label: string;
}

interface ReorderableSlotsData {
  slots: ReorderableSlotEntry[];
  /** slotId -> ordered catalog of available contributions. */
  catalog: Map<string, CatalogItem[]>;
}

/**
 * Walk the enriched plugin tree (reusing docgen's cached build) and collect:
 *  1. every statically-known reorderable render slot, keyed to its DEFINING
 *     plugin's hierarchy path;
 *  2. the contribution catalog for each such slot, from the contributions facet.
 */
async function collectReorderableSlots(
  root: string,
): Promise<ReorderableSlotsData> {
  const tree = await buildEnrichedTree(root);

  // Defining node per slot: the first node whose slots facet declares it. The
  // slots facet already skips template-literal ids (e.g. detail-sections), so
  // only statically-resolvable slot ids land here.
  const definingPath = new Map<string, string>();
  for (const node of tree.byDir.values()) {
    const slots = getFacet(node, slotsFacetDef) ?? [];
    for (const slot of slots) {
      if (slot.kind !== "render") continue;
      if (slot.reorder === false) continue;
      if (definingPath.has(slot.slotId)) continue;
      definingPath.set(slot.slotId, node.id);
    }
  }

  // Catalog: every runtime contribution targeting a reorderable slot.
  const catalog = new Map<string, CatalogItem[]>();
  for (const node of tree.byDir.values()) {
    const data = getFacet(node, contributionsFacetDef);
    if (!data) continue;
    for (const c of data.runtime) {
      if (!definingPath.has(c.slotId)) continue;
      if (!c.id) continue;
      const entryKey = c.pluginId ? `${c.pluginId}:${c.id}` : c.id;
      const label = c.doc.label ?? entryKey;
      let items = catalog.get(c.slotId);
      if (!items) {
        items = [];
        catalog.set(c.slotId, items);
      }
      items.push({ entryKey, label });
    }
  }

  const slots: ReorderableSlotEntry[] = [...definingPath.entries()]
    .map(([slotId, pluginId]) => ({ slotId, pluginId }))
    .sort((a, b) => a.slotId.localeCompare(b.slotId));

  return { slots, catalog };
}

function renderManifest(slots: ReorderableSlotEntry[]): string {
  const lines: string[] = [];
  lines.push(MANIFEST_HEADER);
  lines.push("");
  lines.push("export interface ReorderableSlot {");
  lines.push("  slotId: string;");
  lines.push("  pluginId: string;");
  lines.push("}");
  lines.push("");
  if (slots.length === 0) {
    lines.push("export const reorderableSlots: ReorderableSlot[] = [];");
  } else {
    lines.push("export const reorderableSlots: ReorderableSlot[] = [");
    for (const s of slots) {
      lines.push(
        `  { slotId: ${JSON.stringify(s.slotId)}, pluginId: ${JSON.stringify(s.pluginId)} },`,
      );
    }
    lines.push("];");
  }
  lines.push("");
  return lines.join("\n");
}

/** Path to the committed manifest file. */
export function reorderableSlotsManifestPath(root: string): string {
  return join(root, MANIFEST_REL_PATH);
}

/** Render the manifest file contents in-memory (used by the in-sync check). */
export async function renderReorderableSlotsManifest(
  root: string,
): Promise<string> {
  const { slots } = await collectReorderableSlots(root);
  return renderManifest(slots);
}

/** Build the origin-annotations provider from the per-slot catalog. */
function buildOriginAnnotationsProvider(
  catalog: Map<string, CatalogItem[]>,
): OriginAnnotationsProvider {
  return (descriptor: ConfigDescriptor): string[] => {
    // The directive descriptor's `name` is the slotId.
    const items = catalog.get(descriptor.name);
    if (!items || items.length === 0) return [];
    const lines: string[] = [
      "Available items in this slot (reorder via the `order` array, hide via `hidden`):",
      'Insert a blank gap by adding a "__spacer__<unique-id>" string into the order array.',
    ];
    for (const item of items) {
      lines.push(`- ${item.entryKey}  — ${item.label}`);
    }
    return lines;
  };
}

/**
 * Side-effecting registration: installs the reorder catalog as the process-wide
 * default origin-annotations preparer. Imported by BOTH the build step and the
 * `config-origins-in-sync` check, so both processes resolve the same comments.
 *
 * Returns a no-op for descriptors that aren't reorder directives (their slotId
 * isn't in the catalog) — keeping the provider generic.
 */
setDefaultOriginAnnotationsPreparer(async (root: string) => {
  const { catalog } = await collectReorderableSlots(root);
  return buildOriginAnnotationsProvider(catalog);
});

/** Regenerate `reorderable-slots.generated.ts` if it drifted. */
export async function generateReorderableSlots(opts: {
  root: string;
}): Promise<void> {
  const next = await renderReorderableSlotsManifest(opts.root);
  const file = reorderableSlotsManifestPath(opts.root);
  const existing = existsSync(file) ? readFileSync(file, "utf8") : "";
  if (next !== existing) writeFileSync(file, next);
}
