import { join } from "path";
import { writeGenerated } from "./write-generated";
import { buildEnrichedTree } from "./enriched-tree";
import {
  setDefaultOriginAnnotationsPreparer,
  setDefaultOriginDefaultsPreparer,
  type OriginAnnotationsProvider,
} from "./config-origin-gen";
import { getFacet } from "@plugins/plugin-meta/plugins/facets/core";
import { getCreatedSlots } from "@plugins/framework/plugins/slot-declaration/core";
import { declareSlotsFromBarrels } from "./slot-declaration-guard";
import { contributionsFacetDef } from "@plugins/plugin-meta/plugins/facets/plugins/contributions/core";
import { computeDisabledIds } from "./disabled-ids";
import type { ConfigDescriptor } from "@plugins/config_v2/core";
import { REORDER_NODE_LEGEND } from "@plugins/fields/plugins/reorder-tree/core";

/**
 * Generates the reorderable-slots manifest consumed by the reorder plugin and
 * the per-slot contribution catalog injected into generated config origins.
 *
 * The manifest is a pure-data bridge for ONE runtime: the live server can't see
 * web-slot declarations, so it reads `reorderableSlots` from
 * `plugins/reorder/shared/reorderable-slots.generated.ts` and registers one
 * config_v2 directive per slot. The web runtime holds the slot objects, so it
 * derives the same set from them and reads no generated file — which is what
 * lets this manifest be written between the web and server import phases.
 */

// The output mirrors the placeholder committed at
// plugins/reorder/shared/reorderable-slots.generated.ts.
const MANIFEST_REL_PATH =
  "plugins/reorder/shared/reorderable-slots.generated.ts";

const MANIFEST_HEADER = [
  "// DO NOT EDIT — autogenerated by `./singularity build`",
  "// (see plugins/framework/plugins/tooling/plugins/codegen/core/reorderable-slots-gen.ts).",
  "//",
  "// Every DECLARED slot (`PluginDefinition.slots`) whose `meta.reorderable` is true:",
  "// `defineRenderSlot` (its `.Render` applies the reorder middleware) and",
  "// `defineOrderedDispatchSlot` (contributions carry a structurally-required `id`).",
  "// Each entry's `pluginId` is the DECLARING plugin's id (its tree path), so reorder",
  "// registers the slot's config_v2 directive under `config/<pluginId>/`.",
  "//",
  "// Read by the SERVER only — it cannot see web slots. The web runtime derives the",
  "// same set from the slot objects themselves, so no web barrel imports this file.",
  "//",
  "// The `reorderable-slots-in-sync` check fails on drift.",
].join("\n");

export interface ReorderableSlotEntry {
  slotId: string;
  pluginId: string;
}

interface CatalogItem {
  entryKey: string;
}

interface ReorderableSlotsData {
  slots: ReorderableSlotEntry[];
  /** slotId -> ordered catalog of available contributions. */
  catalog: Map<string, CatalogItem[]>;
}

/**
 * The reorderable-slot SET — read from what each plugin DECLARES.
 *
 * Every plugin's `slots: [...]` is normalised through the same `collectSlots`
 * the browser runs, and `meta.reorderable` (stamped by the slot's constructor)
 * decides membership. So the manifest states what the RUNTIME will do, and a
 * slot whose id is built at run time — `` `pane.${id}.actions` `` — is in it for
 * the first time. Source text cannot answer either question: a templated id is
 * unreadable, and "is this reorderable" was a function name a grep had to
 * recognise.
 *
 * It rides the shared declaration pass, which imports WEB barrels and only web
 * barrels. That is what fixes the ordering this file used to be pinned by: the
 * manifest is written between the web and the server import phases, so the
 * server barrels that read it (the server cannot see web slots) are imported
 * after it lands, while no web barrel reads it at all. Deterministic all the
 * same — the result is sorted by slotId and deduped.
 */
async function collectReorderableSlotSet(
  root: string,
): Promise<ReorderableSlotEntry[]> {
  // The one declaration pass — shared with the orphan guard, which has already
  // proved every created slot is in it.
  const owners = await declareSlotsFromBarrels(root);

  const entries: ReorderableSlotEntry[] = [];
  const seen = new Set<string>();
  // Exactly the derivation the web runtime runs (`syncReorderDescriptors`):
  // every created slot whose own `meta.reorderable` is true, attributed to the
  // plugin that DECLARED it. There is no second filter here — a disabled plugin
  // is already absent from the declaration pass (it is absent from the registry),
  // which is what makes the server's manifest and the web's registrations one
  // derivation of one set rather than two filters that can drift apart.
  for (const slot of getCreatedSlots()) {
    if (!slot.meta.reorderable) continue;
    if (seen.has(slot.id)) continue;
    const pluginId = owners.get(slot.id);
    if (pluginId === undefined) continue;
    seen.add(slot.id);
    entries.push({ slotId: slot.id, pluginId });
  }
  return entries.sort((a, b) => a.slotId.localeCompare(b.slotId));
}

/**
 * Walk the enriched plugin tree (reusing docgen's cached build) and collect:
 *  1. the reorderable-slot set (via `collectReorderableSlotSet`).
 *  2. the contribution catalog for each such slot, from the contributions facet.
 *
 * Used ONLY by the origin-preparers, which run lazily during
 * `generateConfigOrigins` — i.e. after the whole tree (web AND server barrels)
 * is primed, which is what the facet read needs and the slot set alone does not.
 */
async function collectReorderableSlots(
  root: string,
): Promise<ReorderableSlotsData> {
  const tree = await buildEnrichedTree(root);
  // Drop catalog entries contributed by disabled plugins: their barrels never
  // load, so listing them in an enabled slot's materialized default would point
  // the origin hash at contributions that don't register. (The slot SET itself
  // is already disabled-filtered inside `collectReorderableSlotSet`.)
  const disabled = computeDisabledIds(tree);

  // (1) The reorderable-slot set — the declarations (barrels already primed).
  const slots = await collectReorderableSlotSet(root);
  const reorderableIds = new Set(slots.map((s) => s.slotId));

  // (2) Catalog: every runtime contribution targeting a reorderable slot.
  const catalog = new Map<string, CatalogItem[]>();
  for (const node of tree.byDir.values()) {
    if (disabled.has(node.id)) continue;
    const data = getFacet(node, contributionsFacetDef);
    if (!data) continue;
    for (const c of data.runtime) {
      if (!reorderableIds.has(c.slotId)) continue;
      if (!c.id) continue;
      const entryKey = c.pluginId ? `${c.pluginId}:${c.id}` : c.id;
      let items = catalog.get(c.slotId);
      if (!items) {
        items = [];
        catalog.set(c.slotId, items);
      }
      items.push({ entryKey });
    }
  }

  return { slots, catalog };
}

function renderManifest(slots: ReorderableSlotEntry[]): string {
  const lines: string[] = [];
  lines.push(MANIFEST_HEADER);
  lines.push("");
  lines.push("export interface ReorderableSlot {");
  lines.push("  slotId: string;");
  lines.push("  pluginId: string;");
  lines.push("}");
  lines.push("");
  if (slots.length === 0) {
    lines.push("export const reorderableSlots: ReorderableSlot[] = [];");
  } else {
    lines.push("export const reorderableSlots: ReorderableSlot[] = [");
    for (const s of slots) {
      lines.push(
        `  { slotId: ${JSON.stringify(s.slotId)}, pluginId: ${JSON.stringify(s.pluginId)} },`,
      );
    }
    lines.push("];");
  }
  lines.push("");
  return lines.join("\n");
}

/** Path to the committed manifest file. */
export function reorderableSlotsManifestPath(root: string): string {
  return join(root, MANIFEST_REL_PATH);
}

/** Render the manifest file contents in-memory (used by the in-sync check). */
export async function renderReorderableSlotsManifest(
  root: string,
): Promise<string> {
  // Needs the declarations, hence the web barrels — but NOT the contribution
  // catalog, which is a facet read and lives in `collectReorderableSlots`.
  const slots = await collectReorderableSlotSet(root);
  return renderManifest(slots);
}

/**
 * Slim origin-annotations provider: the order lives in the `items` value (a
 * materialized `ReorderTree`) and each entry is a fully-qualified `entryKey`
 * (`pluginId:id`), so the comments are just the hand-edit format legend — the
 * per-entry label map would only restate the already-explicit keys.
 *
 * The legend itself is `REORDER_NODE_LEGEND`, shared with the directive's
 * authoring guidance, so a new node type is one line in one place.
 */
function buildOriginAnnotationsProvider(
  catalog: Map<string, CatalogItem[]>,
): OriginAnnotationsProvider {
  return (descriptor: ConfigDescriptor): string[] => {
    // The directive descriptor's `name` is the slotId.
    const items = catalog.get(descriptor.name);
    if (!items || items.length === 0) return [];
    return [...REORDER_NODE_LEGEND];
  };
}

/**
 * Side-effecting registration: installs the reorder catalog as the process-wide
 * default origin-annotations preparer. Imported by BOTH the build step and the
 * `config-origins-in-sync` check, so both processes resolve the same comments.
 *
 * Returns a no-op for descriptors that aren't reorder directives (their slotId
 * isn't in the catalog) — keeping the provider generic.
 */
setDefaultOriginAnnotationsPreparer(async (root: string) => {
  const { catalog } = await collectReorderableSlots(root);
  return buildOriginAnnotationsProvider(catalog);
});

/**
 * Side-effecting registration: installs the reorder catalog as the process-wide
 * default origin-DEFAULTS preparer. The materialized default for each reorderable
 * slot's `items` field is the full ordered catalog of `entryKey`s (bare strings —
 * terse). This makes the origin hash reflect the live catalog: adding/removing a
 * contribution shifts the hash → committed overrides go stale and
 * `config-origins-in-sync` blocks push until reconciled (the agent forcing
 * function). Returns `undefined` for descriptors whose slotId isn't in the
 * catalog, so non-reorder descriptors fall back to `descriptor.defaults`.
 */
setDefaultOriginDefaultsPreparer(async (root: string) => {
  const { catalog } = await collectReorderableSlots(root);
  return (descriptor: ConfigDescriptor) => {
    const items = catalog.get(descriptor.name);
    return items ? { items: items.map((c) => c.entryKey) } : undefined;
  };
});

/** Regenerate `reorderable-slots.generated.ts` if it drifted. */
export async function generateReorderableSlots(opts: {
  root: string;
}): Promise<void> {
  await writeGenerated({
    file: reorderableSlotsManifestPath(opts.root),
    content: await renderReorderableSlotsManifest(opts.root),
  });
}
