import { existsSync, readFileSync, writeFileSync } from "fs";
import { join, relative } from "path";
import { buildBarrelFreeTree } from "./docgen";
import {
  registerBarrelStubs,
  importBarrel,
} from "@plugins/plugin-meta/plugins/barrel-import/core";

/**
 * Generates the token-group-vars manifest consumed by the build-time CSS
 * single-owner checks (`css-vars-single-owner`, `css-vars-supplied`).
 *
 * The manifest is a pure-data bridge: a build-time check can't import the
 * `@plugins/ui/...` token-group descriptors at runtime (that would invert the
 * framework→ui layering), and `shared/group.ts` is plugin-private (boundary
 * R10). But this build-time codegen can read the REAL `defineTokenGroup`
 * descriptors via `importBarrel` — exactly how the `facets:render-complete`
 * check already reads live web-slot contributions.
 *
 * It generically collects every contribution whose slot id is
 * `ui.theme-engine.token-group` (the TokenGroup slot's own registry — never
 * naming specific groups), reading each contribution's `id` and
 * `descriptor.vars`. This auto-discovers any token group anywhere, satisfying
 * collection-consumer separation.
 */

const TOKEN_GROUP_SLOT_ID = "ui.theme-engine.token-group";

// The output mirrors the placeholder committed at
// plugins/framework/plugins/tooling/plugins/checks/core/token-group-vars.generated.ts.
const MANIFEST_REL_PATH =
  "plugins/framework/plugins/tooling/plugins/checks/core/token-group-vars.generated.ts";

const MANIFEST_HEADER = [
  "// DO NOT EDIT — autogenerated by `./singularity build`",
  "// (see plugins/framework/plugins/tooling/plugins/codegen/core/token-group-vars-gen.ts).",
  "//",
  "// The CSS custom properties (`--x`) declared by each token group, read from",
  "// the real `defineTokenGroup` descriptors via their `ui.theme-engine.token-group`",
  "// web-slot contributions. Consumed by the build-time CSS single-owner checks.",
  "//",
  "// The `token-group-vars-in-sync` check fails on drift.",
].join("\n");

// Memoize per root: the descriptors are immutable for a process's lifetime, so
// the (barrel-importing) collection runs at most once even though the codegen
// step plus three checks (`token-group-vars-in-sync`, `css-vars-supplied`,
// `css-vars-single-owner`) all consume it. Promise-valued so concurrent callers
// share one in-flight pass; evicted on rejection so a transient failure doesn't
// poison later retries.
const collectCache = new Map<string, Promise<Record<string, string[]>>>();

/**
 * Walk the plugin tree, import each plugin's web barrel, and collect — per token
 * group id — the CSS vars its descriptor declares. Generic: keyed on the
 * TokenGroup slot id, never on a specific group's name.
 *
 * This is THE fresh source of truth for the token-group vars. Checks must call
 * this at `run()` time rather than importing the committed
 * `token-group-vars.generated.ts` manifest: that manifest is a statically
 * imported module, frozen in the ESM cache when the check graph first loads —
 * which, in a build, is BEFORE codegen rewrites the file. Reading it would make
 * any token-var rename/addition need two builds (the first failing on stale
 * data). The committed file remains only a reviewable, in-sync-guarded snapshot.
 */
export function collectTokenGroupVars(
  root: string,
): Promise<Record<string, string[]>> {
  let cached = collectCache.get(root);
  if (!cached) {
    cached = collectTokenGroupVarsUncached(root).catch((err) => {
      collectCache.delete(root);
      throw err;
    });
    collectCache.set(root, cached);
  }
  return cached;
}

async function collectTokenGroupVarsUncached(
  root: string,
): Promise<Record<string, string[]>> {
  const tree = await buildBarrelFreeTree(root);
  registerBarrelStubs(root);

  const byGroup: Record<string, string[]> = {};
  for (const node of tree.byDir.values()) {
    const webIndex = join(node.dir, "web", "index.ts");
    if (!existsSync(webIndex)) continue;
    let mod: Record<string, unknown>;
    try {
      mod = await importBarrel(webIndex);
    } catch (err) {
      throw new Error(
        `Failed to import web barrel ${relative(root, webIndex)}: ${String(err)}`,
      );
    }
    const def = mod.default as
      | {
          contributions?: Array<
            Record<string, unknown> & { _slotId?: string }
          >;
        }
      | undefined;
    const contributions = def?.contributions;
    if (!contributions) continue;
    for (const c of contributions) {
      if (c._slotId !== TOKEN_GROUP_SLOT_ID) continue;
      const id = c.id;
      const descriptor = c.descriptor as
        | { vars?: Record<string, string> }
        | undefined;
      if (typeof id !== "string" || !descriptor?.vars) continue;
      const vars = Object.values(descriptor.vars).filter(
        (v): v is string => typeof v === "string",
      );
      byGroup[id] = [...new Set(vars)].sort((a, b) => a.localeCompare(b));
    }
  }

  return byGroup;
}

function renderManifest(byGroup: Record<string, string[]>): string {
  const lines: string[] = [];
  lines.push(MANIFEST_HEADER);
  lines.push("");
  lines.push(
    "export const TOKEN_GROUP_VARS: Record<string, readonly string[]> = {",
  );
  for (const groupId of Object.keys(byGroup).sort((a, b) => a.localeCompare(b))) {
    const vars = byGroup[groupId]!;
    const rendered = vars.map((v) => JSON.stringify(v)).join(", ");
    lines.push(`  ${JSON.stringify(groupId)}: [${rendered}],`);
  }
  lines.push("};");
  lines.push("");
  return lines.join("\n");
}

/** Path to the committed manifest file. */
export function tokenGroupVarsManifestPath(root: string): string {
  return join(root, MANIFEST_REL_PATH);
}

/** Render the manifest file contents in-memory (used by the in-sync check). */
export async function renderTokenGroupVarsManifest(
  root: string,
): Promise<string> {
  const byGroup = await collectTokenGroupVars(root);
  return renderManifest(byGroup);
}

/** Regenerate `token-group-vars.generated.ts` if it drifted. */
export async function generateTokenGroupVars(opts: {
  root: string;
}): Promise<void> {
  const next = await renderTokenGroupVarsManifest(opts.root);
  const file = tokenGroupVarsManifestPath(opts.root);
  const existing = existsSync(file) ? readFileSync(file, "utf8") : "";
  if (next !== existing) writeFileSync(file, next);
}
