import noPendingDataCollapse from "./no-pending-data-collapse";

export default {
  name: "live-state",
  rules: {
    "no-pending-data-collapse": noPendingDataCollapse,
  },
  ignores: {
    "no-pending-data-collapse": [
      // BURNDOWN — pre-existing collapse sites grandfathered when the rule
      // landed (2026-06-11). Migrate to <ResourceView>/matchResource/
      // combineResources (or DataView `loading`) and REMOVE the entry. Do NOT
      // add new entries; the rule must stay green by migrating, not exempting.
      "plugins/active-data/plugins/attempt/web/components/attempt-chip.tsx",
      "plugins/active-data/plugins/task-link/web/components/task-link-chip.tsx",
      "plugins/active-data/plugins/task/web/components/task-card.tsx",
      "plugins/agents/web/components/agent-avatar-title-prefix.tsx",
      "plugins/agents/web/components/agent-detail.tsx",
      "plugins/agents/web/components/agent-launches.tsx",
      "plugins/agents/web/components/agent-side-body.tsx",
      "plugins/agents/web/components/agent-status.tsx",
      "plugins/agents/web/components/expand-collapse-all-action.tsx",
      "plugins/agents/web/panes.tsx",
      "plugins/apps/plugins/deploy/plugins/servers/web/panes.tsx",
      "plugins/apps/plugins/pages/plugins/page-tree/web/components/delete-page-action.tsx",
      "plugins/apps/plugins/pages/plugins/page-tree/web/components/page-header.tsx",
      "plugins/apps/plugins/pages/plugins/page-tree/web/components/pages-sidebar.tsx",
      "plugins/apps/plugins/pages/plugins/page-tree/web/panes.tsx",
      "plugins/apps/plugins/sonata/plugins/library/web/panes.tsx",
      "plugins/apps/plugins/sonata/plugins/playback-history/web/hooks.ts",
      "plugins/apps/plugins/sonata/plugins/track-mixer/web/hooks.ts",
      "plugins/apps/plugins/story/plugins/marker/web/hooks.ts",
      "plugins/apps/plugins/story/plugins/render/web/components/story-render.tsx",
      "plugins/apps/plugins/story/plugins/shell/web/components/story-gallery.tsx",
      "plugins/apps/plugins/story/plugins/shell/web/components/story-header.tsx",
      "plugins/attempt-view/web/components/attempt-switch-button.tsx",
      "plugins/auth/plugins/google/plugins/setup-wizard/web/components/google-setup-pane.tsx",
      "plugins/build/plugins/build-fix/web/components/build-fix-section.tsx",
      "plugins/build/plugins/build-info/web/components/build-info.tsx",
      "plugins/build/web/components/build-button.tsx",
      "plugins/build/web/components/build-popover-content.tsx",
      "plugins/build/web/hooks/use-stale-frontend.ts",
      "plugins/conversations-recover/web/components/recovery-view.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/commits-graph/web/components/commits-chip.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/dependencies/web/components/dependencies-button.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/dependent-count/web/components/dependent-count-chip.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/drop-dependents/web/components/drop-dependents-button.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/event-counter/web/components/event-counter.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/message-toc/web/components/message-toc.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/agent/web/components/agent-report-pane.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/ask-user-question/web/components/answer-here-button.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/ask-user-question/web/components/ask-user-question-tool-view.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/workflow/web/components/workflow-node-pane.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/web/components/jsonl-pane.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/notes/web/internal/use-conversation-note.ts",
      "plugins/conversations/plugins/conversation-view/plugins/op-status/web/components/op-status-banner.tsx",
      "plugins/conversations/plugins/conversations-view/plugins/grouped/web/components/grouped-conversation-list.tsx",
      "plugins/conversations/plugins/summary/web/components/summarize-button.tsx",
      "plugins/conversations/plugins/summary/web/components/summary-pane.tsx",
      "plugins/debug/plugins/claude-cli-calls/web/components/calls-view.tsx",
      "plugins/debug/plugins/crashes/web/components/crashes-view.tsx",
      "plugins/debug/plugins/queue/web/components/queue-view.tsx",
      "plugins/fields/plugins/secret/plugins/config/web/components/secret-renderer.tsx",
      "plugins/floating-bar/web/internal/use-floating-bar-status.ts",
      "plugins/notifications/web/components/bell-button.tsx",
      "plugins/page/plugins/editor/web/components/page-options.tsx",
      "plugins/page/plugins/inline-page-link/web/components/page-link-inline-node.tsx",
      "plugins/page/plugins/page-link/web/components/page-link-block.tsx",
      "plugins/plugin-meta/plugins/plugin-health/web/components/health-section.tsx",
      "plugins/review/plugins/code-review/web/components/code-review-summary.tsx",
      "plugins/tasks/plugins/task-dependencies/web/components/task-dependencies.tsx",
      "plugins/tasks/plugins/task-dependencies/web/components/task-dependents.tsx",
      "plugins/tasks/plugins/task-description/web/components/task-description.tsx",
      "plugins/tasks/plugins/task-draft-form/web/components/task-draft-popover.tsx",
      "plugins/tasks/plugins/task-graph/web/components/task-graph.tsx",
      "plugins/tasks/plugins/task-list/plugins/tree/web/tasks-list.tsx",
      "plugins/tasks/plugins/task-list/web/components/expand-collapse-all-action.tsx",
    ],
  },
};
