import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

const CONFLICT_MARKER_RE = /^(<{7}|={7}|>{7}) /m;

/**
 * Every `plugins/**\/CLAUDE.md` still carrying a git conflict marker.
 *
 * These files mix hand-written prose with an `<!-- AUTOGENERATED -->` block, so
 * the `regen-claudemd` merge driver deliberately accepts a conflicted 3-way
 * result: normalize then rewrites the autogen block (erasing any conflict that
 * was confined to it). Whatever markers SURVIVE that rewrite are in prose — a
 * real conflict a human must resolve, never something regeneration can fix.
 */
export function findClaudeMdConflicts(root: string): string[] {
  const offenders: string[] = [];
  const walk = (dir: string) => {
    let entries: string[];
    try {
      entries = readdirSync(dir);
    } catch (err) {
      const code = (err as NodeJS.ErrnoException).code;
      if (code !== "ENOENT" && code !== "EACCES") throw err;
      return;
    }
    for (const entry of entries) {
      // A workspace's own node_modules holds symlinked copies of the whole
      // plugin tree; walking it would re-scan every CLAUDE.md once per plugin.
      if (entry === "node_modules") continue;
      const full = join(dir, entry);
      let st;
      try {
        st = statSync(full);
      } catch (err) {
        if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
        continue;
      }
      if (st.isDirectory()) {
        walk(full);
      } else if (entry === "CLAUDE.md") {
        if (CONFLICT_MARKER_RE.test(readFileSync(full, "utf8"))) offenders.push(full);
      }
    }
  };
  walk(join(root, "plugins"));
  return offenders;
}
