import { join } from "node:path";

/**
 * The part of the tooling plugin's `RepoFiles` this reads, spelled structurally
 * so this barrel does not depend on the tooling plugin.
 */
export interface ClaudeMdRepo {
  root: string;
  under(dir: string): readonly string[];
  /** Null when the path is not in the set. */
  read(path: string): Promise<string | null>;
}

const CONFLICT_MARKER_RE = /^(<{7}|={7}|>{7}) /m;

/**
 * Every `plugins/**\/CLAUDE.md` still carrying a git conflict marker.
 *
 * These files mix hand-written prose with an `<!-- AUTOGENERATED -->` block, so
 * the `regen-claudemd` merge driver deliberately accepts a conflicted 3-way
 * result: normalize then rewrites the autogen block (erasing any conflict that
 * was confined to it). Whatever markers SURVIVE that rewrite are in prose — a
 * real conflict a human must resolve, never something regeneration can fix.
 *
 * Takes the repo's file set rather than walking `plugins/` itself: inside a
 * check pass that is the run's shared `ctx.repo()`, and a blocking walk that
 * stat-ed every file in the tree held the check runner's one thread for 1.5–2.5 s.
 * Outside a check, pass `loadRepoFiles(root)`. Returns absolute paths.
 */
export async function findClaudeMdConflicts(
  repo: ClaudeMdRepo,
): Promise<string[]> {
  const files = repo
    .under("plugins")
    .filter((rel) => rel.endsWith("/CLAUDE.md"));
  const hits = await Promise.all(
    files.map(async (rel) => {
      const src = await repo.read(rel);
      return src !== null && CONFLICT_MARKER_RE.test(src) ? [rel] : [];
    }),
  );
  return hits.flat().map((rel) => join(repo.root, rel));
}
