import { useMemo } from "react";
import type { Annotation } from "@plugins/apps/plugins/sonata/plugins/score/core";
import { useSongDocument } from "./document";
import { useSongSetting } from "./loaded-song";
import { chordModeSetting } from "./score-settings";

/**
 * Availability gates over the loaded document's composed score, shared by the
 * Sonata section panels that only mean something for a chord-bearing song.
 * They live here — next to `useSongDocument()`, the content they read — rather
 * than being re-derived in each section, so "is this a chord song?" has one
 * definition. A document that is not `ready` has no annotations.
 *
 * Sections pass these straight to the slot's `useAvailable`.
 */

const NO_ANNOTATIONS: readonly Annotation[] = [];

/** The composed score's annotations — none until the document is `ready`. */
function useAnnotations(): readonly Annotation[] {
  const { content } = useSongDocument();
  return content.kind === "ready" ? content.score.annotations : NO_ANNOTATIONS;
}

/** At least one chord annotation, whatever produced it (authored or analyzed). */
export function useHasChords(): boolean {
  const annotations = useAnnotations();
  return useMemo(
    () => annotations.some((a) => a.type === "chord"),
    [annotations],
  );
}

/**
 * At least one AUTHORED chord annotation — i.e. a symbol source (chord grid,
 * Ultimate Guitar) is loaded, so the chord notes are generated by the document's
 * re-voicing step. A MIDI-only song fails this gate even when a chord *analyzer*
 * found chords.
 */
function useHasAuthoredChord(): boolean {
  const annotations = useAnnotations();
  return useMemo(
    () =>
      annotations.some((a) => a.type === "chord" && a.source === "authored"),
    [annotations],
  );
}

/**
 * At least one analyzer-DERIVED chord annotation — the song has note-only
 * regions a chord analyzer could label (a MIDI song, or the MIDI half of a mixed
 * song). This is what the chord-mode toggle has to work with: those are the
 * chords its second voicing pass turns into notes.
 */
export function useHasDerivedChord(): boolean {
  const annotations = useAnnotations();
  return useMemo(
    () => annotations.some((a) => a.type === "chord" && a.source === "derived"),
    [annotations],
  );
}

/**
 * The document's re-voicing step is generating chord notes for this song — so the
 * voicing / rhythm controls have something to act on. True for a symbol source
 * (authored chords), and for any chord-bearing song whose per-song chord mode is
 * on (the detected chords are then voiced too). The Voicing and Rhythm cards gate
 * on this, so flipping chord mode on a MIDI song brings them in unchanged.
 */
export function useHasVoicedChords(): boolean {
  const authored = useHasAuthoredChord();
  const anyChord = useHasChords();
  const chordMode = useSongSetting(chordModeSetting);
  // Pending (or failed) chord mode means the song's settings are not all
  // settled, so the document is not `ready` and has no chords to voice either
  // way.
  switch (chordMode.kind) {
    case "pending":
    case "failed":
      return false;
    case "settled":
      return authored || (chordMode.value && anyChord);
  }
}
