import type { PluginDefinition } from "@plugins/framework/plugins/web-sdk/core";
import {
  SonataDocument,
  useSongDocument,
} from "@plugins/apps/plugins/sonata/plugins/document/web";
import { Sonata } from "@plugins/apps/plugins/sonata/plugins/shell/web";
import { Library } from "@plugins/apps/plugins/sonata/plugins/library/web";
import { compile } from "./compile";
import { UltimateGuitarLoader } from "./loader";
import { UG_SOURCE_ID } from "@plugins/apps/plugins/sonata/plugins/sources/plugins/ultimate-guitar/plugins/tab/core";
import { hydrate } from "./hydrate";
import { ultimateGuitarCreateOption } from "./components/ug-create-option";
import { UltimateGuitarEditorSection } from "./components/ug-editor-section";
import { UltimateGuitarPersistObserver } from "./components/ug-persist-observer";
import { symbol } from "@plugins/ui/plugins/icons/core";

export default {
  description:
    "Player-side Ultimate Guitar source for Sonata: paste a UG tab URL, fetch its raw tab, and compile() the chord/lyric markup into a playable Score (lyric-proportional, bar-quantized timing synthesis → chord annotations, sections, lyrics, synthesized 4/4 tempo). Chord notes are generated by the shell's reactive re-voicing step from the chord annotations. Persists the loaded tab to a per-song side-table, hydrates it on open, and contributes the library 'Import from Ultimate Guitar' URL-paste affordance plus an in-player editor section.",
  contributions: [
    SonataDocument.Source({
      id: UG_SOURCE_ID,
      label: "Ultimate Guitar",
      icon: symbol("music-note"),
      LoaderComponent: UltimateGuitarLoader,
      compile,
    }),
    Library.Source({
      sourceId: UG_SOURCE_ID,
      hydrate,
      createOption: ultimateGuitarCreateOption,
    }),
    Sonata.Section({
      id: "ultimate-guitar-editor",
      label: "Ultimate Guitar",
      icon: symbol("music-note"),
      component: UltimateGuitarEditorSection,
      area: "editor",
      useAvailable: () =>
        useSongDocument().sourceRaw(UG_SOURCE_ID) !== undefined,
    }),
    Sonata.Effect({
      id: "ultimate-guitar-persist",
      component: UltimateGuitarPersistObserver,
    }),
  ],
} satisfies PluginDefinition;
