import noUncoupledHoverReveal from "./no-uncoupled-hover-reveal";

export default {
  name: "hover-reveal-safety",
  rules: {
    "no-uncoupled-hover-reveal": noUncoupledHoverReveal,
  },
  ignores: {
    "no-uncoupled-hover-reveal": [
      // Burndown allowlist — drain by migrating each onto hoverRevealTarget/hoverRevealGroup.
      "plugins/apps/web/components/app-tab-bar.tsx",
      "plugins/apps/plugins/surface/plugins/solo/web/solo-placement.tsx",
      "plugins/apps/plugins/pages/plugins/page-tree/web/components/page-header.tsx",
      "plugins/apps/plugins/pages/plugins/page-tree/web/components/pages-sidebar.tsx",
      "plugins/apps/plugins/pages/plugins/page-tree/web/components/page-cover.tsx",
      "plugins/page/plugins/editor/web/components/block-row.tsx",
      "plugins/page/plugins/bookmark/web/components/bookmark-block.tsx",
      "plugins/page/plugins/video/web/components/video-block.tsx",
      "plugins/page/plugins/file/web/components/file-block.tsx",
      "plugins/page/plugins/audio/web/components/audio-block.tsx",
      "plugins/page/plugins/image/web/components/image-block.tsx",
      "plugins/page/plugins/embed/web/components/embed-block.tsx",
      "plugins/page/plugins/code-block/web/components/code-block.tsx",
      "plugins/reorder/plugins/editor/web/internal/items.tsx",
      "plugins/tasks/plugins/attempt-view/web/components/attempt-pane.tsx",
      "plugins/tasks/plugins/task-draft-form/web/components/chain-connector.tsx",
      "plugins/tasks/plugins/task-description/web/components/description-view.tsx",
      "plugins/layouts/plugins/miller/web/components/resize-handle.tsx",
      "plugins/primitives/plugins/multi-select/web/internal/selection-checkbox.tsx",
      "plugins/primitives/plugins/tree/web/internal/tree-row-chrome.tsx",
      "plugins/primitives/plugins/text-editor/plugins/paste-images/web/components/attachment-thumbnail.tsx",
      "plugins/active-data/web/internal/active-data-inline-node.tsx",
      "plugins/conversations/plugins/conversations-view/web/components/conv-count-label.tsx",
      "plugins/conversations/plugins/conversations-view/plugins/grouped/web/components/group-box.tsx",
      "plugins/conversations/plugins/conversations-view/plugins/grouped/web/components/group-container.tsx",
      "plugins/conversations/plugins/conversations-view/plugins/queue/web/components/queue-view.tsx",
      "plugins/review/plugins/plugin-changes/plugins/file-changes/web/components/file-changes-section.tsx",
      "plugins/review/plugins/code-review/web/components/review-file-row.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/web/internal/event-action-context.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/unknown/web/components/unknown-row.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/attachment/web/components/generic-attachment-view.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/file-path/web/components/file-path.tsx",
      "plugins/apps/plugins/sonata/plugins/library/web/components/song-card.tsx",
      "plugins/primitives/plugins/launch/web/components/launch-control.tsx",
    ],
  },
};
