import { afterAll, describe, expect, test } from "bun:test";
import {
  existsSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "fs";
import { tmpdir } from "os";
import { join } from "path";
import { spawnCaptured } from "@plugins/infra/plugins/spawn/core";

// Drives the real driver through a real `git merge` in a throwaway repo: what
// matters is what GIT concludes from the driver (clean vs `UU`), which no
// direct invocation of the script can show.
const DRIVER = join(
  import.meta.dir,
  "..",
  "..",
  "..",
  "scripts",
  "regen-claudemd.sh",
);

const BEGIN =
  "<!-- AUTOGENERATED:BEGIN — do not edit; regenerated by `./singularity build` -->";
const END = "<!-- AUTOGENERATED:END -->";

function doc(prose: string[], block: string[]): string {
  return [...prose, "", BEGIN, "", ...block, END, ""].join("\n");
}

const repos: string[] = [];

async function git(dir: string, ...args: string[]) {
  const r = await spawnCaptured(["git", ...args], {
    cwd: dir,
    env: {
      ...process.env,
      GIT_CONFIG_GLOBAL: "/dev/null",
      GIT_CONFIG_NOSYSTEM: "1",
    },
    timeoutMs: 30_000,
  });
  return { code: r.exitCode, out: r.stdout + r.stderr };
}

async function ok(dir: string, ...args: string[]): Promise<string> {
  const r = await git(dir, ...args);
  if (r.code !== 0) throw new Error(`git ${args.join(" ")}: ${r.out}`);
  return r.out;
}

/** Commit `base`, then `ours` on main and `theirs` on a side branch; merge. */
async function merge(base: string, ours: string, theirs: string) {
  const dir = mkdtempSync(join(tmpdir(), "regen-claudemd-"));
  repos.push(dir);
  const file = join(dir, "plugins", "x", "CLAUDE.md");
  await ok(dir, "init", "-q");
  await ok(dir, "symbolic-ref", "HEAD", "refs/heads/main");
  await ok(dir, "config", "user.email", "test@example.com");
  await ok(dir, "config", "user.name", "Test");
  await ok(dir, "config", "commit.gpgsign", "false");
  await ok(
    dir,
    "config",
    "merge.regen-claudemd.driver",
    `${DRIVER} %O %A %B %P %S %X %Y`,
  );
  writeFileSync(
    join(dir, ".gitattributes"),
    "plugins/**/CLAUDE.md merge=regen-claudemd\n",
  );
  await ok(dir, "add", ".gitattributes");
  const put = async (content: string, msg: string) => {
    await Bun.write(file, content);
    await ok(dir, "add", "-A");
    await ok(dir, "commit", "-q", "-m", msg);
  };
  await put(base, "base");
  await ok(dir, "checkout", "-q", "-b", "side");
  await put(theirs, "theirs");
  await ok(dir, "checkout", "-q", "main");
  await put(ours, "ours");
  const result = await git(dir, "merge", "--no-edit", "side");
  const status = await ok(dir, "status", "--porcelain");
  return {
    code: result.code,
    status,
    merged: readFileSync(file, "utf8"),
    marker: existsSync(
      join(dir, ".git", "singularity-merge-markers", "generated"),
    ),
  };
}

afterAll(() => {
  for (const d of repos) rmSync(d, { recursive: true, force: true });
});

describe("regen-claudemd merge driver", () => {
  test("an autogen-only difference merges clean, keeping ours' block", async () => {
    const prose = ["# x", "", "Intro.", "", "Middle.", "", "Outro."];
    const r = await merge(
      doc(prose, ["- base"]),
      doc(["# x", "", "Intro, ours.", "", "Middle.", "", "Outro."], ["- ours"]),
      doc(
        ["# x", "", "Intro.", "", "Middle.", "", "Outro, theirs."],
        ["- theirs"],
      ),
    );
    expect(r.code).toBe(0);
    expect(r.status).toBe("");
    expect(r.merged).toBe(
      doc(
        ["# x", "", "Intro, ours.", "", "Middle.", "", "Outro, theirs."],
        ["- ours"],
      ),
    );
    expect(r.marker).toBe(true);
  });

  test("a prose conflict is reported to git as a conflict, with real labels", async () => {
    const r = await merge(
      doc(["# x", "", "Line."], ["- base"]),
      doc(["# x", "", "Line, ours."], ["- ours"]),
      doc(["# x", "", "Line, theirs."], ["- theirs"]),
    );
    expect(r.code).not.toBe(0);
    expect(r.status).toContain("UU plugins/x/CLAUDE.md");
    expect(r.merged).toContain(
      "<<<<<<< HEAD\nLine, ours.\n=======\nLine, theirs.\n>>>>>>> side\n",
    );
    expect(r.merged).not.toContain(".merge_file_");
    // The autogen block is outside the conflict and is ours'.
    expect(r.merged).toContain(`${BEGIN}\n\n- ours\n${END}\n`);
    expect(r.marker).toBe(true);
  });
});
