// DO NOT EDIT — autogenerated by `./singularity build`
// (see plugins/framework/plugins/tooling/plugins/codegen/core/plugin-registry-gen.ts).
//
// Adding/removing a plugin: create or delete the plugin's `<runtime>/index.ts`
// and rebuild — this file regenerates from the filesystem. The
// `plugins-registry-in-sync` check fails on drift.

export interface CollectedEntry {
  pluginPath: string;
  id: string;
  loader: () => Promise<{ default: unknown }>;
  dependsOn: string[];
}

export const lintEntries: CollectedEntry[] = [
  { pluginPath: "apps-core", id: "apps-core", loader: () => import("@plugins/apps-core/lint"), dependsOn: [] },
  { pluginPath: "config_v2/plugins/config-link", id: "config_v2.config-link", loader: () => import("@plugins/config_v2/plugins/config-link/lint"), dependsOn: [] },
  { pluginPath: "conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/collapsible-card", id: "conversations.conversation-view.jsonl-viewer.collapsible-card", loader: () => import("@plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/collapsible-card/lint"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/lint/plugins/bun-safety", id: "framework.tooling.lint.bun-safety", loader: () => import("@plugins/framework/plugins/tooling/plugins/lint/plugins/bun-safety/lint"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/lint/plugins/button-safety", id: "framework.tooling.lint.button-safety", loader: () => import("@plugins/framework/plugins/tooling/plugins/lint/plugins/button-safety/lint"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/lint/plugins/context-safety", id: "framework.tooling.lint.context-safety", loader: () => import("@plugins/framework/plugins/tooling/plugins/lint/plugins/context-safety/lint"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/lint/plugins/element-type-safety", id: "framework.tooling.lint.element-type-safety", loader: () => import("@plugins/framework/plugins/tooling/plugins/lint/plugins/element-type-safety/lint"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/lint/plugins/hover-reveal-safety", id: "framework.tooling.lint.hover-reveal-safety", loader: () => import("@plugins/framework/plugins/tooling/plugins/lint/plugins/hover-reveal-safety/lint"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/lint/plugins/icon-safety", id: "framework.tooling.lint.icon-safety", loader: () => import("@plugins/framework/plugins/tooling/plugins/lint/plugins/icon-safety/lint"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/lint/plugins/promise-safety", id: "framework.tooling.lint.promise-safety", loader: () => import("@plugins/framework/plugins/tooling/plugins/lint/plugins/promise-safety/lint"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/lint/plugins/reactive-server-io", id: "framework.tooling.lint.reactive-server-io", loader: () => import("@plugins/framework/plugins/tooling/plugins/lint/plugins/reactive-server-io/lint"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/lint/plugins/resize-observer-safety", id: "framework.tooling.lint.resize-observer-safety", loader: () => import("@plugins/framework/plugins/tooling/plugins/lint/plugins/resize-observer-safety/lint"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/lint/plugins/trigger-render-safety", id: "framework.tooling.lint.trigger-render-safety", loader: () => import("@plugins/framework/plugins/tooling/plugins/lint/plugins/trigger-render-safety/lint"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/lint/plugins/watcher-safety", id: "framework.tooling.lint.watcher-safety", loader: () => import("@plugins/framework/plugins/tooling/plugins/lint/plugins/watcher-safety/lint"), dependsOn: [] },
  { pluginPath: "framework/plugins/web-core", id: "framework.web-core", loader: () => import("@plugins/framework/plugins/web-core/lint"), dependsOn: [] },
  { pluginPath: "infra/plugins/endpoints", id: "infra.endpoints", loader: () => import("@plugins/infra/plugins/endpoints/lint"), dependsOn: [] },
  { pluginPath: "primitives/plugins/bar", id: "primitives.bar", loader: () => import("@plugins/primitives/plugins/bar/lint"), dependsOn: [] },
  { pluginPath: "primitives/plugins/css", id: "primitives.css", loader: () => import("@plugins/primitives/plugins/css/lint"), dependsOn: [] },
  { pluginPath: "primitives/plugins/css/plugins/badge", id: "primitives.css.badge", loader: () => import("@plugins/primitives/plugins/css/plugins/badge/lint"), dependsOn: [] },
  { pluginPath: "primitives/plugins/css/plugins/column", id: "primitives.css.column", loader: () => import("@plugins/primitives/plugins/css/plugins/column/lint"), dependsOn: [] },
  { pluginPath: "primitives/plugins/css/plugins/control-size", id: "primitives.css.control-size", loader: () => import("@plugins/primitives/plugins/css/plugins/control-size/lint"), dependsOn: [] },
  { pluginPath: "primitives/plugins/css/plugins/icon-auto", id: "primitives.css.icon-auto", loader: () => import("@plugins/primitives/plugins/css/plugins/icon-auto/lint"), dependsOn: [] },
  { pluginPath: "primitives/plugins/css/plugins/radius", id: "primitives.css.radius", loader: () => import("@plugins/primitives/plugins/css/plugins/radius/lint"), dependsOn: [] },
  { pluginPath: "primitives/plugins/css/plugins/row", id: "primitives.css.row", loader: () => import("@plugins/primitives/plugins/css/plugins/row/lint"), dependsOn: [] },
  { pluginPath: "primitives/plugins/css/plugins/spacing", id: "primitives.css.spacing", loader: () => import("@plugins/primitives/plugins/css/plugins/spacing/lint"), dependsOn: [] },
  { pluginPath: "primitives/plugins/css/plugins/surface", id: "primitives.css.surface", loader: () => import("@plugins/primitives/plugins/css/plugins/surface/lint"), dependsOn: [] },
  { pluginPath: "primitives/plugins/css/plugins/text", id: "primitives.css.text", loader: () => import("@plugins/primitives/plugins/css/plugins/text/lint"), dependsOn: [] },
  { pluginPath: "primitives/plugins/css/plugins/viewport-overlay", id: "primitives.css.viewport-overlay", loader: () => import("@plugins/primitives/plugins/css/plugins/viewport-overlay/lint"), dependsOn: [] },
  { pluginPath: "primitives/plugins/css/plugins/z-layers", id: "primitives.css.z-layers", loader: () => import("@plugins/primitives/plugins/css/plugins/z-layers/lint"), dependsOn: [] },
  { pluginPath: "primitives/plugins/data-table", id: "primitives.data-table", loader: () => import("@plugins/primitives/plugins/data-table/lint"), dependsOn: [] },
  { pluginPath: "primitives/plugins/icon-button", id: "primitives.icon-button", loader: () => import("@plugins/primitives/plugins/icon-button/lint"), dependsOn: [] },
  { pluginPath: "primitives/plugins/live-state", id: "primitives.live-state", loader: () => import("@plugins/primitives/plugins/live-state/lint"), dependsOn: [] },
  { pluginPath: "primitives/plugins/loading", id: "primitives.loading", loader: () => import("@plugins/primitives/plugins/loading/lint"), dependsOn: [] },
  { pluginPath: "primitives/plugins/log-channels", id: "primitives.log-channels", loader: () => import("@plugins/primitives/plugins/log-channels/lint"), dependsOn: [] },
  { pluginPath: "primitives/plugins/pane-toolbar", id: "primitives.pane-toolbar", loader: () => import("@plugins/primitives/plugins/pane-toolbar/lint"), dependsOn: [] },
  { pluginPath: "primitives/plugins/pane", id: "primitives.pane", loader: () => import("@plugins/primitives/plugins/pane/lint"), dependsOn: [] },
  { pluginPath: "primitives/plugins/scoped-store", id: "primitives.scoped-store", loader: () => import("@plugins/primitives/plugins/scoped-store/lint"), dependsOn: [] },
  { pluginPath: "ui/plugins/tokens/plugins/type-scale", id: "ui.tokens.type-scale", loader: () => import("@plugins/ui/plugins/tokens/plugins/type-scale/lint"), dependsOn: [] },
];
