import { customType } from "drizzle-orm/pg-core";
import { z } from "zod";
import { withWire } from "@plugins/database/plugins/sql-column/server";

// Binary column type for persisted Yjs doc state (`Y.encodeStateAsUpdate`).
// First `bytea` column type in the repo — mirrors the `rankText` customType
// precedent (`primitives/rank/core/internal/types.ts`). `bytea` is a single-word
// dataType, so no PostgreSQL domain indirection is needed.
//
// `Uint8Array` on both sides: `pg` returns `Buffer` (a `Uint8Array` subclass)
// and accepts binary params, and Yjs consumes/produces plain `Uint8Array` — so
// no conversion layer. Inert until a table declares a column with it (no
// migration is generated by the type alone).
const byteaType = customType<{ data: Uint8Array; driverData: Uint8Array }>({
  dataType() {
    return "bytea";
  },
});

/**
 * The single JS home for stored bytes → wire base64: the column's wire codec
 * below, and any response that ships a state by hand (editor-collab's doc-init),
 * so the two wire representations are identical by construction. Unfolded —
 * never Postgres' `encode(…, 'base64')`, which breaks lines every 76 chars.
 */
export function stateToBase64(state: Uint8Array): string {
  return Buffer.from(state).toString("base64");
}

/**
 * A `bytea` column. Its wire form is base64 (declared once here, so every bytea
 * column has it): a row schema projecting one types the field `string`, and
 * `serveCollection` encodes each row's bytes through {@link stateToBase64}.
 */
export function bytea<TName extends string>(name: TName) {
  return withWire(byteaType(name), {
    schema: z.string(),
    encode: stateToBase64,
  });
}
