import { defineRollup } from "@plugins/database/plugins/derived-tables/core";
import {
  _attempts,
  _conversations,
} from "@plugins/tasks/plugins/tasks-core/server";
import { _latest_conversation } from "./rollup-table";

// Trigger-maintained materialized rollup: the latest NON-system conversation per
// task. Source of truth = `listConversationsForDisplay` (kind <> 'system',
// newest-first, first-per-task). The `agent-launches` set joins it on each
// launch's task (`./agent-launch-rows.ts`). See
// research/2026-06-23-global-agent-launches-incremental-materialization.md.
//
// Every piece of SQL is generated by `defineRollup` (derived-tables) from this
// declaration. Two sources:
//
//  - `conversations`, whose `attempt_id` is mapped to the task through
//    `attempts` (the `via` hop);
//  - `attempts` itself, carrying `task_id` (update + delete). The hop is read
//    at trigger time, so on its own it cannot see a write that MOVES or
//    REMOVES the hop row: an attempt deleted (its conversations go by FK
//    cascade, and their DELETE resolves no task — the attempt row is already
//    gone), an attempt's `task_id` updated. The attempts source re-aggregates
//    the old and new task of every such row (W8; P8 v3 step 21). Its `reads`
//    are empty: `id` (the hop's `match`) is its primary key, so a re-keyed
//    row is seen unmatched on both sides of the diff. An INSERT cannot move
//    the aggregate (a new attempt has no conversation yet), so it is not an
//    op. This is also what a reader routed through the rollup needs (A35):
//    the attempts source's route carries `task_id`, so an attempt write
//    reaches the launches of both tasks.
//
// The `c.id DESC` tie-break makes equal-`created_at` ties deterministic.
export const taskLatestConversation = defineRollup({
  table: _latest_conversation,
  key: _latest_conversation.taskId,
  select: (scope) => `
    SELECT DISTINCT ON (a.task_id)
           a.task_id, c.id AS conversation_id, c.title, c.status, c.created_at
      FROM conversations c JOIN attempts a ON a.id = c.attempt_id
     WHERE c.kind <> 'system' AND ${scope("a.task_id")}
     ORDER BY a.task_id, c.created_at DESC, c.id DESC`,
  sources: [
    {
      table: _conversations,
      carry: _conversations.attemptId,
      via: { table: _attempts, match: _attempts.id, key: _attempts.taskId },
      reads: [
        _conversations.kind,
        _conversations.title,
        _conversations.status,
        _conversations.createdAt,
      ],
    },
    {
      table: _attempts,
      carry: _attempts.taskId,
      reads: [],
      ops: ["update", "delete"],
    },
  ],
});
