// ─── Regenerate server/internal/table-a.ts from Google's place-types page ────
//
//   ./singularity run plugins/page/plugins/place/plugins/google/scripts/fetch-table-a.ts
//
// Google files every place type it can return as a `primaryType` under one of
// the headings of "Table A" (Automotive, Food and Drink, Shopping, …), and lists
// the remaining types it may return in "Table B". Neither table is available
// from any API — only as this docs page — so the provider carries a copy.
//
// Run this when the `place-google-unknown-type` report fires (Google returned a
// type the copy lacks). It rewrites the copy wholesale; a heading the copy does
// not know yet fails here, loudly, and is added to `GOOGLE_HEADINGS`.

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { formatSource } from "@plugins/framework/plugins/tooling/plugins/format/core";
import { GOOGLE_HEADINGS } from "../server/internal/google-headings";

const SOURCE_URL =
  "https://developers.google.com/maps/documentation/places/web-service/place-types?hl=en";

/** The page between two anchors, failing when either is missing. */
function between(html: string, from: string, to: string): string {
  const start = html.indexOf(from);
  const end = html.indexOf(to, start);
  if (start === -1 || end === -1) {
    throw new Error(`place-types page: section ${from} … ${to} not found`);
  }
  return html.slice(start, end);
}

function codes(html: string): string[] {
  return [...html.matchAll(/<code[^>]*>([a-z0-9_]+)<\/code>/g)].map(
    (m) => m[1]!,
  );
}

const res = await fetch(SOURCE_URL);
if (!res.ok) throw new Error(`GET ${SOURCE_URL}: ${res.status}`);
const html = await res.text();

// Table A: one `<th id=…>Heading</th>` row per heading, its types below it.
const tableA = between(html, 'id="place-types"', 'id="table-b"');
const sections = [
  ...tableA.matchAll(/<th\s[^>]*\bid="[^"]+"[^>]*>([^<]+)<\/th>/g),
];
if (sections.length === 0)
  throw new Error("place-types page: no Table A headings");

const known = new Set<string>(GOOGLE_HEADINGS);
const rows: [string, string][] = [];
sections.forEach((m, i) => {
  const heading = m[1]!.trim();
  if (!known.has(heading)) {
    throw new Error(
      `Table A heading "${heading}" is new — add it to GOOGLE_HEADINGS (server/internal/google-headings.ts) and map it to a family.`,
    );
  }
  const body = tableA.slice(m.index, sections[i + 1]?.index ?? tableA.length);
  for (const type of codes(body)) rows.push([type, heading]);
});

// Every heading must be found, or one heading's types were silently filed under
// the heading before it (the page's markup is not uniform: `<th  id=…>`).
const found = new Set(sections.map((m) => m[1]!.trim()));
const missing = GOOGLE_HEADINGS.filter((h) => !found.has(h));
if (missing.length > 0) {
  throw new Error(
    `place-types page: headings not found: ${missing.join(", ")}`,
  );
}

const tableB = codes(between(html, 'id="table-b"', 'id="table-c"'));

const seen = new Set<string>();
for (const [type] of rows) {
  if (seen.has(type)) throw new Error(`Table A lists "${type}" twice`);
  seen.add(type);
}

const today = new Date().toISOString().slice(0, 10);
const file = join(import.meta.dir, "../server/internal/table-a.ts");
const content = `// GENERATED by plugins/page/plugins/place/plugins/google/scripts/fetch-table-a.ts
// from ${SOURCE_URL} on ${today}. Do not edit by hand: rerun the script.

import type { GoogleHeading } from "./google-headings";

/** Table A: every type Google may return as a \`primaryType\`, under its heading. */
export const GOOGLE_TABLE_A: Readonly<Record<string, GoogleHeading>> = {
${rows.map(([t, h]) => `  ${t}: ${JSON.stringify(h)},`).join("\n")}
};

/** Table B: further types Google may return, which belong to no heading. */
export const GOOGLE_TABLE_B: ReadonlySet<string> = new Set([
${tableB.map((t) => `  ${JSON.stringify(t)},`).join("\n")}
]);
`;
writeFileSync(file, await formatSource({ file, content }));
console.log(
  `wrote ${file}: ${rows.length} Table A types under ${sections.length} headings, ${tableB.length} Table B types`,
);
