// DO NOT EDIT — autogenerated by `./singularity build`
// (see plugins/framework/plugins/tooling/plugins/codegen/core/data-views-gen.ts).
//
// Every `defineDataView("<id>")` marker call found in any plugin's web/**
// source. The data-view primitive registers one config_v2 descriptor per id
// on both runtimes from this manifest. Each entry's `pluginId` is the
// *defining* plugin's id (its tree path), so the descriptor registers under
// `config/<pluginId>/<id>.jsonc` — the consuming plugin's tree.
//
// The `data-views-in-sync` check fails on drift.

export interface DataViewEntry {
  id: string;
  pluginId: string;
}

export const dataViews: DataViewEntry[] = [
  { id: "agent-launches", pluginId: "conversations.agents" },
  { id: "agents-list", pluginId: "conversations.agents" },
  { id: "all-conversations", pluginId: "conversations.all-conversations" },
  { id: "build.history", pluginId: "build" },
  { id: "code-explorer.file-tree", pluginId: "code-explorer" },
  { id: "config_v2.settings.nav", pluginId: "config_v2.settings" },
  { id: "conversations-sidebar-history", pluginId: "conversations.conversations-view.data-view.history" },
  { id: "conversations-sidebar-queue", pluginId: "conversations.conversations-view.data-view.queue" },
  { id: "debug.boot-profiles", pluginId: "debug.boot-profile" },
  { id: "debug.config-orphans", pluginId: "debug.config-orphans" },
  { id: "debug.profiling.runtime", pluginId: "debug.profiling.runtime" },
  { id: "debug.reports", pluginId: "debug.reports" },
  { id: "debug.slow-ops.cluster-aggregate", pluginId: "debug.slow-ops.cluster" },
  { id: "debug.slow-ops.cluster-timeline", pluginId: "debug.slow-ops.cluster" },
  { id: "debug.slow-ops.local", pluginId: "debug.slow-ops.pane" },
  { id: "debug.trace.events", pluginId: "debug.trace.pane" },
  { id: "deploy.servers", pluginId: "apps.deploy.servers" },
  { id: "home.apps", pluginId: "apps.home.app-cards" },
  { id: "mail-inbox", pluginId: "apps.mail.inbox" },
  { id: "page.links.backlinks", pluginId: "page.links" },
  { id: "pages-sidebar", pluginId: "apps.pages.page-tree" },
  { id: "prototypes.gallery", pluginId: "apps.prototypes.gallery" },
  { id: "sonata.library", pluginId: "apps.sonata.library" },
  { id: "story.gallery", pluginId: "apps.story.shell" },
  { id: "studio.compositions", pluginId: "apps.studio.compositions" },
  { id: "studio.compositions.closure-tree", pluginId: "apps.studio.compositions.closure-tree" },
  { id: "studio.explorer.tree", pluginId: "apps.studio.explorer" },
  { id: "studio.release.history", pluginId: "apps.studio.compositions.release" },
  { id: "task-deps-tree", pluginId: "tasks.task-deps-tree" },
  { id: "tasks-list", pluginId: "tasks.task-list" },
  { id: "tasks-subtree", pluginId: "tasks.task-list" },
  { id: "tweakcn.community-browser", pluginId: "ui.tweakcn.community-browser" },
  { id: "workflows.definitions", pluginId: "apps.workflows.definitions" },
  { id: "workflows.executions", pluginId: "apps.workflows.executions" },
];
