import { useState } from "react";
import {
  useEndpointMutation,
  getEndpointErrorMessage,
  EndpointError,
} from "@plugins/infra/plugins/endpoints/web";
import {
  Collapsible,
  CollapsibleTrigger,
  CollapsibleContent,
  CollapsibleChevron,
} from "@plugins/primitives/plugins/collapsible/web";
import { Button } from "@plugins/primitives/plugins/css/plugins/ui-kit/web";
import { Stack } from "@plugins/primitives/plugins/css/plugins/spacing/web";
import { Text } from "@plugins/primitives/plugins/css/plugins/text/web";
import { openDialog } from "@plugins/primitives/plugins/imperative-dialog/web";
import { StepDone, StepNote } from "@plugins/primitives/plugins/setup-steps/web";
import {
  generateSshKeypair,
  importSshPrivateKey,
  type Server,
} from "@plugins/apps/plugins/deploy/plugins/servers/web";
import { ReplaceKeyDialog } from "./replace-key-dialog";

/**
 * Duplicated from `servers/web/components/server-fields.tsx`, which is that
 * plugin's private tree and so not importable from here. A `Textarea` in
 * `css/ui-kit` is the structural fix; it is out of this change's scope.
 */
const textareaClass = "bg-input rounded-md border px-sm py-xs font-mono text-caption";

/**
 * Body of the "Create an SSH key" step: generate a managed keypair, or adopt
 * one the user already has.
 *
 * Deliberately does NOT print the fingerprint — it lives exactly once, in the
 * section header, which is the one region visible both collapsed and expanded.
 * Reprinting it here is the bug this whole change removes.
 */
export function GenerateKeyStep({ server }: { server: Server }) {
  const key = server.sshKey;
  const [privateKey, setPrivateKey] = useState("");

  const generate = useEndpointMutation(generateSshKeypair);
  // The paste path's whole value is its error copy (pasted `.pub`, passphrase),
  // so the 400 is rendered inline under the textarea rather than as a toast.
  const importKey = useEndpointMutation(importSshPrivateKey, {
    meta: { suppressError: true },
    onSuccess: () => setPrivateKey(""),
  });

  function replace() {
    if (!key) return;
    // Fire-and-forget: don't return the openDialog promise, or the button would
    // auto-pend for the dialog's whole open lifetime. `loading={…isPending}`
    // reflects the actual replace instead.
    void openDialog((close) => (
      <ReplaceKeyDialog
        fingerprint={key.fingerprint}
        onCancel={close}
        onConfirm={() =>
          generate
            .mutateAsync({ params: { id: server.id }, body: { replace: true } })
            .then(() => close())
            .catch((err: unknown) => {
              // Expected generate failure — the global toast already reported
              // it; keep the dialog open so the user can retry or cancel.
              if (err instanceof EndpointError) return;
              throw err;
            })
        }
      />
    ));
  }

  return (
    <Stack gap="sm" align="start">
      {key ? (
        <>
          {/* "ready", not "created": a key here may have been generated by us,
              pasted by the user, or derived from a pre-existing pasted key at
              boot. The row records no provenance, so claiming one would be the
              same unbacked assertion this section exists to have removed. */}
          <StepDone>
            Key ready — the private half stays on this machine and is never
            shown.
          </StepDone>
          <Button
            variant="outline"
            loading={generate.isPending}
            onClick={replace}
          >
            Replace key…
          </Button>
        </>
      ) : (
        <>
          <StepNote>
            Creates an ed25519 keypair on this machine. The private half is
            stored in the secrets store and never shown.
          </StepNote>
          <Button
            variant="default"
            loading={generate.isPending}
            onClick={() =>
              generate.mutate({ params: { id: server.id }, body: {} })
            }
          >
            Generate key
          </Button>
        </>
      )}

      {/* The trigger states an ACTION, never a status — a closed disclosure
          must never read as a claim about what key this server has. */}
      <Collapsible className="w-full rounded-lg border border-border/60">
        <CollapsibleTrigger className="gap-xs px-md py-sm text-caption text-muted-foreground hover:text-foreground">
          <CollapsibleChevron />
          <span className="font-medium">
            {key
              ? "Paste a different private key"
              : "Paste an existing private key instead"}
          </span>
        </CollapsibleTrigger>

        <CollapsibleContent className="border-t border-border/60 px-md py-md">
          <Stack gap="sm">
            <StepNote>
              An OpenSSH private key with no passphrase. Its public half is
              derived here, so the install command below works for it too.
              {key && " This destroys the key currently stored for this server."}
            </StepNote>
            <textarea
              className={textareaClass}
              rows={5}
              placeholder="-----BEGIN OPENSSH PRIVATE KEY-----"
              value={privateKey}
              onChange={(e) => setPrivateKey(e.target.value)}
            />
            {/* An explicit button, not blur-autosave: this is a validating,
                destructive write, and a blur-save has nowhere to report a 400. */}
            <Button
              variant="outline"
              className="w-fit"
              disabled={!privateKey.trim()}
              loading={importKey.isPending}
              onClick={() =>
                importKey.mutate({
                  params: { id: server.id },
                  body: { privateKey, replace: key !== null },
                })
              }
            >
              Use this key
            </Button>
            {importKey.isError && (
              <Text as="p" variant="caption" tone="destructive">
                {getEndpointErrorMessage(importKey.error)}
              </Text>
            )}
          </Stack>
        </CollapsibleContent>
      </Collapsible>
    </Stack>
  );
}
