import { customType } from "drizzle-orm/pg-core";

// Binary column type for persisted Yjs doc state (`Y.encodeStateAsUpdate`).
// First `bytea` column type in the repo — mirrors the `rankText` customType
// precedent (`primitives/rank/core/internal/types.ts`). `bytea` is a single-word
// dataType, so no PostgreSQL domain indirection is needed.
//
// `Uint8Array` on both sides: `pg` returns `Buffer` (a `Uint8Array` subclass)
// and accepts binary params, and Yjs consumes/produces plain `Uint8Array` — so
// no conversion layer. Inert until a table declares a column with it (no
// migration is generated by the type alone).
export const bytea = customType<{ data: Uint8Array; driverData: Uint8Array }>({
  dataType() {
    return "bytea";
  },
});
