// DO NOT EDIT — autogenerated by `./singularity build`
// (see tooling/src/plugin-registry-gen.ts).
//
// Adding/removing a plugin: create or delete the plugin's `<runtime>/index.ts`
// and rebuild — this file regenerates from the filesystem. The
// `plugins-registry-in-sync` check fails on drift.

import type { ServerPluginDefinition } from "./types";
import activeDataPlugin from "@plugins/active-data/server";
import agentsAutoLaunchTogglePlugin from "@plugins/agents/plugins/auto-launch/plugins/toggle/server";
import agentsPlugin from "@plugins/agents/server";
import appsDeployServersPlugin from "@plugins/apps/plugins/deploy/plugins/servers/server";
import appsForgeCatalogTablesColumnsPlugin from "@plugins/apps/plugins/forge/plugins/catalog/plugins/tables/plugins/columns/server";
import appsForgeCatalogTablesForeignKeysPlugin from "@plugins/apps/plugins/forge/plugins/catalog/plugins/tables/plugins/foreign-keys/server";
import appsForgeCatalogTablesIndexesPlugin from "@plugins/apps/plugins/forge/plugins/catalog/plugins/tables/plugins/indexes/server";
import appsForgeCatalogTablesRowCountPlugin from "@plugins/apps/plugins/forge/plugins/catalog/plugins/tables/plugins/row-count/server";
import appsForgeCatalogTablesSampleRowsPlugin from "@plugins/apps/plugins/forge/plugins/catalog/plugins/tables/plugins/sample-rows/server";
import authGooglePlugin from "@plugins/auth/plugins/google/server";
import authNotionPlugin from "@plugins/auth/plugins/notion/server";
import authPlugin from "@plugins/auth/server";
import backupGoogleDrivePlugin from "@plugins/backup/plugins/google-drive/server";
import backupLocalPlugin from "@plugins/backup/plugins/local/server";
import backupPlugin from "@plugins/backup/server";
import buildBuildProfilingPlugin from "@plugins/build/plugins/build-profiling/server";
import buildPlugin from "@plugins/build/server";
import codeExplorerFileResolvePlugin from "@plugins/code-explorer/plugins/file-resolve/server";
import codeExplorerPlugin from "@plugins/code-explorer/server";
import configPlugin from "@plugins/config/server";
import conversationsRecoverPlugin from "@plugins/conversations-recover/server";
import conversationsConversationCategoryPlugin from "@plugins/conversations/plugins/conversation-category/server";
import conversationsConversationProgressPlugin from "@plugins/conversations/plugins/conversation-progress/server";
import conversationsConversationViewAllowMonitorPlugin from "@plugins/conversations/plugins/conversation-view/plugins/allow-monitor/server";
import conversationsConversationViewCodeReviewPlugin from "@plugins/conversations/plugins/conversation-view/plugins/code/plugins/review/server";
import conversationsConversationViewCodePlugin from "@plugins/conversations/plugins/conversation-view/plugins/code/server";
import conversationsConversationViewCommitsGraphPlugin from "@plugins/conversations/plugins/conversation-view/plugins/commits-graph/server";
import conversationsConversationViewDropAndExitPlugin from "@plugins/conversations/plugins/conversation-view/plugins/drop-and-exit/server";
import conversationsConversationViewExitPlugin from "@plugins/conversations/plugins/conversation-view/plugins/exit/server";
import conversationsConversationViewHoldAndExitPlugin from "@plugins/conversations/plugins/conversation-view/plugins/hold-and-exit/server";
import conversationsConversationViewJsonlViewerPlugin from "@plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/server";
import conversationsConversationViewLaunchPromptsPlugin from "@plugins/conversations/plugins/conversation-view/plugins/launch-prompts/server";
import conversationsConversationViewNotesPlugin from "@plugins/conversations/plugins/conversation-view/plugins/notes/server";
import conversationsConversationViewPromptTemplatesPlugin from "@plugins/conversations/plugins/conversation-view/plugins/prompt-templates/server";
import conversationsConversationViewPushAndExitPlugin from "@plugins/conversations/plugins/conversation-view/plugins/push-and-exit/server";
import conversationsConversationViewQuickPromptsPlugin from "@plugins/conversations/plugins/conversation-view/plugins/quick-prompts/server";
import conversationsConversationViewResumePlugin from "@plugins/conversations/plugins/conversation-view/plugins/resume/server";
import conversationsConversationViewTurnSummaryPlugin from "@plugins/conversations/plugins/conversation-view/plugins/turn-summary/server";
import conversationsConversationsViewGroupedPlugin from "@plugins/conversations/plugins/conversations-view/plugins/grouped/server";
import conversationsConversationsViewQueuePlugin from "@plugins/conversations/plugins/conversations-view/plugins/queue/server";
import conversationsModelProviderPlugin from "@plugins/conversations/plugins/model-provider/server";
import conversationsRuntimeApiPlugin from "@plugins/conversations/plugins/runtime-api/server";
import conversationsRuntimeTmuxPlugin from "@plugins/conversations/plugins/runtime-tmux/server";
import conversationsSummaryPlugin from "@plugins/conversations/plugins/summary/server";
import conversationsTranscriptApiPlugin from "@plugins/conversations/plugins/transcript-api/server";
import conversationsTranscriptWatcherPlugin from "@plugins/conversations/plugins/transcript-watcher/server";
import conversationsPlugin from "@plugins/conversations/server";
import crashesPlugin from "@plugins/crashes/server";
import databaseAdminPlugin from "@plugins/database/plugins/admin/server";
import databaseEmbeddedPlugin from "@plugins/database/plugins/embedded/server";
import databaseMigrationsPlugin from "@plugins/database/plugins/migrations/server";
import databaseQueryPlugin from "@plugins/database/plugins/query/server";
import databasePlugin from "@plugins/database/server";
import debugBroadcastsPlugin from "@plugins/debug/plugins/broadcasts/server";
import debugLogsPlugin from "@plugins/debug/plugins/logs/server";
import debugMemoryPlugin from "@plugins/debug/plugins/memory/server";
import debugProfilingBootPlugin from "@plugins/debug/plugins/profiling/plugins/boot/server";
import debugProfilingBuildPlugin from "@plugins/debug/plugins/profiling/plugins/build/server";
import debugProfilingStatsPlugin from "@plugins/debug/plugins/profiling/plugins/stats/server";
import debugWorktreeCleanupPlugin from "@plugins/debug/plugins/worktree-cleanup/server";
import eventsTestPlugin from "@plugins/events-test/server";
import healthPlugin from "@plugins/health/server";
import improvePlugin from "@plugins/improve/server";
import infraAttachmentsPlugin from "@plugins/infra/plugins/attachments/server";
import infraClaudeCliPlugin from "@plugins/infra/plugins/claude-cli/server";
import infraEntityExtensionsPlugin from "@plugins/infra/plugins/entity-extensions/server";
import infraEventsPlugin from "@plugins/infra/plugins/events/server";
import infraGitWatcherPlugin from "@plugins/infra/plugins/git-watcher/server";
import infraJobsPlugin from "@plugins/infra/plugins/jobs/server";
import infraMcpPlugin from "@plugins/infra/plugins/mcp/server";
import infraPathsPlugin from "@plugins/infra/plugins/paths/server";
import infraSecretsPlugin from "@plugins/infra/plugins/secrets/server";
import infraWorktreePlugin from "@plugins/infra/plugins/worktree/server";
import notificationsPlugin from "@plugins/notifications/server";
import pluginMetaPluginHealthPlugin from "@plugins/plugin-meta/plugins/plugin-health/server";
import pluginMetaPluginViewPlugin from "@plugins/plugin-meta/plugins/plugin-view/server";
import primitivesAvatarPlugin from "@plugins/primitives/plugins/avatar/server";
import primitivesRankPlugin from "@plugins/primitives/plugins/rank/server";
import reorderGroupsPlugin from "@plugins/reorder/plugins/groups/server";
import reorderPlugin from "@plugins/reorder/server";
import screenshotPlugin from "@plugins/screenshot/server";
import statsCommitsPlugin from "@plugins/stats/plugins/commits/server";
import statsCostPlugin from "@plugins/stats/plugins/cost/server";
import statsTasksPlugin from "@plugins/stats/plugins/tasks/server";
import tasksCorePlugin from "@plugins/tasks-core/server";
import tasksAutoStartPlugin from "@plugins/tasks/plugins/auto-start/server";
import tasksTaskTitlePlugin from "@plugins/tasks/plugins/task-title/server";
import tasksPlugin from "@plugins/tasks/server";
import terminalPlugin from "@plugins/terminal/server";
import uiSegmentedProgressBarPlugin from "@plugins/ui/plugins/segmented-progress-bar/server";
import uiThemeEnginePlugin from "@plugins/ui/plugins/theme-engine/server";
import uiTokensChartPlugin from "@plugins/ui/plugins/tokens/plugins/chart/server";
import uiTokensColorAdjustPlugin from "@plugins/ui/plugins/tokens/plugins/color-adjust/server";
import uiTokensColorPalettePlugin from "@plugins/ui/plugins/tokens/plugins/color-palette/server";
import uiTokensShadowPlugin from "@plugins/ui/plugins/tokens/plugins/shadow/server";
import uiTokensShapePlugin from "@plugins/ui/plugins/tokens/plugins/shape/server";
import uiTokensSidebarPalettePlugin from "@plugins/ui/plugins/tokens/plugins/sidebar-palette/server";
import uiTokensTypographyPlugin from "@plugins/ui/plugins/tokens/plugins/typography/server";

(activeDataPlugin as ServerPluginDefinition).dependsOn = [databasePlugin, tasksCorePlugin];
(agentsAutoLaunchTogglePlugin as ServerPluginDefinition).dependsOn = [agentsPlugin, databasePlugin, infraEntityExtensionsPlugin];
(agentsPlugin as ServerPluginDefinition).dependsOn = [conversationsPlugin, databasePlugin, infraAttachmentsPlugin, primitivesAvatarPlugin, primitivesRankPlugin, tasksCorePlugin];
(appsForgeCatalogTablesColumnsPlugin as ServerPluginDefinition).dependsOn = [databasePlugin];
(appsForgeCatalogTablesForeignKeysPlugin as ServerPluginDefinition).dependsOn = [databasePlugin];
(appsForgeCatalogTablesIndexesPlugin as ServerPluginDefinition).dependsOn = [databasePlugin];
(appsForgeCatalogTablesRowCountPlugin as ServerPluginDefinition).dependsOn = [databasePlugin];
(appsForgeCatalogTablesSampleRowsPlugin as ServerPluginDefinition).dependsOn = [databasePlugin];
(authGooglePlugin as ServerPluginDefinition).dependsOn = [configPlugin];
(authNotionPlugin as ServerPluginDefinition).dependsOn = [configPlugin];
(backupGoogleDrivePlugin as ServerPluginDefinition).dependsOn = [authPlugin, backupPlugin, configPlugin];
(backupLocalPlugin as ServerPluginDefinition).dependsOn = [backupPlugin, configPlugin, infraPathsPlugin];
(backupPlugin as ServerPluginDefinition).dependsOn = [configPlugin, databaseAdminPlugin, databasePlugin, infraJobsPlugin, infraPathsPlugin];
(buildBuildProfilingPlugin as ServerPluginDefinition).dependsOn = [infraPathsPlugin];
(buildPlugin as ServerPluginDefinition).dependsOn = [configPlugin, databasePlugin, debugLogsPlugin, infraEventsPlugin, infraGitWatcherPlugin, infraJobsPlugin, infraPathsPlugin];
(codeExplorerFileResolvePlugin as ServerPluginDefinition).dependsOn = [codeExplorerPlugin, infraPathsPlugin];
(codeExplorerPlugin as ServerPluginDefinition).dependsOn = [infraPathsPlugin, infraWorktreePlugin, tasksCorePlugin];
(configPlugin as ServerPluginDefinition).dependsOn = [databasePlugin, infraPathsPlugin, infraSecretsPlugin];
(conversationsRecoverPlugin as ServerPluginDefinition).dependsOn = [conversationsPlugin, tasksCorePlugin];
(conversationsConversationCategoryPlugin as ServerPluginDefinition).dependsOn = [configPlugin, conversationsPlugin, databasePlugin, infraClaudeCliPlugin, infraEntityExtensionsPlugin, infraEventsPlugin, infraJobsPlugin, primitivesAvatarPlugin, tasksCorePlugin];
(conversationsConversationProgressPlugin as ServerPluginDefinition).dependsOn = [conversationsPlugin, databasePlugin, infraEntityExtensionsPlugin, infraEventsPlugin, infraJobsPlugin, infraPathsPlugin, tasksCorePlugin];
(conversationsConversationViewAllowMonitorPlugin as ServerPluginDefinition).dependsOn = [tasksCorePlugin];
(conversationsConversationViewCodeReviewPlugin as ServerPluginDefinition).dependsOn = [configPlugin, databasePlugin, primitivesRankPlugin];
(conversationsConversationViewCodePlugin as ServerPluginDefinition).dependsOn = [infraPathsPlugin, tasksCorePlugin];
(conversationsConversationViewCommitsGraphPlugin as ServerPluginDefinition).dependsOn = [infraPathsPlugin, tasksCorePlugin];
(conversationsConversationViewDropAndExitPlugin as ServerPluginDefinition).dependsOn = [conversationsPlugin, tasksCorePlugin];
(conversationsConversationViewExitPlugin as ServerPluginDefinition).dependsOn = [conversationsPlugin, tasksCorePlugin];
(conversationsConversationViewHoldAndExitPlugin as ServerPluginDefinition).dependsOn = [conversationsPlugin, tasksCorePlugin];
(conversationsConversationViewJsonlViewerPlugin as ServerPluginDefinition).dependsOn = [conversationsTranscriptWatcherPlugin, tasksCorePlugin];
(conversationsConversationViewLaunchPromptsPlugin as ServerPluginDefinition).dependsOn = [databasePlugin, infraAttachmentsPlugin, primitivesRankPlugin];
(conversationsConversationViewNotesPlugin as ServerPluginDefinition).dependsOn = [databasePlugin, infraEntityExtensionsPlugin, tasksCorePlugin];
(conversationsConversationViewPromptTemplatesPlugin as ServerPluginDefinition).dependsOn = [databasePlugin, infraAttachmentsPlugin, primitivesRankPlugin];
(conversationsConversationViewPushAndExitPlugin as ServerPluginDefinition).dependsOn = [conversationsPlugin, databasePlugin, infraJobsPlugin, infraMcpPlugin, tasksCorePlugin];
(conversationsConversationViewQuickPromptsPlugin as ServerPluginDefinition).dependsOn = [databasePlugin, infraAttachmentsPlugin, primitivesRankPlugin];
(conversationsConversationViewResumePlugin as ServerPluginDefinition).dependsOn = [conversationsPlugin, tasksCorePlugin];
(conversationsConversationViewTurnSummaryPlugin as ServerPluginDefinition).dependsOn = [configPlugin, conversationsPlugin, databasePlugin, infraClaudeCliPlugin, infraEntityExtensionsPlugin, infraEventsPlugin, infraJobsPlugin, tasksCorePlugin];
(conversationsConversationsViewGroupedPlugin as ServerPluginDefinition).dependsOn = [databasePlugin, primitivesRankPlugin, tasksCorePlugin];
(conversationsConversationsViewQueuePlugin as ServerPluginDefinition).dependsOn = [conversationsPlugin, databasePlugin, infraEntityExtensionsPlugin, infraEventsPlugin, infraJobsPlugin, primitivesRankPlugin, tasksCorePlugin];
(conversationsRuntimeApiPlugin as ServerPluginDefinition).dependsOn = [conversationsPlugin];
(conversationsRuntimeTmuxPlugin as ServerPluginDefinition).dependsOn = [conversationsPlugin, crashesPlugin, infraPathsPlugin];
(conversationsSummaryPlugin as ServerPluginDefinition).dependsOn = [conversationsPlugin, databasePlugin, infraMcpPlugin, tasksCorePlugin];
(conversationsTranscriptApiPlugin as ServerPluginDefinition).dependsOn = [conversationsTranscriptWatcherPlugin, tasksCorePlugin];
(conversationsTranscriptWatcherPlugin as ServerPluginDefinition).dependsOn = [infraPathsPlugin, tasksCorePlugin];
(conversationsPlugin as ServerPluginDefinition).dependsOn = [conversationsTranscriptWatcherPlugin, crashesPlugin, databaseAdminPlugin, databasePlugin, infraAttachmentsPlugin, infraEventsPlugin, infraJobsPlugin, infraPathsPlugin, infraWorktreePlugin, tasksAutoStartPlugin, tasksCorePlugin];
(crashesPlugin as ServerPluginDefinition).dependsOn = [databasePlugin, infraPathsPlugin, notificationsPlugin, tasksCorePlugin];
(databaseAdminPlugin as ServerPluginDefinition).dependsOn = [infraPathsPlugin];
(databaseQueryPlugin as ServerPluginDefinition).dependsOn = [databaseAdminPlugin, infraMcpPlugin, tasksCorePlugin];
(databasePlugin as ServerPluginDefinition).dependsOn = [databaseMigrationsPlugin];
(debugBroadcastsPlugin as ServerPluginDefinition).dependsOn = [infraWorktreePlugin];
(debugMemoryPlugin as ServerPluginDefinition).dependsOn = [infraPathsPlugin, infraWorktreePlugin];
(debugProfilingBuildPlugin as ServerPluginDefinition).dependsOn = [infraPathsPlugin];
(debugWorktreeCleanupPlugin as ServerPluginDefinition).dependsOn = [databaseAdminPlugin, infraPathsPlugin, infraWorktreePlugin, tasksCorePlugin];
(eventsTestPlugin as ServerPluginDefinition).dependsOn = [databasePlugin, infraEventsPlugin, infraJobsPlugin];
(improvePlugin as ServerPluginDefinition).dependsOn = [conversationsConversationsViewGroupedPlugin, conversationsPlugin, databasePlugin, infraEventsPlugin, infraJobsPlugin, tasksCorePlugin];
(infraAttachmentsPlugin as ServerPluginDefinition).dependsOn = [databasePlugin, infraPathsPlugin];
(infraClaudeCliPlugin as ServerPluginDefinition).dependsOn = [databasePlugin, infraPathsPlugin];
(infraEntityExtensionsPlugin as ServerPluginDefinition).dependsOn = [databasePlugin];
(infraEventsPlugin as ServerPluginDefinition).dependsOn = [databasePlugin, infraJobsPlugin];
(infraGitWatcherPlugin as ServerPluginDefinition).dependsOn = [infraEventsPlugin, infraPathsPlugin, infraWorktreePlugin];
(infraJobsPlugin as ServerPluginDefinition).dependsOn = [databaseAdminPlugin, databasePlugin];
(infraWorktreePlugin as ServerPluginDefinition).dependsOn = [infraPathsPlugin];
(notificationsPlugin as ServerPluginDefinition).dependsOn = [databasePlugin];
(pluginMetaPluginHealthPlugin as ServerPluginDefinition).dependsOn = [databasePlugin, infraEntityExtensionsPlugin, infraMcpPlugin, infraPathsPlugin, infraWorktreePlugin, tasksCorePlugin];
(pluginMetaPluginViewPlugin as ServerPluginDefinition).dependsOn = [infraPathsPlugin];
(primitivesRankPlugin as ServerPluginDefinition).dependsOn = [databasePlugin];
(reorderGroupsPlugin as ServerPluginDefinition).dependsOn = [databasePlugin, primitivesRankPlugin];
(reorderPlugin as ServerPluginDefinition).dependsOn = [databasePlugin];
(statsCommitsPlugin as ServerPluginDefinition).dependsOn = [configPlugin, conversationsConversationCategoryPlugin, databasePlugin, infraPathsPlugin, infraWorktreePlugin];
(statsCostPlugin as ServerPluginDefinition).dependsOn = [configPlugin, databasePlugin, infraPathsPlugin, infraWorktreePlugin, tasksCorePlugin];
(statsTasksPlugin as ServerPluginDefinition).dependsOn = [tasksCorePlugin];
(tasksCorePlugin as ServerPluginDefinition).dependsOn = [databasePlugin, infraAttachmentsPlugin, infraEventsPlugin, primitivesRankPlugin];
(tasksAutoStartPlugin as ServerPluginDefinition).dependsOn = [databasePlugin, infraEntityExtensionsPlugin, tasksCorePlugin];
(tasksTaskTitlePlugin as ServerPluginDefinition).dependsOn = [conversationsPlugin, infraClaudeCliPlugin, infraEventsPlugin, infraJobsPlugin, tasksCorePlugin];
(tasksPlugin as ServerPluginDefinition).dependsOn = [conversationsPlugin, infraAttachmentsPlugin, infraEventsPlugin, infraGitWatcherPlugin, infraJobsPlugin, infraMcpPlugin, infraPathsPlugin, infraWorktreePlugin, tasksAutoStartPlugin, tasksCorePlugin, tasksTaskTitlePlugin];
(terminalPlugin as ServerPluginDefinition).dependsOn = [infraPathsPlugin];
(uiSegmentedProgressBarPlugin as ServerPluginDefinition).dependsOn = [configPlugin];
(uiThemeEnginePlugin as ServerPluginDefinition).dependsOn = [configPlugin];
(uiTokensChartPlugin as ServerPluginDefinition).dependsOn = [configPlugin];
(uiTokensColorAdjustPlugin as ServerPluginDefinition).dependsOn = [configPlugin];
(uiTokensColorPalettePlugin as ServerPluginDefinition).dependsOn = [configPlugin];
(uiTokensShadowPlugin as ServerPluginDefinition).dependsOn = [configPlugin];
(uiTokensShapePlugin as ServerPluginDefinition).dependsOn = [configPlugin];
(uiTokensSidebarPalettePlugin as ServerPluginDefinition).dependsOn = [configPlugin];
(uiTokensTypographyPlugin as ServerPluginDefinition).dependsOn = [configPlugin];

export const plugins: ServerPluginDefinition[] = [
  activeDataPlugin,
  agentsAutoLaunchTogglePlugin,
  agentsPlugin,
  appsDeployServersPlugin,
  appsForgeCatalogTablesColumnsPlugin,
  appsForgeCatalogTablesForeignKeysPlugin,
  appsForgeCatalogTablesIndexesPlugin,
  appsForgeCatalogTablesRowCountPlugin,
  appsForgeCatalogTablesSampleRowsPlugin,
  authGooglePlugin,
  authNotionPlugin,
  authPlugin,
  backupGoogleDrivePlugin,
  backupLocalPlugin,
  backupPlugin,
  buildBuildProfilingPlugin,
  buildPlugin,
  codeExplorerFileResolvePlugin,
  codeExplorerPlugin,
  configPlugin,
  conversationsRecoverPlugin,
  conversationsConversationCategoryPlugin,
  conversationsConversationProgressPlugin,
  conversationsConversationViewAllowMonitorPlugin,
  conversationsConversationViewCodeReviewPlugin,
  conversationsConversationViewCodePlugin,
  conversationsConversationViewCommitsGraphPlugin,
  conversationsConversationViewDropAndExitPlugin,
  conversationsConversationViewExitPlugin,
  conversationsConversationViewHoldAndExitPlugin,
  conversationsConversationViewJsonlViewerPlugin,
  conversationsConversationViewLaunchPromptsPlugin,
  conversationsConversationViewNotesPlugin,
  conversationsConversationViewPromptTemplatesPlugin,
  conversationsConversationViewPushAndExitPlugin,
  conversationsConversationViewQuickPromptsPlugin,
  conversationsConversationViewResumePlugin,
  conversationsConversationViewTurnSummaryPlugin,
  conversationsConversationsViewGroupedPlugin,
  conversationsConversationsViewQueuePlugin,
  conversationsModelProviderPlugin,
  conversationsRuntimeApiPlugin,
  conversationsRuntimeTmuxPlugin,
  conversationsSummaryPlugin,
  conversationsTranscriptApiPlugin,
  conversationsTranscriptWatcherPlugin,
  conversationsPlugin,
  crashesPlugin,
  databaseAdminPlugin,
  databaseEmbeddedPlugin,
  databaseMigrationsPlugin,
  databaseQueryPlugin,
  databasePlugin,
  debugBroadcastsPlugin,
  debugLogsPlugin,
  debugMemoryPlugin,
  debugProfilingBootPlugin,
  debugProfilingBuildPlugin,
  debugProfilingStatsPlugin,
  debugWorktreeCleanupPlugin,
  eventsTestPlugin,
  healthPlugin,
  improvePlugin,
  infraAttachmentsPlugin,
  infraClaudeCliPlugin,
  infraEntityExtensionsPlugin,
  infraEventsPlugin,
  infraGitWatcherPlugin,
  infraJobsPlugin,
  infraMcpPlugin,
  infraPathsPlugin,
  infraSecretsPlugin,
  infraWorktreePlugin,
  notificationsPlugin,
  pluginMetaPluginHealthPlugin,
  pluginMetaPluginViewPlugin,
  primitivesAvatarPlugin,
  primitivesRankPlugin,
  reorderGroupsPlugin,
  reorderPlugin,
  screenshotPlugin,
  statsCommitsPlugin,
  statsCostPlugin,
  statsTasksPlugin,
  tasksCorePlugin,
  tasksAutoStartPlugin,
  tasksTaskTitlePlugin,
  tasksPlugin,
  terminalPlugin,
  uiSegmentedProgressBarPlugin,
  uiThemeEnginePlugin,
  uiTokensChartPlugin,
  uiTokensColorAdjustPlugin,
  uiTokensColorPalettePlugin,
  uiTokensShadowPlugin,
  uiTokensShapePlugin,
  uiTokensSidebarPalettePlugin,
  uiTokensTypographyPlugin,
];
