import { defineRollup } from "@plugins/database/plugins/derived-tables/core";
import { _pageContentEditedAt } from "./rollup-table";
import { _blocks } from "./tables";

// Trigger-maintained materialized rollup: per page P, the newest `updated_at`
// over P's live CONTENT — every live block whose nearest page is P
// (`page_id = P`), sub-page rows included. The page row's own `updated_at` is
// NOT rolled up (it is a column of the row the reader already holds), so a
// page's edit time is `greatest(row.updated_at, rollup.edited_at)` —
// `pageEditedAtSql` (`./page-rows.ts`), the one spelling.
//
// Every piece of SQL — the table, the maintain function and triggers, the
// reconcile — is generated by `defineRollup` (derived-tables) from this
// declaration. See plugins/database/plugins/derived-tables/CLAUDE.md.
//
// COMPLETENESS — why one source suffices: the row is keyed by the block's own
// `page_id` (no hop), so every write that can move a page's aggregate is a
// write to `page_blocks` itself. `page_id` is the carry, so a block moving
// between pages re-aggregates both; `updated_at` and `deleted_at` are the
// reads, so an edit, a trash and a restore re-aggregate. A write that moves
// none of them (a `doc_rank` re-mint, a fold toggle — `updated_at` is derived
// and ignores both) re-aggregates nothing.
//
// Cost per write: one aggregate over that page's blocks (`page_blocks_page_id_idx`)
// and a guarded upsert of one row — bounded by the page, never by the forest.
export const pageContentEditedAt = defineRollup({
  table: _pageContentEditedAt,
  key: _pageContentEditedAt.pageId,
  select: (scope) => `
    SELECT b.page_id, max(b.updated_at) AS edited_at
      FROM page_blocks b
     WHERE b.deleted_at IS NULL AND b.page_id IS NOT NULL
       AND ${scope("b.page_id")}
     GROUP BY b.page_id`,
  sources: [
    {
      table: _blocks,
      carry: _blocks.pageId,
      reads: [_blocks.updatedAt, _blocks.deletedAt],
    },
  ],
});
