export {
  MAIL_LABEL_TYPES,
  type MailLabelType,
  MAIL_OUTBOX_OP_TYPES,
  type MailOutboxOpType,
  MAIL_OUTBOX_STATUSES,
  type MailOutboxStatus,
  MAIL_SYNC_STATUSES,
  type MailSyncStatus,
} from "./internal/enums";
export type {
  MailAddress,
  MailAccount,
  MailSyncState,
  MailLabel,
  MailThread,
  MailMessage,
  MailMessageLabel,
  MailAttachment,
  MailDraft,
  MailOutboxItem,
} from "./internal/types";
export {
  MailAddressSchema,
  MailAccountSchema,
  MailSyncStateSchema,
  MailLabelSchema,
  MailThreadSchema,
  MailMessageSchema,
  MailMessageLabelSchema,
  MailAttachmentSchema,
  MailDraftSchema,
  MailOutboxItemSchema,
  mailAccountFields,
  mailSyncStateFields,
  mailLabelFields,
  mailThreadFields,
  mailMessageFields,
  mailMessageLabelFields,
  mailAttachmentFields,
  mailDraftFields,
  mailOutboxFields,
} from "./internal/fields";
