export {
  MAIL_LABEL_TYPES,
  type MailLabelType,
  MAIL_OUTBOX_OP_TYPES,
  type MailOutboxOpType,
  MAIL_OUTBOX_STATUSES,
  type MailOutboxStatus,
  MAIL_SYNC_STATUSES,
  type MailSyncStatus,
  MAIL_SYNC_ERROR_CODES,
  type MailSyncErrorCode,
  MAX_CONSECUTIVE_RESYNCS,
} from "./internal/enums";
export { mailSyncStateResource } from "./internal/resources";
export {
  type MailViewFilter,
  type MailSystemView,
  MAIL_SYSTEM_VIEWS,
  DEFAULT_MAIL_VIEW,
  labelViewId,
  mailViewLabelId,
  parseMailView,
} from "./internal/views";
export {
  type MailSyncPhase,
  type MailSyncView,
  deriveMailSyncView,
  MAIL_SYNC_REMEDIATION,
} from "./internal/sync-view";
export type {
  MailAddress,
  MailAccount,
  MailSyncState,
  MailLabel,
  MailThread,
  MailMessage,
  MailMessageLabel,
  MailAttachment,
  MailDraft,
  MailOutboxItem,
} from "./internal/types";
export {
  MailAddressSchema,
  MailAccountSchema,
  MailSyncStateSchema,
  MailLabelSchema,
  MailThreadSchema,
  MailMessageSchema,
  MailMessageLabelSchema,
  MailAttachmentSchema,
  MailDraftSchema,
  MailOutboxItemSchema,
  mailAccountFields,
  mailSyncStateFields,
  mailLabelFields,
  mailThreadFields,
  mailMessageFields,
  mailMessageLabelFields,
  mailAttachmentFields,
  mailDraftFields,
  mailOutboxFields,
} from "./internal/fields";
