// DO NOT EDIT — autogenerated by `./singularity build`
// (see plugins/framework/plugins/tooling/plugins/codegen/core/plugin-registry-gen.ts).
//
// Adding/removing a plugin: create or delete the plugin's `<runtime>/index.ts`
// and rebuild — this file regenerates from the filesystem. The
// `plugins-registry-in-sync` check fails on drift.

export interface CollectedEntry {
  pluginPath: string;
  id: string;
  loader: () => Promise<{ default: unknown }>;
  dependsOn: string[];
}

export const facetEntries: CollectedEntry[] = [
  { pluginPath: "plugin-meta/plugins/facets/plugins/commands", id: "plugin-meta.facets.commands", loader: () => import("@plugins/plugin-meta/plugins/facets/plugins/commands/facet"), dependsOn: [] },
  { pluginPath: "plugin-meta/plugins/facets/plugins/contributions", id: "plugin-meta.facets.contributions", loader: () => import("@plugins/plugin-meta/plugins/facets/plugins/contributions/facet"), dependsOn: ["plugin-meta/plugins/facets/plugins/slots"] },
  { pluginPath: "plugin-meta/plugins/facets/plugins/cross-refs", id: "plugin-meta.facets.cross-refs", loader: () => import("@plugins/plugin-meta/plugins/facets/plugins/cross-refs/facet"), dependsOn: [] },
  { pluginPath: "plugin-meta/plugins/facets/plugins/db-schema", id: "plugin-meta.facets.db-schema", loader: () => import("@plugins/plugin-meta/plugins/facets/plugins/db-schema/facet"), dependsOn: [] },
  { pluginPath: "plugin-meta/plugins/facets/plugins/exports", id: "plugin-meta.facets.exports", loader: () => import("@plugins/plugin-meta/plugins/facets/plugins/exports/facet"), dependsOn: ["plugin-meta/plugins/facets/plugins/cross-refs"] },
  { pluginPath: "plugin-meta/plugins/facets/plugins/registrations", id: "plugin-meta.facets.registrations", loader: () => import("@plugins/plugin-meta/plugins/facets/plugins/registrations/facet"), dependsOn: [] },
  { pluginPath: "plugin-meta/plugins/facets/plugins/resources", id: "plugin-meta.facets.resources", loader: () => import("@plugins/plugin-meta/plugins/facets/plugins/resources/facet"), dependsOn: [] },
  { pluginPath: "plugin-meta/plugins/facets/plugins/routes", id: "plugin-meta.facets.routes", loader: () => import("@plugins/plugin-meta/plugins/facets/plugins/routes/facet"), dependsOn: [] },
  { pluginPath: "plugin-meta/plugins/facets/plugins/slots", id: "plugin-meta.facets.slots", loader: () => import("@plugins/plugin-meta/plugins/facets/plugins/slots/facet"), dependsOn: [] },
  { pluginPath: "plugin-meta/plugins/facets/plugins/structure", id: "plugin-meta.facets.structure", loader: () => import("@plugins/plugin-meta/plugins/facets/plugins/structure/facet"), dependsOn: [] },
];
