import { and, eq } from "drizzle-orm";
import { db } from "@plugins/database/server";
import type { Registration } from "@server/types";
import { _jobSteps, _jobWaits } from "./tables";

// Globally-shared brand. `Symbol.for` returns the same Symbol across module
// reloads (HMR), worker pools, and even separate copies of @plugins/jobs that
// might exist if a worktree links it through different paths. That makes
// `isSuspendSignal()` robust where `instanceof SuspendSignal` would silently
// fail when the class identity differs between the throw and the catch.
const SUSPEND_BRAND: unique symbol = Symbol.for(
  "@plugins/jobs:SuspendSignal",
) as never;

// Suspend sentinel thrown by `ctx.waitFor` and `ctx.sleep`. Caught by the
// worker's dispatch — graphile sees the handler as succeeded, the job row is
// released, and the workflow resumes later via a new enqueue from
// `jobs.resume` (event-triggered) or a scheduled `jobs.resume` (timeout).
//
// The class itself is intentionally NOT exported from the plugin barrel —
// users should not need `instanceof SuspendSignal`. If a user MUST catch
// errors around a `ctx.*` call (e.g. wrapping in their own retry), they
// should re-throw via the exported `isSuspendSignal()` helper. Swallowing
// a SuspendSignal hangs the workflow; the brand-based detector is the
// supported escape hatch.
export class SuspendSignal extends Error {
  // Brand shows up on the instance for `isSuspendSignal()`. Read-only and
  // non-enumerable so it doesn't leak into JSON / log serialisation.
  readonly [SUSPEND_BRAND] = true;
  constructor(public readonly reason: "wait" | "sleep") {
    super(
      `[jobs] workflow suspended (${reason}) — must not be caught by user code`,
    );
    this.name = "SuspendSignal";
  }
}

// Brand check that survives module-identity differences. Use this in any
// intentional catch around `ctx.step` / `ctx.waitFor` / `ctx.sleep`:
//
//     try { await ctx.waitFor(...); }
//     catch (err) { if (isSuspendSignal(err)) throw err; ... }
export function isSuspendSignal(err: unknown): boolean {
  return (
    typeof err === "object" &&
    err !== null &&
    (err as Record<symbol, unknown>)[SUSPEND_BRAND] === true
  );
}

// An `EventSource` shape from @plugins/infra/plugins/events/server. We do not import the
// type here because the jobs plugin must not depend on events (events already
// depends on jobs; a reverse edge would close the cycle). Duck-typed via the
// `__kind === "event"` brand and the `def.name` / `filter` fields.
interface EventSourceLike {
  readonly __kind: "event";
  readonly def: { name: string };
  readonly filter: Record<string, unknown>;
}

// Options accepted by `ctx.waitFor`. `match` is reserved for post-v1 — the
// current implementation ignores it and the event filter is whatever `where`
// encodes via the events plugin's typed filter columns.
export interface WaitForOptions<T> {
  where?: Partial<T>;
  match?: (payload: T) => boolean;
  timeoutMs?: number;
  /** Override the autogenerated wait name (`wait:<eventName>:<seq>`). */
  name?: string;
}

// Hook registry for cross-plugin calls. The events plugin installs
// `registerTrigger` at module-load (see `plugins/events/server/internal/
// install-jobs-hooks.ts`). We avoid a static `import` from events to keep
// the plugin graph acyclic (events already imports jobs).
export interface DurableHooks {
  registerTrigger: (spec: {
    event: EventSourceLike;
    with: Record<string, unknown>;
    where: Record<string, unknown>;
    oneShot: boolean;
  }) => Promise<void>;
}

const hooks: Partial<DurableHooks> = {};

/**
 * Returns a {@link Registration} token. The actual `Object.assign(hooks, impl)`
 * fires when the framework invokes `.register()` during the plugin register
 * phase. Plugins list the result in their `register` array.
 */
export function UNSAFE_installDurableHooks(impl: DurableHooks): Registration {
  return {
    _kind: "durable-hooks",
    _factory: "UNSAFE_installDurableHooks",
    _doc: {},
    register() {
      Object.assign(hooks, impl);
    },
  };
}

// Internal identity passed to `makeDurableCtx` by the worker. Encapsulates
// the values ctx.step / ctx.waitFor need to key their durable rows and to
// re-enqueue the handler on resume.
export interface DurableCtxInit {
  jobId: string;
  attempt: number;
  workflowRunId: string;
  jobName: string;
  originalInput: unknown;
  /**
   * Enqueue a job for suspension bookkeeping. The worker passes the registry's
   * own enqueue so we don't recurse through the public barrel. Returns void —
   * we only need to know it scheduled.
   */
  scheduleResume: (
    payload: Record<string, unknown>,
    opts: { jobKey: string; runAt?: Date },
  ) => Promise<void>;
}

export interface DurableCtx {
  /**
   * Graphile job id. Stable across retries of a single failed job, distinct
   * per emit. Use as the dedup key in event-triggered handlers: non-oneShot
   * subscribers MUST dedup on `jobId` rather than the trigger row's UUID,
   * which is identical for every emit of the same trigger.
   */
  jobId: string;
  attempt: number;
  workflowRunId: string;
  step<R>(name: string, fn: () => Promise<R> | R): Promise<R>;
  waitFor<T extends Record<string, unknown>>(
    event: EventSourceLike & { __t?: T },
    opts?: WaitForOptions<T>,
  ): Promise<T | null>;
  sleep(ms: number): Promise<void>;
}

// Reserved keys inserted into the `jobsResumeJob` payload via a trigger's
// `with` clause (or a scheduled enqueue for timeouts). Kept together so the
// resume handler can discriminate them from the event payload's own keys
// (which arrive via the events dispatcher's merge).
export const RESUME_KEYS = {
  workflowRunId: "__resume_workflowRunId",
  waitName: "__resume_waitName",
  jobName: "__resume_jobName",
  input: "__resume_input",
  timeout: "__resume_timeout",
} as const;

export function makeDurableCtx(init: DurableCtxInit): DurableCtx {
  // Per-invocation counters: wait-seq resets every handler entry so the Nth
  // `ctx.waitFor(E)` call on replay reuses the same name it had on the first
  // run. Branching handlers should pass `opts.name` to stay stable.
  const seqByEvent = new Map<string, number>();

  const nextWaitName = (eventName: string, override?: string): string => {
    if (override) return override;
    const n = seqByEvent.get(eventName) ?? 0;
    seqByEvent.set(eventName, n + 1);
    return `wait:${eventName}:${n}`;
  };

  return {
    jobId: init.jobId,
    attempt: init.attempt,
    workflowRunId: init.workflowRunId,

    async step<R>(name: string, fn: () => Promise<R> | R): Promise<R> {
      const existing = await db
        .select()
        .from(_jobSteps)
        .where(
          and(
            eq(_jobSteps.workflowRunId, init.workflowRunId),
            eq(_jobSteps.stepName, name),
          ),
        )
        .limit(1);
      const row = existing[0];
      // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition -- runtime guard, no noUncheckedIndexedAccess
      if (row) {
        if (row.errorMessage) {
          throw new Error(`[jobs.step "${name}"] ${row.errorMessage}`);
        }
        return (row.resultJson?.v ?? undefined) as R;
      }
      let result: R;
      try {
        result = await fn();
      } catch (err) {
        if (isSuspendSignal(err)) throw err;
        const msg = err instanceof Error ? err.message : String(err);
        await db
          .insert(_jobSteps)
          .values({
            workflowRunId: init.workflowRunId,
            stepName: name,
            errorMessage: msg,
          })
          .onConflictDoNothing();
        throw err;
      }
      await db
        .insert(_jobSteps)
        .values({
          workflowRunId: init.workflowRunId,
          stepName: name,
          // Wrap in `{ v }` so the jsonb round-trips `null` / `undefined`
          // without collapsing into the top-level null the column stores for
          // "no recorded result".
          resultJson: { v: result === undefined ? null : (result as unknown) },
        })
        .onConflictDoNothing();
      return result;
    },

    async waitFor<T extends Record<string, unknown>>(
      event: EventSourceLike & { __t?: T },
      opts: WaitForOptions<T> = {},
    ): Promise<T | null> {
      const eventName = event.def.name;
      const waitName = nextWaitName(eventName, opts.name);

      const existing = await db
        .select()
        .from(_jobWaits)
        .where(
          and(
            eq(_jobWaits.workflowRunId, init.workflowRunId),
            eq(_jobWaits.waitName, waitName),
          ),
        )
        .limit(1);
      const row = existing[0];
      // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition -- runtime guard, no noUncheckedIndexedAccess
      if (row) {
        if (row.status === "resolved") {
          return (row.payloadJson ?? null) as T | null;
        }
        if (row.status === "timed_out") return null;
        // `status === "pending"`: a rare replay-while-still-pending case
        // (e.g. the handler was resumed twice by concurrent forces). The
        // trigger is still armed from the first suspend, so just suspend
        // again without re-registering.
        throw new SuspendSignal("wait");
      }

      // First time reaching this wait. Record a pending row, register the
      // event trigger, schedule the timeout, then suspend.
      await db
        .insert(_jobWaits)
        .values({
          workflowRunId: init.workflowRunId,
          waitName,
          status: "pending",
        })
        .onConflictDoNothing();

      if (!hooks.registerTrigger) {
        throw new Error(
          "[jobs] ctx.waitFor called but events plugin hooks are not installed. " +
            "Import @plugins/infra/plugins/events/server somewhere (its side-effect wires this up).",
        );
      }

      const mergedFilter: Record<string, unknown> = {
        // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition -- runtime guard; event.filter may be undefined at runtime
        ...(event.filter ?? {}),
        ...(opts.where ?? {}),
      };

      await hooks.registerTrigger({
        event,
        with: {
          [RESUME_KEYS.workflowRunId]: init.workflowRunId,
          [RESUME_KEYS.waitName]: waitName,
          [RESUME_KEYS.jobName]: init.jobName,
          [RESUME_KEYS.input]: init.originalInput as Record<string, unknown>,
        },
        where: mergedFilter,
        oneShot: true,
      });

      if (opts.timeoutMs && opts.timeoutMs > 0) {
        await init.scheduleResume(
          {
            [RESUME_KEYS.workflowRunId]: init.workflowRunId,
            [RESUME_KEYS.waitName]: waitName,
            [RESUME_KEYS.jobName]: init.jobName,
            [RESUME_KEYS.input]: init.originalInput,
            [RESUME_KEYS.timeout]: true,
          },
          {
            jobKey: `jobs.resume.timeout:${init.workflowRunId}:${waitName}`,
            runAt: new Date(Date.now() + opts.timeoutMs),
          },
        );
      }

      throw new SuspendSignal("wait");
    },

    async sleep(ms: number): Promise<void> {
      const waitName = nextWaitName("__sleep");
      const existing = await db
        .select()
        .from(_jobWaits)
        .where(
          and(
            eq(_jobWaits.workflowRunId, init.workflowRunId),
            eq(_jobWaits.waitName, waitName),
          ),
        )
        .limit(1);
      const row = existing[0];
      // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition -- runtime guard, no noUncheckedIndexedAccess
      if (row) {
        if (row.status === "resolved" || row.status === "timed_out") return;
        throw new SuspendSignal("sleep");
      }

      await db
        .insert(_jobWaits)
        .values({
          workflowRunId: init.workflowRunId,
          waitName,
          status: "pending",
        })
        .onConflictDoNothing();

      await init.scheduleResume(
        {
          [RESUME_KEYS.workflowRunId]: init.workflowRunId,
          [RESUME_KEYS.waitName]: waitName,
          [RESUME_KEYS.jobName]: init.jobName,
          [RESUME_KEYS.input]: init.originalInput,
          [RESUME_KEYS.timeout]: true,
        },
        {
          jobKey: `jobs.resume.sleep:${init.workflowRunId}:${waitName}`,
          runAt: new Date(Date.now() + Math.max(0, ms)),
        },
      );

      throw new SuspendSignal("sleep");
    },
  };
}
