// DO NOT EDIT — autogenerated by `./singularity build`
// (see plugins/framework/plugins/tooling/plugins/codegen/core/plugin-registry-gen.ts).
//
// Adding/removing a plugin: create or delete the plugin's `<runtime>/index.ts`
// and rebuild — this file regenerates from the filesystem. The
// `plugins-registry-in-sync` check fails on drift.

export interface CollectedEntry {
  pluginPath: string;
  id: string;
  loader: () => Promise<{ default: unknown }>;
  dependsOn: string[];
}

export const dataDirsEntries: CollectedEntry[] = [
  { pluginPath: "apps-core/plugins/surface/plugins/floating/plugins/wallpaper", id: "apps-core.surface.floating.wallpaper", loader: () => import("@plugins/apps-core/plugins/surface/plugins/floating/plugins/wallpaper/data-dirs"), dependsOn: [] },
  { pluginPath: "apps/plugins/prototypes/plugins/files", id: "apps.prototypes.files", loader: () => import("@plugins/apps/plugins/prototypes/plugins/files/data-dirs"), dependsOn: [] },
  { pluginPath: "apps/plugins/prototypes/plugins/thumbnails", id: "apps.prototypes.thumbnails", loader: () => import("@plugins/apps/plugins/prototypes/plugins/thumbnails/data-dirs"), dependsOn: [] },
  { pluginPath: "apps/plugins/sonata/plugins/sources/plugins/midi/plugins/folders", id: "apps.sonata.sources.midi.folders", loader: () => import("@plugins/apps/plugins/sonata/plugins/sources/plugins/midi/plugins/folders/data-dirs"), dependsOn: [] },
  { pluginPath: "config_v2", id: "config_v2", loader: () => import("@plugins/config_v2/data-dirs"), dependsOn: [] },
  { pluginPath: "database", id: "database", loader: () => import("@plugins/database/data-dirs"), dependsOn: [] },
  { pluginPath: "database/plugins/embedded", id: "database.embedded", loader: () => import("@plugins/database/plugins/embedded/data-dirs"), dependsOn: [] },
  { pluginPath: "database/plugins/zero/plugins/cache-service", id: "database.zero.cache-service", loader: () => import("@plugins/database/plugins/zero/plugins/cache-service/data-dirs"), dependsOn: [] },
  { pluginPath: "debug", id: "debug", loader: () => import("@plugins/debug/data-dirs"), dependsOn: [] },
  { pluginPath: "debug/plugins/profiling/plugins/op-log", id: "debug.profiling.op-log", loader: () => import("@plugins/debug/plugins/profiling/plugins/op-log/data-dirs"), dependsOn: [] },
  { pluginPath: "framework/plugins/cli", id: "framework.cli", loader: () => import("@plugins/framework/plugins/cli/data-dirs"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks", id: "framework.tooling.checks", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/data-dirs"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/type-check", id: "framework.tooling.checks.type-check", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/type-check/data-dirs"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/web-artifacts", id: "framework.tooling.web-artifacts", loader: () => import("@plugins/framework/plugins/tooling/plugins/web-artifacts/data-dirs"), dependsOn: [] },
  { pluginPath: "infra/plugins/asset-mirror", id: "infra.asset-mirror", loader: () => import("@plugins/infra/plugins/asset-mirror/data-dirs"), dependsOn: [] },
  { pluginPath: "infra/plugins/attachments", id: "infra.attachments", loader: () => import("@plugins/infra/plugins/attachments/data-dirs"), dependsOn: [] },
  { pluginPath: "infra/plugins/host/plugins/duress/plugins/latch", id: "infra.host.duress.latch", loader: () => import("@plugins/infra/plugins/host/plugins/duress/plugins/latch/data-dirs"), dependsOn: [] },
  { pluginPath: "infra/plugins/host/plugins/host-admission", id: "infra.host.host-admission", loader: () => import("@plugins/infra/plugins/host/plugins/host-admission/data-dirs"), dependsOn: [] },
  { pluginPath: "infra/plugins/jobs", id: "infra.jobs", loader: () => import("@plugins/infra/plugins/jobs/data-dirs"), dependsOn: [] },
  { pluginPath: "infra/plugins/launcher", id: "infra.launcher", loader: () => import("@plugins/infra/plugins/launcher/data-dirs"), dependsOn: [] },
  { pluginPath: "infra/plugins/secrets", id: "infra.secrets", loader: () => import("@plugins/infra/plugins/secrets/data-dirs"), dependsOn: [] },
  { pluginPath: "packages/plugins/signal-origin", id: "packages.signal-origin", loader: () => import("@plugins/packages/plugins/signal-origin/data-dirs"), dependsOn: [] },
  { pluginPath: "packages/plugins/signal-origin/plugins/sink", id: "packages.signal-origin.sink", loader: () => import("@plugins/packages/plugins/signal-origin/plugins/sink/data-dirs"), dependsOn: [] },
  { pluginPath: "primitives/plugins/css/plugins/layout-harness", id: "primitives.css.layout-harness", loader: () => import("@plugins/primitives/plugins/css/plugins/layout-harness/data-dirs"), dependsOn: [] },
  { pluginPath: "release/plugins/bundles", id: "release.bundles", loader: () => import("@plugins/release/plugins/bundles/data-dirs"), dependsOn: [] },
  { pluginPath: "reports", id: "reports", loader: () => import("@plugins/reports/data-dirs"), dependsOn: [] },
  { pluginPath: "stats/plugins/cost", id: "stats.cost", loader: () => import("@plugins/stats/plugins/cost/data-dirs"), dependsOn: [] },
];
