#!/usr/bin/env bun
/**
 * Generates icon-svg-map.generated.ts — a static Record<string, SvgNode[]>
 * covering all Material Design icons + curated aliases. Run manually when
 * react-icons version or icon-metadata.json changes.
 *
 * Usage: bun run plugins/primitives/plugins/avatar/server/internal/gen-icon-svg-map.ts
 */
import { createHash } from "crypto";
import { readFileSync, writeFileSync } from "fs";
import { dirname, join, resolve } from "path";

const HERE = dirname(new URL(import.meta.url).pathname);
const WEB_INTERNAL = resolve(HERE, "../../web/internal");
const METADATA_PATH = join(WEB_INTERNAL, "icon-metadata.json");
const OUTPUT_PATH = join(HERE, "icon-svg-map.generated.ts");

interface SvgNode {
  tag: string;
  attr: Record<string, string>;
  child: SvgNode[];
}

function extractChildren(children: unknown): SvgNode[] {
  if (!children) return [];
  const arr = Array.isArray(children) ? children : [children];
  return arr
    .filter((c: unknown): c is { type: string; props: Record<string, unknown> } =>
      typeof c === "object" && c !== null && "props" in c,
    )
    .filter((c) => !(c.props.fill === "none" && typeof c.props.d === "string" && (c.props.d as string).startsWith("M0 0")))
    .map((c) => ({
      tag: c.type,
      attr: Object.fromEntries(
        Object.entries(c.props).filter(([k]) => k !== "children"),
      ) as Record<string, string>,
      child: extractChildren(c.props.children),
    }));
}

function mdNameToReactKey(mdName: string): string {
  return "Md" + mdName.split("_").map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join("");
}

function computeInputsHash(metadataContent: string, reactIconsVersion: string): string {
  const h = createHash("sha256");
  h.update(metadataContent);
  h.update(reactIconsVersion);
  return h.digest("hex").slice(0, 16);
}

async function main() {
  const metadataContent = readFileSync(METADATA_PATH, "utf-8");
  const metadata = JSON.parse(metadataContent) as Record<string, { category: string; tags: string[] }>;

  const pkgPath = require.resolve("react-icons/package.json");
  const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
  const reactIconsVersion: string = pkg.version;

  const mdModule = (await import("react-icons/md")) as Record<string, unknown>;

  const map: Record<string, SvgNode[]> = {};
  let count = 0;

  for (const mdName of Object.keys(metadata)) {
    const reactKey = mdNameToReactKey(mdName);
    const Icon = mdModule[reactKey] as ((props: Record<string, never>) => { props: { children: unknown } }) | undefined;
    if (!Icon) continue;
    const el = Icon({});
    const nodes = extractChildren(el.props.children);
    if (nodes.length > 0) {
      map[mdName] = nodes;
      count++;
    }
  }

  const inputsHash = computeInputsHash(metadataContent, reactIconsVersion);

  const lines: string[] = [
    `// Auto-generated by gen-icon-svg-map.ts — do not edit manually`,
    `// @inputs-hash ${inputsHash}`,
    ``,
    `interface SvgNode { tag: string; attr: Record<string, string>; child: SvgNode[] }`,
    ``,
    `export const ICON_SVG_MAP: Record<string, SvgNode[]> = ${JSON.stringify(map)};`,
    ``,
  ];

  writeFileSync(OUTPUT_PATH, lines.join("\n"));
  console.log(`Generated ${OUTPUT_PATH} — ${count} icons, hash=${inputsHash}`);
}

void main();
