// DO NOT EDIT — autogenerated by `./singularity build`
// (see plugins/framework/plugins/tooling/plugins/codegen/core/plugin-registry-gen.ts).
//
// Adding/removing a plugin: create or delete the plugin's `<runtime>/index.ts`
// and rebuild — this file regenerates from the filesystem. The
// `plugins-registry-in-sync` check fails on drift.

export interface CollectedEntry {
  pluginPath: string;
  id: string;
  loader: () => Promise<{ default: unknown }>;
  dependsOn: string[];
}

export const provisionEntries: CollectedEntry[] = [
  { pluginPath: "database/plugins/zero/plugins/cache-service", id: "database.zero.cache-service", loader: () => import("@plugins/database/plugins/zero/plugins/cache-service/provision"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/e2e-harness", id: "framework.tooling.e2e-harness", loader: () => import("@plugins/framework/plugins/tooling/plugins/e2e-harness/provision"), dependsOn: [] },
];
