// DO NOT EDIT — autogenerated by `./singularity build`
// (see plugins/framework/plugins/tooling/plugins/codegen/core/plugin-registry-gen.ts).
//
// Adding/removing a plugin: create or delete the plugin's `<runtime>/index.ts`
// and rebuild — this file regenerates from the filesystem. The
// `plugins-registry-in-sync` check fails on drift.

export interface CollectedEntry {
  pluginPath: string;
  id: string;
  loader: () => Promise<{ default: unknown }>;
  dependsOn: string[];
}

export const checkEntries: CollectedEntry[] = [
  { pluginPath: "apps/plugins/agent-manager/plugins/welcome", id: "apps.agent-manager.welcome", loader: () => import("@plugins/apps/plugins/agent-manager/plugins/welcome/check"), dependsOn: [] },
  { pluginPath: "config_v2", id: "config_v2", loader: () => import("@plugins/config_v2/check"), dependsOn: [] },
  { pluginPath: "conversations/plugins/model-provider", id: "conversations.model-provider", loader: () => import("@plugins/conversations/plugins/model-provider/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/boundaries", id: "framework.tooling.boundaries", loader: () => import("@plugins/framework/plugins/tooling/plugins/boundaries/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/app-css-utilities-in-sync", id: "framework.tooling.checks.app-css-utilities-in-sync", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/app-css-utilities-in-sync/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/barrel-stubs-in-sync", id: "framework.tooling.checks.barrel-stubs-in-sync", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/barrel-stubs-in-sync/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/config-origins-in-sync", id: "framework.tooling.checks.config-origins-in-sync", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/config-origins-in-sync/check"), dependsOn: ["config_v2"] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/conversation-trailer", id: "framework.tooling.checks.conversation-trailer", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/conversation-trailer/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/css-vars-single-owner", id: "framework.tooling.checks.css-vars-single-owner", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/css-vars-single-owner/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/css-vars-supplied", id: "framework.tooling.checks.css-vars-supplied", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/css-vars-supplied/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/data-migration-dml-only", id: "framework.tooling.checks.data-migration-dml-only", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/data-migration-dml-only/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/migration-hashes-unique", id: "framework.tooling.checks.migration-hashes-unique", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/migration-hashes-unique/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/migrations-in-sync", id: "framework.tooling.checks.migrations-in-sync", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/migrations-in-sync/check"), dependsOn: ["infra/plugins/paths"] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/no-hardcoded-colors", id: "framework.tooling.checks.no-hardcoded-colors", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/no-hardcoded-colors/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/no-plugin-imports-in-core", id: "framework.tooling.checks.no-plugin-imports-in-core", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/no-plugin-imports-in-core/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/no-plugin-workspace-deps", id: "framework.tooling.checks.no-plugin-workspace-deps", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/no-plugin-workspace-deps/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/no-raw-event-source", id: "framework.tooling.checks.no-raw-event-source", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/no-raw-event-source/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/no-raw-sse", id: "framework.tooling.checks.no-raw-sse", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/no-raw-sse/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/no-raw-websocket", id: "framework.tooling.checks.no-raw-websocket", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/no-raw-websocket/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/no-reexport-default", id: "framework.tooling.checks.no-reexport-default", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/no-reexport-default/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/no-relative-server-imports", id: "framework.tooling.checks.no-relative-server-imports", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/no-relative-server-imports/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/no-use-resource-cast", id: "framework.tooling.checks.no-use-resource-cast", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/no-use-resource-cast/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/plugin-boundaries", id: "framework.tooling.checks.plugin-boundaries", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/plugin-boundaries/check"), dependsOn: ["framework/plugins/tooling/plugins/boundaries"] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/plugin-refs-resolve", id: "framework.tooling.checks.plugin-refs-resolve", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/plugin-refs-resolve/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/plugins-doc-in-sync", id: "framework.tooling.checks.plugins-doc-in-sync", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/plugins-doc-in-sync/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/plugins-have-claudemd", id: "framework.tooling.checks.plugins-have-claudemd", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/plugins-have-claudemd/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/plugins-registry-in-sync", id: "framework.tooling.checks.plugins-registry-in-sync", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/plugins-registry-in-sync/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/reorderable-slots-in-sync", id: "framework.tooling.checks.reorderable-slots-in-sync", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/reorderable-slots-in-sync/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/snapshot-chain-intact", id: "framework.tooling.checks.snapshot-chain-intact", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/snapshot-chain-intact/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/token-group-vars-in-sync", id: "framework.tooling.checks.token-group-vars-in-sync", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/token-group-vars-in-sync/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/tsconfig-alias-single-owner", id: "framework.tooling.checks.tsconfig-alias-single-owner", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/tsconfig-alias-single-owner/check"), dependsOn: [] },
  { pluginPath: "framework/plugins/tooling/plugins/checks/plugins/type-check", id: "framework.tooling.checks.type-check", loader: () => import("@plugins/framework/plugins/tooling/plugins/checks/plugins/type-check/check"), dependsOn: ["infra/plugins/paths"] },
  { pluginPath: "infra/plugins/endpoints", id: "infra.endpoints", loader: () => import("@plugins/infra/plugins/endpoints/check"), dependsOn: [] },
  { pluginPath: "infra/plugins/paths", id: "infra.paths", loader: () => import("@plugins/infra/plugins/paths/check"), dependsOn: [] },
  { pluginPath: "plugin-meta/plugins/facets", id: "plugin-meta.facets", loader: () => import("@plugins/plugin-meta/plugins/facets/check"), dependsOn: [] },
  { pluginPath: "primitives/plugins/icon-picker", id: "primitives.icon-picker", loader: () => import("@plugins/primitives/plugins/icon-picker/check"), dependsOn: [] },
  { pluginPath: "reorder", id: "reorder", loader: () => import("@plugins/reorder/check"), dependsOn: [] },
];
