// DO NOT EDIT — autogenerated by `./singularity build`
// (see plugins/framework/plugins/tooling/plugins/codegen/core/token-group-vars-gen.ts).
//
// The CSS custom properties (`--x`) declared by each token group, read from
// the real `defineTokenGroup` descriptors via their `ui.theme-engine.token-group`
// web-slot contributions. Consumed by the build-time CSS single-owner checks.
//
// The `token-group-vars-in-sync` check fails on drift.

export const TOKEN_GROUP_VARS: Record<string, readonly string[]> = {
  "categorical": ["--categorical-1", "--categorical-10", "--categorical-2", "--categorical-3", "--categorical-4", "--categorical-5", "--categorical-6", "--categorical-7", "--categorical-8", "--categorical-9", "--categorical-foreground"],
  "chart": ["--chart-1", "--chart-2", "--chart-3", "--chart-4", "--chart-5"],
  "color-palette": ["--accent", "--accent-foreground", "--background", "--border", "--card", "--card-foreground", "--destructive", "--destructive-foreground", "--faint-foreground", "--foreground", "--info", "--info-foreground", "--input", "--muted", "--muted-foreground", "--popover", "--popover-foreground", "--primary", "--primary-foreground", "--ring", "--secondary", "--secondary-foreground", "--success", "--success-foreground", "--warning", "--warning-foreground"],
  "density": ["--chrome-bar-h", "--chrome-pad-x", "--chrome-pane-h", "--control-gap-lg", "--control-gap-md", "--control-gap-sm", "--control-gap-xs", "--control-height-lg", "--control-height-md", "--control-height-sm", "--control-height-xs", "--control-pad-lg", "--control-pad-md", "--control-pad-sm", "--control-pad-xs", "--pad-card", "--pad-chip-compact-x", "--pad-chip-compact-y", "--pad-chip-x", "--pad-chip-y", "--pad-row-x", "--pad-row-y", "--radius-chip-compact", "--space-2xl", "--space-2xs", "--space-lg", "--space-md", "--space-sm", "--space-xl", "--space-xs", "--status-dot-lg", "--status-dot-md", "--status-dot-sm", "--status-dot-xs"],
  "font-family": ["--font-mono", "--font-sans", "--font-serif", "--font-smoothing", "--letter-spacing"],
  "rich-text-palette": ["--rt-color-blue", "--rt-color-brown", "--rt-color-gray", "--rt-color-green", "--rt-color-orange", "--rt-color-pink", "--rt-color-purple", "--rt-color-red", "--rt-color-yellow"],
  "shadow": ["--shadow", "--shadow-2xl", "--shadow-2xs", "--shadow-lg", "--shadow-md", "--shadow-sm", "--shadow-xl", "--shadow-xs"],
  "shape": ["--pill-pad-extra", "--radius", "--spacing"],
  "sidebar-metrics": ["--sidebar-icon-gap", "--sidebar-icon-size", "--sidebar-label-weight", "--sidebar-panel-width", "--sidebar-row-height", "--sidebar-row-pad-x"],
  "sidebar-palette": ["--sidebar", "--sidebar-accent", "--sidebar-accent-foreground", "--sidebar-border", "--sidebar-foreground", "--sidebar-icon", "--sidebar-primary", "--sidebar-primary-foreground", "--sidebar-ring"],
  "type-scale": ["--font-size-2xs", "--font-size-3xs", "--font-size-body", "--font-size-caption", "--font-size-chip-compact", "--font-size-control", "--font-size-display", "--font-size-heading", "--font-size-label", "--font-size-subheading", "--font-size-title", "--font-weight-bold", "--font-weight-chip-compact", "--font-weight-control", "--font-weight-medium", "--font-weight-normal", "--font-weight-semibold", "--line-height-2xs", "--line-height-3xs", "--line-height-body", "--line-height-caption", "--line-height-chip-compact", "--line-height-control", "--line-height-display", "--line-height-heading", "--line-height-label", "--line-height-subheading", "--line-height-title"],
};
