// DO NOT EDIT — autogenerated by `./singularity build`
// (see cli/src/plugin-registry-gen.ts).
//
// Adding/removing a plugin: create or delete the plugin's `<runtime>/index.ts`
// and rebuild — this file regenerates from the filesystem. The
// `plugins-registry-in-sync` check fails on drift.

import type { PluginDefinition } from "@core";
import activeDataAttemptPlugin from "@plugins/active-data/plugins/attempt/web";
import activeDataConvPlugin from "@plugins/active-data/plugins/conv/web";
import activeDataTaskLinkPlugin from "@plugins/active-data/plugins/task-link/web";
import activeDataTaskPlugin from "@plugins/active-data/plugins/task/web";
import activeDataPlugin from "@plugins/active-data/web";
import agentsAutoLaunchTogglePlugin from "@plugins/agents/plugins/auto-launch/plugins/toggle/web";
import agentsAutoLaunchPlugin from "@plugins/agents/plugins/auto-launch/web";
import agentsPlugin from "@plugins/agents/web";
import appsAgentManagerShellPlugin from "@plugins/apps/plugins/agent-manager/plugins/shell/web";
import appsDeployServersPlugin from "@plugins/apps/plugins/deploy/plugins/servers/web";
import appsDeployShellPlugin from "@plugins/apps/plugins/deploy/plugins/shell/web";
import appsDeployPlugin from "@plugins/apps/plugins/deploy/web";
import appsFileExplorerShellPlugin from "@plugins/apps/plugins/file-explorer/plugins/shell/web";
import appsFileExplorerPlugin from "@plugins/apps/plugins/file-explorer/web";
import appsPlugin from "@plugins/apps/web";
import attemptViewPlugin from "@plugins/attempt-view/web";
import authGoogleSetupWizardPlugin from "@plugins/auth/plugins/google/plugins/setup-wizard/web";
import authGooglePlugin from "@plugins/auth/plugins/google/web";
import authNotionPlugin from "@plugins/auth/plugins/notion/web";
import authPlugin from "@plugins/auth/web";
import buildPlugin from "@plugins/build/web";
import codeExplorerPlugin from "@plugins/code-explorer/web";
import configPlugin from "@plugins/config/web";
import conversationsRecoverPlugin from "@plugins/conversations-recover/web";
import conversationsConversationCategoryPlugin from "@plugins/conversations/plugins/conversation-category/web";
import conversationsConversationProgressPlugin from "@plugins/conversations/plugins/conversation-progress/web";
import conversationsConversationUiItemPlugin from "@plugins/conversations/plugins/conversation-ui/plugins/item/web";
import conversationsConversationUiPlugin from "@plugins/conversations/plugins/conversation-ui/web";
import conversationsConversationViewActionBarPlugin from "@plugins/conversations/plugins/conversation-view/plugins/action-bar/web";
import conversationsConversationViewAllowMonitorPlugin from "@plugins/conversations/plugins/conversation-view/plugins/allow-monitor/web";
import conversationsConversationViewBlockedByPlugin from "@plugins/conversations/plugins/conversation-view/plugins/blocked-by/web";
import conversationsConversationViewCodeDocsButtonPlugin from "@plugins/conversations/plugins/conversation-view/plugins/code/plugins/docs-button/web";
import conversationsConversationViewCodeFilePaneDiffPlugin from "@plugins/conversations/plugins/conversation-view/plugins/code/plugins/file-pane/plugins/diff/web";
import conversationsConversationViewCodeFilePaneImagePlugin from "@plugins/conversations/plugins/conversation-view/plugins/code/plugins/file-pane/plugins/image/web";
import conversationsConversationViewCodeFilePaneMarkdownPlugin from "@plugins/conversations/plugins/conversation-view/plugins/code/plugins/file-pane/plugins/markdown/web";
import conversationsConversationViewCodeFilePaneRawPlugin from "@plugins/conversations/plugins/conversation-view/plugins/code/plugins/file-pane/plugins/raw/web";
import conversationsConversationViewCodeFilePanePlugin from "@plugins/conversations/plugins/conversation-view/plugins/code/plugins/file-pane/web";
import conversationsConversationViewCodeReviewPlugin from "@plugins/conversations/plugins/conversation-view/plugins/code/plugins/review/web";
import conversationsConversationViewCodePlugin from "@plugins/conversations/plugins/conversation-view/plugins/code/web";
import conversationsConversationViewCommitsGraphPlugin from "@plugins/conversations/plugins/conversation-view/plugins/commits-graph/web";
import conversationsConversationViewDropAndExitPlugin from "@plugins/conversations/plugins/conversation-view/plugins/drop-and-exit/web";
import conversationsConversationViewExitPlugin from "@plugins/conversations/plugins/conversation-view/plugins/exit/web";
import conversationsConversationViewForkConversationPlugin from "@plugins/conversations/plugins/conversation-view/plugins/fork-conversation/web";
import conversationsConversationViewForkSessionPlugin from "@plugins/conversations/plugins/conversation-view/plugins/fork-session/web";
import conversationsConversationViewHoldAndExitPlugin from "@plugins/conversations/plugins/conversation-view/plugins/hold-and-exit/web";
import conversationsConversationViewJsonlViewerAssistantTextPlugin from "@plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/assistant-text/web";
import conversationsConversationViewJsonlViewerAssistantThinkingPlugin from "@plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/assistant-thinking/web";
import conversationsConversationViewJsonlViewerSummaryPlugin from "@plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/summary/web";
import conversationsConversationViewJsonlViewerSystemPlugin from "@plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/system/web";
import conversationsConversationViewJsonlViewerToolCallAddTaskPlugin from "@plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/add-task/web";
import conversationsConversationViewJsonlViewerToolCallBashPlugin from "@plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/bash/web";
import conversationsConversationViewJsonlViewerToolCallEditPlugin from "@plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/edit/web";
import conversationsConversationViewJsonlViewerToolCallWritePlugin from "@plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/write/web";
import conversationsConversationViewJsonlViewerToolCallPlugin from "@plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/web";
import conversationsConversationViewJsonlViewerUserImagePlugin from "@plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/user-image/web";
import conversationsConversationViewJsonlViewerUserTextPlugin from "@plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/user-text/web";
import conversationsConversationViewJsonlViewerPlugin from "@plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/web";
import conversationsConversationViewLaunchPromptsPlugin from "@plugins/conversations/plugins/conversation-view/plugins/launch-prompts/web";
import conversationsConversationViewModelPlugin from "@plugins/conversations/plugins/conversation-view/plugins/model/web";
import conversationsConversationViewNewChildTaskPlugin from "@plugins/conversations/plugins/conversation-view/plugins/new-child-task/web";
import conversationsConversationViewNotesPlugin from "@plugins/conversations/plugins/conversation-view/plugins/notes/web";
import conversationsConversationViewOpenAppPlugin from "@plugins/conversations/plugins/conversation-view/plugins/open-app/web";
import conversationsConversationViewPromptInputPlugin from "@plugins/conversations/plugins/conversation-view/plugins/prompt-input/web";
import conversationsConversationViewPushAndExitPlugin from "@plugins/conversations/plugins/conversation-view/plugins/push-and-exit/web";
import conversationsConversationViewQuickPromptsPlugin from "@plugins/conversations/plugins/conversation-view/plugins/quick-prompts/web";
import conversationsConversationViewResumePlugin from "@plugins/conversations/plugins/conversation-view/plugins/resume/web";
import conversationsConversationViewSideConversationPlugin from "@plugins/conversations/plugins/conversation-view/plugins/side-conversation/web";
import conversationsConversationViewSideTaskPlugin from "@plugins/conversations/plugins/conversation-view/plugins/side-task/web";
import conversationsConversationViewStatusPlugin from "@plugins/conversations/plugins/conversation-view/plugins/status/web";
import conversationsConversationViewTasksPanelPlugin from "@plugins/conversations/plugins/conversation-view/plugins/tasks-panel/web";
import conversationsConversationViewTerminalPanePlugin from "@plugins/conversations/plugins/conversation-view/plugins/terminal-pane/web";
import conversationsConversationViewTurnSummaryPlugin from "@plugins/conversations/plugins/conversation-view/plugins/turn-summary/web";
import conversationsConversationViewVscodePlugin from "@plugins/conversations/plugins/conversation-view/plugins/vscode/web";
import conversationsConversationViewPlugin from "@plugins/conversations/plugins/conversation-view/web";
import conversationsConversationsViewGroupedPlugin from "@plugins/conversations/plugins/conversations-view/plugins/grouped/web";
import conversationsConversationsViewHistoryPlugin from "@plugins/conversations/plugins/conversations-view/plugins/history/web";
import conversationsConversationsViewQueuePlugin from "@plugins/conversations/plugins/conversations-view/plugins/queue/web";
import conversationsConversationsViewPlugin from "@plugins/conversations/plugins/conversations-view/web";
import conversationsModelProviderPlugin from "@plugins/conversations/plugins/model-provider/web";
import conversationsSummaryPlugin from "@plugins/conversations/plugins/summary/web";
import crashesLaunchFixPlugin from "@plugins/crashes/plugins/launch-fix/web";
import crashesPlugin from "@plugins/crashes/web";
import debugClaudeCliCallsPlugin from "@plugins/debug/plugins/claude-cli-calls/web";
import debugDbBackupPlugin from "@plugins/debug/plugins/db-backup/web";
import debugLogsPlugin from "@plugins/debug/plugins/logs/web";
import debugMemoryPlugin from "@plugins/debug/plugins/memory/web";
import debugQueuePlugin from "@plugins/debug/plugins/queue/web";
import debugWorktreeCleanupPlugin from "@plugins/debug/plugins/worktree-cleanup/web";
import debugPlugin from "@plugins/debug/web";
import eventsTestPlugin from "@plugins/events-test/web";
import healthPlugin from "@plugins/health/web";
import improvePlugin from "@plugins/improve/web";
import infraAttachmentsPlugin from "@plugins/infra/plugins/attachments/web";
import layoutsMillerPlugin from "@plugins/layouts/plugins/miller/web";
import pluginMetaPluginViewPlugin from "@plugins/plugin-meta/plugins/plugin-view/web";
import pluginMetaPublishPlugin from "@plugins/plugin-meta/plugins/publish/web";
import pluginMetaPlugin from "@plugins/plugin-meta/web";
import primitivesAppShellPlugin from "@plugins/primitives/plugins/app-shell/web";
import primitivesAutoScrollPlugin from "@plugins/primitives/plugins/auto-scroll/web";
import primitivesAvatarPlugin from "@plugins/primitives/plugins/avatar/web";
import primitivesBreadcrumbPlugin from "@plugins/primitives/plugins/breadcrumb/web";
import primitivesEditableFieldPlugin from "@plugins/primitives/plugins/editable-field/web";
import primitivesErrorBoundaryPlugin from "@plugins/primitives/plugins/error-boundary/web";
import primitivesFileLinksPlugin from "@plugins/primitives/plugins/file-links/web";
import primitivesFilepathBreadcrumbPlugin from "@plugins/primitives/plugins/filepath-breadcrumb/web";
import primitivesLaunchPlugin from "@plugins/primitives/plugins/launch/web";
import primitivesLiveStatePlugin from "@plugins/primitives/plugins/live-state/web";
import primitivesNetworkingPlugin from "@plugins/primitives/plugins/networking/web";
import primitivesPanePlugin from "@plugins/primitives/plugins/pane/web";
import primitivesPasteImagesPlugin from "@plugins/primitives/plugins/paste-images/web";
import primitivesPersistentDraftPlugin from "@plugins/primitives/plugins/persistent-draft/web";
import primitivesRankPlugin from "@plugins/primitives/plugins/rank/web";
import primitivesRelativeTimePlugin from "@plugins/primitives/plugins/relative-time/web";
import primitivesSyntaxHighlightPlugin from "@plugins/primitives/plugins/syntax-highlight/web";
import primitivesTreePlugin from "@plugins/primitives/plugins/tree/web";
import primitivesPlugin from "@plugins/primitives/web";
import reorderEditModePlugin from "@plugins/reorder/plugins/edit-mode/web";
import reorderPlugin from "@plugins/reorder/web";
import screenshotDrawCanvasPlugin from "@plugins/screenshot/plugins/draw-canvas/web";
import screenshotDrawOnAppPlugin from "@plugins/screenshot/plugins/draw-on-app/web";
import screenshotPlugin from "@plugins/screenshot/web";
import shellToasterPlugin from "@plugins/shell/plugins/toaster/web";
import shellPlugin from "@plugins/shell/web";
import statsCommitsPlugin from "@plugins/stats/plugins/commits/web";
import statsCostPlugin from "@plugins/stats/plugins/cost/web";
import statsTasksPlugin from "@plugins/stats/plugins/tasks/web";
import statsPlugin from "@plugins/stats/web";
import tasksAutoStartPlugin from "@plugins/tasks/plugins/auto-start/web";
import tasksTaskAttachmentsPlugin from "@plugins/tasks/plugins/task-attachments/web";
import tasksTaskDependenciesPlugin from "@plugins/tasks/plugins/task-dependencies/web";
import tasksTaskDescriptionPlugin from "@plugins/tasks/plugins/task-description/web";
import tasksTaskDetailPlugin from "@plugins/tasks/plugins/task-detail/web";
import tasksTaskDraftFormPlugin from "@plugins/tasks/plugins/task-draft-form/web";
import tasksTaskEventsPlugin from "@plugins/tasks/plugins/task-events/web";
import tasksTaskFilePeekPlugin from "@plugins/tasks/plugins/task-file-peek/web";
import tasksTaskGraphPlugin from "@plugins/tasks/plugins/task-graph/web";
import tasksTaskHeaderPlugin from "@plugins/tasks/plugins/task-header/web";
import tasksTaskListPlugin from "@plugins/tasks/plugins/task-list/web";
import tasksTaskStatusPlugin from "@plugins/tasks/plugins/task-status/web";
import terminalPlugin from "@plugins/terminal/web";
import themePlugin from "@plugins/theme/web";
import welcomePlugin from "@plugins/welcome/web";
import worktreeSwitcherPlugin from "@plugins/worktree-switcher/web";

export const plugins: PluginDefinition[] = [
  activeDataAttemptPlugin,
  activeDataConvPlugin,
  activeDataTaskLinkPlugin,
  activeDataTaskPlugin,
  activeDataPlugin,
  agentsAutoLaunchTogglePlugin,
  agentsAutoLaunchPlugin,
  agentsPlugin,
  appsAgentManagerShellPlugin,
  appsDeployServersPlugin,
  appsDeployShellPlugin,
  appsDeployPlugin,
  appsFileExplorerShellPlugin,
  appsFileExplorerPlugin,
  appsPlugin,
  attemptViewPlugin,
  authGoogleSetupWizardPlugin,
  authGooglePlugin,
  authNotionPlugin,
  authPlugin,
  buildPlugin,
  codeExplorerPlugin,
  configPlugin,
  conversationsRecoverPlugin,
  conversationsConversationCategoryPlugin,
  conversationsConversationProgressPlugin,
  conversationsConversationUiItemPlugin,
  conversationsConversationUiPlugin,
  conversationsConversationViewActionBarPlugin,
  conversationsConversationViewAllowMonitorPlugin,
  conversationsConversationViewBlockedByPlugin,
  conversationsConversationViewCodeDocsButtonPlugin,
  conversationsConversationViewCodeFilePaneDiffPlugin,
  conversationsConversationViewCodeFilePaneImagePlugin,
  conversationsConversationViewCodeFilePaneMarkdownPlugin,
  conversationsConversationViewCodeFilePaneRawPlugin,
  conversationsConversationViewCodeFilePanePlugin,
  conversationsConversationViewCodeReviewPlugin,
  conversationsConversationViewCodePlugin,
  conversationsConversationViewCommitsGraphPlugin,
  conversationsConversationViewDropAndExitPlugin,
  conversationsConversationViewExitPlugin,
  conversationsConversationViewForkConversationPlugin,
  conversationsConversationViewForkSessionPlugin,
  conversationsConversationViewHoldAndExitPlugin,
  conversationsConversationViewJsonlViewerAssistantTextPlugin,
  conversationsConversationViewJsonlViewerAssistantThinkingPlugin,
  conversationsConversationViewJsonlViewerSummaryPlugin,
  conversationsConversationViewJsonlViewerSystemPlugin,
  conversationsConversationViewJsonlViewerToolCallAddTaskPlugin,
  conversationsConversationViewJsonlViewerToolCallBashPlugin,
  conversationsConversationViewJsonlViewerToolCallEditPlugin,
  conversationsConversationViewJsonlViewerToolCallWritePlugin,
  conversationsConversationViewJsonlViewerToolCallPlugin,
  conversationsConversationViewJsonlViewerUserImagePlugin,
  conversationsConversationViewJsonlViewerUserTextPlugin,
  conversationsConversationViewJsonlViewerPlugin,
  conversationsConversationViewLaunchPromptsPlugin,
  conversationsConversationViewModelPlugin,
  conversationsConversationViewNewChildTaskPlugin,
  conversationsConversationViewNotesPlugin,
  conversationsConversationViewOpenAppPlugin,
  conversationsConversationViewPromptInputPlugin,
  conversationsConversationViewPushAndExitPlugin,
  conversationsConversationViewQuickPromptsPlugin,
  conversationsConversationViewResumePlugin,
  conversationsConversationViewSideConversationPlugin,
  conversationsConversationViewSideTaskPlugin,
  conversationsConversationViewStatusPlugin,
  conversationsConversationViewTasksPanelPlugin,
  conversationsConversationViewTerminalPanePlugin,
  conversationsConversationViewTurnSummaryPlugin,
  conversationsConversationViewVscodePlugin,
  conversationsConversationViewPlugin,
  conversationsConversationsViewGroupedPlugin,
  conversationsConversationsViewHistoryPlugin,
  conversationsConversationsViewQueuePlugin,
  conversationsConversationsViewPlugin,
  conversationsModelProviderPlugin,
  conversationsSummaryPlugin,
  crashesLaunchFixPlugin,
  crashesPlugin,
  debugClaudeCliCallsPlugin,
  debugDbBackupPlugin,
  debugLogsPlugin,
  debugMemoryPlugin,
  debugQueuePlugin,
  debugWorktreeCleanupPlugin,
  debugPlugin,
  eventsTestPlugin,
  healthPlugin,
  improvePlugin,
  infraAttachmentsPlugin,
  layoutsMillerPlugin,
  pluginMetaPluginViewPlugin,
  pluginMetaPublishPlugin,
  pluginMetaPlugin,
  primitivesAppShellPlugin,
  primitivesAutoScrollPlugin,
  primitivesAvatarPlugin,
  primitivesBreadcrumbPlugin,
  primitivesEditableFieldPlugin,
  primitivesErrorBoundaryPlugin,
  primitivesFileLinksPlugin,
  primitivesFilepathBreadcrumbPlugin,
  primitivesLaunchPlugin,
  primitivesLiveStatePlugin,
  primitivesNetworkingPlugin,
  primitivesPanePlugin,
  primitivesPasteImagesPlugin,
  primitivesPersistentDraftPlugin,
  primitivesRankPlugin,
  primitivesRelativeTimePlugin,
  primitivesSyntaxHighlightPlugin,
  primitivesTreePlugin,
  primitivesPlugin,
  reorderEditModePlugin,
  reorderPlugin,
  screenshotDrawCanvasPlugin,
  screenshotDrawOnAppPlugin,
  screenshotPlugin,
  shellToasterPlugin,
  shellPlugin,
  statsCommitsPlugin,
  statsCostPlugin,
  statsTasksPlugin,
  statsPlugin,
  tasksAutoStartPlugin,
  tasksTaskAttachmentsPlugin,
  tasksTaskDependenciesPlugin,
  tasksTaskDescriptionPlugin,
  tasksTaskDetailPlugin,
  tasksTaskDraftFormPlugin,
  tasksTaskEventsPlugin,
  tasksTaskFilePeekPlugin,
  tasksTaskGraphPlugin,
  tasksTaskHeaderPlugin,
  tasksTaskListPlugin,
  tasksTaskStatusPlugin,
  terminalPlugin,
  themePlugin,
  welcomePlugin,
  worktreeSwitcherPlugin,
];
