import noArbitraryFontSize from "./no-arbitrary-font-size";

/**
 * First plugin-contributed lint barrel in the repo (see the typography density
 * plan, Part C.2). The root `eslint.config.ts` auto-discovers this default
 * export, registers `no-arbitrary-font-size` repo-wide as `error`, and flips it
 * off for the files listed under `ignores`.
 */
export default {
  name: "typography-tokens",
  rules: {
    "no-arbitrary-font-size": noArbitraryFontSize,
  },
  ignores: {
    // Temporary allowlist — migrate each file to named tokens then delete its
    // entry. Generated from `rg -l 'text-\[[0-9]+px\]' plugins`; every file that
    // still uses an arbitrary sub-scale font size is exempted so the rule can
    // land as `error` without a blocking 277-file sweep. New code is blocked
    // immediately; legacy burns down one allowlist entry at a time.
    "no-arbitrary-font-size": [
      "plugins/apps/plugins/studio/plugins/contributions/plugins/tables/web/components/tables-table.tsx",
      "plugins/apps/plugins/studio/plugins/contributions/web/components/catalog-view.tsx",
      "plugins/apps/plugins/studio/plugins/contributions/web/components/categories/resources-table.tsx",
      "plugins/apps/plugins/studio/plugins/contributions/web/components/categories/routes-table.tsx",
      "plugins/apps/plugins/studio/plugins/contributions/web/components/categories/slots-table.tsx",
      "plugins/apps/plugins/studio/plugins/contributions/web/components/plugin-chip.tsx",
      "plugins/apps/plugins/studio/plugins/explorer/plugins/child-count/web/components/child-count-badge.tsx",
      "plugins/apps/plugins/sonata/plugins/audio/plugins/engine/web/components/audio-panel.tsx",
      "plugins/apps/plugins/sonata/plugins/piano-keyboard/web/components/piano-keyboard.tsx",
      "plugins/apps/plugins/sonata/plugins/piano-roll/web/components/piano-roll.tsx",
      "plugins/apps/plugins/sonata/plugins/rich/plugins/chord-overlay/web/components/chord-overlay.tsx",
      "plugins/apps/plugins/sonata/plugins/rich/plugins/chord-readout/web/components/chord-readout.tsx",
      "plugins/apps/plugins/sonata/plugins/shell/web/components/sonata-layout.tsx",
      "plugins/attempt-view/web/components/attempt-pane.tsx",
      "plugins/build/web/components/build-popover-content.tsx",
      "plugins/config_v2/plugins/settings/web/components/config-field-row.tsx",
      "plugins/config_v2/plugins/settings/web/components/config-row-badge.tsx",
      "plugins/conversations-recover/web/components/recovery-view.tsx",
      "plugins/conversations/plugins/conversation-ui/plugins/item/web/components/conversation-item.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/dependencies/web/components/dep-popover-content.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/dependencies/web/components/dependencies-button.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/assistant-text/web/components/stop-reason-action.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/assistant-thinking/web/components/assistant-thinking-row.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/attachment/plugins/command-permissions/web/components/command-permissions-view.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/attachment/plugins/deferred-tools-delta/web/components/deferred-tools-delta-view.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/attachment/plugins/nested-memory/web/components/nested-memory-attachment-view.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/attachment/plugins/skill-listing/web/components/skill-listing-view.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/attachment/plugins/task-reminder/web/components/task-reminder-attachment-view.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/attachment/web/components/generic-attachment-view.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/file-path/web/components/file-path.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/message-toc/web/components/message-toc.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/task-notification/web/components/task-notification-row.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/add-task/web/components/add-task-tool-view.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/agent/web/components/agent-tool-view.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/ask-user-question/web/components/answer-form.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/ask-user-question/web/components/ask-user-question-tool-view.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/edit/web/components/multi-edit-view.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/read/web/components/read-tool-view.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/skill/web/components/skill-tool-view.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/task-tools/web/components/task-get-tool-view.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/task-tools/web/components/task-list-tool-view.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/task-tools/web/components/task-output-tool-view.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/task-tools/web/components/task-progress-overlay.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/task-tools/web/components/task-stop-tool-view.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/task-tools/web/components/task-update-tool-view.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/workflow/web/components/workflow-graph.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/workflow/web/components/workflow-node-card.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/workflow/web/components/workflow-node-pane.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/plugins/workflow/web/components/workflow-tool-view.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/tool-call/web/components/tool-call-card.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/unknown/web/components/unknown-row.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/plugins/user-image/web/components/user-image-row.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/jsonl-viewer/web/components/timestamp-action.tsx",
      "plugins/conversations/plugins/conversation-view/plugins/notes/web/components/notes-area.tsx",
      "plugins/conversations/plugins/conversations-view/plugins/grouped/web/components/group-box.tsx",
      "plugins/conversations/plugins/conversations-view/plugins/grouped/web/components/group-container.tsx",
      "plugins/conversations/plugins/conversations-view/plugins/grouped/web/components/grouped-conversation-list.tsx",
      "plugins/conversations/plugins/conversations-view/plugins/grouped/web/components/new-group-drop-zone.tsx",
      "plugins/conversations/plugins/summary/web/components/summary-pane.tsx",
      "plugins/debug/plugins/broadcasts/web/components/broadcasts-panel.tsx",
      "plugins/debug/plugins/claude-cli-calls/web/components/call-row.tsx",
      "plugins/debug/plugins/memory/web/components/memory-panel.tsx",
      "plugins/debug/plugins/profiling/plugins/push/plugins/push-gantt/web/components/push-gantt.tsx",
      "plugins/debug/plugins/queue/web/components/queue-view.tsx",
      "plugins/debug/plugins/worktree-cleanup/web/components/worktree-cleanup-panel.tsx",
      "plugins/layouts/plugins/miller/web/components/collapsed-bar.tsx",
      "plugins/notifications/web/components/bell-button.tsx",
      "plugins/plugin-meta/plugins/plugin-health/web/components/health-section.tsx",
      "plugins/plugin-meta/plugins/plugin-view/plugins/public-api/web/components/public-api-section.tsx",
      "plugins/plugin-meta/plugins/plugin-view/plugins/runtimes/web/components/runtimes-section.tsx",
      "plugins/plugin-meta/plugins/plugin-view/plugins/source-path/web/components/source-path-section.tsx",
      "plugins/plugin-meta/plugins/plugin-view/web/components/plugin-detail.tsx",
      "plugins/plugin-meta/plugins/plugin-view/web/components/section.tsx",
      "plugins/primitives/plugins/avatar/web/components/avatar-picker.tsx",
      "plugins/primitives/plugins/avatar/web/components/avatar.tsx",
      "plugins/primitives/plugins/color-picker/web/internal/color-input.tsx",
      "plugins/primitives/plugins/color-picker/web/internal/color-picker.tsx",
      "plugins/reorder/plugins/editor/web/internal/items.tsx",
      "plugins/reorder/web/internal/group-box.tsx",
      "plugins/review/plugins/code-review/web/components/review-file-row.tsx",
      "plugins/review/plugins/plugin-changes/plugins/api-changes/web/components/api-changes-summary.tsx",
      "plugins/review/plugins/plugin-changes/plugins/file-changes/web/components/file-changes-section.tsx",
      "plugins/review/plugins/plugin-changes/web/components/plugin-change-card.tsx",
      "plugins/review/plugins/plugin-changes/web/components/plugin-changes-summary.tsx",
      "plugins/screenshot/web/components/tools-pane.tsx",
      "plugins/tasks/plugins/auto-start/web/components/queued-chip-action.tsx",
      "plugins/tasks/plugins/task-draft-form/web/components/chain-connector.tsx",
      "plugins/tasks/plugins/task-graph/web/components/task-graph.tsx",
      "plugins/tasks/plugins/task-list/web/components/child-count-action.tsx",
      "plugins/ui/plugins/theme-engine/plugins/theme-customizer/web/components/theme-customizer.tsx",
      "plugins/ui/plugins/theme-engine/plugins/theme-customizer/web/components/token-row.tsx",
      "plugins/ui/plugins/tokens/plugins/shadow/web/components/shadow-section.tsx",
      "plugins/ui/plugins/tweakcn/plugins/community-browser/web/components/community-theme-card.tsx",
      "plugins/welcome/web/components/welcome-view.tsx",
    ],
  },
};
