// DO NOT EDIT — autogenerated by `./singularity build`
// (see plugins/framework/plugins/tooling/plugins/codegen/core/plugin-registry-gen.ts).
//
// Adding/removing a plugin: create or delete the plugin's `<runtime>/index.ts`
// and rebuild — this file regenerates from the filesystem. The
// `plugins-registry-in-sync` check fails on drift.

export interface CollectedEntry {
  pluginPath: string;
  id: string;
  loader: () => Promise<{ default: unknown }>;
  dependsOn: string[];
}

export const viteEntries: CollectedEntry[] = [
  { pluginPath: "improve/plugins/element-picker", id: "improve.element-picker", loader: () => import("@plugins/improve/plugins/element-picker/vite"), dependsOn: [] },
];
