import type { z } from "zod";
import type { FieldType } from "@plugins/fields/core";

export type JsonValue =
  | string
  | number
  | boolean
  | null
  | JsonValue[]
  | { [key: string]: JsonValue };

export interface Disposable {
  dispose(): void;
}

export interface FieldMeta {
  label?: string;
  description?: string;
  placeholder?: string;
  typeHint?: string;
}

export interface FieldDef<T = unknown> {
  readonly type: FieldType<T>;
  readonly schema: z.ZodType<T>;
  readonly defaultValue: T;
  readonly meta: FieldMeta;
}

export type FieldsRecord = Record<string, FieldDef>;

export type InferFieldValue<F> = F extends FieldDef<infer T> ? T : never;

export type InferFieldsObject<F extends FieldsRecord> = {
  [K in keyof F]: InferFieldValue<F[K]>;
};

export type ConfigValues<F extends FieldsRecord> = InferFieldsObject<F>;

// Where a config descriptor came from. `manual` is hand-authored `defineConfig`
// (the default); the rest are auto-generated by a primitive, one descriptor per
// instance: `reorder` (one per reorderable render slot) and `view` (one per
// DataView consumer's `viewsDescriptor`). Named `source` — NOT `origin` — to
// avoid colliding with config_v2's `.origin.jsonc` code/git layer terminology.
export type ConfigSource = "manual" | "reorder" | "view";

export interface ConfigDescriptor<F extends FieldsRecord = FieldsRecord> {
  readonly name: string;
  readonly schema: z.ZodObject<Record<string, z.ZodTypeAny>>;
  readonly fields: F;
  readonly defaults: ConfigValues<F>;
  // Optional scope axis. When set, this descriptor can be forked per scope of
  // the given kind (e.g. "app" → per-app). Omitted = global-only (base scope).
  readonly scope?: "app";
  // When true, an in-app edit may be staged as a committed git-layer default
  // (the reorder "default for everyone" path) instead of a per-user override.
  readonly promotableToGit?: boolean;
  // Provenance: hand-authored vs auto-generated. Always set by `defineConfig`
  // (defaults to `manual`). Surfaced as a filterable field + row tag in the
  // settings config nav.
  readonly source?: ConfigSource;
}
