import { existsSync, readFileSync, unlinkSync, writeFileSync } from "fs";
import { join, relative, resolve } from "path";
import {
  buildPluginTree,
  enrichPluginTreeDocs,
  type PluginNode,
  type PluginTree,
  type BarrelExport,
  type DocMetaRegistration,
} from "@plugins/plugin-meta/plugins/plugin-tree/core";

const BEGIN = "<!-- AUTOGENERATED:BEGIN — do not edit; regenerated by `./singularity build` -->";
const END = "<!-- AUTOGENERATED:END -->";

function readIfExists(path: string): string | null {
  return existsSync(path) ? readFileSync(path, "utf8") : null;
}

function formatRegistration(r: DocMetaRegistration): string {
  const label = r.doc.label;
  if (!r.factory) return `\`${label ?? r.kind}\``;
  return label ? `\`${r.factory}('${label}')\`` : `\`${r.factory}()\``;
}

function pluginDescription(p: PluginNode): string | undefined {
  const parts = [p.descriptions.web, p.descriptions.server, p.descriptions.central].filter(Boolean);
  return parts.length > 0 ? parts.join(" ") : p.description;
}

function renderPluginBody(
  p: PluginNode,
  bodyIndent: string,
  root: string,
  lines: string[],
): void {
  const subIndent = `${bodyIndent}  `;

  const defines: string[] = [];
  if (p.slots.length > 0) {
    defines.push(
      `${subIndent}- Slots: ${p.slots.map((s) => `\`${s.groupName}.${s.memberName}\``).join(", ")}`,
    );
  }
  if (p.commands.length > 0) {
    defines.push(
      `${subIndent}- Commands: ${p.commands.map((c) => `\`${c.groupName}.${c.memberName}\``).join(", ")}`,
    );
  }
  for (const f of p.dbFiles) {
    defines.push(`${subIndent}- DB schema: \`${relative(root, f)}\``);
  }
  for (const ext of p.entityExtensions) {
    defines.push(
      `${subIndent}- Entity extension of: \`${ext.parentPlugin}\` (table \`${ext.tableName}\`)`,
    );
  }
  if (defines.length > 0) {
    lines.push(`${bodyIndent}- Defines:`);
    lines.push(...defines);
  }

  const renderExportsAt = (
    runtime: "web" | "server" | "central" | "core" | "shared",
    exports: BarrelExport[],
  ): void => {
    if (exports.length === 0) return;
    const types = exports.filter((e) => e.kind === "type");
    const values = exports.filter((e) => e.kind === "value");
    lines.push(`${bodyIndent}- Exports (${runtime}):`);
    if (types.length > 0) {
      lines.push(`${subIndent}- Types: ${types.map((e) => `\`${e.name}\``).join(", ")}`);
    }
    if (values.length > 0) {
      lines.push(`${subIndent}- Values: ${values.map((e) => `\`${e.name}\``).join(", ")}`);
    }
  };
  renderExportsAt("core", p.exports.core);
  renderExportsAt("web", p.exports.web);
  renderExportsAt("server", p.exports.server);
  renderExportsAt("central", p.exports.central);
  renderExportsAt("shared", p.exports.shared);

  if (p.runtimeContributions && p.runtimeContributions.length > 0) {
    lines.push(`${bodyIndent}- Contributes:`);
    for (const c of p.runtimeContributions) {
      const parts = [`\`${c.slotDisplayName ?? c.slotId}\``];
      if (c.doc.label) parts.push(`"${c.doc.label}"`);
      if (c.doc.detail) parts.push(`(${c.doc.detail})`);
      if (c.componentName) parts.push(`→ \`${c.componentName}\``);
      lines.push(`${subIndent}- ${parts.join(" ")}`);
    }
  }

  const serverRuntimeRegs = p.runtimeRegistrations?.filter((r) => r.runtime === "server") ?? [];
  const serverEntries = [...p.server.httpRoutes, ...p.server.wsRoutes.map((r) => `WS ${r}`)];
  if (serverEntries.length > 0 || p.server.apiUses.length > 0 || p.server.resources.length > 0 || serverRuntimeRegs.length > 0) {
    lines.push(`${bodyIndent}- Server:`);
    if (serverRuntimeRegs.length > 0) {
      lines.push(`${subIndent}- Register: ${serverRuntimeRegs.map(formatRegistration).join(", ")}`);
    }
    if (p.server.apiUses.length > 0) {
      lines.push(`${subIndent}- Uses: ${p.server.apiUses.map((n) => `\`${n}\``).join(", ")}`);
    }
    if (p.server.resources.length > 0) {
      lines.push(
        `${subIndent}- Resources: ${p.server.resources.map((r) => `\`${r.key}\` (${r.mode})`).join(", ")}`,
      );
    }
    for (const r of serverEntries) lines.push(`${subIndent}- \`${r}\``);
  }

  const centralRuntimeRegs = p.runtimeRegistrations?.filter((r) => r.runtime === "central") ?? [];
  const centralEntries = [...p.central.httpRoutes, ...p.central.wsRoutes.map((r) => `WS ${r}`)];
  if (
    centralEntries.length > 0 ||
    p.central.apiUses.length > 0 ||
    p.central.resources.length > 0 ||
    centralRuntimeRegs.length > 0
  ) {
    lines.push(`${bodyIndent}- Central:`);
    if (centralRuntimeRegs.length > 0) {
      lines.push(`${subIndent}- Register: ${centralRuntimeRegs.map(formatRegistration).join(", ")}`);
    }
    if (p.central.apiUses.length > 0) {
      lines.push(`${subIndent}- Uses: ${p.central.apiUses.map((n) => `\`${n}\``).join(", ")}`);
    }
    if (p.central.resources.length > 0) {
      lines.push(
        `${subIndent}- Resources: ${p.central.resources.map((r) => `\`${r.key}\` (${r.mode})`).join(", ")}`,
      );
    }
    for (const r of centralEntries) lines.push(`${subIndent}- \`${r}\``);
  }

  if (p.importedBy.length > 0) {
    lines.push(
      `${bodyIndent}- Imported by: ${p.importedBy.map((n) => `\`${n}\``).join(", ")}`,
    );
  }
  if (p.slotContributors.length > 0) {
    lines.push(
      `${bodyIndent}- Slot contributors: ${p.slotContributors.map((n) => `\`${n}\``).join(", ")}`,
    );
  }
  if (p.endpointCallers.length > 0) {
    lines.push(
      `${bodyIndent}- Endpoint callers: ${p.endpointCallers.map((n) => `\`${n}\``).join(", ")}`,
    );
  }
  if (p.extendedBy.length > 0) {
    lines.push(
      `${bodyIndent}- Extended by: ${p.extendedBy.map((e) => `\`${e.childPlugin}\` (table \`${e.tableName}\`)`).join(", ")}`,
    );
  }
}

type RenderMode = "detail" | "compact";

function renderPluginTreeMd(
  p: PluginNode,
  depth: number,
  root: string,
  mode: RenderMode,
): string[] {
  const headerIndent = "  ".repeat(depth);
  const bodyIndent = `${headerIndent}  `;
  const lines: string[] = [];
  const desc = pluginDescription(p);
  const descStr = desc ? ` — ${desc}` : "";
  const marker = mode === "compact" && p.loadBearing ? " [load-bearing]" : "";
  lines.push(`${headerIndent}- **\`${p.name}\`**${marker}${descStr}`);

  const includeBody = mode === "detail";
  if (includeBody) renderPluginBody(p, bodyIndent, root, lines);

  if (p.children.length > 0) {
    lines.push(`${bodyIndent}- Plugins:`);
    for (const c of p.children) lines.push(...renderPluginTreeMd(c, depth + 2, root, mode));
  }

  return lines;
}

export interface GenerateDocsOptions {
  root: string;
}

export function collectAllPlugins(root: string): PluginNode[] {
  const tree = buildPluginTree(resolve(root, "plugins"));
  return Array.from(tree.byDir.values());
}

export { type PluginNode };

function renderTreeBody(roots: PluginNode[], root: string, mode: RenderMode): string {
  const lines: string[] = [];
  for (let i = 0; i < roots.length; i++) {
    if (i > 0) lines.push("");
    lines.push(...renderPluginTreeMd(roots[i]!, 0, root, mode));
  }
  return lines.join("\n") + "\n";
}

const COMPACT_HEADER =
  "# Plugins (compact)\n\n" +
  "Slim, always-loaded index of every plugin. Shows only `name — description`; load-bearing infrastructure plugins are marked `[load-bearing]`. Read [`plugins-details.md`](./plugins-details.md) for the full reference, or open the per-plugin `CLAUDE.md` when working inside a specific plugin.\n\n";

const DETAILS_HEADER =
  "# Plugins (details)\n\n" +
  "Full reference for every plugin. Read this on demand (e.g. before writing a helper, to check whether one already exists). The slim always-loaded index is [`plugins-compact.md`](./plugins-compact.md).\n\n";

const ROUTES_HEADER =
  "# Plugin Routes\n\n" +
  "All HTTP and WebSocket routes exposed by server and central plugins. " +
  "Only plugins with at least one route (directly or in a descendant) are shown.\n\n";

export async function buildEnrichedTree(root: string): Promise<PluginTree> {
  const tree = buildPluginTree(resolve(root, "plugins"));
  await enrichPluginTreeDocs(tree, root);
  return tree;
}

export async function renderCompactDoc({ root }: GenerateDocsOptions): Promise<string> {
  return renderCompactDocFromTree(await buildEnrichedTree(root), root);
}

export async function renderDetailsDoc({ root }: GenerateDocsOptions): Promise<string> {
  return renderDetailsDocFromTree(await buildEnrichedTree(root), root);
}

export async function renderRoutesDoc({ root }: GenerateDocsOptions): Promise<string> {
  return renderRoutesDocFromTree(await buildEnrichedTree(root), root);
}

function renderPluginClaudeAutogen(p: PluginNode, root: string): string {
  const lines: string[] = [];
  lines.push("## Plugin reference");
  lines.push("");
  const desc = pluginDescription(p);
  if (desc) lines.push(`- Description: ${desc}`);
  if (p.loadBearing) lines.push("- Load-bearing: yes");
  renderPluginBody(p, "", root, lines);
  if (p.children.length > 0) {
    lines.push("- Sub-plugins:");
    for (const c of p.children) {
      const cdesc = pluginDescription(c);
      const cdescStr = cdesc ? ` — ${cdesc}` : "";
      lines.push(`  - **\`${c.name}\`**${cdescStr}`);
    }
  }
  return lines.join("\n") + "\n";
}

function renderPluginClaudeMd(p: PluginNode, existing: string | null, root: string): string {
  const autogen = renderPluginClaudeAutogen(p, root);
  const block = `${BEGIN}\n\n${autogen}\n${END}\n`;

  if (existing === null) {
    return `# ${p.name}\n\n${block}`;
  }
  const beginIdx = existing.indexOf(BEGIN);
  if (beginIdx < 0) {
    const sep = existing.endsWith("\n") ? "\n" : "\n\n";
    return `${existing}${sep}${block}`;
  }
  const endIdx = existing.indexOf(END, beginIdx);
  if (endIdx < 0) {
    return `${existing.slice(0, beginIdx)}${block}`;
  }
  const after = existing.slice(endIdx + END.length);
  const trimmedAfter = after.startsWith("\n") ? after.slice(1) : after;
  return `${existing.slice(0, beginIdx)}${block}${trimmedAfter}`;
}

export function pluginCompactDocPath(root: string): string {
  return join(root, "docs", "plugins-compact.md");
}

export function pluginDetailsDocPath(root: string): string {
  return join(root, "docs", "plugins-details.md");
}

export function pluginRoutesDocPath(root: string): string {
  return join(root, "docs", "routes.md");
}

export function pluginClaudeMdPath(p: PluginNode): string {
  return join(p.dir, "CLAUDE.md");
}

function legacyPluginDocsPath(root: string): string {
  return join(root, "docs", "plugins.md");
}

export async function generatePluginDocs({ root }: GenerateDocsOptions): Promise<void> {
  const tree = await buildEnrichedTree(root);

  const writeIfChanged = (file: string, next: string) => {
    const existing = readIfExists(file) ?? "";
    if (next !== existing) writeFileSync(file, next);
  };

  writeIfChanged(pluginCompactDocPath(root), renderCompactDocFromTree(tree, root));
  writeIfChanged(pluginDetailsDocPath(root), renderDetailsDocFromTree(tree, root));
  writeIfChanged(pluginRoutesDocPath(root), renderRoutesDocFromTree(tree, root));

  for (const info of tree.byDir.values()) {
    const file = pluginClaudeMdPath(info);
    const existing = readIfExists(file);
    const next = renderPluginClaudeMd(info, existing, root);
    if (next !== existing) writeFileSync(file, next);
  }

  const legacy = legacyPluginDocsPath(root);
  if (existsSync(legacy)) {
    try {
      unlinkSync(legacy);
    } catch {
      // Best-effort
    }
  }
}

function renderCompactDocFromTree(tree: PluginTree, root: string): string {
  const body = renderTreeBody(tree.roots, root, "compact");
  return `${COMPACT_HEADER}${BEGIN}\n\n${body}\n${END}\n`;
}

function renderDetailsDocFromTree(tree: PluginTree, root: string): string {
  const body = renderTreeBody(tree.roots, root, "detail");
  return `${DETAILS_HEADER}${BEGIN}\n\n${body}\n${END}\n`;
}

function pluginHasRoutesDeep(p: PluginNode): boolean {
  return (
    p.server.httpRoutes.length > 0 ||
    p.server.wsRoutes.length > 0 ||
    p.central.httpRoutes.length > 0 ||
    p.central.wsRoutes.length > 0 ||
    p.children.some(pluginHasRoutesDeep)
  );
}

function groupHttpRoutes(routes: string[]): string[] {
  const byPath = new Map<string, string[]>();
  for (const r of routes) {
    const sp = r.indexOf(" ");
    const method = r.slice(0, sp);
    const path = r.slice(sp + 1);
    if (!byPath.has(path)) byPath.set(path, []);
    byPath.get(path)!.push(method);
  }
  return [...byPath.entries()].map(([path, methods]) => `${path} (${methods.join(", ")})`);
}

function renderRoutesPluginTree(p: PluginNode, depth: number): string[] {
  if (!pluginHasRoutesDeep(p)) return [];

  const indent = "  ".repeat(depth);
  const bodyIndent = `${indent}  `;
  const lines: string[] = [];

  const desc = pluginDescription(p);
  const descStr = desc ? ` — ${desc}` : "";
  lines.push(`${indent}- **\`${p.name}\`**${descStr}`);

  for (const r of groupHttpRoutes(p.server.httpRoutes))  lines.push(`${bodyIndent}- \`${r}\``);
  for (const r of p.server.wsRoutes)                     lines.push(`${bodyIndent}- \`${r} (WS)\``);
  for (const r of groupHttpRoutes(p.central.httpRoutes)) lines.push(`${bodyIndent}- \`${r}\` _(central)_`);
  for (const r of p.central.wsRoutes)                    lines.push(`${bodyIndent}- \`${r} (WS)\` _(central)_`);

  const routeChildren = p.children.filter(pluginHasRoutesDeep);
  if (routeChildren.length > 0) {
    lines.push(`${bodyIndent}- Plugins:`);
    for (const c of routeChildren)
      lines.push(...renderRoutesPluginTree(c, depth + 2));
  }

  return lines;
}

function renderRoutesDocFromTree(tree: PluginTree, _root: string): string {
  const roots = tree.roots.filter(pluginHasRoutesDeep);
  const lines: string[] = [];
  for (let i = 0; i < roots.length; i++) {
    if (i > 0) lines.push("");
    lines.push(...renderRoutesPluginTree(roots[i]!, 0));
  }
  const body = lines.join("\n") + "\n";
  return `${ROUTES_HEADER}${BEGIN}\n\n${body}\n${END}\n`;
}

export { renderPluginClaudeMd, buildPluginTree };
export type { PluginTree };
