import { existsSync, readdirSync, readFileSync, writeFileSync } from "fs";
import { basename, join, relative, resolve } from "path";

const BEGIN = "<!-- AUTOGENERATED:BEGIN — do not edit; regenerated by `./singularity build` -->";
const END = "<!-- AUTOGENERATED:END -->";

interface SlotDef {
  memberName: string;
  slotId: string;
  groupName: string;
}

interface CommandDef {
  memberName: string;
  commandId: string;
  groupName: string;
}

interface Contribution {
  slot: string; // rendered label like "Shell.Toolbar"
  props: Record<string, string>;
}

interface BarrelExport {
  name: string;
  kind: "type" | "value";
}

interface PluginInfo {
  dir: string;
  name: string;
  parentDir: string | null;
  description?: string;
  definedSlots: SlotDef[];
  definedCommands: CommandDef[];
  dbFiles: string[];
  contributions: Contribution[];
  httpRoutes: string[];
  wsRoutes: string[];
  webExports: BarrelExport[];
  serverExports: BarrelExport[];
  centralExports: BarrelExport[];
  sharedExports: BarrelExport[];
  apiUses: string[];
  resources: { key: string; mode: string }[];
  centralHttpRoutes: string[];
  centralWsRoutes: string[];
  centralApiUses: string[];
  centralResources: { key: string; mode: string }[];
  children: PluginInfo[];
}

function readIfExists(path: string): string | null {
  return existsSync(path) ? readFileSync(path, "utf8") : null;
}

const transpiler = new Bun.Transpiler({ loader: "ts" });

function stripTypes(src: string): string {
  // Strip TypeScript annotations/generics so type parameters never confuse
  // the simpler JS-level pattern matching below.
  try {
    return transpiler.transformSync(src);
  } catch {
    return src;
  }
}

function findAllPluginDirs(pluginsRoot: string): string[] {
  const out: string[] = [];
  function walk(dir: string, depth: number) {
    if (depth > 10) return;
    const hasWeb = existsSync(join(dir, "web", "index.ts"));
    const hasServer = existsSync(join(dir, "server", "index.ts"));
    const hasCentral = existsSync(join(dir, "central", "index.ts"));
    if ((hasWeb || hasServer || hasCentral) && dir !== pluginsRoot) out.push(dir);

    let entries;
    try {
      entries = readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      if (!e.isDirectory()) continue;
      // Recurse into: pluginsRoot/* (plugin dirs) and <plugin>/plugins/*
      if (dir === pluginsRoot) walk(join(dir, e.name), depth + 1);
      else if (e.name === "plugins") {
        const sub = join(dir, e.name);
        const childEntries = readdirSync(sub, { withFileTypes: true });
        for (const c of childEntries) {
          if (c.isDirectory()) walk(join(sub, c.name), depth + 1);
        }
      }
    }
  }
  walk(pluginsRoot, 0);
  return out;
}

function parseStringField(src: string, field: string): string | undefined {
  const re = new RegExp(`\\b${field}\\s*:\\s*"((?:[^"\\\\]|\\\\.)*)"`);
  const m = src.match(re);
  return m ? m[1] : undefined;
}

function parseDefineGroup<T>(
  src: string,
  builder: "defineSlot" | "defineCommand",
  make: (memberName: string, id: string, groupName: string) => T,
): T[] {
  const out: T[] = [];
  const groupRe = /export\s+const\s+([A-Z]\w*)\s*=\s*\{/g;
  let m: RegExpExecArray | null;
  while ((m = groupRe.exec(src))) {
    const groupName = m[1]!;
    const braceStart = src.indexOf("{", m.index);
    const braceEnd = matchBracket(src, braceStart, "{", "}");
    if (braceEnd < 0) continue;
    const body = src.slice(braceStart + 1, braceEnd);
    const memberRe = new RegExp(
      `([A-Z]\\w*)\\s*:\\s*${builder}\\s*\\(\\s*"([^"]+)"`,
      "g",
    );
    let mm: RegExpExecArray | null;
    while ((mm = memberRe.exec(body))) out.push(make(mm[1]!, mm[2]!, groupName));
  }
  return out;
}

interface ImportBinding {
  local: string;
  original: string;
  module: string;
}

function parseImports(src: string): Map<string, ImportBinding> {
  const map = new Map<string, ImportBinding>();
  const namedRe = /import\s+(?:([A-Za-z_$][\w$]*)\s*,\s*)?\{([^}]+)\}\s*from\s*["']([^"']+)["']/g;
  let m: RegExpExecArray | null;
  while ((m = namedRe.exec(src))) {
    const defLocal = m[1];
    const names = m[2]!;
    const mod = m[3]!;
    if (defLocal) map.set(defLocal, { local: defLocal, original: "default", module: mod });
    for (const raw of names.split(",")) {
      let s = raw.trim();
      if (!s) continue;
      s = s.replace(/^type\s+/, "");
      const asMatch = s.match(/^(\w+)\s+as\s+(\w+)$/);
      if (asMatch) map.set(asMatch[2]!, { local: asMatch[2]!, original: asMatch[1]!, module: mod });
      else if (/^\w+$/.test(s)) map.set(s, { local: s, original: s, module: mod });
    }
  }
  const defRe = /import\s+([A-Za-z_$][\w$]*)\s+from\s*["']([^"']+)["']/g;
  while ((m = defRe.exec(src))) map.set(m[1]!, { local: m[1]!, original: "default", module: m[2]! });
  return map;
}

function matchBracket(src: string, start: number, open: string, close: string): number {
  let depth = 0;
  for (let i = start; i < src.length; i++) {
    const c = src[i];
    if (c === '"' || c === "'" || c === "`") {
      const q = c;
      i++;
      while (i < src.length && src[i] !== q) {
        if (src[i] === "\\") i++;
        i++;
      }
      continue;
    }
    if (c === open) depth++;
    else if (c === close) {
      depth--;
      if (depth === 0) return i;
    }
  }
  return -1;
}

function extractContributionsBlock(src: string): string | null {
  const idx = src.search(/\bcontributions\s*:\s*\[/);
  if (idx < 0) return null;
  const start = src.indexOf("[", idx);
  const end = matchBracket(src, start, "[", "]");
  if (end < 0) return null;
  return src.slice(start + 1, end);
}

function findCalls(block: string): { callee: string; argsBody: string }[] {
  const out: { callee: string; argsBody: string }[] = [];
  const re = /([A-Za-z_$][\w$]*(?:\.[A-Za-z_$][\w$]*)+)\s*\(\s*\{/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(block))) {
    const callee = m[1]!;
    const openIdx = m.index + m[0].length - 1;
    const closeIdx = matchBracket(block, openIdx, "{", "}");
    if (closeIdx < 0) continue;
    out.push({ callee, argsBody: block.slice(openIdx + 1, closeIdx) });
  }
  return out;
}

function parsePropsBlock(body: string): Record<string, string> {
  const out: Record<string, string> = {};
  let i = 0;
  const len = body.length;
  const skipWs = () => {
    while (i < len && /\s/.test(body[i]!)) i++;
  };
  const skipString = (quote: string) => {
    i++;
    while (i < len && body[i] !== quote) {
      if (body[i] === "\\") i++;
      i++;
    }
    i++;
  };
  const parseValue = (): string => {
    skipWs();
    if (i >= len) return "";
    const c = body[i]!;
    if (c === '"' || c === "'" || c === "`") {
      const start = i;
      skipString(c);
      return body.slice(start, i);
    }
    if (c === "{" || c === "[") {
      const open = c;
      const close = c === "{" ? "}" : "]";
      const start = i;
      const end = matchBracket(body, i, open, close);
      i = end < 0 ? len : end + 1;
      return body.slice(start, i);
    }
    let depth = 0;
    const start = i;
    while (i < len) {
      const ch = body[i]!;
      if (depth === 0 && ch === ",") break;
      if (ch === "{" || ch === "[" || ch === "(") depth++;
      else if (ch === "}" || ch === "]" || ch === ")") depth--;
      else if (ch === '"' || ch === "'" || ch === "`") {
        skipString(ch);
        continue;
      }
      i++;
    }
    return body.slice(start, i).trim();
  };
  while (i < len) {
    skipWs();
    const rest = body.slice(i);
    const keyMatch = /^([A-Za-z_$][\w$]*)\s*:/.exec(rest);
    if (!keyMatch) break;
    const key = keyMatch[1]!;
    i += keyMatch[0].length;
    const val = parseValue();
    out[key] = val;
    skipWs();
    if (body[i] === ",") i++;
  }
  return out;
}

function parseRouteMap(
  src: string,
  field: "httpRoutes" | "wsRoutes",
): string[] {
  const idx = src.search(new RegExp(`\\b${field}\\s*:\\s*\\{`));
  if (idx < 0) return [];
  const start = src.indexOf("{", idx);
  const end = matchBracket(src, start, "{", "}");
  if (end < 0) return [];
  const body = src.slice(start + 1, end);
  const keys: string[] = [];
  const re = /"([^"]+)"\s*:/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(body))) keys.push(m[1]!);
  return keys;
}

function parseBarrelExports(src: string): BarrelExport[] {
  const map = new Map<string, "type" | "value">();
  const setIfUnset = (name: string, kind: "type" | "value") => {
    if (!map.has(name)) map.set(name, kind);
  };

  // Direct declarations (skip default): export [async] const|let|var|function|class|type|interface|enum NAME
  const declRe =
    /export\s+(?!default\b)(?:async\s+)?(const|let|var|function|class|type|interface|enum)\s+([A-Za-z_$][\w$]*)/g;
  let m: RegExpExecArray | null;
  while ((m = declRe.exec(src))) {
    const keyword = m[1]!;
    const name = m[2]!;
    const kind: "type" | "value" =
      keyword === "type" || keyword === "interface" ? "type" : "value";
    setIfUnset(name, kind);
  }

  // List exports: export [type] { X, type Y, Z as W } [from "..."]
  const listRe = /export\s+(type\s+)?\{([^}]+)\}/g;
  while ((m = listRe.exec(src))) {
    const blockIsType = !!m[1];
    const inner = m[2]!;
    for (const raw of inner.split(",")) {
      let s = raw.trim();
      if (!s) continue;
      let itemIsType = false;
      if (/^type\s+/.test(s)) {
        itemIsType = true;
        s = s.replace(/^type\s+/, "");
      }
      const asMatch = s.match(/^(\w+)\s+as\s+(\w+)$/);
      const name = asMatch ? asMatch[2]! : s;
      if (name === "default") continue;
      if (!/^\w+$/.test(name)) continue;
      const kind: "type" | "value" = blockIsType || itemIsType ? "type" : "value";
      setIfUnset(name, kind);
    }
  }

  return Array.from(map, ([name, kind]) => ({ name, kind })).sort((a, b) =>
    a.name.localeCompare(b.name),
  );
}



function walkFiles(dir: string, out: string[]): void {
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const e of entries) {
    const p = join(dir, e.name);
    if (e.isDirectory()) {
      if (e.name === "node_modules" || e.name === "plugins") continue;
      walkFiles(p, out);
    } else if (e.isFile() && /\.(ts|tsx)$/.test(e.name)) {
      out.push(p);
    }
  }
}

function parseServerApiUses(serverDir: string, selfName: string, runtime: "server" | "central" = "server"): string[] {
  const files: string[] = [];
  walkFiles(serverDir, files);
  const uses = new Set<string>();
  const modRe = new RegExp(`@plugins\\/([^/"'\`]+)\\/${runtime}(?:\\/(?:api(?:\\/index)?|index))?$`);
  const namedRe =
    /import\s+(?:([A-Za-z_$][\w$]*)\s*,\s*)?\{([^}]+)\}\s*from\s*["']([^"']+)["']/g;
  const nsRe =
    /import\s+\*\s+as\s+[A-Za-z_$][\w$]*\s+from\s*["']([^"']+)["']/g;
  const defRe = /import\s+[A-Za-z_$][\w$]*\s+from\s*["']([^"']+)["']/g;
  const sideRe = /import\s*["']([^"']+)["']/g;

  for (const f of files) {
    const src = readIfExists(f);
    if (!src) continue;
    let m: RegExpExecArray | null;
    while ((m = namedRe.exec(src))) {
      const mod = m[3]!;
      const hit = mod.match(modRe);
      if (!hit) continue;
      const plug = hit[1]!;
      if (plug === selfName) continue;
      for (const raw of m[2]!.split(",")) {
        let s = raw.trim();
        if (!s) continue;
        s = s.replace(/^type\s+/, "");
        const asMatch = s.match(/^(\w+)\s+as\s+\w+$/);
        const orig = asMatch ? asMatch[1]! : s;
        if (/^\w+$/.test(orig)) uses.add(`${plug}.${orig}`);
      }
    }
    for (const re of [nsRe, defRe, sideRe]) {
      re.lastIndex = 0;
      while ((m = re.exec(src))) {
        const hit = m[1]!.match(modRe);
        if (!hit) continue;
        const plug = hit[1]!;
        if (plug !== selfName) uses.add(plug);
      }
    }
  }
  return Array.from(uses).sort();
}

function parseResources(serverDir: string): { key: string; mode: string }[] {
  const files: string[] = [];
  walkFiles(serverDir, files);
  const out: { key: string; mode: string }[] = [];
  const seen = new Set<string>();
  for (const f of files) {
    const src = readIfExists(f);
    if (!src) continue;
    const re = /defineResource\s*\(\s*\{/g;
    let m: RegExpExecArray | null;
    while ((m = re.exec(src))) {
      const openIdx = m.index + m[0].length - 1;
      const closeIdx = matchBracket(src, openIdx, "{", "}");
      if (closeIdx < 0) continue;
      const body = src.slice(openIdx + 1, closeIdx);
      const key = parseStringField(body, "key");
      const mode = parseStringField(body, "mode") ?? "push";
      if (key && !seen.has(key)) {
        seen.add(key);
        out.push({ key, mode });
      }
    }
  }
  return out.sort((a, b) => a.key.localeCompare(b.key));
}

function findDbFiles(pluginDir: string): string[] {
  const serverDir = join(pluginDir, "server");
  if (!existsSync(serverDir)) return [];
  const results: string[] = [];
  function walk(d: string) {
    let entries;
    try {
      entries = readdirSync(d, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      const full = join(d, e.name);
      if (e.isDirectory()) {
        walk(full);
      } else if (e.name.endsWith(".ts") && e.name !== "index.ts") {
        const byName = /schema|tables?/.test(e.name.replace(/\.ts$/, ""));
        const src = byName ? null : readIfExists(full);
        const byContent = !byName && !!src && (src.includes("pgTable(") || src.includes("pgView("));
        if (byName || byContent) results.push(full);
      }
    }
  }
  walk(serverDir);
  return results.sort();
}

function collectPlugin(dir: string, pluginsRoot: string): PluginInfo {
  const webIndex = readIfExists(join(dir, "web", "index.ts"));
  const serverIndex = readIfExists(join(dir, "server", "index.ts"));
  const centralIndex = readIfExists(join(dir, "central", "index.ts"));
  const slotsSrc = readIfExists(join(dir, "web", "slots.ts"));
  const commandsSrc = readIfExists(join(dir, "web", "commands.ts"));
  const dbFiles = findDbFiles(dir);

  const webSrc = webIndex ? stripTypes(webIndex) : null;
  const serverSrc = serverIndex ? stripTypes(serverIndex) : null;
  const centralSrc = centralIndex ? stripTypes(centralIndex) : null;

  const webDesc = webSrc ? parseStringField(webSrc, "description") : undefined;
  const serverDesc = serverSrc ? parseStringField(serverSrc, "description") : undefined;
  const centralDesc = centralSrc ? parseStringField(centralSrc, "description") : undefined;
  const description =
    [webDesc, serverDesc, centralDesc].filter(Boolean).join(" ") || undefined;

  const definedSlots = slotsSrc
    ? parseDefineGroup(stripTypes(slotsSrc), "defineSlot", (memberName, slotId, groupName) => ({
        memberName,
        slotId,
        groupName,
      }))
    : [];
  const definedCommands = commandsSrc
    ? parseDefineGroup(
        stripTypes(commandsSrc),
        "defineCommand",
        (memberName, commandId, groupName) => ({ memberName, commandId, groupName }),
      )
    : [];

  const contributions: Contribution[] = [];
  if (webSrc) {
    const block = extractContributionsBlock(webSrc);
    if (block !== null) {
      const importMap = parseImports(webSrc);
      for (const call of findCalls(block)) {
        const [head, ...rest] = call.callee.split(".");
        const tail = rest.join(".");
        const imp = importMap.get(head!);
        const displayHead = imp && imp.original !== "default" ? imp.original : head!;
        contributions.push({ slot: `${displayHead}.${tail}`, props: parsePropsBlock(call.argsBody) });
      }
    }
  }

  const httpRoutes = serverSrc ? parseRouteMap(serverSrc, "httpRoutes") : [];
  const wsRoutes = serverSrc ? parseRouteMap(serverSrc, "wsRoutes") : [];
  const centralHttpRoutes = centralSrc ? parseRouteMap(centralSrc, "httpRoutes") : [];
  const centralWsRoutes = centralSrc ? parseRouteMap(centralSrc, "wsRoutes") : [];

  // Parse barrels on raw source (not stripTypes): the Bun transpiler drops
  // `export type { ... }` re-exports entirely, and our regex is already
  // type-aware.
  const webExports = webIndex ? parseBarrelExports(webIndex) : [];
  const serverExports = serverIndex ? parseBarrelExports(serverIndex) : [];
  const centralExports = centralIndex ? parseBarrelExports(centralIndex) : [];

  const sharedIndex = readIfExists(join(dir, "shared", "index.ts"));
  const sharedExports = sharedIndex ? parseBarrelExports(sharedIndex) : [];

  const serverDir = join(dir, "server");
  const apiUses = existsSync(serverDir) ? parseServerApiUses(serverDir, basename(dir)) : [];
  const resources = existsSync(serverDir) ? parseResources(serverDir) : [];
  const centralDir = join(dir, "central");
  const centralApiUses = existsSync(centralDir)
    ? parseServerApiUses(centralDir, basename(dir), "central")
    : [];
  const centralResources = existsSync(centralDir) ? parseResources(centralDir) : [];

  const rel = relative(pluginsRoot, dir);
  const segs = rel.split(/[\\/]+/);
  let parentDir: string | null = null;
  if (segs.length >= 3 && segs[segs.length - 2] === "plugins") {
    parentDir = join(pluginsRoot, ...segs.slice(0, segs.length - 2));
  }

  return {
    dir,
    name: basename(dir),
    parentDir,
    description,
    definedSlots,
    definedCommands,
    dbFiles,
    contributions,
    httpRoutes,
    wsRoutes,
    webExports,
    serverExports,
    centralExports,
    sharedExports,
    apiUses,
    resources,
    centralHttpRoutes,
    centralWsRoutes,
    centralApiUses,
    centralResources,
    children: [],
  };
}

function stripQuotes(s: string): string {
  if (
    (s.startsWith('"') && s.endsWith('"')) ||
    (s.startsWith("'") && s.endsWith("'")) ||
    (s.startsWith("`") && s.endsWith("`"))
  ) {
    return s.slice(1, -1);
  }
  return s;
}

function renderContribution(c: Contribution): string {
  const parts = [`\`${c.slot}\``];
  const p = c.props;
  if (p["pattern"]) parts.push(`\`${stripQuotes(p["pattern"])}\``);
  else if (p["title"]) parts.push(`"${stripQuotes(p["title"])}"`);
  else if (p["label"]) parts.push(`"${stripQuotes(p["label"])}"`);
  if (p["group"]) parts.push(`(group \`${stripQuotes(p["group"])}\`)`);
  if (p["component"]) parts.push(`→ \`${p["component"].trim()}\``);
  return parts.join(" ");
}

function renderExports(
  runtime: "web" | "server" | "central" | "shared",
  exports: BarrelExport[],
  indent: string,
  lines: string[],
): void {
  if (exports.length === 0) return;
  const types = exports.filter((e) => e.kind === "type");
  const values = exports.filter((e) => e.kind === "value");
  lines.push(`${indent}  - Exports (${runtime}):`);
  if (types.length > 0) {
    lines.push(
      `${indent}    - Types: ${types.map((e) => `\`${e.name}\``).join(", ")}`,
    );
  }
  if (values.length > 0) {
    lines.push(
      `${indent}    - Values: ${values.map((e) => `\`${e.name}\``).join(", ")}`,
    );
  }
}

function renderPlugin(p: PluginInfo, depth: number, root: string): string[] {
  const indent = "  ".repeat(depth);
  const lines: string[] = [];
  const desc = p.description ? ` — ${p.description}` : "";
  lines.push(`${indent}- **\`${p.name}\`**${desc}`);

  const defines: string[] = [];
  if (p.definedSlots.length > 0) {
    defines.push(
      `${indent}    - Slots: ${p.definedSlots.map((s) => `\`${s.groupName}.${s.memberName}\``).join(", ")}`,
    );
  }
  if (p.definedCommands.length > 0) {
    defines.push(
      `${indent}    - Commands: ${p.definedCommands.map((c) => `\`${c.groupName}.${c.memberName}\``).join(", ")}`,
    );
  }
  for (const f of p.dbFiles) {
    defines.push(`${indent}    - DB schema: \`${relative(root, f)}\``);
  }
  if (defines.length > 0) {
    lines.push(`${indent}  - Defines:`);
    lines.push(...defines);
  }

  renderExports("web", p.webExports, indent, lines);
  renderExports("server", p.serverExports, indent, lines);
  renderExports("central", p.centralExports, indent, lines);
  renderExports("shared", p.sharedExports, indent, lines);

  if (p.contributions.length > 0) {
    lines.push(`${indent}  - Contributes:`);
    for (const c of p.contributions) lines.push(`${indent}    - ${renderContribution(c)}`);
  }

  const serverEntries = [
    ...p.httpRoutes,
    ...p.wsRoutes.map((r) => `WS ${r}`),
  ];
  if (serverEntries.length > 0 || p.apiUses.length > 0 || p.resources.length > 0) {
    lines.push(`${indent}  - Server:`);
    if (p.apiUses.length > 0) {
      lines.push(
        `${indent}    - Uses: ${p.apiUses.map((n) => `\`${n}\``).join(", ")}`,
      );
    }
    if (p.resources.length > 0) {
      lines.push(
        `${indent}    - Resources: ${p.resources.map((r) => `\`${r.key}\` (${r.mode})`).join(", ")}`,
      );
    }
    for (const r of serverEntries) lines.push(`${indent}    - \`${r}\``);
  }

  const centralEntries = [
    ...p.centralHttpRoutes,
    ...p.centralWsRoutes.map((r) => `WS ${r}`),
  ];
  if (
    centralEntries.length > 0 ||
    p.centralApiUses.length > 0 ||
    p.centralResources.length > 0
  ) {
    lines.push(`${indent}  - Central:`);
    if (p.centralApiUses.length > 0) {
      lines.push(
        `${indent}    - Uses: ${p.centralApiUses.map((n) => `\`${n}\``).join(", ")}`,
      );
    }
    if (p.centralResources.length > 0) {
      lines.push(
        `${indent}    - Resources: ${p.centralResources.map((r) => `\`${r.key}\` (${r.mode})`).join(", ")}`,
      );
    }
    for (const r of centralEntries) lines.push(`${indent}    - \`${r}\``);
  }

  if (p.children.length > 0) {
    lines.push(`${indent}  - Plugins:`);
    for (const c of p.children) lines.push(...renderPlugin(c, depth + 2, root));
  }

  return lines;
}

export interface GenerateDocsOptions {
  root: string;
}

/**
 * Walk plugins/ and return one PluginInfo per discovered plugin (flat list,
 * including nested sub-plugins). Used by build to derive the central routing
 * manifest.
 */
export function collectAllPlugins(root: string): PluginInfo[] {
  const pluginsRoot = resolve(root, "plugins");
  const dirs = findAllPluginDirs(pluginsRoot);
  return dirs.map((d) => collectPlugin(d, pluginsRoot));
}

export type { PluginInfo };

export function renderPluginDocs({ root }: GenerateDocsOptions): string {
  const pluginsRoot = resolve(root, "plugins");
  const dirs = findAllPluginDirs(pluginsRoot);
  const byDir = new Map<string, PluginInfo>();
  for (const d of dirs) byDir.set(d, collectPlugin(d, pluginsRoot));

  const roots: PluginInfo[] = [];
  for (const info of byDir.values()) {
    let parent = info.parentDir;
    while (parent && !byDir.has(parent)) {
      const rel = relative(pluginsRoot, parent);
      const segs = rel.split(/[\\/]+/);
      if (segs.length >= 3 && segs[segs.length - 2] === "plugins") {
        parent = join(pluginsRoot, ...segs.slice(0, segs.length - 2));
      } else {
        parent = null;
      }
    }
    if (parent && byDir.has(parent)) {
      byDir.get(parent)!.children.push(info);
    } else {
      roots.push(info);
    }
  }

  const sortRec = (list: PluginInfo[]) => {
    list.sort((a, b) => a.name.localeCompare(b.name));
    for (const c of list) sortRec(c.children);
  };
  sortRec(roots);

  const lines: string[] = [];
  for (let i = 0; i < roots.length; i++) {
    if (i > 0) lines.push("");
    lines.push(...renderPlugin(roots[i]!, 0, root));
  }
  return lines.join("\n") + "\n";
}

export function renderFullDoc({ root }: GenerateDocsOptions): string {
  const body = renderPluginDocs({ root });
  const header = "# Plugins list\n\n";
  return `${header}${BEGIN}\n\n${body}\n${END}\n`;
}

export function pluginDocsPath(root: string): string {
  return join(root, "docs", "plugins.md");
}

export async function generatePluginDocs({ root }: GenerateDocsOptions): Promise<void> {
  const file = pluginDocsPath(root);
  const existing = readIfExists(file) ?? "";
  const next = renderFullDoc({ root });
  if (next !== existing) writeFileSync(file, next);
}
